### ISSUE TITLE
Use "document.baseURI" as the relative request's base URL

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#1007]
## Current behavior

We use `location.origin` to be the base URL for relative requests.

https://github.com/mswjs/msw/blob/445fc63f9447df2df346c64d1a751d43b284e52a/src/utils/url/getAbsoluteUrl.ts#L10-L12

While this works, certain scenarios won't have a location set (i.e. sandboxed iframes). Relative request URL resolution would fail in those cases.

## Expected behavior

Use [`document.baseURI`](https://developer.mozilla.org/en-US/docs/Web/API/Node/baseURI) instead, which is always set on the document.

**Comment by watife** [comment]
I would like to jump on this and would open a PR soon.

**Comment by kettanaito** [comment]
@watife, that'd be incredible! Feel free to open the pull request, I'd be glad to help you with the code review and making this improvement happen. Let's improve the experience for developers together.

**Comment by athrunsun** [comment]
@watife @kettanaito Is this `baseUrl` option documented somewhere?

**Comment by kettanaito** [comment]
Hey, @athrunsun. There's no `baseUrl` option supported in MSW. That's an intentional decision and you can learn more about it [here](https://github.com/mswjs/msw/issues/397#issuecomment-751230924).

This particular change has updated an internal implementation detail to result in more reliable relative requests matching in various contexts. This is not a public, developer-facing API.
