### ISSUE TITLE
Worker registration not resolving when run with vscode debugger

### ISSUE THREAD

**Issue by Businesskasper** [kettanaito/msw#1031]
## Describe the bug
When running the browser from vs code debugger, the worker registration is never resolving but also never failing. Therefore all network requests are forever deferred.

## Environment

- `msw: ^0.36.3`
- `nodejs: 16.13.0`
- `npm: 8.1.4`
- `chrome: 96.0.4664.93`

> Please also provide your browser version.

## To Reproduce
1. Setup react app (npx create-react-app my-app) and install msw
2. Setup service worker in index.js
```
const { worker } = require('./mocks/browser')
worker.start()
  .then((registration) => {
    console.log('msw initialisiert')
  })
  .catch(err => {
    console.log('msw initialization failed')
  })

```

/mocks/browser:
```
import { setupWorker } from 'msw'
import { handlers } from './handlers'

const worker = setupWorker(...handlers)
export {worker}
```

./handlers:
```
import { rest } from 'msw'

export const handlers = [
  rest.get('/users', (req, res, ctx) => {
    return res(
      ctx.status(200),
      ctx.json([]),
    )
  })
```

3. Configure launch.json in .vscode:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/src",
            "sourceMapPathOverrides": {
              "/*": "/__vscode-remote-uri__/*"
            }
          }
    ]
}
```

4. Start the react app (npm start), close the opening browser and press F5 to launch the vscode browser debugger.

Neither the catch nor then handlers in worker.start() are called. When debugging, the last line to follow is 647 in node_modules\msw\lib\esm\index.js: `const registration = yield navigator.serviceWorker.register(url, options);`. Because of line 1335          `deferNetworkRequestsUntil(workerRegistration);` no fetch requests are made anymore.

## Expected behavior
worker.start() should either resolve or crash with an error object.

**Comment by Businesskasper** [comment]
Update: I got it working by changing my launch.json to this:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "WSL Chrome",
            "type": "legacy-chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/src",
            "sourceMapPathOverrides": {
              "/*": "/__vscode-remote-uri__/*"
            },
          }
    ]
}
```

Does anybody know why "legacy-chrome" works but "chrome" not? It seems to have something to do with worker registration in general. If i run `await navigator.serviceWorker.register('http://localhost:3000/mockServiceWorker.js')` in the dev chrome console directly, nothing happens. If i run chrome from the desktop shortcut, it works, as it does in "chrome-legacy".

**Comment by adrianzielonka** [comment]
## Environment
* `msw: ^0.36.3`
* `nodejs: 14.18.2`
* `npm: 8.1.3`
* `chrome: 97.0.4692.71 (Official Build) (arm64)`

Same issue here using the above configuration.

**Comment by kettanaito** [comment]
Sorry, I don't have the capacity right now to look into this, and this isn't a critical issue. I will close it. Anyone is welcome to investigate and open a pull request. Thanks for understanding.
