### ISSUE TITLE
Initial load request interception

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#1051]
As reported in #1049 and a few other issues, the library is having trouble intercepting initial load requests. That often happens because of the race condition between the worker registration and application making requests. We do attempt to eliminate that race condition by capturing and replaying all requests that happened in that timeframe but that clearly doesn't work for everybody. 

https://github.com/mswjs/msw/blob/527add209585c134fd7702327ded3f4721922ee3/src/utils/deferNetworkRequestsUntil.ts#L8

## Expected behavior

The library is capable of intercepting requests issued upon the initial load/mount of an application. 

## Suggested solutions

1. For once, we may investigate why `deferNetworkRequestsUntil` doesn't work in those problematic cases. Perhaps there's an issue in the implementation that's the culprit.
2. Alternatively, think of a different approach to the problem.

**Comment by marcosvega91** [comment]
Hellooo, it could be bacause the `deferNetworkRequestsUntil` function has been called ad the end of the start process? There are some await before and this could make the application ready before MSW is ready. Maybe it could be better to move the function at the beginning of the function using a different promise ?

**Comment by kettanaito** [comment]
This has a high chance of being fixed by #1146. The `deferNetworkUntil` hijacked `window.fetch` and inserted an intermediary Promise to await—the worker registration Promise. Since the latter used to resolve improperly on the worker's registration but not activation, it was possible that the hijacked fetch would restore itself earlier than the worker was indeed activated, becoming ready to handle requests. 

This needs testing and verification.

**Comment by kettanaito** [comment]
One way to test this is to use the NextJS example and start the worker without explicitly awaiting it activation before rendering the app (without the deferred mounting approach). This must always work.

**Comment by kettanaito** [comment]
I confirm that #1146 fixes the initial load issue some of our users have been experiencing. Here's a video of the `GET /reviews` request being delayed until the worker has been activated (for 1.5s):

https://user-images.githubusercontent.com/14984911/157251896-5a6eff51-4c3c-475f-958c-aafb60b57d08.mov

The request happens on the `App` component mount. There are no changes made to how the NextJS app is rendered, the mocking is enabled as per the [NextJS usage example](https://github.com/vercel/next.js/tree/canary/examples/with-msw).
