### ISSUE TITLE
setUpServer error: " TypeError: Cannot read properties of undefined (reading 'indexOf')"

### ISSUE THREAD

**Issue by laurencefass** [kettanaito/msw#1053]
## Describe the bug
I have recreated a basic demo from [here](https://github.com/vercel/next.js/tree/canary/examples/with-msw) to demonstrate client and server msw mocks. I am getting an error on call to setUpServer. The browser worker code appears to work fine.

mocks/server.js
```
import { setupServer } from "msw/node";
import { handlers } from "./handlers";
export const server = setupServer(...handlers);
```

there does not appear to be a problem with the browser worker code
```
import { setupWorker } from 'msw'
import { handlers } from './handlers'
export const worker = setupWorker(...handlers)
```

server and worker code are called from mocks/index.ts which in turn is required by app code
```
try {
    if (typeof window === 'undefined') {
        const { server } = require('./server')
        server.listen()
    } else {
        const { worker } = require('./browser')
        worker.start()
    }
}
catch (e) {
    console.log("catch!", e);
}
```

_app.ts (executes index.js in mocks folder)
```
require('../mocks')
export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```

error on server
```
1|next-next18  | catch! TypeError: Cannot read properties of undefined (reading 'indexOf')
1|next-next18  |     at hasFlag$1 (webpack://_N_E/./node_modules/msw/node/lib/index.js?:1400:24)
1|next-next18  |     at eval (webpack://_N_E/./node_modules/msw/node/lib/index.js?:1412:5)
1|next-next18  |     at Object../node_modules/msw/node/lib/index.js (/app/next/next18/.next/server/pages/msw.js:1127:1)
1|next-next18  |     at __webpack_require__ (/app/next/next18/.next/server/middleware-ssr-runtime.js:37:33)
1|next-next18  |     at fn (/app/next/next18/.next/server/middleware-ssr-runtime.js:288:21)
1|next-next18  |     at eval (webpack://_N_E/./mocks/server.ts?:5:66)
1|next-next18  |     at Module../mocks/server.ts (/app/next/next18/.next/server/pages/msw.js:1237:1)
1|next-next18  |     at __webpack_require__ (/app/next/next18/.next/server/middleware-ssr-runtime.js:37:33)
1|next-next18  |     at fn (/app/next/next18/.next/server/middleware-ssr-runtime.js:288:21)
1|next-next18  |     at eval (webpack://_N_E/./mocks/index.ts?:5:29)

```

## Environment

node  v16.13.1
npm 8.1.2
msw 0.36.3

> Please also provide your browser version.
n/a

## To Reproduce
ive based a test version from here:
https://github.com/vercel/next.js/tree/canary/examples/with-msw

note: ive installed a later version of msw

## Expected behavior
setUpServer should return a server object but is throwing an exception.

## Screenshots
n/a - applies to server only

**Comment by laurencefass** [comment]
scrapped the project and rebuilt from scratch seems to be working.

**Comment by jacobweberbowery** [comment]
For anyone running into this, it may happen if your test code overwrites `process.argv`.
