### ISSUE TITLE
msw breaking intercepted puppeteer API calls

### ISSUE THREAD

**Issue by navinpai** [kettanaito/msw#1058]
## Describe the bug

If you use puppeteer in your code, then calls made by puppeteer to the browser instance it spins up are being incorrectly intercepted, leading to unexpexted breakages in tests. 

## Environment

- `msw: 0.36.4`
- `nodejs: 16.13.1`
- `npm: 8.1.2`
- `puppeteer: 13.0.1`

> Please also provide your browser version.

## To Reproduce
Whipped up a sample repo to allow easier reproduction of the issue: https://github.com/navinpai/puppeteer-msw-bug
1. npm install
2. npm run dev
    - If you go to `http://localhost:3000/test` it opens up a browser instance , navigates to http://example.com, and then shuts down after 10 secs
    - _(I've set puppeteer to `headless: false` so that you can actually "see" the browser)_
3. npm run test
    - No API mocks have been created at the moment.
    - Test is set up with msw to just call the `/test` endpoint. Browser gets opened, however nothing happens on the browser past this, even though `onUnhandledRequest` is set to[ "bypass" or "warn"](https://github.com/navinpai/puppeteer-msw-bug/blob/main/index.test.js#L11) and the test fails.

---

If we set `onUnhandledRequest` to `warn`, we see this is in log:

```
  console.warn
    [MSW] Warning: captured a request without a matching request handler:

      • GET http://127.0.0.1:60331/test

    If you still wish to intercept this unhandled request, please create a request handler for it.
    Read more: https://mswjs.io/docs/getting-started/mocks

      at Object.warn (node_modules/msw/node/lib/index.js:3163:13)
      at onUnhandledRequest (node_modules/msw/node/lib/index.js:7826:22)
      at node_modules/msw/node/lib/index.js:7857:13
      at fulfilled (node_modules/msw/node/lib/index.js:51:58)

  console.warn
    [MSW] Warning: captured a request without a matching request handler:

      • GET http://127.0.0.1:60333/devtools/browser/37243e11-a4d5-4975-8626-c18b14c58fc7

    If you still wish to intercept this unhandled request, please create a request handler for it.
    Read more: https://mswjs.io/docs/getting-started/mocks

      at Object.warn (node_modules/msw/node/lib/index.js:3163:13)
      at onUnhandledRequest (node_modules/msw/node/lib/index.js:7826:22)
      at node_modules/msw/node/lib/index.js:7857:13
      at fulfilled (node_modules/msw/node/lib/index.js:51:58)
```

## Expected behavior
Since we've not mocked any of the APIs, the "bypass"/"warn" settings should kick in and the test should not break. Unsure if there's something I'm missing here.

## Related

This issue _may be_ similar to a previously reported issue: https://github.com/mswjs/msw/issues/418 , but I'm not sure.

---
As an aside, thanks @kettanaito for maintaining this lib... It's been great to see the project grow to maturity so quickly! 👏

**Comment by kettanaito** [comment]
Hey, @navinpai. Thanks for reporting this, and for your kind words!

I will take a look at your reproduction scenario (bonus points for preparing that) and update the issue with my findings.

**Comment by kettanaito** [comment]
I've followed the reproduction steps multiple times but couldn't reproduce this issue as of `0.40.2`. It might have been fixed in earlier versions, I have no prior knowledge of that. 

```sh
npm test

> puppeteer-msw-bug@1.0.0 test /Users/kettanaito/Projects/contrib/puppeteer-msw-bug
> jest

  console.warn
    [MSW] Warning: captured a request without a matching request handler:
    
      • GET http://127.0.0.1:57725/test
    
    If you still wish to intercept this unhandled request, please create a request handler for it.
    Read more: https://mswjs.io/docs/getting-started/mocks

      at Object.warn (node_modules/msw/node/lib/index.js:3602:13)
      at applyStrategy (node_modules/msw/node/lib/index.js:8058:26)
      at onUnhandledRequest (node_modules/msw/node/lib/index.js:8074:5)
      at node_modules/msw/node/lib/index.js:8105:13
      at fulfilled (node_modules/msw/node/lib/index.js:51:58)

  console.warn
    [MSW] Warning: captured a request without a matching request handler:
    
      • GET http://127.0.0.1:57727/devtools/browser/5ceb1a62-24fc-4e15-b4c9-74fa8f921ab8
    
    If you still wish to intercept this unhandled request, please create a request handler for it.
    Read more: https://mswjs.io/docs/getting-started/mocks

      at Object.warn (node_modules/msw/node/lib/index.js:3602:13)
      at applyStrategy (node_modules/msw/node/lib/index.js:8058:26)
      at onUnhandledRequest (node_modules/msw/node/lib/index.js:8074:5)
      at node_modules/msw/node/lib/index.js:8105:13
      at fulfilled (node_modules/msw/node/lib/index.js:51:58)

 PASS  ./index.test.js
  ✓ GET /test (2410 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.944 s, estimated 3 s
```

You see the warnings about unhandled requests, which is correct. The test is passing, MSW does not affect the network in any way. 

If you experience any related issues please open a new issue in the repo.

**Comment by navinpai** [comment]
Can confirm the issue is fixed. Thanks for following up on this @kettanaito 👍 👋
