### ISSUE TITLE
Vulnerability found with node-fetch

### ISSUE THREAD

**Issue by black-signature** [kettanaito/msw#1065]
## Describe the bug
A vulnerability has been found with `node-fetch` which is a dependency in msw. Updating it to 3.1.1 or higher should fix the issue.
https://security.snyk.io/vuln/SNYK-JS-NODEFETCH-2342118

## Environment

- `msw: 0.36.4`

**Comment by kettanaito** [comment]
Hey, @black-signature. Thanks for reporting this. 

As MSW is meant to run in a development environment, this vulnerability is a low priority for the library. We will update `node-fetch` in the next minor release.

**Comment by black-signature** [comment]
Great! Thanks for the update, @kettanaito

**Comment by kettanaito** [comment]
Closed by #1072.
