### ISSUE TITLE
Function use() not work in browser

### ISSUE THREAD

**Issue by kazeichev** [kettanaito/msw#1084]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.36.8   |
| browser | Chrome    |

### browser.ts

```js
import { rest, setupWorker } from 'msw';

const worker = setupWorker(...);

window.msw = {
    worker,
    rest,
};

export { worker };
```

### worker.ts

```js
import { worker } from '../../mocks/browser';

export const setupMsw = () => {
    return worker.start({
        onUnhandledRequest: 'bypass',
        serviceWorker: {
            url: process.env.CI ? SOME_PATH/mockServiceWorker.js : '/mockServiceWorker.js',
        },
    }).then(() => {
        window.msw.ready = true;
    });
};
```

## Current behavior

1. Open the page where mock url uses
2. Check that mock url fired correctly and mock data received successfully
3. Open browser console and try to change mock data with use() function
```js
window.msw.worker.use(
    window.msw.rest.get('**/rest/shops', (_req, res, ctx) => {
        return res(
            ctx.json([]),
        );
    }),
);
```
4. Try to use printHandlers() function. I see old and new mock urls
```js
window.msw.worker.printHandlers()

[rest] GET /rest/shops
—- SOME OTHERS —-
[rest] GET /rest/shops
```
5. Try to fetch mock url one more time in browser console
```js
fetch('/rest/shops')
```
6. I can see 2 debug messages in browser console (old and new mocks fired)
```js
[MSW] 14:01:37 GET /rest/shops (200 OK)
[MSW] 14:01:37 GET /rest/shops (200 OK)
```
7. Response from fetch are equal old mock (not new from use() function)

## Expected behavior
7. Response from fetch are equal new mock

I try to write e2e test with PlaywrightJs and in my test use() function working not correct. So, I try to reproduce my case in browser and I see the same error which I described earlier. 

Could you help me with this issue Thank you!

**Comment by kettanaito** [comment]
Hey, @kazeichev. Did you manage to resolve the issue? What was the culprit?

**Comment by florianmatz** [comment]
@kazeichev I'm experiencing the same issue! And I kinda went the same path as you do. Also using playwright and then tried to make it work in the browser. 

Did you solve it, and if yes, how?

**Comment by kazeichev** [comment]
@florianmatz I haved 2 instance of mswjs launched in browser.

**Comment by florianmatz** [comment]
@kazeichev Mmhhh... And how did you find out? Did you have two worker.start() or something?

**Comment by kazeichev** [comment]
@florianmatz Yes, I have got two workers.start() in different place of app.
