### ISSUE TITLE
msw compiled with warnings after installing and configuring according to the documentation

### ISSUE THREAD

**Issue by Dwipasca** [kettanaito/msw#1086]
## Describe the bug

I have followed the installation method of MSW to React with the instruction documentation, Indeed my expectations are in accordance with the documentation, but when I looking at my terminal it's say compiled with warnings, and after I checked the response it's 304 and the fake data not showing.

## Environment

- `msw: 0.36.8`
- `nodejs: 17.4.0`
- `npm: 8.3.1`

> Please also provide your browser version.
- `firefox: 96`

## To Reproduce

1. Perform the installation according to the documentation : https://mswjs.io/docs/getting-started/install
2. But change code in `handlers.js`, for example: 
```
const coins = [
  { name: "Cardano", website: "https://cardano.org" },
  { name: "Polkadot", website: "https://polkadot.network" },
];

export const handlers = [
  rest.get("/coins", (req, res, ctx) => {
    return res(
      ctx.status(200),
      ctx.delay(500),
      ctx.json(
        coins.map((data) => {
          return [...data];
        })
      )
    );
  }),
];
```
3. Run the app `yarn start`

or you can see this repo : https://github.com/Dwipasca/MSW-compiled-with-warnings-BUG

## Expected behavior
Don't have any error or warning in terminal, and show the fake data if we hit the api.

## Screenshots
![Screen Shot 2022-02-01 at 10 38 26](https://user-images.githubusercontent.com/19584291/151912194-9026fba6-4c12-4aad-9e52-54fcceea2ca5.png)
![Screen Shot 2022-02-01 at 12 19 12](https://user-images.githubusercontent.com/19584291/151912237-2b77e6a7-73f5-4147-996e-6a7d6477ce09.png)
<img width="990" alt="Screen Shot 2022-02-01 at 12 19 47" src="https://user-images.githubusercontent.com/19584291/151912302-d412ce53-92fa-4ab7-b871-101c51bd4d45.png">

**Comment by kettanaito** [comment]
Hi, @Dwipasca. Thanks for reporting this. The issue is known and we are tracking it in https://github.com/mswjs/msw/issues/1030. You can follow the status update there. Feel free to contribute as well, it's a matter of publishing the source of one of the dependencies to npm.
