### ISSUE TITLE
msw + Typescript complain cannot find HeaderName and Lowecase

### ISSUE THREAD

**Issue by ghost** [kettanaito/msw#1087]
## Describe the bug
I'm using msw in my Vue2+TS project for storybook and testing purposes. Whenever I run said project, TS is complaining about not being able to find `HeaderName` and `Lowecase` type definition in `set.d.ts` file.

## Environment

- `msw: 0.36.8`
- `nodejs: 14.16.0`
- `npm: 6.14.11`
- `typsecript: 3.9.10`
- `axios: 0.24.0`

## Expected behavior
As TS is supported by default by the lib, it should not happen.

## Screenshots
![Untitled](https://user-images.githubusercontent.com/53071794/152076639-272d8dec-5ab4-4e69-a322-74fe70cc4024.png)

`handlers.ts`
```
import auth from './api/auth';

export const handlers = [
    ...auth,
];
```

`api/auth.ts`
```
import {rest} from 'msw';
import {LooseObject} from '@/types';

export default [
    rest.post<LooseObject, LooseObject>(`/auth/cms/login`, (req, res, ctx) => {
        const {
            params,
            url: {searchParams},
        } = req;

        const json = require('../response/v1.auth.login.json'); // this is a mock json response file
        return res(ctx.json(json));
    }),
];
```

`browser.ts`
```
import {setupWorker} from 'msw';
import {handlers} from './handlers';

export const worker = setupWorker(...handlers);
```

**Comment by kettanaito** [comment]
Hey, @gretchelin. Thanks for reporting this.

MSW is currently requiring `typescript@4.2.x`. Older versions will not compile as we depend on newer API of TypeScript, like `Lowercase`.

We are also trying to set the `typescript` as a peer dependency in https://github.com/mswjs/msw/pull/985, which is still in progress. This should make the progress of discovering the required TypeScript version easier.
