### ISSUE TITLE
Nginx proxy with srr + rtk problem

### ISSUE THREAD

**Issue by Tenutes** [kettanaito/msw#1088]
## Describe the bug
So, we are using rtk for react with ssr with express and nginx as a proxy for requests to express. Including msw's worker to browser in docker-compose build causes an strange error in rtk (redux toolkit) (screen below). After removing msw - error disapears.

## Environment

- `msw: 0.35.0`
- `nodejs: any 14+`
- `npm: 6+`

## To Reproduce
1. create a 2 containers with: frontend with react + node ssr and nginx, which proxies all request to frontend container.
2. run docker
3. open in browser

## Expected behavior
App is working

## Screenshots
![image](https://user-images.githubusercontent.com/34067613/152653298-cb6f94e5-437d-4079-8798-18096ea93dd8.png)

## P.S.
I can provide test docker-compose with nginx and frontend to test it, if you need

**Comment by msutkowski** [comment]
What version of RTK are you using? This was previously an issue with certain versions of node-fetch and redux-toolkit, but was resolved several releases ago. This is most likely the source of what you're running into: https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/fetchBaseQuery.ts#L251-L266

Note: if a version bump of redux-toolkit doesn't resolve this, a repro container would be great so we can look into it :)

**Comment by Tenutes** [comment]
Im using the latest version of rtk. And yes, i saw that issue, i'll provide docker config in few days

**Comment by kettanaito** [comment]
Hey, @Tenutes. Thanks for reporting this.

The error is related to https://github.com/mswjs/interceptors/pull/152 which we addressed in [0.36.0](https://github.com/mswjs/msw/releases/tag/v0.36.0). You're using quite an old version of MSW, so I highly recommend updating it. The error should be gone then.

Let us know if this still happens once you update to the latest `msw` version. Thanks.
