### ISSUE TITLE
Ability to pause response on runtime in the worker

### ISSUE THREAD

**Issue by rahulsinghk** [kettanaito/msw#1108]
Mock service Worker is an awesome library, it's very helpful to mock the API response. 
however, while testing the component, you want to test the state where there is a delay in response from the server and you would manage some state between this.

See that the MSW has the delay() to add the delay in response. but here while testing we would like to have complete control over the delay in run time. 

For example:- if I want to test the state where there is a delay in response. then I have to set the `dealy()` just right enough to test the use case and to avoid adding too much delay so that it takes too much time than required, making the test slow.

it would be noce to have the runtime modifier to pause the response and resume as we want. 
For example:- 
                                     `const { worker, rest } = window.msw`
                                      ` rest.pause()  // this will pause the response `
                                      ` // do some asserts and test the state`
                                     `  rest.resume() // this will resume the reponse `
                                       `// do some more asserts and test rest of the flow`

**Comment by kettanaito** [comment]
Hey, @rahulsinghk. Thanks for your kind words and for proposing this feature!

> if I want to test the state where there is a delay in response. then I have to set the dealy() just right enough to test the use case and to avoid adding too much delay so that it takes too much time than required, making the test slow.

```js
rest.get('/user', (req, res, ctx) => {
  const url = new URL(location.href)
  const delay = url.searchParams.get('delay') || 0
  return res(ctx.delay(delay), ctx.text('hello world'))
})
```

> This is a great pattern I've seen people use: you read the `delay` from your page's query parameters. This way you control response delays on runtime by appending the `?delay=X` parameter to the page you're loading. Note that this reads the delay from the _page_ but applies the delay to a particular response (`GET /user` in this example). 

Most test runners execute assertions immediately so even a 100ms delay is enough to test the loading state, for example. Do you have a concrete test case in mind you could share where this doesn't apply? 

Overall, having a pause/resume control over the network may be beneficial but I don't think it's what you need for testing in your particular case. If anybody needs this during development, you can utilize `debugger` in your request handler to pause your application:

```js
rest.get('/user', (req, res, ctx) => {
  // The entire application will pause in the browser,
  // allowing you to inspect its state.
  debugger
})
```
