### ISSUE TITLE
Server.use is not working in describe function in react testing liberary 

### ISSUE THREAD

**Issue by rahulsinghk** [kettanaito/msw#1112]
## Describe the bug
I am using MSW with react testing library to test my react app.
I have the following setup. 
```js
          describe("testsdddding Deprovision with deployment", () => {
              beforeEach(async () => {
                  await render(<MyWidget   />);
              });
              test("Deprovision renders correctly with the", async () => {
                  server.use(
                      rest.get(`my/url/test`, (req, res, ctx) => {
                          return res(ctx.json(
                              CUSTOM_RESPONSE
                          ));
                      }),
                  );
                  expect(screen.getByTestId("CenterLoader")).toBeInTheDocument();
                  await waitForElementToBeRemoved(() => screen.getByTestId("CenterLoader"));
                  expect(screen.queryByTestId("test_ErrorBar")).not.toBeInTheDocument();
                  expect(screen.getByTestId("test_deprovision:deprovision_button")).toBeEnabled();
              });
          });
```
here the `Server.use` is not working. 
when running the test it is behaving as if there is no request handler. 
However, I am able to see the desired handler in `server.printHandler()`

my server code:-
```js
        import { rest } from 'msw';
        import { setupServer } from 'msw/node';
        import {  DELETE_RESPONSE } from './response.mock';
        
        
        var server = setupServer(
            rest.delete(`my/url/test`, (req, res, ctx) => {
                return res(ctx.json(
                    DELETE_RESPONSE
                ));
            }),
        );
        
        export { 
            server,
            rest,
        };
```
if I add the GET handler in the server setup code then it's working, but it's not working when added with `Server.use`.

Just the observation, it will  work if the `test` is taken out from the `describe` 
or the `beforeEach()` is removed from the `Describe` .

Am is missing something here ?

## Environment

- `msw: 0.36.8`
- `nodejs: 14.17.1`
- `npm: 7.21.1`

> Google Chrome Version 98.0.4758.102 (Official Build) (x86_64)

## To Reproduce
set the test as mentioned above

## Expected behavior
the expected behavior is that the route added with the `server.use` as above should be hit.

**Comment by kettanaito** [comment]
Hi, @rahulsinghk. Thanks for reporting this. 

Based on the test you've included, you're rendering your React component, which makes requests, _before_ you add a new handler via `server.use`:

- The component is rendered in `beforeEach`;
- The runtime handler is added in the next `test`, which runs _after_ the `beforeEach` hook.

This means that when your component is making a request, MSW doesn't yet have the new `rest.get` handler you're appending. 

I recommend moving the `render` part into each individual test. You lose nothing by doing so, only make your tests more explicit (I'm not a fan of global testing hooks). You can also fix this by ensuring that `server.use()` is called before `render()` in any way you find suitable with your testing setup.
