### ISSUE TITLE
Add support for QUERY verb

### ISSUE THREAD

**Issue by arturohernandez10** [kettanaito/msw#1114]
**Is your feature request related to a problem? Please describe.**
I have a complex read request that does not fit in the query string

**Describe the solution you'd like**
I'd like to send the query as a payload instead of the query string. And I would like to have another request type named query to create handlers.

**Describe alternatives you've considered**
Use GET instead, and somehow I would need to modify my code so it issues a GET during testing. Except that it is exactly the kind of problem that led me to use MSW in the first place.

**Additional context**
[Here](https://www.ietf.org/id/draft-ietf-httpbis-safe-method-w-body-02.html) is the W3 proposal for QUERY.

**Comment by kettanaito** [comment]
Hi, @arturohernandez10. 

MSW does not validate requests nor check if they are spec-compliant—that responsibility is delegated to the browser. As long as you perform a valid HTTP request, it will get intercepted in the worker or Node.js and will be exposed to you in the request handler as the `req` (first) argument.

From what I understand, it's a matter of you dispatching the request you want, MSW should capture it just fine. I imagine the proposed QUERY request implements HTTP, so I think it should get intercepted. If it doesn't, chances are it's not supported by the browser or service worker. If that's the case, we can look into it together. 

Please feel free to provide more details on what that QUERY request looks like in your code and whether it's intercepted or not. A minimal reproduction repository is the best if you wish for me to help you out with this.
