### ISSUE TITLE
vite dev server: infinte refresh loop when using msw

### ISSUE THREAD

**Issue by rathax** [kettanaito/msw#1115]
## Describe the bug

running a vite dev server with msw will result in a refresh loop that keeps restarting the vite dev server. The setup did work in the past without issues, so I assume it may have something to do with some changes in a dependency.

## Environment

- `msw: ^0.38.1`
- `nodejs: v16.13.2`
- `npm: 8.1.2
 up to date Chrome and Firefox

## To Reproduce
1. Go to https://github.com/vuejs/create-vue
2. create a vite app
3. npm install msw --save-dev
4. npx msw init public/ --save
5 setup MSW in main.ts

```
import { createApp } from "vue";
import { createPinia } from "pinia";

import App from "./App.vue";
import router from "./router";
import { setupWorker, rest } from "msw";

const worker = setupWorker(
  // Provide request handlers
  rest.get("https://example.com/user/:userId", (req, res, ctx) => {
    return res(
      ctx.json({
        firstName: "John",
        lastName: "Maverick",
      })
    );
  })
);

async function prepare() {
 return worker.start();
}

prepare().then(() => {
  const app = createApp(App);
  app.use(createPinia());
  app.use(router);
  app.mount("#app");
});
```

5. npm run dev

**Comment by rathax** [comment]
manually clearing the service worker from both firefox and chrome seem to have resolved the issue.

**Comment by dankremniov** [comment]
I am getting the same issue by using MSW with Next.js (v10.2.0). Manually unregistering service worker temporary fixes the issue until any change is made to files related to MSW setup. It would be great to understand the reason.

**Comment by rathax** [comment]
yeah, still have the issue popping up once in a while. Not sure what triggered this exactly and if it could be solved with a different setup of the SW.

**Comment by kettanaito** [comment]
@dankremniov, @rathax, could you please submit a reproduction repo? We can find out the reason behind the behavior you're experiencing together.

**Comment by dankremniov** [comment]
@kettanaito, I tried but didn't manage to reproduce it in a clean repo. However, I managed to fix the issue in the project I was working on. The Next.js app was having a `basePath` set which means that worker's scope was not root. As soon as I specifically specified root scope and added the required header (as per MSW docs) - the issue disappeared.
