### ISSUE TITLE
Request Not Intercepted By Defined Handler

### ISSUE THREAD

**Issue by cutterbl** [kettanaito/msw#1123]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.38.1   |
| node | 16.14.0   |
| axios | 0.21.1   |
| macOS | 10.15.7   |

## Request handlers

```js
import { setupServer } from 'msw/node';
import { rest } from 'msw';
import lookups from './lookups'; // Map of lookup sets

// Fallback request handler
// If a Dev adds an incorrect request handler or forgets to add one this
// will stop the api from making a real call and chastise them. Sternly.
const mockNotFound = (req) => {
  console.error(
    `[MSW ${req.method.toUpperCase()}]: Add request handler for "${req.url.toString()}"`
  );
  server.printHandlers(); // put this here temporarily for troubleshooting
};

const handlers = [
  // default the lookup search
  rest.get(
    `${apiUrl}/lookups/sets/:systemName/search`,
    (req, res, ctx) => {
      const { systemName } = req.params;
      const type = systemName.toLowerCase();
      const result = lookups.get(type) ?? []; // default to empty array if Map returns undefined
      return res(ctx.json(result));
    }
  ),
];

const server = setupServer(...handlers);

beforeAll(() => server.listen({ onUnhandledRequest: mockNotFound }));
afterAll(() => server.close());

afterEach(() => {
  server.resetHandlers();
  jest.resetAllMocks();
});
```

## Actual request

```js
// Example of making a request. Provide your code here.
axios.get(`${apiUrl}/lookups/sets/:systemName/search?selectedValue=${ObjectId}`)
```

## Current behavior

On certain tests I am getting the following output for no apparent reason:

```
console.error
    [MSW GET]: Add request handler for "http://localhost/api/lookups/sets/VaccineTypes/search?selectedValue=72600"

      at ../[my/server/and/handler/setup/file.js]
      at RestHandler.<anonymous> (../node_modules/msw/lib/umd/index.js:25950:63)
      at ../node_modules/msw/lib/umd/index.js:1719:73
      at __awaiter$3 (../node_modules/msw/lib/umd/index.js:1715:14)
      at ../node_modules/msw/lib/umd/index.js:25949:37

   // all of my not found handlers are printed, and...

  console.log
    [rest] GET http://localhost/api/lookups/sets/:systemName/search
      Declaration: [my/server/and/handler/setup/file.js]

      at ../node_modules/msw/node/lib/index.js:8177:29
          at Array.forEach (<anonymous>)
```

## Expected behavior

That my request matcher work as written. I run my jest testing with `--runInBand`. The setup above is manually included in every test suite. Other handlers optionally added appear to fire, most of the time, but occasionally the same happens for no apparent reason. Printing the handlers show them as being there, every time, from the same `*` handler that says the requested url handler is missing, but can still plainly be seen in the path.

**Comment by cutterbl** [comment]
Think I *may* have found my issue, but not sure how to address. Our app wraps `axios` to take advantage of (and simplify access to) request cancellation. We're still on 0.21.1 because we (not for much longer) have to support IE 11. Ultimately my question becomes, is it possible to decorate `res`?

We currently take the promise, returned from axios, and attach cancellation token methods to the promise:

```js
const CancelToken = axios.CancelToken
const source = CancelToken.source()

axios.get('/user/12345', {
  cancelToken: source.token
})

const promise = axios.get(url, {...config, cancelToken: source.token})

// adds these cancellation helpers to the promise returned
return attachPromiseProperties(promise, {
  cancel: source.cancel, // the cancel() method
  isCancel: axios.isCancel // axios' method for determining if catch error is a cancellation
})
```

And gets used something like this (which is why this *may* be a non issue):

```js
  const medStaffRef = useRef();

  useEffect(() => {
    // cleanup on unmount
    return () => {
      // eslint-disable-next-line no-unused-expressions
      medStaffRef?.current?.cancel?.();
    };
  }, []);

  const getMedStaff = () => {
      // kill active request if state updated during current one
      // eslint-disable-next-line no-unused-expressions
      medStaffRef?.current?.cancel?.();
      medStaffRef.current = ulEntity
        .get({
          urlKey: 'main.security.users',
          params: { userId },
          expectSingleResult: true,
        })
        .then((result) => {
          form.setValues({ MedicalStaffSK: result.MedicalStaffSK });
        });
    };
```

So my question becomes, is this something I can possibly emulate with msw response objects? Do I even need to?

**Update**
Realize that my implementation wouldn't matter, as it would still attach the 'cancel' methods to the promise from `msw`, they just wouldn't do anything right now.

**Comment by cutterbl** [comment]
Got my `onHandledRequest` handler straight (though still a problem #1134), but still unsure as to how to handle request cancellation.

**Comment by kettanaito** [comment]
Hey, @cutterbl. 

First things first, regarding this comment:

```js
// Fallback request handler
// If a Dev adds an incorrect request handler or forgets to add one this
// will stop the api from making a real call and chastise them. Sternly.
```

That's not true, the `onUnhandledRequest` has 0 control over whether a request gets performed or not. It's meant only to report when such requests happen. You can control whether the request is performed by halting the code execution via `throw`. That's also how it works when you use the "error" handling strategy. So, if you wish for unhandled request to never be performed, make sure to throw in your `mockNotFound` function.

Based on what you're trying to do you should be fine using the `onUnhandledRequest: 'error'` though.

> So my question becomes, is this something I can possibly emulate with msw response objects? Do I even need to?

Keep in mind that the behavior you describe with MSW is _server_ behavior. There's no request cancelation when handling a request on the server. You receive a request and you send a response. If your client (axios) has a requests cancelation logic it's not something MSW cares about.

The issue I see you describing is that some requests during the test are not intercepted. I've responded to you [here](https://github.com/mswjs/msw/issues/1134#issuecomment-1054859701) what you can do to debug this but I will summarize below:

1. Check the value of `apiUrl` and make sure it's correct;
2. Set `onUnhandledRequest: 'error'`, this will print handler suggestions;
3. Isolate a problematic test and run it in a debug mode:

```sh
DEBUG=* npm test <...>
```

As I've said in the linked issue, I will be happy to look into this if you provide a reproduction repository. Until then I have to treat any issue as non-reproducible. Thanks for your understanding on this.
