### ISSUE TITLE
onUnhandledRequest Firing On Handled Requests

### ISSUE THREAD

**Issue by cutterbl** [kettanaito/msw#1134]
## Describe the bug
I am writing unit testing with jest. I have my server setup, and have defined my handlers. My tests pass. But, my `onUnhandledRequest` handler is firing on every request.

## Environment

- `msw: 0.38.1`
- `nodejs: 16.14.0`
- `npm: 8.3.1`

## To Reproduce

```js
// in my server setup process
const mockNotFound = (req) => {
  console.error(
    `[MSW Error]: Add "${req.method.toUpperCase()}" request handler for "${req.url.toString()}"`
  );
};

beforeAll(() => server.listen({ 
  onUnhandledRequest: mockNotFound
 }));
```

```js
// in my handler setup
rest.get(
  `${apiUrl}/healthy/api/casemanagementconfiguration/:objectId`,
  (req, res, ctx) => res(ctx.json(config))
),
rest.get(`${apiUrl}/lookups/sets/:systemName/search`, (req, res, ctx) =>
  res(ctx.json(patterns))
),
```

```
// In my terminal output
console.log
    [apiUrl] http://localhost/api

      at Object.<anonymous> (caseManagementOptions/CaseManagementOptions.spec.js:75:9)

  console.error
    [MSW Error]: Add "GET" request handler for "http://localhost/api/lookups/sets/CaseNumberPatterns/search"

      at mockNotFound (../setup.js:108:11)
      at onUnhandledRequest (../node_modules/msw/node/lib/index.js:8019:9)
      at ../node_modules/msw/node/lib/index.js:8049:13
      at fulfilled (../node_modules/msw/node/lib/index.js:51:58)

  console.error
    [MSW Error]: Add "GET" request handler for "http://localhost/api/healthy/api/casemanagementconfiguration/9"

      at mockNotFound (../setup.js:108:11)
      at onUnhandledRequest (../node_modules/msw/node/lib/index.js:8019:9)
      at ../node_modules/msw/node/lib/index.js:8049:13
      at fulfilled (../node_modules/msw/node/lib/index.js:51:58)
```

## Expected behavior
That only truly undefined requests be captured by the `onUnhandledRequest`.

**Comment by cutterbl** [comment]
I think I understand what's happening. This is fired on any request that wasn't defined at the time `server.listen()` was called, so it isn't matching on requests defined through `server.use()`.

**Comment by kettanaito** [comment]
Hey, @cutterbl.

If `onUnhandledRequest` callback is called then one or multiple requests you're issuing are not described with request handlers. I recommend double-checking the value of `apiUrl`, and then following [this guide](https://mswjs.io/docs/recipes/debugging-uncaught-requests#run-in-debug-mode). Then, I suggest setting `"error"` as the value for `onUnhandledRequest` property. It will contain some possible suggestions in case there's a typo or a similar handler for the occurred request. 

I will close this but feel free to provide a reproduction repository that would showcase the issue. I will be glad to look into it then. Thanks.

**Comment by cutterbl** [comment]
@kettanaito Yeah, I thought of that. Which is why I added the `server.printHandlers()` (temporarily) to that `onUnhandledRequest`, where it showed the handler being there.
