### ISSUE TITLE
server.use issues with graphql. Doesn't intercept request.

### ISSUE THREAD

**Issue by MindfulBell** [kettanaito/msw#1139]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.38.2   |
| node | 12.16.3     |
| Mac Catalina   | 10.15.7     |

## Request handlers

```js
// For simplicity, I don't use any handlers here because the problem has to do with server.use() below. But rest assured
// it doesn't work when I have some base handlers setup that are then attempted to be over written.

const server = setupServer();

beforeAll(() => {
    server.listen();
});

afterEach(() => {
    server.resetHandlers();
});

afterAll(() => {
    server.close();
});


// Test code

const mockQueryResponse = {
        dealroom: { // some mocked data }
    };

    server.use(
        graphql.query(Queries.SuggestedBuildingsDealroomQuery, (req, res, ctx) => {
            return res.once(ctx.data(mockQueryResponse));
        })
    );

    const ui = <SuggestedBuildingsView dealroomId={123} />;
    jest.spyOn(useAlgoliaHelper, "default").mockImplementation(
        () => mockUseAlgoliaHelperReturn as any
    );

    const { queryByTestId, queryByText } = render({ ui });

    // helper function from gql testing docs, just runs a 0 second timeout and resolves a promise
    await waitForGqlLoadingState();
    await waitForGqlLoadingState();

    await waitFor(() => {
        // assertions go here
    });
```

## Actual request

```js
// we use codegen to generate react-hooks from our GQL queries. the Hook below is auto generated based on the query name

const {
        data: dealroomData,
        loading: dealroomQueryLoading,
    } = useSuggestedBuildingsDealroomQuery({
        variables: { dealroomId },
        onCompleted: (dealroomData) => { // dealroomData is being mocked, it comes up undefined }
        })
```

## Current behavior

In the onCompleted function above, dealroomData should come back with the mockQueryResponse I define in the usage of server.use();

It comes back undefined.

I have successfully used server.use() in another test suite.

## Expected behavior

dealroomData comes back with the mocked data, not undefined.

I'm not sure if its a race case and the rendering if finished before the intercepting can happen...it kinda seemed that way in my logs...Just very very curious why I can use server.use() elsewhere, but not here...the only diff I can see is i am using a mocked algolia hook here...

**Comment by kettanaito** [comment]
Hey, @MindfulBell. Thanks for reporting this. 

I suggest you follow this [guide](https://mswjs.io/docs/recipes/debugging-uncaught-requests). Otherwise, I cannot help much with a reproduction repository. Feel free to push one to GitHub and share it here so I'd be able to look into it.
