### ISSUE TITLE
request will always be in the pending state

### ISSUE THREAD

**Issue by Woodii1998** [kettanaito/msw#1149]
## Describe the bug
if i start msw, Mock requests return correctly but The original request will always be in the pending state

## Environment
- `MacBook Pro (16-inch, 2019) `
- `msw: 0.38.2`
- `nodejs: 16.13.0`
- `yarn: 1.22.11`

> Please also provide your browser version.
- `chrome 99.0.4844.51`

>  I Using local HTTPS and the trusted certificates are configured correctly

## My Code

```javascript
if (process.env.NODE_ENV === 'development') {
        const { worker } = require('./mocks/browser');
        // worker.start();
        window.__mswStart = () => {
          worker.start({
            onUnhandledRequest: 'bypass',
          });
        };
        window.__mswStop = worker.stop;
      }
```

```javascript
// src/mocks/browser.js
import { setupWorker } from 'msw'
import { handlers } from './handlers'

// This configures a Service Worker with the given request handlers.
export const worker = setupWorker(...handlers)
```

```javascript
// src/mocks/handlers.js
import { rest } from 'msw';

export const handlers = [
  rest.get('myUrl', (req, res, ctx) => {
    return res(
      ctx.status(200),
      ctx.json({ data: 6666, errorCode: 0, code: null, msg: null, success: true, count: 0, page: 0, pagesize: 0 }),
    );
  }),
];
```

## To Reproduce
1. start my project
2. Type ‘__mswStart()’ in the console

## Expected behavior
The request result is returned correctly

## Screenshots
The request has been in the pending state

## if not start
<img width="2001" alt="WeChat83625f1f36240a75ce34a556835c7684" src="https://user-images.githubusercontent.com/33593572/157041524-e0f627ae-962d-414e-a212-46903a915009.png">

## if start
<img width="1989" alt="WeChat30e927aa80da8772819cb5b92a9ef7a8" src="https://user-images.githubusercontent.com/33593572/157041601-72c36099-b2dc-4c4e-9805-546b73482aaa.png">

<img width="2017" alt="WeChat513ea94b5e3a6a383a95a68cc9435229" src="https://user-images.githubusercontent.com/33593572/157041626-37c573d3-ea4a-4e69-a57c-5b4411ea0067.png">

**Comment by kettanaito** [comment]
Hey, @1322756558. Thanks for reporting this. 

Any chance you've forgotten to link your project? I'd appreciate a reproduction repository to look into this, otherwise, there's little I can do. Thanks.

**Comment by Woodii1998** [comment]
> Hey, @1322756558. Thanks for reporting this.
> 
> Any chance you've forgotten to link your project? I'd appreciate a reproduction repository to look into this, otherwise, there's little I can do. Thanks.

It may be a little difficult This project is private and this project is a bit complicated, I maintain an old project that uses local https startup and single sign-on (SSO), I will try to write a reproducible demo, very Sorry for taking up your time, I'll close this issue first and re-open when I can provide a reproducible demo
