### ISSUE TITLE
Contentful (axios) throws: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by arcos** [kettanaito/msw#1150]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.39.0   |
| node | v16.13.0     |
| OS   | Windows 10  |

## Request handlers

See a complete reproducible repo [here](https://github.com/arcos/msw_protocol_bug). Just `npm i` and then `node app.js`.

## Current behavior

Mocking a minimal get request to Contentful's readonly API causes `msw/NodeClientRequest.Client` request to throw:

```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
```

...akin to previous issues, but something new must be going on here. Under the hood Contentful uses axios, which might shed some light on the cause. If I revert back to `0.36.8` this issue does not happen (but has its own set of issues).

## Expected behavior

For msw to intercept the request successfully and return a mocked response.

## Screenshots

![image](https://user-images.githubusercontent.com/143747/157125651-7171a3df-d0f6-4906-8b18-6a317e476ba6.png)

**Comment by kettanaito** [comment]
Hey, @arcos. Thanks for reporting this. 

I will look into the reproduction repository you've prepared and update this thread with my findings. This may be related to #486, #632, #865, #263. Usually, issues like this one mean that the client you're using (Contentful in this case) constructs a `ClientRequest` instance with a set of parameters from which MSW cannot infer all the necessary information it needs to process the request. 

This is how you can debug what's going on:

```sh
DEBUG=http* <your test command>
```

**Comment by kettanaito** [comment]
## Insights

The error is thrown when validating expected and actual protocols of the request:

```js
  const protocol = options.protocol || defaultAgent.protocol;
  let expectedProtocol = defaultAgent.protocol;

  // ...

  if (protocol !== expectedProtocol) {
    throw new ERR_INVALID_PROTOCOL(protocol, expectedProtocol);
  }

```
> [_http_client.js#146-147](https://github.com/nodejs/node/blob/418ff70b810f0e7112d48baaa72932a56cfa213b/lib/_http_client.js#L146-L147)

The request that Contentful makes has the following options:

```js
{
    maxRedirects: 21,
    maxBodyLength: 1073741824,
    protocol: 'https:',
    path: '/spaces/7fa304q47ttv/environments/master/entries?sys.id=7na3pnjbD0TAwCbl7H4kOt',
    method: 'GET',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/vnd.contentful.delivery.v1+json',
      'X-Contentful-User-Agent': 'sdk contentful.js/9.1.12; platform node.js/v16.14.0; os macOS/v16.14.0;',
      Authorization: 'Bearer b3-BHjF6jhid0Xsr7hi4yj_8YmQ_gXsAmNklWJj2f8M',
      'user-agent': 'node.js/v16.14.0',
      'Accept-Encoding': 'gzip'
    },
    agent: false,
    agents: { http: false, https: false },
    auth: undefined,
    hostname: 'cdn.contentful.com',
    port: '443',
    nativeProtocols: { 'http:': [Object], 'https:': [Object] },
    pathname: '/spaces/7fa304q47ttv/environments/master/entries',
    search: '?sys.id=7na3pnjbD0TAwCbl7H4kOt'
  }
```

You can see `agent: false` being set. This means that the `Agent.globalAgent` will be used instead as the value of the _expected_ protocol:

```js
const defaultAgent = options._defaultAgent || Agent.globalAgent;
```

> [_http_client.js#130](https://github.com/nodejs/node/blob/418ff70b810f0e7112d48baaa72932a56cfa213b/lib/_http_client.js#L130)

Providing `agent: false` is a valid scenario:

> By providing {agent: false} as an option to the http.get() or http.request() functions, a one-time use Agent with default options will be used for the client connection.
> —[Node.js 16.x documentation](https://nodejs.org/docs/latest-v16.x/api/http.html)

The global agent is always constructed with `protocol = 'http:`', as declared in the `Agent` class:

```js
this.protocol = 'http:';
```
> [_http_agent.js#100](https://github.com/nodejs/node/blob/418ff70b810f0e7112d48baaa72932a56cfa213b/lib/_http_agent.js#L100)

But the intended protocol (`options.protocol` from the Contentful request options) is clearly `https:`. This means that:

- The expected protocol is `https:`;
- The actual protocol (from the `Agent.globalAgent`) is `http`:` (the default one).

Thus the protocol mismatch, resulting in the following error:

```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
```

**Comment by kettanaito** [comment]
Note that `https` module has its own global agent, which extends `http.Agent` and overrides the `protocol` property:

> [https.js#182](https://github.com/nodejs/node/blob/418ff70b810f0e7112d48baaa72932a56cfa213b/lib/https.js#L182)

That is, however, not the agent used in the `_http_client.js` logic, as it always imports the `http.Agent`:

> [_http_client.js#56](https://github.com/nodejs/node/blob/418ff70b810f0e7112d48baaa72932a56cfa213b/lib/_http_client.js#L56)

**Comment by arcos** [comment]
Just for other peoples' future reference. This was a matter of passing node's `https.Agent()` to the Contentful client param `httpsAgent` during instantiation. Thanks for your help @kettanaito.

**Comment by kettanaito** [comment]
A nice observation, @arcos! 

I think MSW should still handle this scenario. The global (default) Agent must be assumed and derived from the request option's protocol. This should rarely happen in practice but it's a matter of bullet-proofing the `ClientRequest` arguments normalization logic. Will land in the next patch release of the package.
