### ISSUE TITLE
Inferred path parameters fallback to "DefaultParamsType" when specifying "RequestBodyType"

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#1175]
- Related to #1073 

## Current behavior

```ts
rest.get<never>('/user/:id', (req) => {
  req.params.id // is not an inferred type
  req.params // DefaultParamsType
})
```

## Expected behavior

```ts
rest.get<never>('/user/:id', (req) => {
  req.params.id // is an inferred "string"
  req.params // { id: string } (inferred)
})
```

**Comment by kettanaito** [comment]
TypeScript does not support partial generics default values, so the behavior above is, sadly, expected. I can give it a try if we can somehow split the generic internally but I don't see that happening: the end developer must be able to provide both `ReqBodyType` generic and the string literal value of the path on the same function.

**Comment by kettanaito** [comment]
I think this is a deal breaker of the path parameter inference because it renders the inference null when the user annotates their request/response body, which I expect most of the users to do. 

Do you have any ideas on how we can fix this, @cmolina? 🤔

**Comment by cmolina** [comment]
I don't know. 

I just asked in the TypeScript's open PR, in case somebody can help us with this.

**Comment by TylorS** [comment]
@kettanaito you can definitely parse out path parameters using conditional types and template literal types. I have covered most of the `path-to-regexp` syntax. Here's a [playground](https://www.typescriptlang.org/play?#code/PQKgBApgzgNglgOwC4FoAmcoEMBGMJgACSAngA7QDGATnGatPMsDlgiqRVGCMAFChIsRKgzY8BYuSq16KRiOAIA9igCuCNVAhoUANyzVuvPnAC2ZZdSRgA3mACCAGjAA5MAF8wAM2rKzYADkSFAcysowOBAwSIF8fJwEAGLhAApYSAAWYAC8QcAAXKzUhawAXgD8cYlgKcrp1Fhm3HkNTVAA8t4APHXpWQB8CdK14QCSyBDUljAZOrlgE0hTM3O9aRmZLrbFBUEAjIEu5XuBAEyBHkMC4ADKSIY2AEoQAOZwygh7bWYQy9RgAAitwAMjx+HwIAAPSzWMA1H7dByQKHLBBobhQJC0BCvAYLAAGBQAJLYHB4CfFobCbJRPliwGRDE0FkiUWiMWAsTi8QAKJmNMx7BwASm+zLMSPxOXxRNJAqaFKpMKsNhqHXoHwQWBgbOhHMx2MQeMJpPJFUpkJVcLpCAZyk1nx1rOR+og6MNPIG-IlwrFYA1SC1OqluVl8olHgtypp8JGqWoEG8cCh3VS7PdnO5xpcrtRmc9xulYAJtlJqQ8Zo8SqtsdtDLIieTUNZ6bdHq5RtxuYzHcR2dx+IAPmAAKoIbW-NDextJlPfFwKoWOf0Juep1K56VDMAlsu2WfNysHyM10AgPg8MAAYXp2LUlBsAEc1FMSIyJVBLyZqaq4xQwAARVfagSERABpXssy7V4XAANSgwtBwWBwADoAFEXx1KBujglwCQJfF205fYwAqMBIL2AlSXAjwclJOCzxAC8r1vO170fMAXzfD9BS-cFaz-etnxAsCJVZSDiKQ2CwAQqTOy9XkAGsIBIPZwJcAwYFfPY4JFMNLxLUkVJIOjSS018KTALBuGAt8IPg65z2-MAyimZQwCsMAzCsAgmSyXiQjAAB3OAYBgMAom8jJKEyeYkA8rJMF4ppv34X84RqAAtdyOmoABZXy9XzDsBxNPJqNsREHAGDwQEtDLaTvVzcoK3yXUQhSix9QU-T2HK-DywrE1DGUSxJE9BTqhrrTVEYOgQCAhqKvMDS65CKvLCUpQ8ABqS1nKvT4CC8nzEw-AKBSC0LwsiggzBiuK0HhRLMmSpc0sEm1muO5bzryYq1rKmdfRXPYFqWtqRpqsNxojKb9viQ7wBvRM5m4LI-M2MIUETV5qS5EhkCwFtvC87jQJS35-n4n9Zv-Ag7NAn4cMAzqXiwNBPhgEgHGoRoSG6JmxMFbo2BIFxxYGAYXCeTqysJQiFjZ+S0a5hAebAABtQzEG8KYwAACQgTmnEM1CLb1g2ABUsDCvgAF1DPI4WWe6Qzd13NDrxspBultsLZZN9Web5gWhdExFxclhASGlmWPc9gj2bIksAB004qM1UJ9rFumN031rxKyqNJJ4PAAMmz3O-YLtAXGBpVPbAHcwD2J4YyE5qKZF9pW06tXuffLXXe26PrNjmWwAt1Cw6wQXR9F8epYGB3vXNi2lygb4+H9Rf2jTbd08z+H2lQgArZREF5QIK8CEUrJsoDI8-Q-O++9iwA0Sd5gq3lUJACKAk1luDCXfnNAC44f7PTyIkZQ3gv4TiaDoJGzEXK3gsMobQ3BlCYwBP5bIV1uAiA8lgLkxp8AXUyJ9RqDMwD9EyAAKSvggQGBYwCDw1u+MqWs14oQHsHIe2srYAjri4GeIiwABxgE7Xc5FKopGoA9JADQ-be19vnYODcYLS2PAw5hiAkQ5w0dIlwnDNY8LXrVSku4qIzTrM1AhBiED91VoIrhRdeEg2sNvehq5NjOMPrDWwusEE9RCKhfAuIAo5FiWAAADPpEJzdExIDUNQFxycn76JYW-XcHh4i7mEtrOKhcZ4PDCg7BYRDDLFLJkojIywYFGVsPU5RqjeSlLQA-CMWRnG8gqTAB+lpdypPSS4tpjT5jZICbk1IQwCk3BYuARRyjuBkLIHACAlAToII2ZsFyhBKBzFeFYd8GCcCIAyFYQ5UBEA7ISahfYABmVC8SaH0zqVYdpjwFjhL2GVfSY1kmBQWImHyegIAgmDsaW4swoCZHCSKQpYA4BhKuqhLEjwoAAHU4BZBvrYe+STE5jIyYFQyizdxorAOEzFDwfF4oJYEDOVQRQkpSX8cZFL8korJS4q6uQ4mBECKnEVbcSzAHhkgJUizkbpXpjUVZGRVFpnljolCGEsIwBwpuEsSt5L7GdvQwy7cIAQqhTC3EcKbKZCCfJAkrLSSSIAPpN1Ti8C10LOawvhXa+ZpqwCeuUJC71GBrV+vtSVTkpZnUIH1gCN1NiPXmpDZan1EbbV5IlW2aNtkX58W6K6lwrrW7kVSIG3Na196SmLai+NBsXVlpNbYyVZdU2hqta8G1CLD5MWWUGjtBB6nBUMM9WAtroCMibCmKdiZKDpLuZCnmHzYw1GDZ2jN3bI0wzyKtdhBIpW2EkeXYB5EN3pvDdurNTx8TCnAWAYp4K01ht9bajq8lga8iwH1QdXqu09rtbu-EIL8A2BaNZTF8Adm8mRYZYKb1KG8igPS7FTLEWBGAMSuwicIMoeEDB-YyLeWGX5VyEBf6X0AZ3Qs1BYB0LokHe8T44pBR-ANsCMEJgbhgHuL8l4zGvj0dRI0TiPx2NGB8H4AIDCBICGAMJ7EWBOKYyphJnBagbDwOslQpZq6-wIk-F0NhpUNV5AwUyR8aZsXW3qK-BhtnVE4RqtLJGCn0IieU2qOKz8eJLnU55TTnk9m6flV9CBjMC3tGM1W9hwMFgWa8xHN8jn7ObFs8LQ+rn5M3k+JCuE+yAqsEoEpetCUdNpLIJQ7TBDApfjC7QwzWRUs+KCa0TqlVJF1w8E649DaATSPdeRcxw8Z4Obs61uuU9HUn1sINgksic0dbjQmo2wcPBHskfN41I3tZjfSxNkImjOZT3281w7OFpGr0rctvrq3uv7kkYBasWc7s2ztjAIbHD3Gay1mdzILWjtTfwvuZ7UYCTiItuNpz3RKrzeu622LHZOv9bW5zDwj3Udg5W+9sKX3dt-ahwdmHwO9ykjBxD6eRPzsw7hx9ikCOJXJ3khWuR33OZCN4YGgnqQnZ6YEo1+MNmJsH33R2Xbljcy3GtgsWwVx+FuI5x4rWXWtFU9Qltj7i3y3C7duovOpj2ch24TBLxUuZcV3oY8FrTQjE12O-XIuU8HDS9c62l31tUHLIVWuoX1gbeSjF9BHk5vixB+4DNnHAJT3GqcwH1mUXmiA5wk8FwZvHCu8DeHscSCpzGpBZypXv3IKIFqIgNArh9QTDQNCJErvOqaDMFEAE5Ekjl8r6iavtePd3rAItfLDsAUwUTgU93t3XXHigcgtAL3k3kXsATkvLi2-og70gLvqYe8N7UE3g2rf29V-RN3+vex+9TAdhUIfPJPBZ-H6jt1pIp9TmrHPuwRvOdL7L6vw-NfN-1-ko3s3qnCvhXj-sftbL3mftQIPkXDfmPg6lHmAA-lVNtCerVODvnu-srp-k8BflfsaHARKtnijqtsgYiGgS-pgYvvWkGjAQrKPkQXfqQXoqgajrehgWzgvj9sPDgXgbAQwcKEwY2iwaLBQYjJwVgcXjQbgXsATmVJDvSjyLwlUgIY4EIYmiIbbhQfVFQdwdrLwbIXoZYoQYIQgW9hoVtKIWwdYroUXjwdIXQTBCYXYHKmggLoqiMDWlAMnkLOqiHkGgInYZ4nwnkCrHmsfK9k9l9l4T4YBLLK3HsGEWtASJEVjtEYnt4RdkLPEYGkkQeogd1lXOYVIvTq-jEVkYbuUSTmrregkZIaNhbKnr5szBKHBDqK+ELNdvznTL7gBMLPHr4Z+jBObrLvLqEeoWjjPkUZrnjmUaJAMZUfMSLs0A7qHnUXkcjqkatrRHMSlssThBpBnhAbkRMbRNGGzh7mAJbqonACGDWg4HnOBG7hKhsTGogTscapcZbvcY8XUR7m5osAgDQOau6EFGoGQFJv4IsIgkGBFPij4OXusi4uXtCPCJkBkKitwCoGqFgCpAgN0T7gZiMCAWvhvnXtbC4GMNvrvgCHkPEsWFSfJCZNppcfvt-p3kfn-hSW4LPGgGgN0GMC4PsNLBKmMF7vpplELudplkjsHkWAsLKRHogW6hnIgc9mekBEzpaDUDWm0dpBAN0JJOEfFnkEackcqWZMUaeh6hKmVPEDqYng8X7GaXFmZoOnYd0C8HSNQPyT8UgOBKpIaVPH6XqR0U8dlg6fZBKE6QGYLC6aZl6AsPGW8cUbRPRMUUmqnJRBRPaZ4Y6ViKGQacmdJMWMWS0hPumSel9nLCzqwaQcODntAonORHac3O3IGnacMABIllZrum-tQaXsyQgg4DAQ4FrOBCoXRgxs9AJlqHsB5kpmJhKAFr4FCbJtxoIHxnCLOSxoCf8KsEGPSHJg1h4QBEsCsBEGsIqUXC4CzJ1CzDFiKe1mYarujr1jMZ9q-jkoYonLuOedMJecsOhl4d0LcFVviiBVdreZ+JSQgPQBebMMsDDtDtig7lPCzNLFrPEotruHUd+awhMPBQBYhRAMhcTqhfMtBXxAMFhWvOKe4b0QQIRfuYBaRahYZE5oEcbhPCQLwmbLuHefJHLvxQEYrtxeLLwgsHxYZJcXkHLnwMWJxWJZzl1goVttrkbJ1IGMGLqGuM2EWqjmuC4E-joM8WziSWAVyUROEUOVbnxL+anMxQhXMDDg5c3BSW5Z7CzCJc3M3A4GQBQOiHpSmJ6beYmPhNXBoizFrBZRyb-uSavNotfiOIAVMNYgnL5b5V8YOt6fyYbFRe0DFQfnFeAavK3JleVZ7HsE5cRS5ahdyd5UGqHonHsIbPeTOqmJIkZY2dPpVeRDVQeWxa1p5R5ZlQJTBZ5f5YFWgMFamE0d1ZVPrn7NFUtb0MVevpyQlS4LZRhQ7ElQQSlTvs3ulT5VldLlcTlVYHlQVc0FrKtbFRtfFT3ttapNprtZVbhS1ZpfJNpU6LpR1QZatt1eQYZfHM2fQp1DtZ+A5f1XBSxSRa5WNZ7KNUjXZe0KdZlVNZmLNaFfQuFY4MYnnCtYTctS9SQG9Z+IlU7hlajdlV6VdfnDdVAHdSTWmGTRTdRXRUjR9aKXDc5UhfVUzbLM1W2d9eETjV1fjSDUDWZY5XzbVQLcNUjSjZld5ZNQFdjQDfNfjatcTfbnqlDZzftYODTZjedZbvTT6YzWjbdbrezQgu9Q5ZVdVZMArUNbXELUcdZWtATpIs4PWqtgAEI4Vy1EWDVOboZr7+ye1NEE7+3B3O2Alh2sUw4NUwVNVe3c56FaxNEe584nmMWOAa1BVa1cVCISV7V40EBDH+HXkmmiXhEE4bwa6o4TD4oiWSIgiOw7bZ0zxt1IARVkis0gjG3FzliJh6IUiLbtkEnhZ0IDUp1ob4qZBR0cXYpl0eIV0iWCXhHCWGQ1mN16Fb2GRr4b2-bLyxxOwMny3h0UXYqe0E4zxNFr60WV0v37B0Wz2C5nmu233WBs021QCh4KlaWOjai6V1kGy1HGoH1rSG3tDg086fg52V103bIM3zXIO4GM6toE4irm7T0Q21lWGra3owOQ2vUO3Q3NzDbZ3RW4EjEW3oNW2YN8QoM4MSo84EM3byQmVoDGoPVklb5MmUOAPg3-mDV8OqqNWCObXPWZ2i1cNHGEPXkS2GVS2QPR7PHnoUPk1UP2U0PayVRrjHi61YOV2NyU5oO5W430Nrwh17Bc6I6gOHngNpgA2S0QA3WA1QNg1s6wPsLwPNDg1azGMT2RVE3mOj3WKMN2VBghiW38msOFXYMcOOOENKN530U9FEk-3w1zBSOPDWZ8QuBllBNANe1grZ1r1sMTkiXWMM2HHRUTlDB841ASOsXAUZHuy7ivHcAS6m57U1Po0cWJh6AfBaBn3DwX0kBDO7ht5GA2DyQ4DhD4BsALD3gQAKXKxTPCKo5iLq4fkaUdMkVdNRmFoOWrWG4DNKFrwY2AP3MnNzA1qqoHONVrjjPKBaAuALNYg0XYWPO-2sUvNFNvPp0fMTMVO-NIA0Uf2Jx4VjOQvZOEmSl5P80QAgv-01MD3DPNDb2ItfPcDKXK43PGh8U8VzNl6LOdQrMRAmz4mKW-LyQ1o+MAiHGSJwTNpPPLCYtIDoaxk9O+XQudSbOpwpE0QlwlhFE7H3MQuEu0WAv5OK1+x4QPNV2fNaBawf2m2ezQvwtZ1BFaxGtjYEuasAtxOV1yuasf2V3eDYQQBtMjDcsYuJ6qL8uBmGRlnyHYtEuH1BGS6jMQAau+s+3Z3yEUsiXCvLOrP0vbN5Dios6mvM3YWpxGtOZhVBuQtasOyV3QtVKOPGtE4+KD1pnj2ZvyvYVT0ZvBvZu2v2uOsARgXwBIAgV11unXkkEGyFGIHbZs4E4HMzxNsQXdNXYZN0N85AA)

**Comment by kettanaito** [comment]
@cmolina, thanks! Let's see 👀 

@TylorS, hey. Yeah, we've already implemented and merged path parameters inference. This is an issue describing how generic default values get lost in TypeScript if you supply preceding generics:

```ts
declare function foo<One extends string, B extends string>(path: B): void

foo('/bar') // "B" extends "/bar"
foo<'hello'>('/bar') // "B" extends "string", "path" value inference is lost
```

**Comment by TylorS** [comment]
Ahhh I see, sorry about the noise then. I saw the cross-post on the TS thread and thought I might have something useful for you all

**Comment by TylorS** [comment]
I'm not familiar with this library, but one thing I've done in the past is creating a curried function like the following to add constraints without needing to lose inference on additional params

```
declare function foo<One extends string>(): <B extends string>(path: B) => void

foo<'hello'>()('/bar')
```

**Comment by kettanaito** [comment]
Yeah, splitting it into multiple functions will work but it's not the API we have. It's crucial so that the request handler functions remain flat:

```ts
rest.get('/resource', resolver)
```

Moving the request/response body types to the `rest` namespace also doesn't feel natural to me. What a conundrum. 

Not sure what I feel about moving those generics to the resolver. I don't know if this is a supported syntax:

```ts
rest.get('/resource', <RequestBody, ResponseBody>(req, res, ctx) => {})
```

**Comment by kettanaito** [comment]
I had a wild thought to try to propagate the path type to the resolver like this:

```ts
function createRestHandler(path: PathType) {
  const resolver: Resolver<PathType> = () => {}
  // ...
}
```

I have doubts this will work but will give it a try in a playground.

**Comment by kettanaito** [comment]
I've tried any possible syntax there is around generics but they do not work this way. Whenever you specify at least one generic, all the other optional generics automatically take their fallback value. 

I've even tried assigning `RequestBodyType` and `ResponseBodyType` on the resolver itself. And while that's a correct syntax, I have zero idea how to provide those generics:

```ts
function createHandler() {
  // There's no way to provide "K" when calling this.
  return <P>(path: P, resolver: <K>() => void) => {}
}

const handler = createHandler()
handler('/', <string>() => {}) // TypeError!
```

Sadly, it seems we'd have to revert this awesome feature.

**Comment by kettanaito** [comment]
Automatic path parameters inference has been reverted.

**Comment by cmolina** [comment]
@kettanaito Thanks for the time spent trying to make it work. I think reverting the change was the correct decision. Maybe one day TypeScript will support this use case.

**Comment by kettanaito** [comment]
I'm sad we didn't get to ship this to our users. @cmolina, thank you for the fantastic work on this. The change is not forgotten, and I hope once TS will get around generics and we can merge this.
