### ISSUE TITLE
unsupported MIME type error in CRA v5

### ISSUE THREAD

**Issue by eldyvoon** [kettanaito/msw#1178]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

The script has an unsupported MIME type ('text/html').

### Reproduction steps

run npm start on my repo you'll see
```
The script has an unsupported MIME type ('text/html').
```
on the console

### Current behavior

doesn't seems to work well with CRA 5

### Expected behavior

it should work as I used the code from https://github.com/mswjs/examples/tree/master/examples/rest-react

**Comment by kettanaito** [comment]
Hey, @eldyvoon.

The error means that the worker script URL you're pointing at serves a static HTML page and not the worker script (application/javascript). This means the `mockServiceWorker.js` file is not available where MSW expects it. This is almost definitely an issue in your code.

Did you forget to run `npx msw init` in your public directory? Make sure to adjust the configuration if you're using a custom worker script URL (see `serviceWorker.url` in [Options](https://mswjs.io/docs/api/setup-worker/start#options)).

**Comment by haikonguyen** [comment]
Hi @kettanaito ,

I had the same issue thank you it helped a lot! 👍

**Comment by kettanaito** [comment]
You are most welcome, @haikonguyen! Glad my suggestion helped.
