### ISSUE TITLE
Unable to disable ("stop") mocking after msw has been started for the first time, when testing with Cypress

### ISSUE THREAD

**Issue by zac18992** [kettanaito/msw#1179]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/zac18992/cypress-msw-example

### Reproduction steps

Reproduction steps are in the `README` of the reproduction repo.

### Current behavior

I am running `msw` with `cypress` in order to mock responses for certain test suites. However, as recommended by Cypress, I cover a mixture of live API tests and mocks across my suites. In order to achieve this, I attempted to start/stop `msw` between test suites.

When trying this with Cypress, I am unable to get the desired result. After the first time the worker is started, even after calling `stop()`, it will always mock the responses from that point on. I do see the `"mocking disabled"` log in the console, and everything seems to happen in order, but the mocking still happens.

I have set up a reproduction repo in which you can run the tests. It switches (in order) between msw tests and live api tests to demonstrate what I am trying to achieve. Please check the logs to see the order that things are happening.

I may well be doing something wrong, in which case I would greatly appreciate your assistance.

### Expected behavior

After stopping mocks, api requests should not be mocked again.

**Comment by gilmillasseau** [comment]
@zac18992 did you manage to solve this? I am facing a similar issue

**Comment by zac-keakie** [comment]
Hey @gilmillasseau unfortunately I haven't managed to solve it and have put use of MSW on hold. I'm not too sure how the internals of this library work as of now. I'm not sure if any repo maintainers have an idea of why this is happening?

**Comment by gilmillasseau** [comment]
@zac-keakie my use case is actually a bit different, I am spinning a node application where you can enable/disable MSW for each request, I created an express middleware that looks for each request and checks if a cookie exists and boots the MSW server, after each request I stop the mocker server calling `mockServer.close()`. 

I need to perform more tests but for now It's working with the version `0.41.0`.

**Comment by kettanaito** [comment]
`worker.stop()` returns a `Promise` that you have to await:

https://github.com/zac18992/cypress-msw-example/blob/e1d82e15ea3f88c6261405185198e4992831cad0/cypress/support/common/actions.js#L11

Do that, and the issue should be gone. 

There's also been a ton of updates on MSW side since this has been reported, so start from updating to the latest MSW first.
