### ISSUE TITLE
Request handler not working when used in playwright test file

### ISSUE THREAD

**Issue by rajmasha** [kettanaito/msw#1181]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.), Firefox, Safari

### Reproduction repository

https://github.com/rajmasha/nextjs-testing

### Reproduction steps

npm install
npx playwright test example

### Current behavior

1. I have defined a request handler `http://localhost:5000/user` to return a mock response `{name: 'John'}`
2. I have a single playwright test that expects to see the text "John" when submit button is clicked on the index page
3. On running the test with `npx playwright test example`, the test fail as it could not find the text "John" due to the mock handler not working.

### Expected behavior

The request handler for `http://localhost:5000/user` should return the mock response - `{user: 'John'}` and therefore the playwright test should pass with the text "John" appearing on the page after submit button is clicked.

**Comment by josuevalrob** [comment]
What kind of error do you got from the console? 
maybe something like:
```
console.warn
      [MSW] Warning: captured a request without a matching request handler:
      
        • POST http://localhost:500/user
      
      If you still wish to intercept this unhandled request, please create a request handler for it.
      Read more: https://mswjs.io/docs/getting-started/mocks
```

If so, can you [print your current handlers](https://mswjs.io/docs/api/setup-server/print-handlers)?
maybe before your test, add:
`    server.printHandlers();`

**Comment by rajmasha** [comment]
This is the error I am getting when running `npx playwright test example`:

```
➜  nextjs-testing git:(main) ✗ npx playwright test --project=chromium example

Running 1 test using 1 worker
  1) [chromium] › example.spec.ts:20:3 › Request tests › should display John when submit is clicked 

    Error: expect(received).toContainText(expected)

    Expected string: "John"
    Received string: "Failed"
    Call log:
      - expect.toContainText with timeout 5000ms
      - waiting for selector "[data-testid=content]"
      -   selector resolved to <div data-testid="content">Failed</div>
      -   unexpected value "Failed"
      -   selector resolved to <div data-testid="content">Failed</div>
      -   unexpected value "Failed"
      -   selector resolved to <div data-testid="content">Failed</div>
      -   unexpected value "Failed"
      -   selector resolved to <div data-testid="content">Failed</div>
      -   unexpected value "Failed"
      -   selector resolved to <div data-testid="content">Failed</div>
      -   unexpected value "Failed"
      -   selector resolved to <div data-testid="content">Failed</div>
      -   unexpected value "Failed"
      -   selector resolved to <div data-testid="content">Failed</div>
      -   unexpected value "Failed"
      -   selector resolved to <div data-testid="content">Failed</div>
      -   unexpected value "Failed"


      20 |   test("should display John when submit is clicked", async ({ page }) => {
      21 |     await page.locator("[data-testid=btn]").click();
    > 22 |     await expect(page.locator("[data-testid=content]")).toContainText("John");
         |                                                         ^
      23 |   });
      24 | });
      25 |

        at /Users/raj/code/nextjs-testing/tests/example.spec.ts:22:57


  1 failed
    [chromium] › example.spec.ts:20:3 › Request tests › should display John when submit is clicked =
```

Here is the test file where I have also defined the request handler to return mock response:
```
test.describe("Request tests", () => {
  test.beforeAll(() => {
    if (typeof window !== "undefined") {
      const worker = setupWorker(
        rest.get("http://localhost:5000/user", (req, res, ctx) => {
          return res(ctx.status(200), ctx.json({ name: "John" }));
        })
      );
      worker.start();
    }
  });

  test.beforeEach(async ({ page }) => {
    await page.goto("http://localhost:3000/");
  });

  test("should display John when submit is clicked", async ({ page }) => {
    await page.locator("[data-testid=btn]").click();
    await expect(page.locator("[data-testid=content]")).toContainText("John");
  });
});
```

For some reason, the request handler defined above is not being used by the test.

**Comment by dstampher** [comment]
I am having a similar issue.  I have followed the docs to create my first request handler list, and I am receiving the expected response to the endpoint with axios.  But with playwright, the unhandled page response is presented in my browser.

**Comment by kettanaito** [comment]
We seriously need to stress that any browser-driven framework requires browser integration _on the app's side_. For example, doing this in your Playwright test will do absolutely nothing:

```js
const worker = setupWorker()

test.beforeAll(() => {
  worker.start(rest.get(some, criteria)
})
```

In fact, I'd be surprised if this doesn't throw! Because you write Playwright tests in Node.js where `setupWorker` mustn't be run. 

Instead, you should use `setupWorker` _in the application_ that you're testing in Playwright.

```js
// src/app.js
import { setupWorker, rest } from 'msw'

// Start the worker in your app.
// Feel free to make this conditional.
const worker = setupWorker(...handlers)
worker.start()

window.msw = {
  worker,
  rest,
}
```

Then, serve the app and navigate to it in Playwright. The mocking will be enabled and you can control runtime behaviors by the `window.msw` binding!

## Example

I highly recommend checking out the setup of the Cypress usage example:

- [**Cypress usage example**](https://github.com/mswjs/examples/tree/master/examples/rest-react/e2e)

You can swap Cypress with literally any browser-driven framework (e.g. Playwright) and the setup remains the same. Because if you look into it, you notice that there are 0 things needed on Cypress' side—you just write the test, that's it.
