### ISSUE TITLE
Failed to locate service worker on address containing credentials

### ISSUE THREAD

**Issue by mstaniuk** [kettanaito/msw#1185]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.), Firefox

### Reproduction repository

https://github.com/mstaniuk/msw-browser-with-credentials

### Reproduction steps

1. Install project by `npm i`
2. Run dev server by `npm run dev`
3. Go to `login:password@localhost:3000/`

### Current behavior

The MSW throws an error
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/25054081/161048801-b08c5765-c5af-4525-bada-ce1740d9bb53.png">

The service worker is registered on the: `login:password@localhost:3000/`
<img width="669" alt="image" src="https://user-images.githubusercontent.com/25054081/161049104-b0d3c015-f3d5-4834-b670-da714c8dccf1.png">

Mocking is not working.

If you open the address without credentials, the MSW works correctly.
If the page is protected by basic auth, the user need to input credentials, and MSW works correctly.

### Expected behavior

Service worker is registered and found correctly.

**Comment by kettanaito** [comment]
Hey, @mstaniuk. Thanks for reporting this.

Please, have you tried using the custom Service Worker URL as the error message suggests?

You can do that via the `serviceWorker.url` option to `setupWorker:

```js
setupWorker({
  serviceWorker: {
    url: 'http://login:password@localhost:3000/mockServiceWorker.js'
  }
})
```

The second thing I'd suggest to try is to see if the worker script is indeed served on this path:

```
http://login:password@localhost:3000/mockServiceWorker.js
```

Can you see its contents in the browser if you open this URL? If not, then the script is served from a different path and you should account for that in the `setupWorker` options. 

We have a few tips on worker scripts and custom worker scopes in the [Debugging uncaught requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests#verify-the-workers-scope) recipe. 

Please follow my suggestions above and let me know if the issue persists. Thanks.

**Comment by mstaniuk** [comment]
> Hey, @mstaniuk. Thanks for reporting this.
> 
> Please, have you tried using the custom Service Worker URL as the error message suggests?
> 
> You can do that via the `serviceWorker.url` option to `setupWorker:
> 
> ```js
> setupWorker({
>   serviceWorker: {
>     url: 'http://login:password@localhost:3000/mockServiceWorker.js'
>   }
> })
> ```
> 
> The second thing I'd suggest to try is to see if the worker script is indeed served on this path:
> 
> ```
> http://login:password@localhost:3000/mockServiceWorker.js
> ```
> 
> Can you see its contents in the browser if you open this URL? If not, then the script is served from a different path and you should account for that in the `setupWorker` options.
> 
> We have a few tips on worker scripts and custom worker scopes in the [Debugging uncaught requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests#verify-the-workers-scope) recipe.
> 
> Please follow my suggestions above and let me know if the issue persists. Thanks.

Hey, thanks for the quick response!

This solution
```
setupWorker({
  serviceWorker: {
    url: 'http://login:password@localhost:3000/mockServiceWorker.js'
  }
})
```
works correctly on Chrome*, but on Firefox I get a different error that I cannot fully understand:
<img width="1889" alt="image" src="https://user-images.githubusercontent.com/25054081/161056414-48b5eec1-c25c-436a-9bc0-6e46aef08dd9.png">

Additionally, I think that setting the credentials and full path in the code may not be that good in terms of maintainability 🤔

I've also checked debugging uncaught requests with no luck.

While using `findWorker` function in the `worker.start` I've found out that 
`scriptURL` is `http://localhost:3000/mockServiceWorker.js`
but
`absoluteWorkerUrl` is `http://localhost:3000/mockServiceWorker.js`

I'll prepare some more examples in the repo provided above in a few moments.

[*] I've got Chrome once into an infinite refresh loop but I doubt that it is because of MSW.

**Comment by kettanaito** [comment]
Can you share more context about why your application is served with credentials? I don't think that's ever the case. Looks more like you're serving the worker from a host that requires authorization. Is that correct? 

In any case, this looks like a browser-specific behavior. MSW calls `navigator.serviceWorker.register(url)` where `url` is `serviceWorker.url` value. We do analyze the URL for internal purposes (to ensure it's always absolute), but we are not in control of whether the browser can digest certain URL schemes.

**Comment by mstaniuk** [comment]
@kettanaito 
Thank you very much for your time.

The app is the Storybook, mostly for internal usage, and the link is shared with credentials for the users' convenience.
I thought that it may be browser-specific since couldn't figure out the place where it may be failing in MSW source.

I think since that is the case we can close this issue - on our side, it's not critical at all - it was just for the convenience of our internal staff.

**Comment by jakub-coinmetro** [comment]
Came across exactly the same issue, our storybook is protected via basic auth with https://username:password@website.com. Like in the issue, it ended up failing to locate mockServiceWorker.js. 

Tried using `findWorker`, but using it caused endless loop in Chrome, regardless of output. 

Solution in Chrome and Safari for now seems to be overriding `serviceWorker.url` with `${window.location.origin}/mockServiceWorker.js` which evaluates to `http://localhost:3000/mockServiceWorker.js` - without `username:password@`

Firefox unfortunatelly finds itself in endless loop. Not sure what's the cause.
