### ISSUE TITLE
Memory leak while using node 16 (but not 14)

### ISSUE THREAD

**Issue by jyuvaraj03** [kettanaito/msw#1194]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [x] I'm using Node.js version 14 or higher

### Node.js version

v16.14.2

### Reproduction repository

https://github.com/mathanpec/msw-memory-leak-test

### Reproduction steps

1. Use node version `16`.
2. Clone the reproduction [repo](https://github.com/mathanpec/msw-memory-leak-test) (originally created by @mathanpec for #710).
3. Edit package.json to change `msw` package version to `0.39.2` and execute `yarn install`.
4. Execute `node --expose-gc ./node_modules/.bin/jest --silent --runInBand --logHeapUsage`.
5. Notice the heap usage increase for each test.

### Current behavior

There seems to be some memory leak going on when using node `16`. 

<img width="1099" alt="Screenshot 2022-04-05 at 8 15 11 PM" src="https://user-images.githubusercontent.com/29891001/161790867-42cef8b9-da01-4307-ae3f-53d2ba67ec7c.png">
 
The heap profile also seems to show multiple copies of the same msw index file.
<img width="1552" alt="Screenshot 2022-04-05 at 9 07 52 PM" src="https://user-images.githubusercontent.com/29891001/161792237-b6c763b8-49d6-465c-9d04-115ec062b205.png">

### Expected behavior

Memory heap should not increase for each test file run when using node `16`. Executing jest with **node `14` does not cause any memory leak** as shown in the following screenshot:

<img width="1099" alt="Screenshot 2022-04-05 at 8 14 27 PM" src="https://user-images.githubusercontent.com/29891001/161793045-3e034458-1a7a-4af0-8b52-2e06950c76c2.png">

**Comment by kettanaito** [comment]
Hey, @jyuvaraj03. Thank you for reporting this one!

We will look into the reproduction repo and investigate what is causing the leak. I somewhat doubt it's related to Node 16 but rather to the latest version of MSW. But I can't rule out any options just yet. 

If anybody has time to look into this, I'd appreciate the help. Otherwise, I'd get to it when I have time.

**Comment by finalight** [comment]
so should we downgrade the msw version?

**Comment by kettanaito** [comment]
@finalight, if you're experiencing this issue then yes, by all means, remediate it by downgrading. I'd much appreciate help with this one, it shouldn't take too much time to analyze the profiler's output and see where the memory heap/leak occurs.

**Comment by artkoshelev** [comment]
We also experience this issue, except we don't use `msw`. It also reproduces on Node 18.

**Comment by finalight** [comment]
> We also experience this issue, except we don't use `msw`. It also reproduces on Node 18.

ah i see, so the memory leak is because of the node, not the msw

**Comment by jyuvaraj03** [comment]
I searched around a little. It seems the memory leak is in jest itself (for node 16.11.0+) and not in msw. @kettanaito, feel free to close this issue if needed. Here's the [bug report](https://github.com/facebook/jest/issues/11956) in the jest repo if anyone is interested.
