### ISSUE TITLE
Unit tests in the project does not run tests in `src/test` directory

### ISSUE THREAD

**Issue by Xayer** [kettanaito/msw#1195]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I was checking out the source code, as I wanted to implement a new feature.

I ran the unit tests, and discovered that none of the tests from `src/test` were included.

This is because they are not included in the `roots`part of the jest.config.js file.

``` javascript
// jest.config.js
module.exports = {
  roots: ['<rootDir>/src', '<rootDir>/cli'], // no '<rootDir>/test entry is present.
```

After adding the directory to the `roots`, I experienced alot of failing tests.
I would like someone to verify this, as It might only be onmy environment.

**Comment by kettanaito** [comment]
Hey, @Xayer.

Could you please include the path to the test you've added and trying to run?

`<rootDir>/src` covers `src/test` and any other tests located under `src`. We use those for unit testing. I also recommend you to read the [Testing Guidelines](https://github.com/mswjs/msw/blob/main/CONTRIBUTING.md#tests).

**Comment by kettanaito** [comment]
Also, I'd encourage you to open a discussion around the feature you'd like to propose before developing it. I am thankful for your effort, that's why I feel it's crucial to discuss things before spending time on them.
