### ISSUE TITLE
Ambiguous URL not prioritized with Use

### ISSUE THREAD

**Issue by cah-brian-gantzler** [kettanaito/msw#1198]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/bgantzler/examples/tree/handler-order-with-use

### Reproduction steps

cd examples/with-jest
yarn
yarn test 

The test that fails is the one that should succeed, the one the succeeds is the one that should fail. 

### Current behavior

I am running into the same issue as https://github.com/mswjs/msw/issues/742. I do have the routes in the correct order. The difference is I am using `use`. Is `use` acting differently than when the routes are first defined. This is a simple example to get the point across.  For me, no routes are being defined when the worker is created. They are defined ad hoc later, so I am using a `use` for each. 

```js
let worker = setupWorker();

worker.use(
   rest.get('/account/referrer/stats', (req, res, ctx) => res(ctx.text('one')))
);

worker.use(
    rest.get('/account/referrer/:code', (req, res, ctx) => res(ctx.text('two')))
);
```

In this case, if I switch the order, it appears as if the last one defined is the always the one that is used. 

### Expected behavior

To be able to define routes that overlap, but allow for a prioritization of explicit routes over segmented routes when using `use`

In the example repo, the test that defines the specific route `/login` before the segment `/:id` is the one that fails. Since the specific was defined first (see reference issue https://github.com/mswjs/msw/issues/742), I would have expected it to succeed

The next test that defines the specific route second, I would have expected that to fail, but it succeeds. I am assuming that the one that is defined last is the one that is always being used. 

Expected behaviour would be that the defining the handlers with `use`, the same prioritization would be respected as when defining the handlers with `setupWorker`.

**Comment by kettanaito** [comment]
Hey. Thanks for submitting this. 

> In this case, if I switch the order, it appears as if the last one defined is the always the one that is used.

That's precisely how `.use()` works: it _prepends_ handlers. Handlers are applied in order, and the first matching handler is used. 

> To be able to define routes that overlap, but allow for a prioritization of explicit routes over segmented routes when using use

You are doing this with `use` already. The latest prepended handler you add is the one that will be used (given it matches the request). _That_ is the mechanism that allows you to control the priority of ambiguous handlers. 

If you wish for `/account/referrer/stats` to take precedence, prepend it last:

```js
worker.use(
  rest.get('/account/referrer/:code', (req, res, ctx) => res(ctx.text('two'))),
  rest.get('/account/referrer/stats', (req, res, ctx) => res(ctx.text('one')))
);
```

> Note that you may provide multiple handlers to a single `.use()` call. This does not affect any behavior, just a shorter call signature. I assume you're splitting the calls in your example because they happen at different times. 

However, I think the root cause of the problem you're experiencing is caused by pretending irrelevant handlers between tests. You shouldn't add any handlers via `use` unless they are immediately relevant to the test scenario you're in. This means you shouldn't even have an ambiguous situation to begin with:

```js
afterEach(() => {
  // Don't forget to reset handlers you add via "use" between tests.
  // You don't want a shared state between tests.
  worker.resetHandlers()
})

it('first scenario', () => {
  worker.use(rest.get('/account/referrer/:code', resolver)
})

it('second scenario', () => {
  worker.use(rest.get('/account/referrer/stats', resolver)
})
```

Have you tried following this pattern?

**Comment by kettanaito** [comment]
In your reproduction repository, you're adding a more generic handler last, so it will always match any requests:

```js
  server.use(
    rest.post('/login', (req, res, ctx) => {
      const { username } = req.body

      return res(
          ctx.json({
            id: 'f79e82e8-c34a-4dc7-a49e-9fadc0979fda',
            username,
            firstName: 'John',
            lastName: 'Maverick',
          }),
      )
    })
  );
  server.use(
      rest.post('/:id', (req, res, ctx) => {
        const { username } = req.body

        return res(
            ctx.json({
              id: 'f79e82e8-c34a-4dc7-a49e-9fadc0979fda',
              username,
              firstName: 'John',
              lastName: 'Doe',
            }),
        )
      }),
  );
```

Switch their order, and the `POST /login` request will match `rest.post('/login')` first.

**Comment by cah-brian-gantzler** [comment]
Ok after reading through this I understand the problem. Missed the pre-append part (it is in your docs) which means I need to do the opposite of what was in the referenced issue.

I have gotten farther. Now on to the next issue. 

For your FYI, I am converting an large set of tests from pretender to msw. In pretender, then server is created, then all the handlers are created. The code I have does this in different spots, so use makes similar drop in replacement, rather than re-designing the whole test suite to create the handlers first, then create the worker.

**Comment by kettanaito** [comment]
Happy to hear you've progressed with this. 

You can manage handlers' creation in any way you find suitable. The end point is to provide them to the server/worker instance either initially (to `setupWeorker`/`setupServer` calls) or post-factum via `.use` on both instances.

**Comment by cah-brian-gantzler** [comment]
I am converting MirageJS https://github.com/miragejs/miragejs which is heavily dependent on Pretender to allow it to optionally use pretender and then instead use MSW. Work is almost completed. I think you may get a lot of converts. One of my current gaps will be filled with this issue https://github.com/mswjs/msw/issues/420, hope work is still being done on this.

**Comment by kettanaito** [comment]
Excited to hear this, @cah-briangantzler! 🎉 

> One of my current gaps will be filled with this issue https://github.com/mswjs/msw/issues/420, hope work is still being done on this.

As far as I know, nobody is tackling the logs predicate as of now. If you feel like this is blocking you, or find the thing interesting, I encourage you to give it a try. I will be happy to support you during the code review. 

My focus is on WebSocket support right now, and I don't think it will change for the next months to come.

**Comment by cah-brian-gantzler** [comment]
Will have to land the other stuff first, then see what I can do here.
