### ISSUE TITLE
TypeScript 4.7 compat

### ISSUE THREAD

**Issue by phryneas** [kettanaito/msw#1210]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

irrelevant, this is a type-only issue

### Reproduction repository

see CI builds below

### Reproduction steps

see this [CI build](https://github.com/reduxjs/redux-toolkit/runs/6060707012?check_suite_focus=true)

### Current behavior

Right now, msw as a dependency causes three errors with TypeScript 4.7:

```
Error: ../../node_modules/msw/lib/types/sharedOptions.d.ts(23,83): error TS2344: Type 'ResponseType' does not satisfy the constraint 'Record<string | symbol, any>'.
Error: ../../node_modules/msw/node_modules/type-fest/ts41/get.d.ts(95,37): error TS2344: Type 'BaseType' does not satisfy the constraint 'Record<string | number, any>'.
Error: ../../node_modules/msw/node_modules/type-fest/ts41/get.d.ts(96,19): error TS2344: Type 'BaseType' does not satisfy the constraint 'Record<string | number, any>'.
Error: Process completed with exit code 2.
```

Two of those originate from the dependency `type-fest`, which in the currently used major version 1 does not seem to support TS 4.7. Since `type-fest` does not have multiple major-version branches and already has an open issue for a v3, I would assume they are not going to backport any fixes (although I might be wrong).

Updating the dependency to major version 2 seems to [fix that issue](https://github.com/reduxjs/redux-toolkit/runs/6060991065?check_suite_focus=true).
That would drop type-fest support for TS<4.2 though - I guess it's either support for future TS versions or old versions at that point.

The other error seems to be resolved by changing
```diff
-export declare type LifeCycleEventEmitter<ResponseType> = Pick<StrictEventEmitter<ResponseType>, 'on' | 'removeListener' | 'removeAllListeners'>;
+export declare type LifeCycleEventEmitter<ResponseType extends Record<string | symbol, any>> = Pick<StrictEventEmitter<ResponseType>, 'on' | 'removeListener' | 'removeAllListeners'>;
```

I can open a PR for that if desired.

### Expected behavior

No type errors, even with `skipLibChecks: false`

**Comment by kettanaito** [comment]
Hey, @phryneas. Thanks for raising this. 

We don't have official support for TS >= 4.4 but if your suggestion is compatible with 4.3 which we support now, I'd love to have this merged. In any case, opening a pull request would be useful. Thank you!

**Comment by jbockle** [comment]
is typescript listed as a peer dependency solely for the typings? is there something in >=4.4 that breaks typings?  other than that, if this package is serving the transpiled ts (which it appears it is as package.json `main` is pointing to `lib/main.js`), typescript shouldn't be a peer dependency

**Comment by phryneas** [comment]
@jbockle I believe that has really nothing to do with this and might be it's own issue ;) I would want to add that TS is an **optional** peer dependency though.

**Comment by kettanaito** [comment]
TypeScript is specified as an optional peer dependency. I believe that's the correct approach to control what range is supported without enforcing TS installations for users who don't use TS. But, as always, it's open to suggestions.

**Comment by phryneas** [comment]
Generally you wouldn't specify it at all - if you really want to go for something like that, use `typesVersion`, but it's better to have half-broken types than no types at all. One can always turn `skipLibChecks` off.

**Comment by kettanaito** [comment]
With #1256, the library should be compatible with TypeScript 4.7. Could you please test it out and report any issues? 

I don't think we have to cover the proposed changes in the types above.

**Comment by kettanaito** [comment]
@phryneas, I think it's a good idea to clearly state that version of other tools you support. Violating peer dependency range won't break your types—you can disable that check.
