### ISSUE TITLE
MSW seems to not run with react?

### ISSUE THREAD

**Issue by erkanisuf** [kettanaito/msw#1215]
Hello guys i have been stuck with this task for very long time and yet couldn't figure out after checking the docs and other resources in online.

So i have this setup with Jest and MSW but i think the msw server not running at all.

 

       let url = "/api/v1/267/1285/property/search/Bet?searchAll=true";
    const server = setupServer(
        rest.get(url, async (req, res, ctx) => {
            req.url.searchParams.get("searchAll")
            ctx.delay(1000)
            return res(
                ctx.status(200),
                ctx.json([
                    {
                        cadastralId: "04901000140007",
                        street: "Bet",
                        postalCode: "02150",
                        city: "Espoo",
                        buildingModels: [],
                        buildingIds: null
                    }
                ])
            );
        })
    );
    
    beforeAll(() => server.listen());
    afterAll(() => server.close());
    afterEach(() => server.resetHandlers());
    
    
    test("Valuation List Page tests", async () => {
            render(<ValuationListPage/>)
            await user.type(screen.getByTestId('search-input'), 'Bet');
            await waitForElementToBeRemoved(() => screen.getByTestId('circle-spinner'));
            expect(screen.getByText("Bet")).toBeInTheDocument()
        }
    )

I expect when the mock fetch gets triggered the spinner to be shown but when i check in the logs it seems that its not even rendering atleast in the test and it gives this error:

     TestingLibraryElementError: Unable to find an element by: [data-testid="circle-spinner"]

Ive also tried to do add some text and try with `getByText` but its still not working , thats because seems that the server mock is not being called at all :\ .

the component itself looks liek this:

      const [search, setSearch] = useState('');
        const [isLoading, setIsLoading] = useState(false);
        const [isNationWide, setIsNationWide] = useState(false);
        const [propertyList, setPropertyList] = useState([]);
    
        let controller = new AbortController();
        const handleSearchChange = async (searchTerm: string) => {
            console.log("I RUN")
            if (search && search.length > 2) {
                setIsLoading(true);
                let url = "/api/v1/" + props.user?.organizationId + "/" + props.portfolioId
                    + "/property/search/" + searchTerm + (isNationWide ? "?searchAll=true" : "");
    
                if (controller)
                    controller.abort();
    
                controller = new AbortController();
    
                try {
                    const results = await axios.get(url, {
                            signal: controller.signal
                        }
                    )
                    setPropertyList(results.data.sort((a: valuationListBuilding, b: valuationListBuilding) => (a?.buildingModels?.length || 0) < (b?.buildingModels?.length || 0) ? 1 : -1))
                } catch (error) {
                    console.log(`URL:${url} , error: ${error}`)
                } finally {
                    setIsLoading(false)
                }
    
            } else {
                setPropertyList([])
                setIsLoading(false)
            }
        }
    
    
        useEffect(() => {
            const delayDebounceFn = setTimeout(() => {
                handleSearchChange(search)
            }, 500)
    
            return () => clearTimeout(delayDebounceFn)
        }, [search, isNationWide])
 

and rendered like so:

     {isLoading ? <CircleLoader height={35} width={35}
                                                           className="d-flex justify-content-center align-items-center mt-5"/> : propertyList.length ?
                                    <ValuationListTable properties={propertyList}
                                                        user={props.user}
                                                        sortList={(key, isAsc) => sortList(key, isAsc)}/> :
                                    <h6 className="text-muted text-center mt-5"><i
                                        className="fa-solid fa-triangle-exclamation mx-2"></i>{l("valuation_view.list.no_result")}
                                    </h6>}

Versions:

       "@testing-library/jest-dom": "^5.16.4",
       "@testing-library/react": "^12.0.04",
       "jest": "^27.5.1",
       "jest-canvas-mock": "^2.3.1",
       "jest-environment-jsdom": "^27.5.1",
       "msw": "^0.39.2",

**Comment by kettanaito** [comment]
Hey, @erkanisuf. 

If there are no warnings about unhandled HTTP requests then MSW is running correctly.

The error you experience likely suggests that you are not asserting asynchronous UI elements correctly:

```
TestingLibraryElementError: Unable to find an element by: [data-testid="circle-spinner"]
```

Use `.find*` to assert elements that may not exist straight away. 

Just a kind warning: I'm going to automatically close all issues that don't have a reproduction repository. There's not enough bandwidth to try to guess the setups and environments of each individual issue. You can always open a Dicussion on the repo but issues require reproduction scenarios.
