### ISSUE TITLE
rest.all documentation

### ISSUE THREAD

**Issue by RyanClementsHax** [kettanaito/msw#1217]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

It seems that `rest.all` that was added with [this pull request](https://github.com/mswjs/msw/pull/896) #896 isn't mentioned in the [documentation](https://mswjs.io/docs/api/rest#methods). Is this intentional?

I have added [an issue to the docs repository](https://github.com/mswjs/mswjs.io/issues/196) in case y'all would rather this be handled over there.

Thanks

**Comment by kettanaito** [comment]
Hey, @RyanClementsHax! Thanks for raising this.

Yes, this is an oversight on our part. Let's tackle this in the website's repo.
