### ISSUE TITLE
next.js: Cannot read properties of undefined (reading 'listen') when importing faker

### ISSUE THREAD

**Issue by djaustin** [kettanaito/msw#1227]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v17.8.0

### Reproduction repository

https://github.com/djaustin/msw-faker-reproduction/tree/with-faker

### Reproduction steps

`yarn && yarn dev`

Visit http://localhost:3000

To revert to a working configuration, checkout branch 'working-factory' (https://github.com/djaustin/msw-faker-reproduction/tree/working-factory)

The import of faker seems to cause the error to occur.

### Current behavior

An error is displayed in the console and the browser. 
```bash
TypeError: Cannot read properties of undefined (reading 'listen')
    at eval (webpack-internal:///./mocks/index.js:3:12)
    at Object../mocks/index.js (/Users/daustin/development/msw/.next/server/pages/_app.js:32:1)
    at __webpack_require__ (/Users/daustin/development/msw/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.js:9:5)
    at Object../pages/_app.js (/Users/daustin/development/msw/.next/server/pages/_app.js:65:1)
    at __webpack_require__ (/Users/daustin/development/msw/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/daustin/development/msw/.next/server/pages/_app.js:130:39)
    at /Users/daustin/development/msw/.next/server/pages/_app.js:131:28
    at Object.<anonymous> (/Users/daustin/development/msw/.next/server/pages/_app.js:134:3)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
TypeError: Cannot read properties of undefined (reading 'listen')
    at eval (webpack-internal:///./mocks/index.js:3:12)
    at Object../mocks/index.js (/Users/daustin/development/msw/.next/server/pages/_app.js:32:1)
    at __webpack_require__ (/Users/daustin/development/msw/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.js:9:5)
    at Object../pages/_app.js (/Users/daustin/development/msw/.next/server/pages/_app.js:65:1)
    at __webpack_require__ (/Users/daustin/development/msw/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/daustin/development/msw/.next/server/pages/_app.js:130:39)
    at /Users/daustin/development/msw/.next/server/pages/_app.js:131:28
    at Object.<anonymous> (/Users/daustin/development/msw/.next/server/pages/_app.js:134:3)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
error - mocks/index.js (3:9) @ eval
TypeError: Cannot read properties of undefined (reading 'listen')
  1 | if (typeof window === 'undefined') {
  2 |   const { server } = require('./server')
> 3 |   server.listen()
    |         ^
  4 | } else {
  5 |   const { worker } = require('./browser')
  6 |   worker.start()
```
<img width="965" alt="Screenshot 2022-05-04 at 16 47 44" src="https://user-images.githubusercontent.com/9084497/166719969-c83e711b-0c4b-435b-b9bd-72727bb89470.png">

### Expected behavior

msw successfully creates a new object from the factory model and returns it for display in the application

**Comment by djaustin** [comment]
I've noticed that changing the `import` statements to `require` statements in `mocks/model/db.js` and `mocks/handlers.js` also allows this to run correctly but I've been unable to find out why as I can use `import` elsewhere in the project with no issue.

**Comment by kettanaito** [comment]
Hey, @djaustin. Thanks for reporting this. 

Something seems to be off with this. I will try looking into the repository you've shared when I have a minute. I'm certain it's a little detail that affects this.

**Comment by kettanaito** [comment]
If you inspect the return of the `require('./server')` you will notice that it returns a Promise:

```js
// mocks/index.js
const allExports = require('./server')
console.log(allExports) // Proimse<...>
```

Something in the import chain forces the `./server` module to be imported asynchronously. I believe that's not the native `require` behavior (I'm also running Node.js v14.18.1). 

If you rewrite `require` to `import` and await it, the issue gets resolved:

```js
// mocks/index.js
async function initMocks() {
  if (typeof window === 'undefined') {
    const { server } = await import('./server')
    server.listen()
  } else {
    const { worker } = await import('./browser')
    worker.start()
  }
}

initMocks()
```

If this issue occurs only when you introduce a certain dependency, like faker, I suspect that dependency somehow affects the import type your module uses. Sorry, I don't have the capacity to look deeper into this but the `import` proposal above is functional and should unblock you. 

Anybody having more experience with module resolution is welcome to write a more constructive explanation below. Thank you!

**Comment by SalahAdDin** [comment]
> If you inspect the return of the `require('./server')` you will notice that it returns a Promise:
> 
> ```js
> // mocks/index.js
> const allExports = require('./server')
> console.log(allExports) // Proimse<...>
> ```
> 
> Something in the import chain forces the `./server` module to be imported asynchronously. I believe that's not the native `require` behavior (I'm also running Node.js v14.18.1).
> 
> If you rewrite `require` to `import` and await it, the issue gets resolved:
> 
> ```js
> // mocks/index.js
> async function initMocks() {
>   if (typeof window === 'undefined') {
>     const { server } = await import('./server')
>     server.listen()
>   } else {
>     const { worker } = await import('./browser')
>     worker.start()
>   }
> }
> 
> initMocks()
> ```
> 
> If this issue occurs only when you introduce a certain dependency, like faker, I suspect that dependency somehow affects the import type your module uses. Sorry, I don't have the capacity to look deeper into this but the `import` proposal above is functional and should unblock you.
> 
> Anybody having more experience with module resolution is welcome to write a more constructive explanation below. Thank you!

It is even worst in Typescript, and it does not work to me yet.

**Comment by sum93** [comment]
Hey @SalahAdDin,
I've also had issues with this "use import instead" solution.
In the end, I've deleted the `.next` folder and the problem's gone. I'm not sure what the cause is but my wild guess is it has to do something with `nextjs` caching.

Cheers!

**Comment by j0k3r** [comment]
Shouldn't the doc be updated here https://mswjs.io/docs/getting-started/integrate/node?
Maybe at least to mention that in the context of Next.js it's better to use [async/await](https://github.com/vercel/next.js/blob/canary/examples/with-msw/mocks/index.ts) to avoid that `undefined` error.

**Comment by AtomSpy** [comment]
I've tried async/await and deleting the .next file. This issue still persists for me. Has anyone got any more solutions?

**Comment by SalahAdDin** [comment]
This issue should be reopened, i think.

**Comment by AtomSpy** [comment]
I think there needs to be some clarification in the documentation regarding this. Reading some other issues suggest that MSW isn't fully compatible with the latest version of NextJS (v13.2.3). If this is known, it would be nice if this is mentioned in the documentation.

Using `import` and `await` seems to enable MSW in a server environment. However, it doesn't seem to work in a browser environment.

**Comment by SalahAdDin** [comment]
> I think there needs to be some clarification in the documentation regarding this. Reading some other issues suggest that MSW isn't fully compatible with the latest version of NextJS (v13.2.3). If this is known, it would be nice if this is mentioned in the documentation.
> 
> Using `import` and `await` seems to enable MSW in a server environment. However, it doesn't seem to work in a browser environment.

So, we will need to wait till they find a fix for this problem, right?
