### ISSUE TITLE
mockServiceWorker.js in pending state

### ISSUE THREAD

**Issue by alabianca** [kettanaito/msw#1233]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/mswjs/examples

### Reproduction steps

Browser: 101.0.4951.54 
Node.js version: 14.18.2

1. Clone Repo
2. cd examples/rest-react
3. npm install
4. npx msw init public/
5. npm start
6. Open network tab
7. Find mockServiceWorker.js in pending state

![Screen Shot 2022-05-12 at 9 49 03 AM](https://user-images.githubusercontent.com/25507518/168105699-b11a4db4-6b2b-446c-ac60-c30328e57ad8.png)

### Current behavior

The request for the mockServiceWorker.js is in a pending state. The service worker is active and running (according to Dev Tools > Application > Service Workers). The mock handlers work as expected. 

### Expected behavior

A 200 response code when fetching the mockServiceWorker.js

**Comment by do-kevin** [comment]
Hi, I want to add onto this as well. So I'm not sure if it's my Javascript skills or it's a Mock Service Worker bug (with fetch API maybe), but I encountered pretty much the same behavior. It sends me the status code 200, but the promise is still pending. What I had to do was separate `fetch` and put it into its own async function that's then called inside whatever function is handling submission event. I was able to get the response's body back after setting up the code like that.

So for `rest-react` example, it should work after this change for `LoginForm.js`:
```
import React, { useState, useCallback } from 'react'

export const LoginForm = () => {
  // Store the username so we can reference it in a submit handler
  const [username, setUsername] = useState('')

  // Create a state for the user data we are going to receive
  // from the API call upon form submit.
  const [userData, setUserData] = useState(null)

  // Whenever we change our username input's value
  // update the corresponding state's value.
  const handleUsernameChange = useCallback((event) => {
    setUsername(event.target.value)
  }, [])

  // do-kevin's changes:
  const login = async (value) => {
    // Perform a POST /login request and send the username
    const response = await fetch('/login', {
      method: 'POST',
      body: value,
    })

    const result = await response.json()

    if (result) {
      setUserData(result)
    }

    console.log('result: ', result)
  }

  // Handle a submit event of the form
  const handleFormSubmit = useCallback(
    (event) => {
      // Prevent the default behavior, as we don't want
      // for our page to reload upon submit.
      event.preventDefault()

      return login(JSON.stringify({ username }))
    },
    [username],
  )

  if (userData) {
    return (
      <div>
        <h1>
          <span data-testid="firstName">{userData.firstName}</span>{' '}
          <span data-testid="lastName">{userData.lastName}</span>
        </h1>
        <p data-testid="userId">{userData.id}</p>
      </div>
    )
  }

  return (
    <form onSubmit={handleFormSubmit}>
      <div>
        <label htmlFor="username">Username:</label>
        <input
          id="username"
          name="username"
          value={username}
          onChange={handleUsernameChange}
        />
        <button type="submit">Submit</button>
      </div>
    </form>
  )
}
```

I don't have a reproduction repository ready, but I am also encountering a different problem. Let's say we wrap my fetch function in a try catch and set up a handler that returns `ctx.status(403)` and `ctx.json({ errorMessage: "Username cannot be empty")` for example. For some reason, the `catch` block doesn't get the error response. It's always the `try` block.

**Comment by kettanaito** [comment]
Thanks for more insight on this, @do-kevin. 

As to why 4xx responses don't trigger the catch statement is because only exceptions do. a 4xx and even 5xx responses are _successful responses_ in regard to request execution, so fetch calls behind them _won't throw_. This is how Fetch API behaves.

**Comment by kettanaito** [comment]
There are a few reasons why the worker script can be infinitely pending. I wanted to review the examples repository anyway, so this may be a good thing to watch out for.

**Comment by kettanaito** [comment]
We've updated the usage examples since last year, and I believe this issue is no longer the case. If the worker script is pending, please double-check how your application is serving it, and make sure you can access it when navigating to `/mockServiceWorker.js` in the browser. 

If you still experience this problem, please open a new issue with a reproduction repo. Thanks.
