### ISSUE TITLE
Version 0.40.0 has npm errors (and is uninstallable) with TypeScript 4.6.4

### ISSUE THREAD

**Issue by sklawren** [kettanaito/msw#1243]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.15.0

### Reproduction repository

https://github.com/installation-error-not-a-repo

### Reproduction steps

Trying to install msw 0.40.0 (from 0.39.2) with TypeScript 4.6.4 installed.

### Current behavior

The following is output in the terminal, blocking the installation.
```bash
Command failed: npm install --save-dev msw@0.40.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: msw@0.40.0
npm ERR! Found: typescript@4.6.4
npm ERR! node_modules/typescript
npm ERR!   typescript@"^4.6.4" from @commitlint/load@17.0.0
npm ERR!   node_modules/@commitlint/load
npm ERR!     @commitlint/load@"^17.0.0" from @commitlint/cli@17.0.0
npm ERR!     node_modules/@commitlint/cli
npm ERR!       dev @commitlint/cli@"^17.0.0" from the root project
npm ERR!     optional @commitlint/load@">6.1.1" from cz-conventional-changelog@3.2.0
npm ERR!     node_modules/commitizen/node_modules/cz-conventional-changelog
npm ERR!       cz-conventional-changelog@"3.2.0" from commitizen@4.2.4
npm ERR!       node_modules/commitizen
npm ERR!         commitizen@"^4.0.3" from cz-conventional-changelog@3.2.0
npm ERR!         1 more (cz-conventional-changelog)
npm ERR!     1 more (cz-conventional-changelog)
npm ERR!   peer typescript@">=3.7.0" from @rollup/plugin-typescript@8.3.2
npm ERR!   node_modules/@rollup/plugin-typescript
npm ERR!     dev @rollup/plugin-typescript@"^8.3.1" from the root project
npm ERR!   12 more (@storybook/react-docgen-typescript-plugin, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"4.2.x" from msw@0.40.0
npm ERR! node_modules/msw
npm ERR!   dev msw@"0.40.0" from the root project
npm ERR!   peer msw@">=0.35.0 <1.0.0" from msw-storybook-addon@1.6.3
npm ERR!   node_modules/msw-storybook-addon
npm ERR!     dev msw-storybook-addon@"^1.6.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@4.2.4
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"4.2.x" from msw@0.40.0
npm ERR!   node_modules/msw
npm ERR!     dev msw@"0.40.0" from the root project
npm ERR!     peer msw@">=0.35.0 <1.0.0" from msw-storybook-addon@1.6.3
npm ERR!     node_modules/msw-storybook-addon
npm ERR!       dev msw-storybook-addon@"^1.6.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Expected behavior

Conflicts to be resolved (hopefully not too difficult).

**Comment by yannbf** [comment]
Hey @sklawren thanks for opening this issue! Did you update a lot of libraries together? `@commitlint/load` was just released with a high version of typescript as a dependency.

MSW does have a quite strict peerDependency range for typescript, but it's tagged as optional. Are you using npm 7?

**Comment by kettanaito** [comment]
I believe the error is, although verbose, quite helpful:

```sh
Found: typescript@4.6.4
# ...
peerOptional typescript@"4.2.x" from msw@0.40.0
```

Since `0.40.0`, MSW explicitly lists `typescript@4.2.x` as an optional peer dependency. We currently don't guarantee the library will work with any other TypeScript version. You seem to be using TypeScript 4.6.4, which is not in the supported range for MSW.

I'm working on adding some compatibility tests around which versions of TS we can support (#1242). I can already see issues starting from 4.4. If those are feasible, I will address them in an upcoming pull request and extend the version range for the TypeScript peer dependency.

**Comment by kettanaito** [comment]
I'm closing the issue because as of not it's a matter of using a tool with a peer dependency it has no official support for.

**Comment by sklawren** [comment]
@yannbf  I am using npm 8.10.0 and the latest version of TypeScript 4.6.4.

@kettanaito Is the issue that I need to wait until MSW has TypeScript 4.6.x support? Maybe I can install msw 0.40.x with --legacy-peer-deps?

Version 0.39.2 of msw does not report this resolve error when installing. Is that because you added the strict peerDependency in 0.40.x?

I just tried installing 0.40.1 (as per #1242 being merged), but still have the same error.

**Comment by kettanaito** [comment]
We are going to release the 4.2 - 4.6 TypeScript support tonight. I don't think it's viable to suggest any workarounds right now. 

> Version 0.39.2 of msw does not report this resolve error when installing. Is that because you added the strict peerDependency in 0.40.x?

Yes. We'd like to be more evident about what TypeScript versions we support.
