### ISSUE TITLE
TypeError: interceptors.createInterceptor is not a function

### ISSUE THREAD

**Issue by ripvannwinkler** [kettanaito/msw#1248]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.13.2

### Reproduction repository

https://github.com/ripvannwinkler/msw-create-interceptor-issue

### Reproduction steps

1. Clone the linked repo
2. Run yarn install
3. Run yarn test

### Current behavior

Decided to give MSW a go and installed the latest version with a brand new project and a single empty test w/ jest. Got the following error while running the test:

```
 FAIL  test/empty.spec.ts
  ● Test suite failed to run
                                                                                                                                                                        
    TypeError: interceptors.createInterceptor is not a function

      2 | import { setupServer } from 'msw/node';
      3 |
    > 4 | const server = setupServer(
        |                           ^
      5 |       // Describe the requests to mock.
      6 |       rest.get('/book/:bookId', (req, res, ctx) => {
      7 |               return res(

      at setupServer (node_modules/msw/node/lib/index.js:8192:42)
      at Object.<anonymous> (test/empty.spec.ts:4:27)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
```

Installing msw@0.39.1 works as expected. msw@0.39.2 and later fail with the above

### Expected behavior

```
❯❯ fetchUtils git:(main) 03:02 yarn test
Debugger attached.
yarn run v1.22.17
$ jest .
Debugger attached.
 PASS  test/empty.spec.ts
  √ renders a book data
```

**Comment by rphlmr** [comment]
Maybe related to https://github.com/mswjs/interceptors/issues/245 ?

**Comment by ripvannwinkler** [comment]
Seems so. I googled and found nothing. I guess that issue hasn't been indexed yet.

**Comment by kettanaito** [comment]
Thanks for reporting. This is a duplicate of https://github.com/mswjs/interceptors/issues/245. Running `npm install` in your project will fix this.
