### ISSUE TITLE
Module not found: Error: Can't resolve 'http' in the browser

### ISSUE THREAD

**Issue by NullVoxPopuli** [kettanaito/msw#1250]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
    - a very similar issue is in closed issues though: https://github.com/mswjs/msw/issues/1142
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version (0.40.2 at the time of reporting this issue)
- [X] I'm using Node.js version 14 or higher

### Browsers

Firefox (but doesn't matter yet, because my error occurs during webpack's prep)

### Reproduction repository

https://github.com/NullVoxPopuli/ember-resources/pull/497

### Reproduction steps

- `cd testing/ember-app`
- `pnpm install && pnpm start`

### Current behavior

Error:
```
ERROR in <repo>/node_modules/.pnpm/@mswjs+interceptors@0.15.2/node_modules/@mswjs/interceptors/lib/utils/getUrlByRequestOptions.js 33:13-28
Module not found: Error: Can't resolve 'http' in '<repo>/node_modules/.pnpm/@mswjs+interceptors@0.15.2/node_modules/@mswjs/interceptors/lib/utils'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }
 @ <repo>/node_modules/.pnpm/@mswjs+interceptors@0.15.2/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/utils/normalizeClientRequestArgs.js 55:31-79
 @ <repo>/node_modules/.pnpm/@mswjs+interceptors@0.15.2/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/http.get.js 41:35-80
 @ <repo>/node_modules/.pnpm/@mswjs+interceptors@0.15.2/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/index.js 87:17-38
 @ <repo>/node_modules/.pnpm/@mswjs+interceptors@0.15.2/node_modules/@mswjs/interceptors/lib/RemoteInterceptor.js 219:22-61
 @ <repo>/node_modules/.pnpm/@mswjs+interceptors@0.15.2/node_modules/@mswjs/interceptors/lib/index.js 27:13-43
 @ <repo>/node_modules/.pnpm/msw@0.40.2_typescript@4.6.3/node_modules/msw/lib/esm/index.js 11:0-56 1662:22-39
 @ ./tests/msw.ts 2:0-40 12:11-22 37:6-10
 @ ./assets/test.js 242:13-39}
```

At the bottom of the stack there is my actual code. 

Here is my msw.js file:
```js
import * as QUnit from 'qunit';

import { rest, setupWorker } from 'msw';

import type { SetupWorkerApi } from 'msw';

let worker: SetupWorkerApi;

/**
 * Setup worker before any test begins so that we don't introduce
 * any potential instabilities due to "sometimes" making a test
 * run longer by lazily setting up the work for the first test
 * that uses `setupMSW`
 */
QUnit.begin(async () => {
  worker = setupWorker();

  /**
   * At this point we have no request handlers, but that's what
   * setupMSW is for
   */
  await worker.start();
});

QUnit.done(async () => {
  worker.printHandlers();
  worker?.stop();
});

export async function setupMSW(
  hooks: NestedHooks,
  handlers: (args: { rest: typeof rest }) => Parameters<typeof worker['use']>
) {
  hooks.beforeEach(async function () {
    /**
     * Remove handlers that were maybe added during a previous a test.
     */
    worker.resetHandlers();

    /**
     * Install the handlers passed in from the test
     */
    worker.use(...handlers({ rest }));
  });

  hooks.afterEach(function () {
    /**
     * Ensure that we clean up after ourselves
     */
    worker?.resetHandlers();
  });
}
```

### Expected behavior

No importing of node files. I'm in the browser :sweat_smile:

**Comment by NullVoxPopuli** [comment]
Ok, I think I found "a" problem, but not _the_ problem.

I'm up and running again by being a bit more careful with my lockfile.
[This diff here](https://github.com/NullVoxPopuli/ember-resources/pull/497/commits/11a7a660fe7643d2c5fcd62d71388d20eec6c2bd) shows what happened to "fix it"
[Here is my current lockfile](https://github.com/NullVoxPopuli/ember-resources/pull/497/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb) from just updating msw

The root of the problem is somewhere in that fast and loose lockfile re-roll. :thinking:

**Comment by kettanaito** [comment]
I can recommend re-installing the dependencies to ensure there are no lockfile shenanigans.

**Comment by NullVoxPopuli** [comment]
oh I'm unblocked. I tried installing a few of the upgraded deps but couldn't reproduce the issue (I gave up after a while, because there were too many simultaneous changes). 
What's goofy is that my "floating deps" test (where I delete the lockfile entirely) still passes.... so idk what the deal is. There is _some_ unknown relationship between the dependencies in the above diff, and msw or webpack trying to load a node thing in a browser context :upside_down_face:

**Comment by kettanaito** [comment]
Something has certainly gone wrong with the bundling, which may have been caused by the dependencies issue. To be clear: webpack's warning is correct—they don't bundle built-ins anymore. But what's incorrect is that it happens in a browser context, coming from the module that's meant to be consumed in Node.js. 

@NullVoxPopuli, I'm glad this has been resolved!
