### ISSUE TITLE
Unstable behaviour while using testcafe

### ISSUE THREAD

**Issue by Spronghi** [kettanaito/msw#1251]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Reproduction repository

https://github.com/Spronghi/msw-testcafe

### Reproduction steps

``` bash
npm install
npm test
```

### Current behavior

I am facing a lot of issue by using MSW and testcafe, it seems like that the `mockServiceWorker.js` is not found consistently using Firefox and Safari.

### Expected behavior

The test using testcafe should never fail using msw, as it does with real API

**Comment by kettanaito** [comment]
Hi, @Spronghi. Thanks for reporting this.

If the worker script cannot be resolved during your test run, this likely means you are not configuring TestCafe to serve the worker script, in the first place. 

Please refer to the TestCafe's docs to learn how to serve static assets as a part of your test run. Thanks.
