### ISSUE TITLE
`response.url` always returns empty string for mocked responses

### ISSUE THREAD

**Issue by kirill-galimov-plutotv** [kettanaito/msw#1258]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

14.18.1

### Reproduction repository

https://codesandbox.io/s/new-wood-dz1g4b?file=/src/App.test.js

### Reproduction steps

`yarn test`

### Current behavior

`response.url` always returns empty string value

### Expected behavior

`response.url` should return `request.url` value

**Comment by kettanaito** [comment]
Hey, @kirill-galimov-plutotv. Thanks for reporting this!

There's an issue with our XHR interceptor that we never actually set the `this.responseURL` on the mocked request instance. I'm addressing this with a fix, adding some tests. Should be released soon.

**Comment by kettanaito** [comment]
`response.url` will also equal `""` when using the fallback mode (`FetchInterceptor`).

**Comment by kettanaito** [comment]
## Released: v0.42.0 🎉

This has been released in v0.42.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.42.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.42.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
