### ISSUE TITLE
Upgrade from 0.36.8 to any other version breaks nock

### ISSUE THREAD

**Issue by Ulian** [kettanaito/msw#1268]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.14.2

### Reproduction repository

https://github.com/Ulian/msw-nock-issue

### Reproduction steps

With version 0.42.0
```
git clone https://github.com/Ulian/msw-nock-issue.git
git checkout main
npm install
npm run test
// FAIL  ./issue.test.js
// getaddrinfo ENOTFOUND fake-url.com
```

With version 0.36.8
```
git clone https://github.com/Ulian/msw-nock-issue.git
git checkout with-0.36.8
npm install
npm run test
//  PASS  ./issue.test.js
```

### Current behavior

If you have any test with nock to intercept a request It will not work even if that URL is not intercepted with MSW.

I saw issue #1264 but I think is not related since this happens in 0.41.0 as well.

### Expected behavior

0.42.0 and 0.36.8 should be compatible?

**Comment by kettanaito** [comment]
Hey, @Ulian. Thanks for raising this. 

MSW and Nock are both API mocking tools. It's not recommended to mix those, even if you think you scoped them to specific test suites. I highly advise against that, as both are patching native modules, and if their patches overlap your test will break. 

You need to choose one API mocking solution and stick to it. MSW has never positioned itself compatible with any other API mocking solutions—there is no need to combine them. I understand that migrating a large code base may be time-consuming, but it's worth it. 

I believe #1264 speaks of broken interception when using MSW alone. That indeed sounds like an issue on our side. 

> 0.42.0 and 0.36.8 should be compatible?

No. MSW is pre-1.0, which means every minor release contains breaking changes. That's correct versioning per SemVer until we reach 1.0.
