### ISSUE TITLE
Typeerror when using third party libraries to generate mocked data in Nextjs 12 + typescript

### ISSUE THREAD

**Issue by keaghan-kennedy-dev** [kettanaito/msw#1269]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/KeaghanKennedy/msw-next-typeerror-repro

### Reproduction steps

1. Clone the above repository
2. run `yarn install` and  then `yarn dev`
3. Visit http://localhost:3000/ to produce error.

### Current behavior

I'm trying to use MSW in conjunction with some third party libraries (primarily faker and nanoid) to generate large amounts of sensible fake data in my mocked requests. If the handler returns hardcoded primitive data as in the example below, the handler runs fine. 

```typescript
// src/test/mocks/handlers/index.ts
import { rest } from "msw";

export const handlers = [
  rest.get("https://my.backend/example", (req, res, ctx) => {
    return res(
      ctx.json({
        id: "testID",
        imageUrl: "/book-cover.jpg",
        description:
          "The Lord of the Rings is an epic high-fantasy novel written by English author and scholar J. R. R. Tolkien.",
      })
    );
  }),
];
```

However, if I try and use any methods from third party libraries to generate the data,

```typescript
// src/test/mocks/handlers/index.ts
import { rest } from "msw";
import { nanoid } from "nanoid";

export const handlers = [
  rest.get("https://my.backend/example", (req, res, ctx) => {
    return res(
      ctx.json({
        id: nanoid(),
        imageUrl: "/book-cover.jpg",
        description:
          "The Lord of the Rings is an epic high-fantasy novel written by English author and scholar J. R. R. Tolkien.",
      })
    );
  }),
];
```

I receive the following type error:
```bash
error - src\test\mocks\index.ts (4:11) @ initMocks
TypeError: Cannot read properties of undefined (reading 'listen')
  2 |   if (typeof window === "undefined") {
  3 |     const { server } = require("./server");
> 4 |     server.listen();
    |           ^
  5 |   } else {
  6 |     const { worker } = require("./browser");
  7 |     worker.start();
```

### Expected behavior

Handler runs correctly and returns data generated by `nanoid()` method. If this is a dumb question and I've missed something basic I apologize ahead of time.

**Comment by kettanaito** [comment]
Hey, @KeaghanKennedy. 

This looks like a similar question to [this discussion](https://github.com/mswjs/msw/discussions/1236#discussioncomment-2767365). Please take a look at the answer there, I believe it apply to your use case as well. 

Shortly, using `require` will strip any types from the required module. That's how TypeScript processes `require` statements. So, to preserve the types, you need to cast `worker` and `server` manually, using the types exposed by MSW. Once you do, you get the type checking back.

**Comment by kettanaito** [comment]
Also, to clarify: the issue is not connected to using any third-party modules, nor it is really an MSW issue. It's about how to type TypeScript modules that have been `required`. The only MSW-related context here is that you use `require` and not `import` (see the explanation in the discussion above).

**Comment by keaghan-kennedy-dev** [comment]
@kettanaito Legend. Apologies for the unneeded issue. I should have taken a deeper look in the discussions section.

**Comment by keaghan-kennedy-dev** [comment]
@kettanaito Going to leave this here in case it helps anyone else out. This was the only way I could get it working. As you pointed out in [this comment](https://github.com/mswjs/msw/issues/1227#issuecomment-1118492523), the require statement returns a promise so I switched to the async/await syntax with a bit of custom typing. It seems to work fine like this:

```typescript
import type { SetupWorkerApi } from "msw";
import { SetupServerApi } from "msw/node";

export async function initMocks() {
  if (typeof window === "undefined") {
    const { server }: { server: SetupServerApi } = await import("./server");

    server.listen();
  } else {
    const { worker }: { worker: SetupWorkerApi } = await require("./browser");
    worker.start();
  }
}

```

**Comment by kettanaito** [comment]
I'm glad you've managed to resolve it! 🎉
