### ISSUE TITLE
OpenSource and politics

### ISSUE THREAD

**Issue by gromov-io** [kettanaito/msw#1275]
### Scope

Improves an existing behavior

### Compatibility

- [X] This is a breaking change

### Feature description

Today you posted a political banner, and tomorrow what? a Trojan for formatting the disk, or suddenly a banner will pop up on the entire page with the content of the war? there have already been cases, and it is with the theme of support for Ukraine.

Open source - should be out of politics.. think about it, unfortunately, due to security reasons, we are forced to abandon this beautiful package ((

Examples of malware in open source:

es5-ext - https://github.com/medikoo/es5-ext/commit/28de285ed433b45113f01e4ce7c74e9a356b2af2
node-ipc - https://github.com/RIAEvangelist/node-ipc/commit/1220522453a0388cb4af1a74fe9a0482b6b3a9f3

**Comment by kettanaito** [comment]
I'm using the chance to reach out to people to ask for help. If you don't like this, or any other statements that I make, you are free to explore different software. Before we start saying what open-source _should_ be, it should be _paid_ first and foremost. I've developed countless libraries in my spare time. I don't own anything to you, or to any other consumer, so I find this issue simply inappropriate.

**Comment by kettanaito** [comment]
I'm locking this thread because I know better than to participate in this kind of discussions. It's outrageous to demand something from a library maintainer, thinking they own you anything. You have a fundamentally distorted understanding of open source.
