### ISSUE TITLE
The runtime request handler does not overwrite the existent one

### ISSUE THREAD

**Issue by slim-hmidi** [kettanaito/msw#1281]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.14.0

### Reproduction repository

*

### Reproduction steps

I create a server:
```ts
import {rest} from 'msw'
import {setupServer, SetupServerApi} from 'msw/node'

const handlers = [
rest.get('http://localhost/products/search', (req, res, ctx) => {
    return res(
      ctx.status(200),
      ctx.set('Content-Type', 'application/json'),
      ctx.json({
        products: [],
        total: 0,
      }),
    )
  })
]

const server: SetupServerApi = setupServer(...handlers)
export {server, rest}
```

test.tsx:
```ts
test('Should the list of products', async () => {
    const {findAllByRole, findByText} = wrapper
    server.use(
        rest.get('http://localhost/products/search', (req, res, ctx) => {
          return res(ctx.json({
              products: [{
                id: 1,
                brand: "xxx",
                name: "CW452 ",
              }],
         total: 1
        }),
      )
    
      const productName = await findByText(/CW452/i)
      expect(firstProductName).toBeInTheDocument()

  })
```

### Current behavior

The runtime request handler is not overwritten when I run the tests and it fails. If I update the request handler inside the server file the test passes successfully.

### Expected behavior

The runtime request handler should override the existent one.

**Comment by kettanaito** [comment]
Hey, @slim-hmidi. Thanks for reporting this. Unfortunately, I can see you forgot to attach a reproduction repository. I can't help you much without it.

Still, I will share some thoughts after looking at the code snippets you've attached:

- You can drop `Content-Type` header if using `json()`, it's automatically set to `application/json` to produce a valid response.
- I suspect you render your component in the `wrapper`. If that's the case, move the `server.use()` call to the very beginning of your test suite. As a rule of thumb, apply request handlers as the first thing your test does. That way you will be sure you're not applying them after your code has been executed already. 
- If you're using any request libraries, like React Query or SWR, make sure you _disable their cache during tests_. You don't want to receive a cached response from an unrelated test.

**Comment by slim-hmidi** [comment]
Thanks for these info.
Yes it was due to rtk-query which returns the cached value. I updated the code and it's fixed now.
