### ISSUE TITLE
Can no longer nest setupServer within Jest describe blocks

### ISSUE THREAD

**Issue by msamsonoff** [kettanaito/msw#1283]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.15.0

### Reproduction repository

https://github.com/msamsonoff/msw-jest-describe

### Reproduction steps

`npm run test`

### Current behavior

The test within the second `describe` block is handled by the server configured in the first `describe` block. The value returned is `"one"` instead of `"two"`. Closing and recreating the server across the two `describe` blocks no longer resets the mock server.

### Expected behavior

I expect to be able to scope `setupServer` within a `describe` block. This worked up through 0.41. You can see this in my example repository if you either check out the initial commit or if you otherwise roll msw back to version 0.41.

**Comment by kettanaito** [comment]
Hey, @msamsonoff. Thanks for reporting this. 

While this might've worked before, you shouldn't use multiple `setupServer` calls within the same test file. The test framework you're using may decide to parallelize tests in a single (or multiple) test files, calling both "describe" blocks at the same time. This will result in `setupServer` applying the interception of requests on top of each other, resulting in all sorts of unexpected behavior. 

## Recommended usage

Always use a single `setupServer` call per test file. If you wish to control different server behaviors in different "describe" blocks, utilize `server.use()`:

```js
const server = setupServer(...handlersThatApplyToAllTestsBelow)

beforeAll(() => server.listen())
afterEach(() => server.resetHandlers())
afterAll(() => server.close())

describe('one', () => {
  beforeEach(() => server.use(...handlersForThisDescribeOnly))

  it('test', ...)
})

describe('two', () => {
  beforeEach(() => server.use(...someOtherHandlersForThisDescribe))
})
```

> Note that you likely want to use `beforeEach()` in your "describe" blocks because the root-level `afterEach` will trigger after _each individual test_, not after each "describe" block. If you apply request handler overrides in `beforeAll`, they will get reset by the root-level `afterEach` while your tests are being run.

**Comment by captain2b** [comment]
Hi! I was wondering, if we cant have more than one server how can we simultaneously use https://github.com/mswjs/msw-storybook-addon and plain Jest testing? Since storybook-addon would call setupServer in initialize method.
