### ISSUE TITLE
Graphql “all” error policy returns undefined data

### ISSUE THREAD

**Issue by ritchieanesco** [kettanaito/msw#1286]
Setting the graphql client to use “all” error policy, it is expected that the response should return both an array of errors and partial data.

I’ve tested this with 2 libraries (apollo-client and urql ) and both returned data as undefined with a correct error payload.

Below is an example of what was used:

```ts
graphql.query('GetUserInfo', (req, res, ctx) => {
 return res(ctx.data({…}), ctx.errors([…]))
})
```

**Comment by kettanaito** [comment]
Hey, @ritchieanesco. 

Please provide a reproduction repository with the steps how to get to the issue you're experiencing. Without those, any issue will be closed.

What MSW does is constructs a `Response` with the JSON payload you've specified in the request handler. The "error" policy is something applied and resolved by your GraphQL Client (Apollo/URQL). If you see that the returned payload is incorrect, this means that you're not returning the GraphQL response your configured policy expects. 

To fix this, disable any mocking and perform the GraphQL request with the "all" policy enabled. Inspect its response body in the Network of your browser's dev tools. Then, make sure to construct _identical_ response using request handlers in MSW. Chances are, you're missing things like `__typename`, certain fields, or something else. This is very unlikely to be an issue with the library.
