### ISSUE TITLE
Cannot set multiple "Set-Cookie" response headers

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#1290]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.14.0

### Reproduction repository

https://codesandbox.io/s/relaxed-vaughan-fuo4gq?file=/index.js

### Reproduction steps

1. Open the sandbox in a new window.
2. Navigate to `/`. See the `set-cookie` response header in the Devtools.
3. Navigate to `/another`. See the `set-cookie` response header in the Devtools. It's missing a value. 

### Current behavior

Only the latest `Set-Cookie` value is being set on the mocked response. 

### Expected behavior

You can set multiple `Set-Cookie` response headers on a mocked response using the `ctx.cookie` transformer.s

**Comment by kettanaito** [comment]
## Insights

This happens because MSW uses `headers.set()` instead of `headers.append()` when adding the `Set-Cookie` header to the mocked response: 

https://github.com/mswjs/msw/blob/f37142d0cc9048f525792416d93e49f9f1d0786a/src/context/cookie.ts#L15

I believe that changing this to `res.headers.append` will fix the issue. This also needs an integration test, as our current tests don't report this as an issue.

**Comment by kettanaito** [comment]
Hey, @aleehedl. Thank you once more for reporting this. Please, would you be interested in tackling this issue? I can help you with writing a test for it. Let me know if this interests you, it can be a great chance to collaborate. See you in the pull requests!

**Comment by aleehedl** [comment]
Hi @kettanaito. I think I could, possibly tomorrow :-)

**Comment by kettanaito** [comment]
Hey, @aleehedl. If you don't mind, I went ahead and fixed this issue. It'd be nice to include it in the next release.

**Comment by aleehedl** [comment]
Great! I got caught up with work stuff and then vacation stuff :-)

**Comment by kettanaito** [comment]
No worries! I'm thankful for you bringing up this issue. It should be resolved in the next release.

**Comment by kettanaito** [comment]
## Released: v0.43.1 🎉

This has been released in v0.43.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.43.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.43.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
