### ISSUE TITLE
Test isolation possibly not working (SyntaxError: Unexpected end of JSON input at parse)

### ISSUE THREAD

**Issue by ca057** [kettanaito/msw#1295]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.15.0

### Reproduction repository

https://github.com/ca057/msw-bug-reproduction

### Reproduction steps

Run `npm test`

### Current behavior

The second test of `src/useData.test.ts` fails when running the tests with the following error:

```
 FAIL  src/useData.test.ts
  ✓ returns null when API call fails (10 ms)
  ✕ returns the data retrieved from the API call (52 ms)

  ● returns the data retrieved from the API call

    SyntaxError: Unexpected end of JSON input
        at parse (<anonymous>)

      12 |   const fetchData = useCallback(async () => {
      13 |     const response = await fetch(`http://localhost:4730/${path}`);
    > 14 |     const result = await response.json();
         |                    ^
      15 |     setData(result);
      16 |   }, [path]);
      17 |

      at src/useData.ts:14:20
```

Both test cases are executed properly, when either one of the following adaptions are made:

* the test cases are reversed in order, so the test-case with the one-time overwrite is executed last
* the one-time overwrite in the first test-case is adapted to return a body in addition to a status code of 500 (`res.once(ctx.status(500), ctx.json({}))` instead of `res.once(ctx.status(500))`

Logging e.g. the status code of the response inside the `useData`-hook shows that the overwrite is reset after each test case (the first test case prints a status code of 500, the second one a status code of 200).

### Expected behavior

Both test cases work regardless of their order and work even if the one-time overwrite for an error response doesn’t return an empty object as JSON response.

A similar behaviour can be observed on the branch `server-response-as-text`, where the mock-server returns the JSON as text and the hook uses `response.text()` to parse the response body and performs a `JSON.parse(result)` of the outcome afterwards (https://github.com/ca057/msw-bug-reproduction/blob/server-response-as-text/src/useData.ts#L15). This time, not the `response.text` is breaking but parsing the JSON, although valid JSON is sent all the time. This can only be fixed by adapting the one-time overwrite to return an empty JSON object as stringified body (`ctx.text("{}")`) or by swapping the tests (similar to the main reported issue).

Is there something I’m doing wrong when setting up/running the tests or something broken with the environment? I’m happy to support more with debugging/understanding the issue/providing information. Thanks for your awesome work and support!

**Comment by ca057** [comment]
For context: This code snippet is part of an introductory React application bootstrapped with `create-react-app`, I removed most files which have no impact on the observed behaviour.

**Comment by kettanaito** [comment]
Hi, @ca057. Thanks for reporting this. I've just got time to look into this issue and it appears to be fixed in the latest v1 of MSW. 

```diff
index 26508ea..84f5782 100644
--- a/package.json
+++ b/package.json
@@ -41,6 +41,6 @@
     ]
   },
   "devDependencies": {
-    "msw": "^0.42.1"
+    "msw": "^1.3.2"
   }
 }
```

Run `npm i -D msw@^1` to get the fix. 

Also, please consider [migrating to MSW 2.0](https://mswjs.io/docs/migrations/1.x-to-2.x) as it includes a ton of improvements and additional features. v1 is not maintained anymore. Thanks.
