### ISSUE TITLE
ci(smoke): this workflow should use `node-version: 16` instead of `node-version: 16.14` for consistency 

### ISSUE THREAD

**Issue by oscard0m** [kettanaito/msw#1304]
### Scope

Improves an existing behavior

### Compatibility

- [X] This is a breaking change

### Feature description

Other workflows of this project are using `node-version: 16` instead of `16.14`. I think same version should be used across all the workflows for consistency.

**Comment by kettanaito** [comment]
## Released: v0.43.0 🎉

This has been released in v0.43.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.43.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.43.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
