### ISSUE TITLE
Documentation/example for rest generics in TypeScript

### ISSUE THREAD

**Issue by philals** [kettanaito/msw#1306]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Morning

First off, thanks for msw. It's great!

I'm upgrading to the latest version and having an issue quickly understanding the generics on rest (there might have been changes 0.34.0 -> 0.42.3).

Is there an example on this? I could not find it. Some times reading the code and type definitions can be a bit hard. I don/t mind writing it up (once I know what is what). Something like the first generic is X and the second is Y and examples.

I can see quite a few tickets related to the development of generics support (https://github.com/mswjs/msw/pull/352) but cannot find it on the main docs/example page.

Cheers

Edit: just worked out there is now 3 generics! Body, PathParams, Response. Cool! The definition file was really wide and I could not parse it :).

**Comment by kettanaito** [comment]
Hey, @philals. Thanks for raising this.

I highly recommend reading [Type-safe API mocking with MSW](https://dev.to/kettanaito/type-safe-api-mocking-with-mock-service-worker-and-typescript-21bf). If you spot it not being up to date please let me know. That article should explain the usage of rest/graphql generics.
