### ISSUE TITLE
Chrome fails to register Service Worker

### ISSUE THREAD

**Issue by skysantoroa** [kettanaito/msw#1314]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/skysantoroa/msw-chrome-init-fail

### Reproduction steps

1. Launch `docker compose up`, it should run two containers: `reverse-proxy` and `client`
2. Open `https://localhost`
3. Open the console, it will print the following error:

```
getWorkerInstance.ts:85 Uncaught (in promise) Error: [MSW] Failed to register the Service Worker:

Failed to register a ServiceWorker for scope ('https://localhost/') with script ('https://localhost/mockServiceWorker.js'): An SSL certificate error occurred when fetching the script.
    at getWorkerInstance (getWorkerInstance.ts:85:1)
    at async startWorkerInstance (createStartHandler.ts:31:1)
```

### Current behavior

Chrome will fail printing `An SSL certificate error occurred when fetching the script.`. None of the [suggestions](https://mswjs.io/docs/recipes/using-local-https) on the official doc help.

### Expected behavior

The service worker should be launched correctly by printing `[MSW] Mocking enabled.` like Firefox.

**Comment by kettanaito** [comment]
Hey, @skysantoroa. 

The issue you're experiencing is caused by your local HTTPS setup. The browser will refuse to register a Service Worker on an insecure host, and localhost is insecure by default, even if you're using a self-signed certificate. 

Please follow the guide on [Using local HTTPS](https://mswjs.io/docs/recipes/using-local-https) from our documentation to resolve this issue.

**Comment by skysantoroa** [comment]
> None of the [suggestions](https://mswjs.io/docs/recipes/using-local-https) on the official doc help.

1. The certificate in my repo has been signed using Let's encrypt.
2. The `allow-insecure-localhost` won't help bypass the certificate check.

**Comment by kettanaito** [comment]
Sorry for overlooking your mention of the docs 👍 

Then there's an issue with the certificate. Perhaps it's been signed for a different domain than `localhost`? What does the internet suggest to resolve this? 

This is a browser issue so there's virtually nothing we can do on the library's side. Looks like the browser cannot check that signed certificate for some reason. If there are any logs available, check those. I don't remember if you can hover over the certificate and see some potential issues—if that was ever the thing in the browser.

**Comment by skysantoroa** [comment]
> Then there's an issue with the certificate. Perhaps it's been signed for a different domain than localhost? What does the internet suggest to resolve this?

The certificate has been generated for localhost using the script provided by [let's encrypt](https://letsencrypt.org/docs/certificates-for-localhost/).

When launching multiple browser instances from Playwright, Chromium browsers are the only ones getting the error.
