### ISSUE TITLE
Support native fetch and vitest

### ISSUE THREAD

**Issue by gkiely** [kettanaito/msw#1319]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.4.0

### Reproduction repository

https://github.com/gkiely/vite-react-template

### Reproduction steps
```
git pull https://github.com/gkiely/vite-react-template
npm i
npm test
```

### Current behavior
Fetching never runs the msw route or completes.

In the repo when running `npm test` you will see the logs:
```
fetching http://localhost:8080/api/posts
```

But the request never completes or throws an error.

### Expected behavior

You see the logs:
```
fetching http://localhost:8080/api/posts
rest handler called
fetched posts ...
```

**Comment by ekwoka** [comment]
Was this actually handled? I'm having issues with the native fetch in Node right now. Everything seems to be working but the requests bypass the handlers entirely.

**Comment by gkiely** [comment]
@ekwoka It wasn’t handled I just switched to something else. Feel free to re-open.

The repo linked above no longer recreates the issue so it will need a new example.

**Comment by kettanaito** [comment]
A fair mention: there's no official support for native fetch in Node. It's implemented differently than the standard `http`, and so we need to write an explicit logic to detect such requests on the [interceptors level](https://github.com/mswjs/interceptors).

**Comment by mncorreia** [comment]
Hi guys, any solution here? I had same problem with Vitest and MSW.

![Captura de Tela 2023-06-23 às 18 56 32](https://github.com/mswjs/msw/assets/26151779/9fefbcc7-9399-4a45-b02c-d88b0e1488fa)

**Comment by ekwoka** [comment]
I mainly used Undici. Undici is the actual fetch implementation used by Node, and it has some of its own tools for mocking. But I have had issues with newer versions of node, but that works on 18 fine.

I guess there is also the option to, in your tests, override the native fetch with something like node-fetch/cross-fetch to then use msw

**Comment by kettanaito** [comment]
The current version of MSW support intercepting global fetch requests in Node.js. Make sure to update to the latest tag on npm.

However, we're shipping a much better Fetch API support in #1464. If you can afford it, please migrate to the 2.0 version right now and share your feedback. Thanks.
