### ISSUE TITLE
The response is intermittently not returned in the Firefox.

### ISSUE THREAD

**Issue by BEGEMOT9I** [kettanaito/msw#1325]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Firefox

### Reproduction repository

I've tried to create example in codesandbox, but i've got error ([MSW] Failed to execute `setupWorker` in a non-browser environment. Consider using `setupServer` for Node.js environment instead.)

### Reproduction steps

1. Create mock
2. Try to get data from this mock in Firefox (v102, MacOS version)
3. U will get smth like this:
<img width="516" alt="Снимок экрана 2022-07-13 в 15 37 27" src="https://user-images.githubusercontent.com/11138075/178735567-ac15be1c-8057-436f-bcde-58af7acfc792.png">

### Current behavior

Response doesn't end
In Chrome everything alright, this behaviour appeared in `msw@0.43`

### Expected behavior

The response must be ended

**Comment by mattcosta7** [comment]
I've seen the same behavior recently with msw version 0.43 and 0.44

**Comment by kettanaito** [comment]
## Released: v0.44.2 🎉

This has been released in v0.44.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.44.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.44.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by mattcosta7** [comment]
New version looks good to me, thanks @kettanaito !

**Comment by BEGEMOT9I** [comment]
Thank u very much!
