### ISSUE TITLE
msw fails to run on 0.44.0

### ISSUE THREAD

**Issue by netcoding87** [kettanaito/msw#1326]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.), Firefox, Safari

### Reproduction repository

https://github.com/netcoding87/msw-safari

### Reproduction steps

- `npm install` (will install `msw` in v. `0.43.0`) 
- `npm run start`
=> Worker is enabled and working
---

- update `msw` to latest version (`0.44.0`)
- `npm run start`
=> Worker is enabled but throwing errors

### Current behavior

![image](https://user-images.githubusercontent.com/54022880/178737159-cbbf25de-26f2-445a-82c1-d41876397cd0.png)

### Expected behavior

Working `msw` 😄

**Comment by fabriciodorneles** [comment]
Same here, when updated for 0.44.0 this error starts to happen. Going back to 0.43.0 the application works right.

![image](https://user-images.githubusercontent.com/64965851/178950610-7a63447d-5378-4b03-94b1-a3b591a2d1f4.png)

**Comment by kettanaito** [comment]
Thanks for reporting this, everyone. We are working on a fix to this issue. You can use 0.43.0 meanwhile.

**Comment by kettanaito** [comment]
Interestingly enough, I can't reproduce this issue in that repo in Chrome/Safari at all. One of our maintainers can, though, and he has implemented a fix.

**Comment by kettanaito** [comment]
## Released: v0.44.1 🎉

This has been released in v0.44.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.44.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.44.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
