### ISSUE TITLE
Allow escaping reserved characters

### ISSUE THREAD

**Issue by sjoerdvanBommel** [kettanaito/msw#1347]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

When trying to mock an endpoint that contains a reserved character, in my case a colon, msw will treat it as it should: like a variable. It would be nice, however, to be able to escape certain characters in case they are present in the users' URL.
e.g. `https://example.com/test/picture:hide` where `:hide` is part of the URL, not a variable.

I'm aware of [this comment](https://github.com/mswjs/msw/discussions/739#discussioncomment-2524732) mentioning you can escape the character by prepending it with 2 backward slashes, but this exists for internal usage. I think this should be supported for consumers as well and that it should be documented ([here](https://mswjs.io/docs/basics/request-matching#path-with-parameters) for example).

**Comment by kettanaito** [comment]
Hi, @sjoerdvanBommel. Thanks for raising this. 

We're using [path-to-regexp](https://github.com/pillarjs/path-to-regexp) library, which also powers Express and newly introduced `URLPattern` native API in the browser. This means we're bound to how that library implements character escaping. 

You should use double backslash `\\` to escape a special character from the URL. I don't believe it's meant for internal usage as it's also featured in `path-to-regexp` examples multiple times. 

```js
rest.get('/test/picture\\:hide', resolver)
```
