### ISSUE TITLE
Node17 and Node18: Unable to parse stubbed response bodies from the mws rest.post

### ISSUE THREAD

**Issue by rosatolen** [kettanaito/msw#1349]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.6.0 and v17.9.1

### Reproduction repository

https://github.com/rosatolen/msw-stub-post-bug-node17-node18

### Reproduction steps

All steps are in the readme of the provided repository but they are provided here again:

1. Ensure you are using node18 or node17. An .nvmrc file has been provided for ease of use.
2. Run yarn install
3. Run yarn test

### Current behavior

When stubbing this [post request response](https://github.com/rosatolen/msw-stub-post-bug-node17-node18/blob/main/__tests__/fooRouter.spec.js#L24) with msw, the response body causes the production code to hang while parsing it [here](https://github.com/rosatolen/msw-stub-post-bug-node17-node18/blob/main/fooRouter.js#L18). On the other hand, if I [stub a get request response instead](https://github.com/rosatolen/msw-stub-post-bug-node17-node18/blob/main/__tests__/fooRouter.spec.js#L39), I do not see the same issue. 

### Expected behavior

Parsing the response body stubbed by an msw rest.post should not cause my code to hang. The response body provided by the msw rest.post seems to be malformed in some way. The rest.post functionality should match the existing working functionality in rest.get.

**Comment by nathanhannig** [comment]
My requests were also hanging, but I was on Node 16.10.0
https://github.com/mswjs/msw/issues/1327

**Comment by rosatolen** [comment]
@nathanhannig The version of node16 where I don't see issues is 16.16.0. Not sure if that will help

**Comment by ddolcimascolo** [comment]
Node 16.13.0 here, reproduction repo is in #1327

**Comment by kettanaito** [comment]
Hey, folks. Thanks for raising this. 

We've addressed this issue in the latest `next` release tag. Please upgrade to `npm i msw@next` and read #1464 since it's a release candidate for 2.x and is a breaking change. 

Working with request and response bodies is done using Fetch API primitives like `Request` and `Response` and works without issues. There's no intention to address this in the 1.x version of the library. Thank you for understanding.
