### ISSUE TITLE
fetch failed - connect ECONNREFUSED ::1:8080 with vitest and @testing-library/react

### ISSUE THREAD

**Issue by Marvin9** [kettanaito/msw#1351]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.6.0

### Reproduction repository

https://github.com/Marvin9/vitest-msw-reprod

### Reproduction steps

```
pnpm install
```

```
pnmp test
```

### Current behavior

<img width="1440" alt="Screenshot 2022-07-25 at 5 51 27 PM" src="https://user-images.githubusercontent.com/17699717/180778109-62da8710-d4d6-4038-8299-9b6319bd0175.png">

### Expected behavior

msw should intercept requests to localhost.

**Comment by zapalagrzegorz** [comment]
For me it intercepts my calls to _http://localhost:3000_

**Comment by nknapp** [comment]
Duplicate of #1319, probably

**Comment by hbsnow** [comment]
Try polyfilling fetch

```ts
// ./setup.ts
import { fetch } from 'cross-fetch';
global.fetch = fetch;

// ./vite.config.ts
export default defineConfig({
  ...
  test: {
    ...
    setupFiles: ["./setup.ts"],
  },
});
```

![スクリーンショット 2023-01-02 6 00 44](https://user-images.githubusercontent.com/661266/210184451-07d1bc8f-ed49-4a1d-900b-004507260b27.png)

link: https://markus.oberlehner.net/blog/using-mock-service-worker-with-vitest-and-fetch/

**Comment by kettanaito** [comment]
Yes, please remember that you need to polyfill `fetch` in order to test client-side code that uses it in Node.js environment (where Vitest, Jest, and other testing frameworks run).

**Comment by uxduck** [comment]
From my understanding of the current docs, polyfilling `fetch` seems to not be necessary. However, I have the same error now.
