### ISSUE TITLE
Can't handle requests from a shared worker

### ISSUE THREAD

**Issue by njoel24** [kettanaito/msw#1354]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/njoel24/integration-test-ms-shared-worker

### Reproduction steps

Hi @kettanaito, I  created a new issue with requested info from you.
I don't know if you get notifications on closed issue, and I just created a new one, just to be sure.

Here the issue:

When trying to request a shared worker, the clientId attached to fetch event object is an empty string.

That causes the following line to break under mockServiceWorker.js in resolveMainClient function:
if(client.frameType === 'top-level')

I managed to make it work currently by checking for client like the following:
if(client && client.frameType === 'top-level')

With that I am able to work with shared workers.

In the issue I described there are no iframes involved.

Here an integration test to reproduce the issue: https://github.com/njoel24/integration-test-ms-shared-worker
Just clone, install, run 'npm run build' and run 'npm run start' 

Here a screenshot of the error:

![test results](https://user-images.githubusercontent.com/71449544/181627987-03dd1248-d8c3-475d-84a3-515eb15a4549.PNG)

Please note that the handler has not been implemented and left as null because the error happens before.

Grateful if you can check it.
I would be more than happy to give you more information and contribute as well.

msw version: 0.44.2

Thanks

### Current behavior

the msw fails handling the request

### Expected behavior

msw should handle the request.

**Comment by kettanaito** [comment]
## Released: v0.48.0 🎉

This has been released in v0.48.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.48.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.48.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
