### ISSUE TITLE
Variables not intercepted in GraphQL queries and mutations

### ISSUE THREAD

**Issue by MaxPowerReforged** [kettanaito/msw#1355]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.16

### Reproduction repository

https://github.com/MaxPowerReforged/report-msw-error

### Reproduction steps

After cloning the repository:

- Install dependencies `yarn install`.
- Execute tests using `yarn test-once`.

### Current behavior

When a GraphQL request is intercepted (both queries and mutations), the variables object is empty. Therefore, accessing the variables as shown in the [documentation](https://github.com/MaxPowerReforged/report-msw-error) is not possible.

I have provided 3 test examples (two mutations and one query). One of the test fails because the response is designed to fail in case that the variables are not matching. In the three cases, the `req` object has an empty variables body.

### Expected behavior

I should be able to access the variables from the `req` object as explained in the [documentation](https://mswjs.io/docs/api/graphql/query#query-variables).

**Comment by MaxPowerReforged** [comment]
The error was due to an error on my end, the package works as expected.

**Comment by kettanaito** [comment]
Hey, @MaxPowerReforged. Glad to see it resolved! 🎉
