### ISSUE TITLE
Enable caching of `req.passthrough()`

### ISSUE THREAD

**Issue by Norfeldt** [kettanaito/msw#1364]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

MSW is making testing with jest so much better. We're using seeded users and sometimes I just use msw as a middle-man-attack to check if things are working correctly. This approach is hitting the server many times and sometimes I wish I had a service-worker for mock-service-worker.

would be fantastic if I could do something like

```
return req.passthrough({ allowCaching: true })
```

and then it will only fetch it once and otherwise it would get it from the cache.

**Comment by kettanaito** [comment]
Hey, @Norfeldt. Thank you for your kinds words. 

MSW itself is not concerned with resource caching, and `passthrough()` is just an escape mechanism to tell the library that it should "release" the captured request and let the rest of your app handle it as it does (without mocking). I'm afraid introducing caching here would stretch the library's responsibilities and is overall not something MSW promises you. If anything, it mustn't interfere with the actual request in any way unless you instruct it to (then it'd be mocking and still not caching). 

Note that there are no workers in Jest, so you wouldn't be able to cache your requests akin to a Service Worker in that environment anyway. There are a couple of things you can do.

## Option 1: Implement the caching layer

Implement a basic response storage for any requests you bypass. Then, you can even go as far as to creating a custom `passthrough()` function that'd resolve previously performed requests from cache. 

```js
import { response, context } from 'msw'

const cache = {}

export function passthroughWithCache(req) {
  const key = generateCacheKey(req)
  const cachedResponse = cache[key]

  if (cachedResponse) {
    // Use "response" and "context" as pure functions
    // so we don't have to pass the entire "req, res, ctx"
    // to this function.
    return response(
      context.status(304), // remain semantic
      context.json(cachedResponse)
    )
  }

  return req.passthrough()
}
```

And use it in your handlers:

```js
import { passthroughWithCache } from './passthroughWithCache'

rest.get('/resource', (req, res, ctx) => {
  return passthroughWithCache(req)
})
```

## Option 2: Add caching Service Worker (browser-only)

You can compose `mockServiceWorker.js` with your custom Service Worker that implements caching (use `importScripts` for that). This should be rather straightforward and you can find materials on how to cache responses in the worker online.

**Comment by Norfeldt** [comment]
thank you very much for the suggestion @kettanaito
