### ISSUE TITLE
tsc error: Cannot find module 'graphql' or its corresponding type declarations

### ISSUE THREAD

**Issue by irico3** [kettanaito/msw#1371]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.11.0

### Reproduction repository

https://github.com/takanokana/msw-for-issue

### Reproduction steps

1．npm ci
2. npm run typecheck

### Current behavior

node_modules/msw/lib/index.d.ts:4:63 - error TS2307: Cannot find module 'graphql' or its corresponding type declarations.

4 import { GraphQLError, OperationTypeNode, DocumentNode } from 'graphql';

### Expected behavior

No errors when executing tsc.

**Comment by kettanaito** [comment]
Hey, @takanokana. Thanks for reporting this.

This issue is tied to the recent discussion around `graphql` here: https://github.com/mswjs/msw/pull/1356. You can find more info about it in the linked pull request. 

We're looking for contributors to fix this. Would you like to help us out?

**Comment by mattcosta7** [comment]
> Hey, @takanokana. Thanks for reporting this.
> 
> This issue is tied to the recent discussion around `graphql` here: #1356. You can find more info about it in the linked pull request.
> 
> We're looking for contributors to fix this. Would you like to help us out?

As a first step, I wonder if a patch release removing the _optional_ peerDependency Meta might be a stopgap (npm should, i believe, install peers automatically - but not 100% sure offhand).  From there, most users shouldn't be warned / see errors.

After that - Separating out the graphql entry might be possible, but not super clear yet

**Comment by nathanredblur** [comment]
I'm getting this using the latest version ("msw": "^0.45.0") and I can not compile. I just want to mock my regular API.

`Module not found: Error: Can't resolve 'graphql' in '/.../node_modules/msw/lib'`

any workaround?

**Comment by mattcosta7** [comment]
> I'm getting this using the latest version ("msw": "^0.45.0") and I can not compile. I just want to mock my regular API.
> 
> `Module not found: Error: Can't resolve 'graphql' in '/.../node_modules/msw/lib'`
> 
> any workaround?

`npm i graphql` or downgrade to 0.44.x

**Comment by kettanaito** [comment]
We're opening a fix in https://github.com/mswjs/msw/pull/1381. Everyone is welcome to participate in the discussion there.

**Comment by kettanaito** [comment]
## Released: v0.46.1 🎉

This has been released in v0.46.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.46.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.46.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
