### ISSUE TITLE
isLoading from mutations not working with msw >= 0.42.3 when using react-query v4

### ISSUE THREAD

**Issue by beatriz1304** [kettanaito/msw#1372]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.15.0

### Reproduction repository

https://github.com/beatriz1304/msw-react-query

### Reproduction steps

To reproduce the problem, you need to install, execute the test, and check the output.
```
git clone https://github.com/beatriz1304/msw-react-query
cd msw-react-query
yarn install && yarn test
```

Output from msw v0.45.0
````
 console.log
    STATUS:  idle

      at App (src/App.js:7:11)

  console.log
    STATUS:  success

      at App (src/App.js:7:11)

 FAIL  src/App.test.js
  ✕ renders mock data "Hello" (1039 ms)

  ● renders mock data "Hello"

    Unable to find an element with the text: /loading.../i. [...]
````

Output from the msw v0.42.2
````
  console.log
    STATUS:  idle

      at App (src/App.js:7:11)

  console.log
    STATUS:  loading

      at App (src/App.js:7:11)

 PASS  src/App.test.js
  ✓ renders mock data "Hello" (43 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.843 s, estimated 2 s
Ran all test suites related to changed files.
````

The issue is specifically with react-query v4, I tested with react-query v3, and everything worked fine.

With MSW v0.42.2 (using the react-query v4), everything works fine (the status goes through the loading state).
So I can confirm that the issue was introduced with the v0.42.3, more specifically with this PR: https://github.com/mswjs/msw/pull/1300

### Current behavior

Notice that the status goes from `idle` to `success` while I was waiting to see the `loading` status as well.
The assertion is waiting for the status change to `loading`, it'll never happen then the test will fail.

### Expected behavior

I want to see the status of a mutation as`running` when using react-query v4 and msw>=0.42.3

**Comment by gammatitan** [comment]
I'm also experiencing this issue but running react-query v3.39.2. Did you manage to find a workaround?

**Comment by Saracevas** [comment]
This is caused by a removal of `setTimeout` in the MSW response transformer [right here](https://github.com/mswjs/msw/blob/main/src/node/SetupServerApi.ts#L93) in v0.42.3. 

To fix this, you can do the following in your handlers:

```
rest.get(
  '/api/endpoint', (req, res, ctx) => {
      return res(ctx.status(200), ctx.json(mockData), ctx.delay(1))
  }
)
```

**Comment by kettanaito** [comment]
Both MSW and React Query have evolved quite a lot since this issue has been reported. For once, MSW no longer has the `setTimeout` that was reported as the root cause of this.

I suggest you [update to MSW 2.0](https://mswjs.io/docs/migrations/1.x-to-2.x), update React Query also, and see if the issue is still there. I'm rather confident it's not. If you encounter any problems, please open a new issue and attach the link to a reproduction repository. Thanks.

**Comment by dstone1983** [comment]
I am also experience this issue with the latest version of MSW in storybook. I put an await delay() as well inside an async function.

`
http.put(UserUrls.mfaEnabled, async ({request}) => {
        await delay('real')
        return HttpResponse.json({
          mfaEnabled: false,
        });
    })
`

This has made using onSuccess impossible for me as well as isLoading and other aspects of react-query.

"msw": "^2.1.6",

**Comment by rafaelegh** [comment]
i'm having the same issue with react-query and storybook:

    "msw": "^2.2.1",
    "msw-storybook-addon": "2.0.0-beta.1",
    "@tanstack/react-query": "^5.24.1",

during a mutation, the stataful logic is never changing, isPending, isSuccess and isIdle are always on the same state.
