### ISSUE TITLE
Jest/Testing-Library with RTK-query, msw fails to reset handlers when testing for error case after success case.

### ISSUE THREAD

**Issue by ymoon715** [kettanaito/msw#1377]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.13.1

### Reproduction repository

https://github.com/ymoon715/rtk-query-msw

### Reproduction steps

clone the repo at https://github.com/ymoon715/rtk-query-msw

```javascript
npm i
npm run test
```

### Current behavior

I have my tests to reset the handlers after every test.
I ran into an error when testing for both success and error cases.
If i test error case FIRST, then success SECOND, it all passes.

However, if i test success case FIRST, then error case SECOND, error case fails.

I am using server.use() to test both success and error cases.
I have 4 different test files to showcase that testing error case first THEN the success case always works, where as testing success case first THEN the error case always fails

### Expected behavior

server.resetHandlers() to successfully reset the handlers, or for us to be able to test for error case after successful cases.

**Comment by kettanaito** [comment]
Hey, @ymoon715.

Did you try running your test with the `--runInBand` option for Jest?

```sh
jest --runInBand
```

MSW doesn't support parallel runs (see #474), so you need to make sure you run your tests sequentially. I believe once you add this option to your test script the issue will be gone:

https://github.com/ymoon715/rtk-query-msw/blob/9f761fc110d96446207c9218ced90faadd5b4558/scripts/test.js#L52

Could you please try this out?

**Comment by ymoon715** [comment]
> Hey, @ymoon715.
> 
> Did you try running your test with the `--runInBand` option for Jest?
> 
> ```shell
> jest --runInBand
> ```
> 
> MSW doesn't support parallel runs (see #474), so you need to make sure you run your tests sequentially. I believe once you add this option to your test script the issue will be gone:
> 
> https://github.com/ymoon715/rtk-query-msw/blob/9f761fc110d96446207c9218ced90faadd5b4558/scripts/test.js#L52
> 
> Could you please try this out?

Thanks for the reply @kettanaito 
I just tried `--runInBand` and it made no difference.

**Comment by kettanaito** [comment]
Then it’s either shared state issue that introduces between-test dependency, or a bug.

**Comment by ymoon715** [comment]
If the following tests succeeds with `nock`, would you consider this a msw issue? These tests were written on create-react-app. I also tried it with bunch of clean up methods including resetting the reducer.

**Comment by jucian0** [comment]
I got the same error with react query, any solution?

**Comment by jucian0** [comment]
For me the problem was that React Query by default retry when a request fails, so, I disabled that in tests, @ymoon715, probably RTK works in the same way.

**Comment by SaltedCaramelCoffee** [comment]
I was running into the same issue when fetching data using SWR. My issue was I was fetching data with the same key, so the first request's response is cached, and was returned to me in subsequent test runs.

I was able to resolve my issue by providing a clean SWR provider at every render like this:

```
<SWRConfig value={{ provider: () => new Map() }}>
  { children }
</SWRConfig>
```

From what I can see in the [RTK docs](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior), looks like RTK does something similar and caches response data based on some key. You might be able to solve your problem if you figure out how to invalidate cache and re-fetch for each test case even if you're using the same key.

**Comment by ymoon715** [comment]
> I was running into the same issue when fetching data using SWR. My issue was I was fetching data with the same key, so the first request's response is cached, and was returned to me in subsequent test runs.
> 
> I was able to resolve my issue by providing a clean SWR provider at every render like this:
> 
> ```
> <SWRConfig value={{ provider: () => new Map() }}>
>   { children }
> </SWRConfig>
> ```
> 
> From what I can see in the [RTK docs](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior), looks like RTK does something similar and caches response data based on some key. You might be able to solve your problem if you figure out how to invalidate cache and re-fetch for each test case even if you're using the same key.

Tried removing/resetting cache afterEach. This did not work.

**Comment by DominicGBauer** [comment]
@ymoon715 I think you need to add this to your RTK Query API

```
export const api = createApi({
  ...
  keepUnusedDataFor: process.env.NODE_ENV === 'test' ? 0 : 60, <----- THIS HERE
});
```

So that data is not cached when using tests

**Comment by augusticor** [comment]
If cache is the problem use this solution from another issue

```javascript
beforeEach(() => {
  store.dispatch(pokemonApi.util.resetApiState());
});
```

https://github.com/mswjs/msw/issues/251#issuecomment-1274474669

Same solution but on stackoverflow from rtk query contributor:
https://stackoverflow.com/questions/67999073/how-to-clear-rtk-query-cache-in-tests-between-requests-when-using-msw-and-jest

**Comment by gonzalo-novak** [comment]
Same issue here. My app uses TS, React Context, and the fetch API (using cross-fetch as a polyfill for node). There's no cache management, and I'm experiencing the same issue. 

The versions I'm using are the following:
`msw: ^1.3.2`
`jest: ^29.2.2`
`node version: 18.12.1`

I have to order the failed scenarios first before the successful ones. Otherwise, I get the same behavior. 😢

**Comment by kettanaito** [comment]
I'm fairly certain this has been fixed. Please upgrade your dependencies (including jest and related ones) and let me know. If it hasn't, submit a new issue with a new reproduction repo. 

If you are using Jest and JSDOM, use https://github.com/mswjs/jest-fixed-jsdom to make sure you don't have the broken environment to run MSW 2.0.
