### ISSUE TITLE
Flakiness with Cypress Component Testing - "Failed to update a ServiceWorker for scope ... An unknown error occurred when fetching the script"

### ISSUE THREAD

**Issue by jchi2241** [kettanaito/msw#1378]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

private repo :(

### Reproduction steps

We have Cypress Component Testing setup with MSW as follows:

we have a `setupMockServer` function that looks like
```typescript
import { setupWorker } from "msw";

export function setupMockServer(handlers: Parameters<typeof setupWorker>) {
    const server = setupWorker(...handlers);

    before((done) => {
        server
            .start({
                onUnhandledRequest: (req) => {
                    if (
                        !req.url.pathname.includes("__cypress") &&
                        !req.url.pathname.includes("static")
                    ) {
                        console.error("Unhandled Request:", req);
                        throw new Error("Unhandled Request");
                    }
                },
            })
            .then(() => done());
    });

    afterEach(() => server.resetHandlers());
    after(() => server.stop());
}
```
that is called in each `.spec.tsx` test file as follows:
```typescript
// example.spec.tsx
import { graphql } from "msw";
import { setupMockServer } from "...";

describe("example", () => {
    setupMockServer([
        graphql.query("getBlah", () => { ... }),
        ...
    ]);

    it("example test", () => {
        render(<App />);
        ....
    });
});
```

To start the tests, we run `msw init` and then run `cypress run-ct`

95% of the time the tests pass without issues. However, once in awhile a spec flakes with the following error
```
The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  > Failed to update a ServiceWorker for scope ('http://localhost:37565') with script ('http://localhost:37565/mockServiceWorker.js'): An unknown error occurred when fetching the script.
```
![image](https://user-images.githubusercontent.com/1195698/187294038-2b5abce3-c559-4891-b067-0b2150448e1e.png)

I assume the error is occurring [here](https://github.com/mswjs/msw/blob/2e7ecd87e5568c6e59a408e812535f088498e437/src/setupWorker/start/utils/getWorkerInstance.ts#L40)

### Current behavior

See above

### Expected behavior

The tests to not flake with the error mentioned above

**Comment by kettanaito** [comment]
Hey, @vai0. Thanks for reporting this. 

Unfortunately, I don't have the capacity to look into issues that don't have clear reproduction repositories. You certainly don't have to publish your private project. Instead, isolate the issue on a fresh project as close to your original one as possible. The good thing is that you may discover the fix along the way by yourself.

**Comment by kettanaito** [comment]
Based on the error message, I can only assume that you're not serving the worker script during your test runs. Make sure to serve the public directory in Cypress.

**Comment by jchi2241** [comment]
Thanks for the follow-up. 

As mentioned, this mostly occurs in the CI, and only happens every once-in-awhile (5%'ish of the time), indicating some sort of flake -- not sure setting up a repro could reproduce this as it very rarely occurs locally.

The error also starts with it "Fails to update...", which indicates that the service worker already exists, possibly from a previous spec file that just ran, which means that the public directory where /mockServiceWorker.js does exist -- otherwise we'd see the ["404" error message msw throws](https://github.com/mswjs/msw/blob/main/src/setupWorker/start/utils/getWorkerInstance.ts#L74)

I suspect it could be due to how we're loading msw alongside cypress component testing -- was wondering if anyone else had experienced this before

**Comment by anilanar** [comment]
We are experiencing the same. We run `mswServer.start()` in `before` hook and wrap it with `cy.wrap`. Sometimes it mysteriously fails with the same error, and the whole test suit fails.
