### ISSUE TITLE
MSW doesn't resolve with Jest 28 .useFakeTimers()

### ISSUE THREAD

**Issue by harry-gocity** [kettanaito/msw#1390]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

14, 16, 18 (we are on 16)

### Reproduction repository

https://github.com/harry-gocity/msw-examples/tree/repro

### Reproduction steps

Switch to 'repro' branch
Run the tests in examples/with-jest
Test fails as MSW resolver does not respond

### Current behavior

This has come up before (https://github.com/mswjs/msw/issues/448, https://github.com/mswjs/msw/issues/966, and elsewhere [here](https://github.com/testing-library/dom-testing-library/issues/988) and similarily [here](https://stackoverflow.com/questions/28504545/how-to-mock-a-constructor-like-new-date#comment118708676_65548068)) but I can't find a solution when using `fetch` (polyfilled with `whatwg-fetch` and Jest 27 / 28. Please feel free to close this issue and direct me elsewhere if this isn't the case!

I believe that this issue could be to do with [jest mocking out functions used by MSW](https://github.com/mswjs/msw/issues/966#issuecomment-1141489352) (`setTimeout`, `nextTick` etc) but skipping these via Jest's [selective faking](https://jestjs.io/docs/28.x/timer-mocks#selective-faking) has no effect.  

https://github.com/mswjs/msw/issues/1125 suggests it may be due to node version, but that's marked as solved.

### Expected behavior

MSW resolver should respond

**Comment by milesrichardson** [comment]
Not sure, but this sounds related to to [changes in Jest global injection](https://jestjs.io/blog/2022/04/25/jest-28#all-nodejs-globals), which will cause it to inject the node-native `fetch`, which will not be intercepted. I recommend verifying that your tests are using the polyfilled `whatwg-fetch` and not the node native `fetch`.

Here's a [PR where I fixed a similar issue](https://github.com/mswjs/interceptors/pull/283/commits) (see the first commit). You might find some helpful information in there. This PR is part of a series of PRs to add support for native `fetch` and migrate `msw` development and CI to Node 18. 

The root problem is that msw does not intercept native `fetch` in Node 18. I have some PRs in progress to fix this. See my [recent comment](https://github.com/mswjs/msw/issues/1388#issuecomment-1241180921) on #1388 for summary and discussion.

**Comment by harry-gocity** [comment]
Hi @milesrichardson, In the repro above this is also an issue on Node 16 and 14. Have updated the issue description. There is some discussion in https://github.com/mswjs/msw/issues/1388 around using `cross-fetch` or `node-fetch` instead but neither solve the issue either.

**Comment by ronkot** [comment]
Just adding my 2 cents. We encountered two kind of weird problems using the latest msw version (1.1 or something):
- `ReferenceError: setTimeout is not defined` when calling `server.close()` (https://github.com/facebook/jest/issues/11713#issuecomment-1462013989)
- Runtime handler configs (`server.use()`) were not always taking precence. By logging the handlers it seemed that the runtime handler was there but response was delivered from default handlers. The behaviour was not deterministic - on some runs runtime handler was called and in some runs not.

Both problems were fixed by downgrading to msw@0.41.1. I found this working version by binary searching through msw versions. So it seems that from 0.42.0 onwards something changed with timers (or something..)

My setup:
- Node 16.13.2
- Jest 27.5.1
- whatwg-fetch 3.6.2

**Comment by TrAndreiR** [comment]
Any updates regarding this issue?

**Comment by harry-gocity** [comment]
Currently upgrading to v2, with Node 20.9, and now on Jest 29. The following config seems to work:

```tsx
const mockDate = new Date(2022, 6, 26);

beforeEach(() => {
    jest.useFakeTimers({
        now: mockDate,
        doNotFake: ['queueMicrotask'],
    });
});

afterEach(() => {
    jest.useRealTimers();
});
```

**Comment by kettanaito** [comment]
I confirm that you should be `doNotFake: ['queueMicrotask']` with Jest's `useFakeTimers` to prevent Jest from stopping any scheduled microtasks in the process. We are working on updating the documentation to feature this as well. 

- [How to use `jest.useFakeTimers()` with global fetch](https://mswjs.io/docs/runbook#requests-are-not-resolving-when-using-jestusefaketimers)

**Comment by harry-gocity** [comment]
Cheers @kettanaito - have to say upgrading our codebase from v1 -> v2 (~150 rest resolvers) was an absolute breeze, largely thanks to the fantastic new docs 🎉

**Comment by kettanaito** [comment]
Thank you, @harry-gocity! It means a lot to me to hear that! Writing the new docs took _a ton_ of time. I'm happy to see that time paying off.

**Comment by tomdglenn91** [comment]
Just commenting here as I'm currently on msw 0.x and this solution does not work for me. However if I add `setTimeout'` it does work. No idea if this is the 'correct' approach, all I know is before this code, it did not work, and after adding it, now it does.

```
  jest.useFakeTimers({
      doNotFake: ['setTimeout'],
    });
```

Thanks @kettanaito for getting me 99% of the way there, hopefully this helps someone out who stumbles along this
