### ISSUE TITLE
Slow pending with cypress

### ISSUE THREAD

**Issue by iamyoki** [kettanaito/msw#1391]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/QhlabTeam/cra-template-qhlab/tree/msw-cypress-slow-issue

### Reproduction steps

Clone 
```
git clone https://github.com/QhlabTeam/cra-template-qhlab.git
cd cra-template-qhlab
git switch msw-cypress-slow-issue
```

Install
```sh
yarn install
```

Run cypress
```sh
yarn scripts
# Select tests
# Select e2e-test-mock
```

Run e2e
- run 1-intro.cy.js
- re-run, it becomes slowly after first run

### Current behavior

Since the second re-run e2e test, it becomes very slow pending js chunks due to msw serviceworker

![image](https://user-images.githubusercontent.com/74389358/188535965-31e68d9b-f44a-403c-80ec-a26cbfb8c345.png)

### Expected behavior

Should be normal like the first time e2e runs.

**Comment by HeVictor** [comment]
Hi @iamyoki, I've had a crack attempting to re-create the bug from cloning your repository branch and installing the deps and then running the 1-intro.cy.js followed by a re-run (selecting the e2e testing type and Chrome through Cypress). Unfortunately, I wasn't able to encounter a slow execution like you described as the second run was also pretty quick like the first. Is it possible that I'm missing some steps or there are some differences in configuration and the like?

![Screen Shot 2022-09-20 at 1 29 10 pm](https://user-images.githubusercontent.com/20733994/191148682-95521341-c061-493a-9bae-55618ba91fde.png)

I'm using the latest msw version with node v16.17.0, and I'm using a Mac with M1.

**Comment by iamyoki** [comment]
@HeVictor Thank you for respond,I'll check again.

**Comment by kettanaito** [comment]
No updates for about a year, I will consider this issue not reproducible. 

MSW doesn't do anything special to affect the response load times. If they take too much time, I suggest investigating that in your app/test setup. Start from the "Timings" tab in the Network to see _what_ is taking that time. That can be a good first clue. 

Update all the dependencies to their latest versions before doing any debugging. Good luck!
