### ISSUE TITLE
Typo in word `currently`, mispelled as `cyurrently`

### ISSUE THREAD

**Issue by kishannareshpal** [kettanaito/msw#1402]
https://github.com/mswjs/msw/blob/18f57789f6ff620c0b1c2ee472673eb85d0575c9/src/node/glossary.ts#L49

**Comment by kettanaito** [comment]
Hey, @kishannareshpal. Thanks! Do you mind opening a pull request?

**Comment by kishannareshpal** [comment]
> Hey, @kishannareshpal. Thanks! Do you mind opening a pull request?

Hi @kettanaito, sure. will do

**Comment by kettanaito** [comment]
## Released: v0.47.2 🎉

This has been released in v0.47.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.47.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.47.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
