### ISSUE TITLE
MSW listen() doesn't work on Expo React Native app 

### ISSUE THREAD

**Issue by fregayeg** [kettanaito/msw#1408]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [x] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.17.0

### Reproduction repository

https://github.com/fregayeg/optional-proj

### Reproduction steps

1. Run ``yarn install`` 
2. Run ``expo start -c`` and wait the web server to be ready.
3. Once server is up, open navigator on ``http://localhost:19002``
4. Scan QR code on device or on Android/iOS if you have Android studio or xCode installed.
5. The app must be running under Expo Go in your device or emulator.
6. Once its ready, it must be open.

### Current behavior

Actually, following [your examples and discussion about React Native support](https://github.com/mswjs/msw/issues/203#issuecomment-692550528), I've made a sample app, that must call and endpoint through something called [redux-toolkit query](https://redux-toolkit.js.org/rtk-query/overview) (equivalent to React Query, Apollo etc...). The behavior is: When I open the app I get my main screen (ui) as expected:  [a bottom tab navigator](https://reactnavigation.org/docs/bottom-tab-navigator/) with exactly 2 sub-screens. When I go the 2nd screen where the API call is, I get nothing and **no errors** are printed out on console.

### Expected behavior

When I open the app I get my 1st screen (ui) as expected: [a bottom tab navigator](https://reactnavigation.org/docs/bottom-tab-navigator/) with exactly 2 sub-screens. If I tap on 2nd tab, I go to the screen where the api call is, and then I must see a loading indicator then a list of items must appear instead, without errors.

**Comment by fregayeg** [comment]
Hi again! after many tried, I've figured out a way to make it work! 😆 I appreciate the way how you made msw work for RN apps tbh. Thus, I close this issue as it doesn't have any sense as it I know now.

You can see [my answer on Expo Forum](https://forums.expo.dev/t/msw-server-cannot-run-properly-with-expo/66495?u=iga-frg), where I asked same a similar question 😄 .

 Thanks for you attention.  🙏

**Comment by mwood23** [comment]
@fregayeg I can't thank you enough for this. MSW would silently fail and thought I was going crazy over here.

**Comment by kettanaito** [comment]
Okay, so the silently failing part is definitely not fine. 

I think MSW should check if the global `URL` construct exists and if it's not, throw an exception with suggestion steps to use a polyfill. 

The fact that you need to use `msw/node` is referenced in the docs, I believe, but we need to create a standalone "Integration > React Native" page (looking forward to this in the next docs). 

Is there anything else I'm missing?

**Comment by kettanaito** [comment]
If anybody could give https://github.com/mswjs/msw/pull/1520 a review, I'd be thankful. Let's improve the experience around React Native polyfills.

**Comment by fregayeg** [comment]
Hello @kettanaito ! Thank you for this good job! I didn't see the updates sincel last week sorry. Could you please tell me if I should do something else ?

**Comment by fregayeg** [comment]
Ok maybe I'm late. In order to help people understand what is the minimal setup to run React Native with MSW, I recommend to use Expo, it makes the task straighforward and pretty simple. 

I suggest to visit [my expo-msw sample](https://github.com/firas1220/expo-msw) , its linked to my personal github. 

thanks all

**Comment by kettanaito** [comment]
## Released: v1.0.0 🎉

This has been released in v1.0.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v1.0.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/1.0.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
