### ISSUE TITLE
MSW + Logrocket + Axios do not work together

### ISSUE THREAD

**Issue by rodriguezmarting** [kettanaito/msw#1413]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.), Firefox, Safari

### Reproduction repository

https://github.com/rodriguezmarting/LogrocketAxiosMSW/tree/master

### Reproduction steps

- Clone [this repo](https://github.com/rodriguezmarting/LogrocketAxiosMSW/tree/master)
- `npm install && npm run generate:api`
- `npm run dev`
- Open the app in any browser and check the console

### Current behavior

The app hangs and this error message shows up in the console:
![image](https://user-images.githubusercontent.com/51244476/191544014-e9c3d990-c97a-4378-9f27-97e9ed0dcc15.png)

### Expected behavior

The app should just work.

## Notes
- Without Logrocket the app just works
- Without MSW the app just works
- Updating the generate:api script removing --axios option and rerunning npm run generate:api will "fix" the app

Opened the same issue in swagger-typescript-api
 repo:
https://github.com/acacode/swagger-typescript-api/issues/412

Also shared both of these issues to Logrocket support (not open source).

**Comment by hiddenest** [comment]
+1 for this

**Comment by js2me** [comment]
Checking this repo I found interesting thing, if we disabled all things based on `Logrocket` then application works fine.   
I think something in Logrocket configuration\implementation is not valid.

**Comment by rodriguezmarting** [comment]
> Checking this repo I found interesting thing, if we disabled all things based on `Logrocket` then application works fine.
> I think something in Logrocket configuration\implementation is not valid.

That's what I mentioned in the `Notes` section, any of these three options work but not everything together:
```
- Without Logrocket the app just works
- Without MSW the app just works
- Updating the generate:api script removing --axios option and rerunning npm run generate:api will "fix" the app
```
We ended up going for the third option and creating our own fetch with abort utility.

**Comment by awer000** [comment]
+1 for this

**Comment by kettanaito** [comment]
Hey, @rodriguezmarting. Thanks for raising this. 

Can somebody lookup this error from LogRocket? When is it thrown? What causes it to be thrown?

I don't see how this is related to MSW at the moment. I suspect that the generated API somehow cause LogRocket to get out of memory (what does that mean? what's the memory limit?). The reproduction repository has no handlers for MSW (`setupWorker(...[])`) so they're either intentionally empty or are generated by `generate:api`—@rodriguezmarting, which one is the intended way?

**Comment by kettanaito** [comment]
There hasn't been any activity on this issue so I deem it resolved (my last questions went unanswered). 

## But I still experience this issue

1. [Upgrade to MSW 2.0](https://mswjs.io/docs/migrations/1.x-to-2.x/).
2. If the problem is still there, open a new issue with detailed description and a standalone reproduction repository. 

Thanks.
