### ISSUE TITLE
When I run it on Vitest, I get `TypeError: Invalid URL`.

### ISSUE THREAD

**Issue by shooooori0128** [kettanaito/msw#1415]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.17.0

### Reproduction repository

https://github.com/shooooori0128/vitest-sample

### Reproduction steps

1. Run `yarn install`
2. Run `yarn test`

It also works with jest.

### Current behavior

```sh
 ❯ tests/CreateNewTraining.test.js (1)
   ❯ greeting (1)
     × 挨拶を返す

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  tests/CreateNewTraining.test.js > greeting > 挨拶を返す
TypeError: Invalid URL
 ❯ Object.getUrlByRequestOptions node_modules/@mswjs/interceptors/lib/utils/getUrlByRequestOptions.js:80:57
 ❯ normalizeClientRequestArgs node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/utils/normalizeClientRequestArgs.js:137:40
 ❯ Object.request node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/http.request.js:36:89
 ❯ RedirectableRequest._performRequest node_modules/follow-redirects/index.js:284:24
 ❯ new RedirectableRequest node_modules/follow-redirects/index.js:66:8
 ❯ Object.request node_modules/follow-redirects/index.js:523:14
 ❯ dispatchHttpRequest node_modules/axios/lib/adapters/http.js:262:25
 ❯ httpAdapter node_modules/axios/lib/adapters/http.js:49:10
 ❯ dispatchRequest node_modules/axios/lib/core/dispatchRequest.js:58:10
 ❯ Axios.request node_modules/axios/lib/core/Axios.js:109:15
 ❯ Axios.<computed> [as get] node_modules/axios/lib/core/Axios.js:131:17
 ❯ Function.wrap [as get] node_modules/axios/lib/helpers/bind.js:9:15
 ❯ greeting tests/CreateNewTraining.test.js:15:28
     13| // テスト対象の関数
     14| const greeting = async (name) => {
     15|   const word = await axios.get('greeting');
       |                            ^
     16|   return `${word.data} ${name}`;
     17| };
 ❯ tests/CreateNewTraining.test.js:30:26

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ERR_INVALID_URL",
  "input": "http://::1",
}


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  1 failed (1)
  Start at  22:07:10
  Duration  1.25s (transform 480ms, setup 0ms, collect 210ms, tests 13ms)
```

### Expected behavior

I want the test to pass.

**Comment by kettanaito** [comment]
Hey, @shooooori0128. Thanks for reporting this.

This looks suspiciously similar to a new hostname resolution behavior introduced in Node 18. Yet you state it happens on Node 16, which makes it interesting. 

Anyone is welcome to look into this, by the way.

**Comment by breslauer** [comment]
@shooooori0128 did you find any solution? Have the same problem in my project :(

**Comment by DeeSouza** [comment]
This happen to me, in Node v14. Did you fix @shooooori0128?
But, this happen when the property `testEnvironment` is with the value `node`, in file `jest.config.js`.

If I change to `jsdom`, it's works.

**I think this behavior is not an MSW bug.**

**Comment by DeeSouza** [comment]
> This happen to me, in Node v14. Did you fix @shooooori0128? But, this happen when the property `testEnvironment` is with the value `node`, in file `jest.config.js`.
> 
> If I change to `jsdom`, it's works.

Hey, I fix it.

First, how I sayd before, this happen when the property `testEnvironment` have the value `node`.
Thinking about that, the documentation of the MSW says that:

![image](https://user-images.githubusercontent.com/12430887/210802873-3ba476e1-89d7-4c08-bbdb-8347dc332b6b.png)

Therefore, the URL from API should be **absolute**. 

### Observation:

But, if **Axios** is not working as it should in the part of placing the `baseURL`, do the following in your service:

`axios.defaults.baseURL = 'http://your-base-url'`

This it works for me!

@shooooori0128 @kettanaito

**Comment by kettanaito** [comment]
> Therefore, the URL from API should be absolute.

💯 In Node, nothing to be relative to. Although it's fair to mention that some testing frameworks, like Jest, do support relative URLs by polyfilling `window.location`.

**Comment by aligneddev** [comment]
I had this issue after updating msw to 1.2.3 from ^0.0.0-fetch.rc-15 and happy-dom to 10.5.2.

The linked issue https://github.com/capricorn86/happy-dom/issues/678 pointed me to this commit https://github.com/Lipoic/Lipoic-Frontend/commit/cf83276c147e19820f639b3eb34b6220263a4f27 which I followed.

Setting `location.href = 'https://myurl.com/'` in your vitest.setup.ts worked for me
