### ISSUE TITLE
Jest with ESM modules fails to parse headers-polyfill

### ISSUE THREAD

**Issue by earnubs** [kettanaito/msw#1419]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.17.0

### Reproduction repository

https://gist.github.com/earnubs/97bef90158e77cb8b646ab4586acf19d

### Reproduction steps

`npm test`

### Current behavior

```Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/stephen/Workspace/try-jest-msw/node_modules/headers-polyfill/lib/esm/index.js:204
    export {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1678:14)
          at async Promise.all (index 12)
          at async Promise.all (index 0)```

### Expected behavior

Test passes.

**Comment by simonbergstrom** [comment]
+ 1 on this issue

**Comment by kettanaito** [comment]
Hey, @mattcosta7 👋 Would you happen to know what may be going wrong in this case? 

I suspect that the project is incorrectly importing the ESM build of `headers-polyfill` and doesn't use the `require` entrypoint instead. But that should only happen if the project itself is marked as ESM, should it not?

**Comment by mattcosta7** [comment]
I'll take a look when i get some cycles.

> https://gist.github.com/earnubs/97bef90158e77cb8b646ab4586acf19d#file-package-json-L8

I think this line is likely causing some lookup considerations? 

"test": "node --experimental-vm-modules ./node_modules/.bin/jest"

causing `import` to get used instead of require.  I'm not sure if that's from the version of node looking at the 'module' entry now from that flag (which I've not used directly) or if it's using the exports["."]["import"] field.  determinging that might be the first step.

**Comment by earnubs** [comment]
Adding `type: module` to headers-polyfill package.json does fix this for the repro case.

From https://nodejs.org/api/esm.html#esm_enabling

> Authors can tell Node.js to use the ECMAScript modules loader via the .mjs file extension, the package.json ["type"](https://nodejs.org/api/packages.html#type) field, or the [--input-type](https://nodejs.org/api/cli.html#--input-typetype) flag. Outside of those cases, Node.js will use the CommonJS module loader. See [Determining module system](https://nodejs.org/api/packages.html#determining-module-system) for more details.

The esm output has `.js` file extensions, so maybe they need to be `.mjs`.

EDIT: yeah, changing all the esm extensions to `mjs` also fixes the repro, and that's probably the correct fix in this case.

**Comment by kettanaito** [comment]
I'm for changing the extension. Please, can someone open a PR to headers-polyfill?

**Comment by mattcosta7** [comment]
PR opened here - https://github.com/mswjs/headers-polyfill/pull/47

**Comment by chinanderm** [comment]
That PR has been merged a v3.1.1 has been released.

**Comment by kettanaito** [comment]
3.1.1 should propagate to your node_modules if you re-install `msw`. Can someone confirm that please?

**Comment by earnubs** [comment]
```
~/Workspace/try-jest-msw is  v1.0.0 via  v16.17.0 on  (eu-west-1) 
❯ npm test

> try-jest-msw@1.0.0 test
> node --experimental-vm-modules ./node_modules/.bin/jest

(node:3838162) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  ./foo.test.js
  ✓ axiom (2 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.384 s, estimated 1 s
Ran all test suites.

~/Workspace/try-jest-msw is  v1.0.0 via  v16.17.0 on  (eu-west-1) 
❯ npm info headers-polyfill

headers-polyfill@3.1.1 | MIT | deps: none | versions: 10
A native "Headers" class polyfill.

dist
.tarball: https://registry.npmjs.org/headers-polyfill/-/headers-polyfill-3.1.1.tgz
.shasum: 798e265f80edfc53fb8fd01e8963b356b12c2514
.integrity: sha512-ifvvIC+VDeLTEkJDwxECSI7k9rJF7sJavCh/UfhGsgJ+LXMbGILRf+NXhc4znuf+JA5X2/leQdOXk6Lq6Y2/wQ==
.unpackedSize: 54.2 kB

maintainers:
- kettanaito <kettanaito@gmail.com>

dist-tags:
latest: 3.1.1  

published 20 hours ago by kettanaito <kettanaito@gmail.com>

```

:tada:

**Comment by earnubs** [comment]
Thanks @kettanaito @chinanderm @mattcosta7

**Comment by kettanaito** [comment]
Fantastic! Thank you everyone for making this happen 🎉

**Comment by mattcosta7** [comment]
> Thanks @kettanaito @chinanderm @mattcosta7 

Thank you for helping troubleshoot

**Comment by earnubs** [comment]
This may have squashed one bug only to reveal a few more with the ESM build:

The first one is related to the import of `chalk` at https://github.com/mswjs/msw/blob/main/src/node/createSetupServer.ts#L1

```
SyntaxError: The requested module 'chalk' does not provide an export named 'bold'
```
That's easily fixed I think, but when fixed you hit:

```
Dynamic require of "node-fetch" is not supported

      at node_modules/msw/lib/node/index.mjs:25:9
      at node_modules/msw/src/context/fetch.ts:6:21
```

Which I think will be this line https://github.com/mswjs/msw/blob/main/src/context/fetch.ts#L6 and would require rewriting with something like `await import ...`

[5 mins later] OK, I see this PR https://github.com/mswjs/msw/pull/1399/files has all of what I've found so far, so I'll try it out locally.
