### ISSUE TITLE
Vulnerability found with xmldom 0.7.5

### ISSUE THREAD

**Issue by Antho2407** [kettanaito/msw#1434]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Hi team, 

it seems like a vulnerability has been found with a `msw` dependency, `xmldom`

Would it be possible to upgrade to at least `0.8.3` ?

**Comment by kettanaito** [comment]
Hey, @Antho2407. Thanks for reporting this. 

This is a duplicate of #1432 that has been resolved. Should be released in `@mswjs/interceptors@0.17.6`. Make sure to re-install `msw` to get the fix once it's out.
