### ISSUE TITLE
unhandledRejection: SyntaxError: 'headers-polyfill' is a CommonJS module

### ISSUE THREAD

**Issue by AleskiWeb** [kettanaito/msw#1465]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.17.0

### Reproduction repository

https://github.com/AleskiWeb/mswjs-next

### Reproduction steps

- clone the repro repo
- yarn
- yarn dev

### Current behavior

```
error - unhandledRejection: SyntaxError: Named export 'Headers' not found. The requested module 'headers-polyfill' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'headers-polyfill';
const { Headers } = pkg;
```

### Expected behavior

No errors in the console

**Comment by kettanaito** [comment]
Hey, @AleskiWeb.

Please use the latest version of MSW, which, at the moment of me writing this, is [0.48.3](https://github.com/mswjs/msw/releases/tag/v0.48.3). You're using `0.47.4` in your example.  Update the version and give this issue another try. Let me know if it's still reproducible then.

**Comment by egorpavlikhin** [comment]
@kettanaito this is still an issue with msw 1.0.1 when running tests via vitest.

**Comment by lukasberbuer** [comment]
@egorpavlikhin & @kettanaito: I can confirm that this is still an issue with `msw 1.1.0` and `vitest` with `jsdom` environment.

Edit: `npm i --no-save headers-polyfill@latest` (>= 3.1.1) fixes the issue
