### ISSUE TITLE
Graphql request not recognised

### ISSUE THREAD

**Issue by harm-meijer** [kettanaito/msw#1471]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.18.1

### Reproduction repository

private repo

### Reproduction steps

Following server setup (using jest):

```
beforeAll(() => {
  server.listen({
    onUnhandledRequest: (req) => {
      console.log(`unhandled ${req.url.pathname}`)
      req
        .json()
        .then((body) => {
          console.log('body:::', body)
        })
        .catch((e) => e)
    },
  })
})
```

Handlers:

```
export const handlers = [
  graphql.operation((req, res, ctx) => {
    //does not mattter, this is never executed
    console.log('keys:', Object.keys(req))
    return res(
      ctx.errors([
        {
          message: 'Access denied',
          positions: [1, 92],
        },
      ])
    )
  }),
  rest.post('*/oauth/token', (req, res, ctx) => {
    console.log('TOKEN:', req.url.pathname)
    if (req.url.pathname === '/oauth/token') {
      return res(
        ctx.status(200),
        ctx.json({
          mock: 'token',
        })
      )
    }
    console.log('pass through')
    return req.passthrough()
  }),
  rest.post('*/products', (req, res, ctx) => {
    console.log('PRODUCTS', req.url.pathname)
    return res(
      ctx.status(201),
      ctx.json({
        some: 'result',
      })
    )
  }),
]
```

This will log:
```
 TOKEN: /oauth/token
unhandled /project/graphql
    body::: {
      query: '\n' +
        '    query fetchProductTypeId($where: String) {\n' +
        '      productTypes(where: $where, limit: 1) {\n' +
        '        results {\n' +
        '          id\n' +
        '        }\n' +
        '      }\n' +
        '    }\n' +
        '  ',
      variables: { where: 'key="connector"' }
    }
```

I'm pretty sure the unhandled request is a graphql request yet it is not picked up by `graphql.operation` 

### Current behavior

Not picking up what I think is obviously a graphql request by `graphql.operation`

### Expected behavior

Expected `graphql.operation` to handle a graphql request instead of ignoring it.

**Comment by harm-meijer** [comment]
I see the library I use created a header `'Content-Type': 'application/graphql',` seems fine according to a quick read [here](https://graphql.org/learn/serving-over-http/) but when I change it to `'Content-Type': 'application/json'` it will be picked up by the handler.

**Comment by kettanaito** [comment]
Thanks for reporting this, @harm-meijer. Yeah, we don't support `application/graphql` content type request header at the moment for GraphQL requests. It's synonymous with `application/json`, so using it shouldn't be a breach of the specification on your side. 

This is tightly related to how we parse JSON request bodies internally, and this issue won't be a thing once #1436 lands.
