### ISSUE TITLE
Update to @mswjs/interceptors ^0.18.0

### ISSUE THREAD

**Issue by cdimitroulas** [kettanaito/msw#1484]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

@mswjs/interceptors v0.18.0 has support for upload events which would be great to incorporate in the higher-level msw library.

I'm happy to take a stab at this, but I'm completely unfamiliar with the codebase so it has proven challenging to understand how to adapt msw to the breaking changes from @mswjs/interceptors.

In particular, I see that `IsomorphicRequest` was removed - what's the correct way to handle this change? I would love to help out by creating a PR for this but I could use some guidance here :)

**Comment by cdimitroulas** [comment]
Ah I see this is already covered by this WIP PR: https://github.com/mswjs/msw/pull/1436

**Comment by kettanaito** [comment]
Hey, @cdimitroulas. Yes, version 0.18.0 introduces Fetch API primitives to our Node.js request interception library. We've migrated to it as a part of a larger change, which is #1436. 

If you have a minute, I'd be thankful if you give that new change a try. You can find more info in this discussion: #1464. Thanks!

**Comment by cdimitroulas** [comment]
@kettanaito thanks for explaining. I did try to give the new change a whirl yesterday but got stuck due to the issue which has already been raised on #1464 about `Unexpected token 'export'`.
I'm trying to find time to push forwards on https://github.com/mswjs/interceptors/pull/283 in order to get that problem fixed

**Comment by kettanaito** [comment]
Thank you so much for looking into this! I will support you with code reviews.
