### ISSUE TITLE
MSW does not intercept fetch in plain node application

### ISSUE THREAD

**Issue by dbojarski** [kettanaito/msw#1516]
Everywhere I see usage of MSW in React app but what about plain Javascript project?

my-app.js
```
export class MyApp {
  async fetchData() {
    const response = await fetch('/my-url');
    const content = await response.json();
    
    return content;
  }
}
```

my-app.test.js
```
const server = setupServer(
  rest.get('/my-url', (req, res, ctx) => res(ctx.json({data: null}))
);

describe('MyApp') {
  beforeAll(() => server.listen());
  afterEach(() => server.resetHandlers());
  afterAll(() => server.close());
  
  it('should be ok', async () => {
    const app = new MyApp();
    const result = await app.fetchData();

    expect(result).toEqual({data: null});
  })
}
```

server.on("request.start", ...) - not working
fetch returns oryginal content instead of { data: null } mocked in rest.get

nodle version 18.0.0
msw version latest
jest 29.3.1

simple project that includes my-app.js, my-app.test.js, jest.config.json (default), babel.config.json

**Comment by dbojarski** [comment]
Well, I had two servers

First one in setup-jest.js file and second one in my test. The problem was that due to having it in setup-jest.ts I started listening to another server with no handlers. Decided to keep only one and everything is okay now.

**Comment by kettanaito** [comment]
Hey, @dbojarski. 

Yeah, the setup you posted looks fine (my only comment is that it's the `request:start` event, notice the semicolon). I'm glad you've found the issue and resolved it!
