### ISSUE TITLE
update strict-event-emitter to at least v0.3.x to avoid implicit dependency on Node.js type definitions.

### ISSUE THREAD

**Issue by chrisguttandin** [kettanaito/msw#1519]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Firefox

### Reproduction repository

https://github.com/chrisguttandin/msw-test

### Reproduction steps

Run the following commands:

```sh
mkdir msw-test
cd msw-test 
npm init --yes
npm install msw
npm install typescript --save-dev
tsc --init --skipLibCheck false --target es2022 --types " "
touch index.ts
```

Open `index.ts` and add the following content:

```ts
// index.ts
import { setupWorker } from 'msw';

setupWorker;
```

Compile the project:

```sh
tsc -p tsconfig.json
```

### Current behavior

```txt
node_modules/strict-event-emitter/lib/StrictEventEmitter.d.ts:1:30 - error TS7016: Could not find a declaration file for module 'events'. '.../msw-test/node_modules/events/events.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/events` if it exists or add a new declaration (.d.ts) file containing `declare module 'events';`

1 import { EventEmitter } from 'events';
```

### Expected behavior

I would expect it to compile.

**Comment by chrisguttandin** [comment]
Hi @kettanaito I think the error would be resolved when updating `strict-event-emitter`. I guess `@mswjs/interceptors` would need to be updated, too. It seems to depend on `strict-event-emitter` as well.

I'm happy to give this a try if you agree.

**Comment by kettanaito** [comment]
Hey, @chrisguttandin! Thanks for raising this.

If MSW depends on this package directly then let's bump it. You won't be able to update the Interceptors because the newest version already ships with the Fetch API support so its being updated as a part of the said feature in MSW. 

People can use package resolutions for now to avoid this issue, I hope.

**Comment by kettanaito** [comment]
I can use some help with the strict-event-emitter update for the Interceptors though https://github.com/mswjs/interceptors/issues/324

**Comment by chrisguttandin** [comment]
I created a fresh fork of `msw` and ran `yarn install`. I got this error:

```txt
➤ YN0066: │ typescript@patch:typescript@npm%3A4.5.4#builtin<compat/typescript>::version=4.5.4&hash=8133ad: Cannot apply hunk #2 (set enableInlineHunks for details)
➤ YN0066: │ typescript@patch:typescript@npm%3A4.9.3#builtin<compat/typescript>::version=4.9.3&hash=8133ad: Cannot apply hunk #2 (set enableInlineHunks for details)
```

Does that somehow look familiar to you?

**Comment by kettanaito** [comment]
@chrisguttandin, the first time I see that. Maybe check your Node version? I develop on 16.18.0.

**Comment by chrisguttandin** [comment]
I uninstalled yarn itself and re-installed it again. Now I'm on v1.22.19 of yarn. I'm also using Node.js v16. Everything works as expected now. I can run `yarn install` and `yarn test`.

I've created a PR to update over `strict-event-emitter` here: #1522.

**Comment by kettanaito** [comment]
## Released: v0.49.3 🎉

This has been released in v0.49.3!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.49.3)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.49.3)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by BoussonKarel** [comment]
Hi, this latest bugfix release suddenly broke my Ember.js build.
Was not an issue in 0.49.2

![image](https://user-images.githubusercontent.com/55881713/213406110-e67b86da-25b1-4b6b-8e09-c2aa679ae401.png)

@kettanaito @chrisguttandin

**Comment by kettanaito** [comment]
Thanks for reporting this, @BoussonKarel. Looks like we need to compile `strict-event-emitter` to lower target to support older projects. Alternatively, migrate from the class private method syntax to `private` properties.

**Comment by kettanaito** [comment]
Will be released as `strict-event-emitter@3.4.4`. Once that's out, re-install `msw` and you will get the latest dependency with the fix.

**Comment by BoussonKarel** [comment]
I looked into it further yesterday at it seemed like the issue is also ember-auto-import.

Class private methods are supposed to be enabled, but apparently they're not.

https://github.com/ef4/ember-auto-import/issues/559

**Comment by BoussonKarel** [comment]
The strict-event-emitter update did fix it, thanks!

**Comment by guillaume-gorret** [comment]
I'm facing the same issue with the 1.2.1 on an Angular Project.

browser.ts:
```
import { setupWorker } from 'msw'
import { handlers } from './handlers'

export const worker = setupWorker(...handlers);
```

I added ```src/mockServiceWorker.js``` in my angular.json and started the worker in my environment file. 

Any idea what's going on ?
