### ISSUE TITLE
Support HAR

### ISSUE THREAD

**Issue by dstampher** [kettanaito/msw#1524]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I have tons of requests and responses that I need to create msw handlers for.  All of these requests and responses are contained in a HAR file.  It would be great if could simply convert the HAR file to MSW handlers.

There is a package that claims to create this functionality: https://github.com/Tapico/tapico-msw-webarchive

However, there is missing information in the docs.  I have reported the issue on that repo, but it seems the project is not well maintained.

**Comment by kettanaito** [comment]
Hey, @dstampher. Thanks for reporting this. 

I'm glad you've [resolved the issue](https://github.com/Tapico/tapico-msw-webarchive/issues/15#issuecomment-1402360713). Seems like it was related to configuring your compiler to support `*.har` imports.

I'm working on HAR support for MSW but given the reality of the project, it's going to be a paid package available only to MSW sponsors on GitHub when it comes out. In fact, I already have the implementation done, all I need is a few organizational things.
