### ISSUE TITLE
Gitlab integration

### ISSUE THREAD

**Issue by vlefr** [kettanaito/msw#1564]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

19

### Reproduction repository

https://github.com/mswjs/msw

### Reproduction steps

Hi,

I used MSW with vitest and nx workspace. I used setupServer to mock API.
When I'm launching the test from my laptop, the test pass but from gitlab-ci shared runner isn't working (my job runs with node19-alpine).
I tried to increase the timeout but it's still not working.

`mockedServer = setupServer(
 rest.get(
    `${import.meta.env.VITE_API_URL}/users/me/cars`,
    (_, res, ctx) => {
      return res(ctx.status(200), ctx.json(mockedCars))
    }
  ),
)

  beforeAll(() => {
    mockedServer.listen({ onUnhandledRequest: 'error' })
  })
  afterAll(() => {
    mockedServer.close()
  })

`

### Current behavior

     95|     await waitFor(
       |           ^
     96|       () => {
     97|         expect(
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/3]⎯
 FAIL  src/features/dashboard/pages/DashboardPage.test.tsx > [Integration tests] - Dashboard Page > Should display car name
TestingLibraryElementError: Unable to find an element by: [data-testid="separate-sustainment"]
Ignored nodes: comments, script, style

### Expected behavior

test pass locally

**Comment by vlefr** [comment]
I found the problem. It's come from alpine distribution. Fixed!

**Comment by Olgagr** [comment]
@vlefr Can you tell me more about what the issue was in the alpine distribution?
