### ISSUE TITLE
FetchInterceptor giving `Request is not defined` error

### ISSUE THREAD

**Issue by raiatul26** [kettanaito/msw#1576]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [x] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.12.1

### Reproduction repository

https://github.com/raiatul26/msw-demo

### Reproduction steps

git clone the repo
use node v18
run `npm install`
run `npm run test`

Failing test is mentioned in `hooks/cats.hooks.test.js` file

### Current behavior

MSW is not intercepting fetch calls with node v18.
Getting `ReferenceError: Request is not defined` while running the test.
As per stack trace the error is coming from `mswjs/interceptors/src/interceptors/fetch/index.ts:42:13`

The same test was working correctly with node `v16.13.2` and  msw `^0.36.8`. While upgrading the msw to `^1.1.0` and node to `v18.12.1` we started facing this issue.

### Expected behavior

The test mentioned inside `hooks/cats.hooks.test.js` file should pass.

**Comment by kettanaito** [comment]
Hey, @raiatul26. 

I can see you're using Jest. Jest is notoriously bad with meddling with Node.js global APIs, such as `Request`. In other words, Jest purposefully removes standard APIs so they throw being `undefined`. I believe that's what you're experiencing. 

Try mapping Fetch API directly in your `jest.config.js`:

```js
// jest.config.js
module.exports = {
  globals: {
    fetch: globalThis.fetch,
  }
}
```

This will grab the standard Node.js Fetch API in v18 and set them globally on the Jest process as they should be in the first place. Let me know if that helps. 

If that doesn't help, you have to map Node globals manually in `jest.setup.js`:

```js
// jest.setup.js
globalThis.Request = Request
// ...any globals you need, like Response or Headers.
```

**Comment by raiatul26** [comment]
Hi @kettanaito ,
The below approach didn't work for me.
```javascript
// jest.config.js
module.exports = {
  globals: {
    fetch: globalThis.fetch,
  }
}
```


I was using `isomorphic-unfetch` as polyfill to use fetch API on server side. I was also using NextJS which internally also uses `unfetch` as a [polyfill](https://nextjs.org/docs/basic-features/supported-browsers-features#polyfills) for server side fetch API. 

Instead switching to `cross-fetch` or `node-fetch` as a fetch API polyfill worked for me. As mentioned by you, I had to manually set Node globals in `jest.setup.js`.  Below mentioned are the implementations that worked.

```javascript
// For `cross-fetch`
// jest.setup.js
import 'cross-fetch/polyfill' 
```

```javascript
// For `node-fetch`
// jest.setup.js
import fetch, {
  Headers,
  Request,
  Response,
} from 'node-fetch' 

if (!globalThis.fetch) {
  globalThis.fetch = fetch
  globalThis.Headers = Headers
  globalThis.Request = Request
  globalThis.Response = Response
}

```

**Comment by zigang93** [comment]
this doesn't work in latest nextjs 13.14.x with jest and msw.. tried every possible solution still not able to fix

**Comment by kettanaito** [comment]
@zigang93, have you manually set the Fetch API globals like suggested [here](https://github.com/mswjs/msw/issues/1576#issuecomment-1483802564)? Jest explicitly omits them even if you're on the Node.js version that ships those globals. Very easy to check:

```js
console.log(typeof Request)
```

If it undefined, you don't have the globals set. Follow either the suggestion above or any other suitable suggestion for Jest. It's a strictly Jest issue. 

One more thing to keep in mind, MSW doesn't support Next.js 13 at the moment. More on that here #1644.
