### ISSUE TITLE
Codesandbox for Issues is not working when forked, unable to run tests

### ISSUE THREAD

**Issue by nathanhannig** [kettanaito/msw#1588]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v14.19.3

### Reproduction repository

https://codesandbox.io/s/msw-react-xx1c8

### Reproduction steps

Fork CodeSandbox at https://codesandbox.io/s/msw-react-xx1c8 

Upgrade msw to latest version

Run tests `yarn test`

### Current behavior

Codesandbox doesn't initialize

No tests found, exiting with code 0

### Expected behavior

For it to work and run a test

**Comment by kettanaito** [comment]
## Released: v2.1.6 🎉

This has been released in v2.1.6!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.1.6)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.1.6)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
