### ISSUE TITLE
Bug with Next.js App Router in Server Component - Mocking stops working after refreshing

### ISSUE THREAD

**Issue by Kolby-Udacity** [kettanaito/msw#1610]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.20.0

### Reproduction repository

https://github.com/Kolby-Udacity/msw-nextjs-app-router-bug

### Reproduction steps

- npm i
- npm run dev
- refresh page
- error

### Current behavior

When using MSW with React Server Components via Next.js App Router, mocks work for the first page load, but refreshing the page will return a server error:

```
[MSW] Error: captured a request without a matching request handler:

  • GET http://localhost:59761/
```

### Expected behavior

Mocks continue to work after refreshing the page.

**Comment by kettanaito** [comment]
Hey, @Kolby-Udacity. Thanks for reporting this. MSW doesn't support Next 13 at the moment so we won't accept issues until we provide the official support. Sorry for the inconvenience but hope for your understanding. We have very few resources to figure out integration with all the new releases of all the new tools, so our best bet is to join forces with the Next team to help us out. I hope that will happen.
