### ISSUE TITLE
When changing MSW response with Use method I get a random AXIOS network error

### ISSUE THREAD

**Issue by darren-dickerson** [kettanaito/msw#1611]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Reproduction repository

msw

### Reproduction steps

![image](https://github.com/mswjs/msw/assets/129077474/044766a2-f172-469b-8c6a-d1c14a48a973)
![image](https://github.com/mswjs/msw/assets/129077474/955546c1-12d6-4f7e-9a1d-4e98d1eff1bc)

### Current behavior

I only get one failed test.  If I comment out the offending test the error moves to another test in the same test file.

### Expected behavior

No failed test.

**Comment by kettanaito** [comment]
Hi, @darren-dickerson. Thanks for reporting this. Could you please create a reproduction repository for your issue? You can use our [sandbox](https://codesandbox.io/s/msw-react-xx1c8) to bootstrap the reproduction faster. 

I'm afraid I don't have the capacity to look into the issue without reproduction repositories. Thanks for your understanding.

**Comment by darren-dickerson** [comment]
Hi Kettanaito.   Is there a rest api mocking tool that works similar to MSW?
