### ISSUE TITLE
Log response body in plain text/json instead of a ReadableStream

### ISSUE THREAD

**Issue by esquevin** [kettanaito/msw#1620]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

The MSW log when a query is handled used to let me see the body that was returned in plain JSON.

Now I get a `body: ReadableStream { locked: false }` in the console that is of little value to me when developing.

<img width="894" alt="image" src="https://github.com/mswjs/msw/assets/147997/d13d38d1-f483-4d30-bfd8-d19d3822441f">

I think it'd would make this log more useful if it was human readable.

**Comment by kettanaito** [comment]
Hi, @esquevin. Thanks for suggesting this. 

I agree, the request/response body must be printed as text to be human-friendly. I believe this is a matter of 1) cloning the request and 2) reading its body as text over here:

https://github.com/mswjs/msw/blob/c32241627da09af8b34c4068cc17dd1941ff3b0d/src/utils/logging/prepareRequest.ts#L19

Could you open a pull request for this?
