### ISSUE TITLE
Could not find a declaration file for module 'events'

### ISSUE THREAD

**Issue by janwidmer** [kettanaito/msw#1621]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/janwidmer/spartacus-test

### Reproduction steps

1. Clone Repository
2. Run `npm i`
3. Run `npm run dev`
4. Notice the error in the console
5. Add "@types/events": "~3.0.0", to the `package.json` to workaround the error

### Current behavior

We have built an angular library by using MSW to offer a mock server for an angular application.

When we use our angular library (which installs msw in the angular project), we get the following error when I trying to start the angular application:

```
Error: node_modules/@mswjs/interceptors/node_modules/strict-event-emitter/lib/StrictEventEmitter.d.ts:1:30 - error TS7016: Could not find a declaration file for module 'events'. '/Users/janwidmer/projects/spartacus-test/node_modules/events/events.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/events` if it exists or add a new declaration (.d.ts) file containing `declare module 'events';`

1 import { EventEmitter } from 'events';
                               ~~~~~~~~
```

Here is my tsconfig.json file:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "skipLibCheck": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "paths": {
      "spartacus-mock": ["dist/spartacus-mock"]
    },
    "module": "es2020",
    "lib": ["es2020", "dom"]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  },
  "exclude": ["./dist", "node_modules"]
}
```

Does msw need to add @types/events to its devDep and export the definitions or is there a misconfiguration on my side?

For now I fix the issue by npm i -D @types/events but I don't think I should have to install the types in my consumer project since I do not directly use events but msw does.

### Expected behavior

I can use mws in my Angular Application without errors.

**Comment by kettanaito** [comment]
Hi, @janwidmer. I believe you should get the type definitions for `events` from `@types/node`. `events` is a global Node.js module on which MSW relies on. 

Could you try installing `@types/node` and see if it resolves the issue? I'm fairly certain it will as I haven't encountered this when preparing a new Angular example recently.

**Comment by janwidmer** [comment]
Hey @kettanaito, 

I have installed types for node, the error still comes:
<img width="2544" alt="image" src="https://github.com/mswjs/msw/assets/3381820/b2395599-6df1-441a-8d19-0fbb3cdb728d">

**Comment by janwidmer** [comment]
@kettanaito seems that using angular 15 and installing `@types/events` for dev dependencies fixes the problem..

**Comment by davidwalschots** [comment]
@janwidmer it indeed fixes the problem. But msw declaring the dependency themselves, instead of each individual consumer having to figure this out does make most sense to me. I'm not sure if this issue should be closed?

**Comment by janwidmer** [comment]
@davidwalschots I agree with you.. reopening it..
@kettanaito would it be possible, that mws adds `@types/events`?

**Comment by JAspeling** [comment]
I feel like this is something that can be resolved with some documentation. Install the dependency and add it to your tsconfig file. For me (on an angular web app), I just added the following:

```json
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "node"
    ]
  }
}
```

> I can't remember exactly which node types it was dependent on in my case though

**Comment by kettanaito** [comment]
Hey, folks. Can someone please give this a try on `msw@latest`? I don't believe the issue is there. Also take a look at the official [Angular usage example](https://github.com/mswjs/examples/tree/main/examples/with-angular) that runs and builds without this type of issue. I will treat the example as the source of truth here. If you still experience this issue, please comment. Thanks.

**Comment by janwidmer** [comment]
@kettanaito I can confirm that with version 2.0.x, the problem is fixed.
