### ISSUE TITLE
MSW fails bypassing to remote server using self-signed SSL certificate

### ISSUE THREAD

**Issue by mfrieling** [kettanaito/msw#1652]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

not possible, read reproduction steps

### Reproduction steps

I theoretically could provide a reproduction repository, but I cannot provide a server with a self-signed and therefore insecure SSL certificate which is not localhost.

- Setup an empty worker (no handlers needed)
- Start the worker in a app (in my case it's Angular but can be React, Vue or whatever) with `{ onUnhandledRequest: 'bypass' }`
- In the app execute a request to an external server which uses a self-signed SSL certificate which is considered insecure by the browser. Because MSW doesn't have a matching handler it should bypass and execute.

### Current behavior

As long as I haven't opened the insecure url in the same browser and used the advanced option _"Proceed to [domain] (unsafe)"_ the request should fail with an informative error message, without as well as with MSW enabled.

Without MSW, after I've clicked "Proceed (unsafe)", the request is executed correctly.

With MSW, after I've clicked "Proceed (unsafe)", MSW fails to execute the request producing the following log output:
![image](https://github.com/mswjs/msw/assets/8668756/ff2e2e27-a1f9-4e1a-97bd-1d9f0d275219)
(Blurred url parts contain customer and product names, but basically that is a docker instance running the backend on a specific branch via CI. That url is internal/behind a VPN.)

### Expected behavior

:white_check_mark: Without MSW, after I've clicked "Proceed (unsafe)", the request is executed correctly.
:x: With MSW, after I've clicked "Proceed (unsafe)", the request is executed correctly.

**Comment by H0JLuk** [comment]
i have the same behavior when use my system certificate for API, but with another log in console:
`The FetchEvent for "https://ci04770618-web.apps.dev-gen1-ds.delta.sbrf.ru/web/auth/user/" resulted in a network error response: the promise was rejected`

**Comment by kettanaito** [comment]
I'm going to close this. This likely has to do with whether your system trusts the self-signed certificate, and thus allows the Service Worker API to run. Contributions are welcome here (e.g. a reliably failing test for this).
