### ISSUE TITLE
[vite] Internal server error: No known conditions for "./node" specifier in "msw" package   Plugin: vite:import-analysis

### ISSUE THREAD

**Issue by kmiwa007** [kettanaito/msw#1657]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

N/A

### Reproduction steps

I'm following this [migration guide](https://github.com/mswjs/msw/blob/feat/standard-api/MIGRATING.md) since that was recommended to deal with the `Class extends value undefined is not a constructor or null` [issue](https://github.com/mswjs/msw/issues/1539).  

The tests running in Node migrated successfully however running in the browser produces this error.  Note: I'm using Vite build system.

```
No known conditions for "./node" specifier in "msw" package
3:00:19 PM [vite] Internal server error: No known conditions for "./node" specifier in "msw" package
  Plugin: vite:import-analysis
```

Any idea what's happening?

### Current behavior

Throws error (see above).

### Expected behavior

No error

**Comment by kmiwa007** [comment]
@kettanaito apologies for the tag but any idea what could be causing this build issue?  

FWIW, my `mocks/browser.ts` file is:

```
import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

// This configures a Service Worker with the given request handlers.
export const worker = setupWorker(...handlers);

```

I updated the setupWorker import as per https://github.com/mswjs/msw/blob/feat/standard-api/MIGRATING.md#imports

**Comment by kettanaito** [comment]
Hi, @kmiwa007. Thanks for giving the next version of MSW a spin.

The error message itself means that somewhere along the way Vite attempts to import from `msw/node` while being in the browser. Rightfully so, the library explicitly marks the `browser` export condition for the `msw/node` path as `null`:

https://github.com/mswjs/msw/blob/59c3e5286a319a9b0cd87424bf0c2890b631a735/package.json#L23

All I can recommend without a reproduction scenario is to look at how you're importing `msw` and make sure that you don't import `msw/node` in browser-oriented modules and `msw/browser` in Node.js-oriented modules. I'd look at `./handlers` as the first thing. 

If you can provide a reproduction scenario I'd be happy to help with this. I know how difficult debugging export conditions may get.

**Comment by kmiwa007** [comment]
@kettanaito ahh you're absolutely right!  I had an import from a util which referenced another util which referenced 'msw/node'. 🤦

Closing as this is not an issue w/ msw@next.

**Comment by cleysonsilvame** [comment]
I have a similar situation

Inside the test environment (using `vitest`), I get the same error, because with `./browser`.

If I follow the instruction to remove the conditional `node`, or put an empty string in the array, I end up breaking other tests that need the conditional `node`

Does anyone have any suggestions?

**Comment by jswhisperer** [comment]
https://github.com/mswjs/examples-new/tree/main/examples/with-vitest

**Comment by WanWanHsieh** [comment]
@kmiwa007   @kettanaito

I encountered the same problem. There was no problem in executing the unit test, but an error occurred when executing yarn serve. How did you deal with it?

![image](https://github.com/mswjs/msw/assets/19661909/8f4d9ccf-576a-4f4e-be44-50d59d13f022)

**Comment by DanielAraldi** [comment]
Hello, I'm having the same problem with the `2.2.0` version, follow the error in my terminal below:
```bash
FAIL  src/templates/Home/Home.spec.jsx [ src/templates/Home/Home.spec.jsx ]
Error: No known conditions for "./node" specifier in "msw" package
 ❯ e node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:47355:25
 ❯ n node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:47355:646
 ❯ o node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:47355:1297
 ❯ resolveExportsOrImports node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:48032:20
 ❯ resolveDeepImport node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:48051:31
 ❯ tryNodeResolve node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:47776:20
 ❯ Context.resolveId node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:47539:28
 ❯ Object.resolveId node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:50733:64
 ❯ TransformContext.resolve node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:50424:23
 ❯ normalizeUrl node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:65554:34
```

This is my test code with the problem:
```.jsx
import React from 'react';
import { render, screen, waitForElementToBeRemoved } from '@testing-library/react';
import { it, describe, beforeAll, afterAll, afterEach } from 'vitest';
import { http, HttpResponse } from 'msw';
import { setupServer } from 'msw/node';
import { Home } from '.';

const handlers = [
  http.get('https://jsonplaceholder.typicode.com/posts', () =>
    HttpResponse.json([
      {
        userId: 1,
        id: 1,
        title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
        body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
      },
      {
        userId: 1,
        id: 2,
        title: 'qui est esse',
        body: 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla',
      },
      {
        userId: 1,
        id: 3,
        title: 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
        body: 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut',
      },
    ]),
  ),
];

const server = setupServer(...handlers);

describe('Home page', () => {
  // Starts requests interception
  beforeAll(() => server.listen());

  // Reset each handler after each request
  afterEach(() => server.resetHandlers());

  // Stops requests interception
  afterAll(() => server.close());

  it('should render search, posts and load more', async () => {
    const { debug } = render(<Home />);
    debug();

    const postsDoesntExist = screen.getByText('Não existem posts =(');

    // Wait for the posts to be loaded and then remove the posts message
    await waitForElementToBeRemoved(postsDoesntExist);
    debug();
  });
});
```

What's happening with this code?

**Comment by sdanshita** [comment]
I also struggled with this issue, but dynamic imports may be effective.
Please let me know if this method is wrong!
```ts
export const initMocks = async () => {
  if (import.meta.env.VITE_API_MOCKING === 'true') {
    if (typeof window === 'undefined') {
      const { server } = await import('./node') // dont use in browser
      console.log('Server worker started')
      server.listen()
    } else {
      console.log('Browser worker started')
      worker.start()
    }
  }
}
```
