### ISSUE TITLE
Sad path throws jest error which fails the test using RTK query

### ISSUE THREAD

**Issue by DominicGBauer** [kettanaito/msw#1661]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.13.0

### Reproduction repository

https://github.com/DominicGBauer/msw-test-example

### Reproduction steps

* Run `yarn test`
* The sad path tests will fail
* Go to `Example.tsx` and uncomment the function with try catch and comment the function without try catch.
* Run `yarn test`
* The tests pass

### Current behavior

I get this error at the end of the tests

```js
    thrown: Object {
      "data": null,
      "status": 500,
    }

      at _getError (../../node_modules/jest-circus/build/utils.js:431:18)
          at Array.map (<anonymous>)
```

### Expected behavior

Jest shouldn't be throwing an error

**Comment by kettanaito** [comment]
Hi, @DominicGBauer. Thanks for reporting this.

This looks like a concurrency issue, perhaps. Can you try running your Jest tests with the `--runInBand` flag?

https://github.com/DominicGBauer/msw-test-example/blob/525827e8e747221bfc390d7a0825ce02bff807c4/examples/rtk-query-jest-react-native/package.json#L12

This will ensure that all test scenarios run sequentially. If it helps, it's likely a concurrency issue. 

Other than that, there's nothing on the MSW side that would throw in case of a mocked response. You'd have to look at your code and the request clients you're using. Perhaps, something along the way handles 5xx responses with an exception.

**Comment by DominicGBauer** [comment]
@kettanaito thanks for the response, I have checked and confirmed it's not a concurrency issue. I have raised an issue in redux toolkit now as well 
https://github.com/reduxjs/redux-toolkit/issues/3620
