### ISSUE TITLE
Feature toggle request: Drop unhandled network requests instead of bypassing them

### ISSUE THREAD

**Issue by amir-ziaei** [kettanaito/msw#1664]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I am delighted with how the msw library warns me about unhandled network requests, as shown in the example below:
```
console.warn
      [MSW] Warning: captured a request without a matching request handler:
      
        • GET http://example.com/some-path
      
      If you still wish to intercept this unhandled request, please create a request handler for it.
      Read more: https://mswjs.io/docs/getting-started/mocks
```

However, I would like to propose an additional opt-in feature: I suggest the option to automatically drop any network requests that do not have a matching handler by default. By enabling this feature, devs will be required to provide a handler for all requests, resulting in more deterministic tests.

I would love to hear your opinions and thoughts on this.

**Comment by kettanaito** [comment]
Hi, @amir-ziaei. Thanks for the proposal!

Can you please tell me more about what you mean by "drop any network requests"?

We do have something that sounds very similar to your proposal, that being the `"error"` value of the `onUnhandledRequest` option:

```js
server.listen({ onUnhandledRequest: 'error' })
```

This will throw an exception whenever a request happens that doesn't have a corresponding request handler. Would this address your concern?
