### ISSUE TITLE
[msw@next] Error: Cannot find package 'statuses' imported from .../node_modules/msw/lib/core/utils/HttpResponse/decorators.mjs

### ISSUE THREAD

**Issue by kmiwa007** [kettanaito/msw#1666]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.16.0

### Reproduction repository

N/A

### Reproduction steps

N/A

### Current behavior

Running vitest with `npm run test` throws

```
Error: Cannot find package 'statuses' imported from /Users/kenji.miwa/Code/dod-webclient-doctor/webclientdoctor/dod-react/node_modules/msw/lib/core/utils/HttpResponse/decorators.mjs

Serialized Error: {
  "code": "ERR_MODULE_NOT_FOUND",
}

```

### Expected behavior

No error.

**Comment by kettanaito** [comment]
Hi, @kmiwa007. This is very likely a dependency issue. Please make sure you're using `msw@next`. I recommend this:

```
npm unistall msw
npm install msw@next
```

Depending on your package manager, removing the `node_modules` directory may also help. 

Once done:

```bash
npm ls msw
# msw@0.0.0-fetch.rc-15

npm ls @mswjs/interceptors
# @mswjs/interceptors@0.23.0
```

The issue should be gone with those dependency versions.
