### ISSUE TITLE
Not able to intercept network request when axios is called from other monorepo package 

### ISSUE THREAD

**Issue by doublehrajput** [kettanaito/msw#1672]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.19.0

### Reproduction repository

https://github.com/mswjs/examples/tree/master/examples

### Reproduction steps

I have a monorepo setup with lerna ("useWorkspaces": false) so each package of lerna have their own scope of npm pacakges

directory structure
```
monorepo
  | -- packages
    | -- package-1  -- (jest and msw setup defined )
              | -- src
              | -- util.test.js
              | -- package.json --- contains (jest, msw , axios)


    | -- design-system    --- (have util.js file which is using axios)
              | -- src
                    | -- util.js
              | -- package.json --- contains (axios)
```

util.js content

```
export default callApi = (logObj) => {
      return axios
		  .post("http://urltotest.com", logObj)
		  .then((res) => {
			  console.log(res);
		  })
		  .catch((e) => {
			  console.log(e);
		  });
}
```

My request interceptor

```
import { rest } from "msw";

export const handlers = [
	// Handles a POST /login request
	rest.post("http://urltotest.com"", (req, res, ctx) => {
		return res(ctx.json({ status: true }));
	}),
];
```

With this type I am not able to intercept my network request

### Current behavior

Not able to intercept network request when axios is called from other monorepo package 

### Expected behavior

It should able to intercept network request when axios is called from other monorepo package

**Comment by kettanaito** [comment]
Hi, @doublehrajput.

Could you please include a minimal reproduction repository for this issue? The one you linked points to our Examples repo that doesn't have an example with Lerna. There's more to the setup than you provided in the description, and points like how you integrate MSW with your test framework can be one of the reasons why requests are not being intercepted. 

I would like to help you resolve this but first, you have to isolate this behavior into a standalone repository. You can use the examples you linked to get you started. Sandboxes are also fine. Once you have it, post it here and I can look into it if you wouldn't discover the culprit before then.
