### ISSUE TITLE
Move request error message from the worker to the main thread

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#1683]
### Scope

Improves an existing behavior

### Compatibility

- [X] This is a breaking change

### Feature description

Right now, whenever _any_ request errors, MSW will produce the error message saying that something went wrong and it's unlikely an issue with MSW. That error message is really meant only for one purpose: to facilitate exceptions rising from the request handlers. But since it's just a `try/catch` block around the _entire_ `fetch` event in the worker, that message also gets printed when extraneous request error, including requests that are meant to error by the developer.

## Expected behavior

- The current message is printed only upon an exception originating from the request handlers the user has defined. 
- The current message is not printed upon any other request error, if those requests or their handling has nothing to do with MSW. 

## References

https://github.com/mswjs/msw/blob/e87e00b5de5b9145d6010793d2049b242f999c16/src/mockServiceWorker.js#L128-L136

**Comment by kettanaito** [comment]
@thepassle, thanks for suggesting this. I opened the issue to keep track of it. If you have any feedback to share on this or how it should behave, please let me know. Thanks.

**Comment by thepassle** [comment]
> including requests that are meant to error by the developer.

Additionally: requests that are not related to MSW at all

But otherwise this looks good to me :) Thanks for creating the issue, I hadn't got round to it yet!
