### ISSUE TITLE
Support throwing Response in resolvers

### ISSUE THREAD

**Issue by kentcdodds** [kettanaito/msw#1690]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

In Remix, I have this really handy utility:

```tsx
/**
 * Provide a condition and if that condition is falsey, this throws a 400
 * Response with the given message.
 *
 * inspired by invariant from 'tiny-invariant'
 *
 * @example
 * invariantResponse(typeof value === 'string', `value must be a string`)
 *
 * @param condition The condition to check
 * @param message The message to throw (or a callback to generate the message)
 * @param responseInit Additional response init options if a response is thrown
 *
 * @throws {Response} if condition is falsey
 */
export function invariantResponse(
	condition: any,
	message: string | (() => string),
	responseInit?: ResponseInit,
): asserts condition {
	if (!condition) {
		throw new Response(typeof message === 'function' ? message() : message, {
			status: 400,
			...responseInit,
		})
	}
}
```

```tsx
const post = await getPost(params.postId)
// post: Post | undefined
invariant(post, 'Post not found', { status: 404 })
// post: Post
```

This works because remix catches errors I throw in my actions and loaders and checks whether it's a response and uses that response if so.

I would love to be able to reuse this utility in my MSW handlers. I think it's a great way to allow folks to build abstractions.

If accepted, could you please get ahead of Remix on [this particular issue](https://github.com/remix-run/remix/discussions/7043) 😅?

**Comment by kettanaito** [comment]
## Released: v2.1.0 🎉

This has been released in v2.1.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.1.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.1.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
