### ISSUE TITLE
Allow different types returned from a single handler

### ISSUE THREAD

**Issue by kentcdodds** [kettanaito/msw#1691]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

18

### Reproduction repository

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCRjMAlApgZ0gOxywBo4wBDHHGACyggFcBzG0qXeAXzgDN6Q4AchA4A7oLgB6SXBgBPMLgBccAAwA6DaoC0PLDADGNdVAPaAjAFYAUNYMRC8JACscDuNwC8KNJlwEiW2lZGmAcOBwaRgAbABM4ACMsOAgAa2t2anUmfQAKQUlyfDlaYHwmQVJcgEo4TwA+RGsASGAeOFyAWXJaEyLYiBAauEaNS1r2GAYofDhXB1ykBywAFVDylRgoBmTOapbJ6dn5-EWU2iwoNbKmTe3d-b3rIA

### Reproduction steps

```ts
rest.get('/anything', () => {
	if (Math.random() > 0.5) return json({ oneThing: true })
	return json({ otherThing: true })
})
```

My actual use case:

```ts
rest.post(`https://api.resend.com/emails`, async ({ request }) => {
	if (!request.headers.has('Authorization')) {
		return json({
			name: 'missing_api_key',
			message: 'Missing API key in the authorization header.',
			statusCode: 401,
		}, { status: 401 })
	}

	const email = EmailSchema.parse(await request.json())
	console.info('🔶 mocked email contents:', email)

	const dir = path.join(fixturesDirPath, 'email')
	await fsExtra.ensureDir(dir)
	await fsExtra.writeJSON(path.join(dir, `./${email.to}.json`), email)

	return json({
		id: faker.string.uuid(),
		from: email.from,
		to: email.to,
		created_at: new Date().toISOString(),
	})
})
```

### Current behavior

The beta types don't appear to like it if you return conditionally different responses.

### Expected behavior

I expect to be able to make my code resemble the API as closely as possible.

**Comment by kettanaito** [comment]
Closing this with the recommended approach described [here](https://github.com/mswjs/msw/issues/1792#issuecomment-1908551010).
