### ISSUE TITLE
Delay function not working in mocked response

### ISSUE THREAD

**Issue by jeinhorn787** [kettanaito/msw#1692]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://codesandbox.io/s/msw-delay-test-lnv4pm

### Reproduction steps

The `delay()` function available in the `ctx` parameter of a `rest.get()` callback is being ignored. 

## Environment
`msw: "^1.2.1"`
`react: "^17.0.2"`
`node: "18.14.1"`
`npm: "9.3.1"`
`Chrome: "115.0.5790.170"`

## Reproduce

1. Create a new React app via the `create-react-app` command
2. Install **latest** msw
3. Create a an MSW `rest.get()` mock route. In the callback, include the `delay()` function in the `response()`.  It can be any number
4. Fetch the route

Similar to [an older issue of the same nature](https://github.com/mswjs/msw/issues/136), I can't get the `codesandbox` to work as intended but in my local project, I did add in some `console.log` statements before and after the request to show the timing. The code looks like this
```
console.log(`Request started: ${new Date()}`);

const res = await fetch("http://something.com');

console.log(`Response received: ${new Date()}`);
```

My mocked MSW route looks like the following:
```
const testApi = rest.get("http://something.com", (req, res, ctx) => {
  return res(ctx.status(200), ctx.json({ value: "test" }), ctx.delay(5000)); <-- 5s delay
});
```

### Current behavior

The mocked API is immediately responding with no delay even though a 5000ms `delay()` is defined.

**Note: I am using a real API in my local project so I am blocking out the URL here for security. However, the issue is still the same with the same steps being followed and the same environment configs**

<img width="886" alt="Screen Shot 2023-08-07 at 4 32 17 PM" src="https://github.com/mswjs/msw/assets/29580247/f8ff2cf8-ede6-4d30-b819-0bddd756902b">

### Expected behavior

A 5000ms, or 5 second, delay in the response should occur.

**Comment by kettanaito** [comment]
Hi, @jeinhorn787. Thanks for reporting this. 

I'm fairly confident `ctx.delay()` works as intended. We have a test suite exactly for your user case and it passes:

https://github.com/mswjs/msw/blob/c0cec117975e9f71c5d70bcdfbaaafd46ad81277/test/node/msw-api/context/delay.node.test.ts#L34-L36

Could you give your example a try in a different environment? Trying it out locally may be a good starting point. 

If you still experience the issue, try using `msw@next` instead. See more on what's and how's here #1464. Unfortunately, I don't have the time capacity to address issues in 1.x and I highly encourage you to update to `msw@next` if you have the time yourself.
