### ISSUE TITLE
Add "continue" helper

### ISSUE THREAD

**Issue by kentcdodds** [kettanaito/msw#1694]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I would like to be able to do this:

```ts
	const email = faker.internet.email()
	let emailRequest: Request
	server.use(
		rest.post(`https://api.resend.com/emails`, async ({ request }) => {
			emailRequest = request
			return continue()
		}),
	)
```

This would allow me to override the handler just to get the request so I can make assertions on it, but then let msw continue to look for another existing handler that will handle this request.

**Comment by kettanaito** [comment]
Hi, @kentcdodds. The fallthrough behavior is already implemented and it's the default behavior MSW exhibits. 

## Fallthrough in 1.x

In version 1.x, it's enough to return undefined from the resolver to tell MSW to keep looking for any other matching handler.

```js
rest.get('/resource', (req, res, ctx) => {
  // ...any side-effects.
  return
})
```

## Fallthrough in 2.x (#1404) 

In version 2.x, it works the same way: MSW keeps iterating until it meets a handler that returns a response:

https://github.com/mswjs/msw/blob/90b854ab2a82cd742ebbe9647ed645f0ce9ff04c/src/core/utils/getResponse.ts#L36-L43

Did you experience an issue with this behavior? I'm rather confident it's stable in 1.x but I might have introduced a regression in the 2.x rewrite. If that's the case, please let me know. Thanks.

**Comment by kentcdodds** [comment]
Ah! That makes plenty of sense. I'll test it out and let you know if I have issues. I guess I forgot about this behavior 😅
