### ISSUE TITLE
MSW stops working after navigating to a custom protocol URL ("vscode://")

### ISSUE THREAD

**Issue by mackelito** [kettanaito/msw#1697]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

n/a

### Reproduction steps

when prompting to open a app like this
`window.location.href = 'vscode://';`

and then hit cancel 
and then do a request the service worker does not catch the request..

so:
1. window.location.href = 'vscode://'
2. press cancel
3. do a request eg `this.http.delete("auth/authentications/${id}")`

If I remove the step of opening vscode it works fine.. :)

### Current behavior

does not catch the request at all

### Expected behavior

should catch it

**Comment by kettanaito** [comment]
Hey, @mackelito. Thanks for reporting this. 

I wonder if setting `window.location.href` emits the `beforeunload` event on the document? Could you confirm if it does?

```js
document.addEventListener('beforeunload', () => console.log('it does'))
window.location.href = 'vscode://...'
```

I also found a related issue submitted to Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=522370. Could you give this a try in other browsers, like Firefox or Safari? I wonder if the behavior is browser-specific.

**Comment by mackelito** [comment]
Just tested and it does work in safari but not in chrome, firefox or edge..

````
        addEventListener('beforeunload', (event) => {
          console.log('beforeunload', window.location.href);
        });
        onbeforeunload = (event) => {
          console.log('onbeforeunload', window.location.href);
        };
````

This code logs after I see "[MSW] Mocking enabled."

**Comment by kettanaito** [comment]
This is a browser-specific behavior, and potentially a bug in the browser. Nothing we can do on MSW's side, unfortunately.

**Comment by alex-way** [comment]
For further reference; Chromium based browsers seem to send an "unload" event when a user clicks an anchor tag with a custom protocol (`mailto:`, `vscode://`).

A simple workaround in my case was to use the `target="_blank"` attribute.

As a separate note, using the "next/link" Link component didn't work even with the above fix. I had to revert back to using an anchor tag.
