### ISSUE TITLE
MSW + Next.js does not intercept requests after page refresh

### ISSUE THREAD

**Issue by khoi-fish** [kettanaito/msw#1698]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

`>= 16`

### Reproduction repository

https://github.com/khoi-fish/with-msw-fix/tree/fix

### Reproduction steps

1. `yarn`
2. `yarn dev`
3. Navigate to `localhost:3000`
4. Notice that the page loads fine
5. Hit refresh
6. `msw` fails to intercept request and the page breaks

### Current behavior

<img width="970" alt="image" src="https://github.com/mswjs/msw/assets/4228966/20c48adc-48d6-47de-9fe3-22e82453edae">

### Expected behavior

The expectation is that refreshing should not break the page.

**Comment by khoi-fish** [comment]
Happy to answer any questions to further help identify the issue 🙂

**Comment by gidztech** [comment]
I ran into this issue today after updating Next.js. I played around with the different versions that have been released recently, and it seems it only started happening in [v13.4.13](https://github.com/vercel/next.js/releases/tag/v13.4.13). On prior versions, you can refresh the page and the interception works. I've not dug deeper into why yet.

**Comment by kettanaito** [comment]
I'm going to close this. Next.js doesn't work well with MSW at the moment. Until I have a fully functional example as confirmation of that, Next.js is not supported. 

You can follow the progress of that example here:
https://github.com/mswjs/examples/pull/101

The Next.js team has also reached out to me to help address the remaining issues on Next.js side, so I hope to post some updates soon.

**Comment by SalahAdDin** [comment]
> I'm going to close this. Next.js doesn't work well with MSW at the moment. Until I have a fully functional example as confirmation of that, Next.js is not supported.
> 
> You can follow the progress of that example here: [mswjs/examples#101](https://github.com/mswjs/examples/pull/101)
> 
> The Next.js team has also reached out to me to help address the remaining issues on Next.js side, so I hope to post some updates soon.

It does not work at all.
