### ISSUE TITLE
Simulate polling

### ISSUE THREAD

**Issue by mackelito** [kettanaito/msw#1700]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I would love to see a official way to mimic responses when polling a endpoint...
so for the first 3 requests you get a response (eg. a pending status) and then you get a final response :)

**Comment by kettanaito** [comment]
Hi, @mackelito. 

You can achieve HTTP polling by declaring your response resolver as a _generator_ function:

https://github.com/mswjs/msw/blob/c0cec117975e9f71c5d70bcdfbaaafd46ad81277/test/browser/rest-api/generator.mocks.ts#L4-L23

With this approach, you control the response to each consecutive request and can return different data before ending the response with the final chunk. 

I will improve this example's discoverability in our documentation.
