### ISSUE TITLE
Throw when run in production

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#1703]
### Scope

Adds a new behavior

### Compatibility

- [X] This is a breaking change

### Feature description

I propose MSW, both `setupWorker` and `setupServer` throw an exception when detected being run in `NODE_ENV === 'production'`. 

## Motivation

When MSW gets to a production environment that's a mistake on the developer's end 9 times out of 10. I believe this would be a good default behavior to have to prevent this kind of mistake. 

## Implementation

Apart from raising an exception, this feature should also introduce an opt-out mechanism for those who explicitly wish to run MSW in production. We must still permit to run MSW anywhere the end user want but they need to explicitly state their intention. I know that a lot of teachers rely on MSW in production to teach their workshops. I want them to keep doing that without hindrance.

```js
worker.start({ dangerouslyRunInProduction: true })
server.listen({ dangerouslyRunInProduction: true })
```

When the `dangerouslyRunInProduction` is provided and equals `true`, suppress the said exception.

**Comment by kettanaito** [comment]
@kentcdodds hi, 👋  Do you have any considerations I may be not seeing in regard to this feature? How would this impact your and your students' experience, for example?

**Comment by kentcdodds** [comment]
The opt-out is sufficient for me. This looks great.

**Comment by kettanaito** [comment]
Closing this. Reason: https://github.com/mswjs/msw/pull/1791#issuecomment-2143374320
