### ISSUE TITLE
MSW 2.0: Breaks on file URLs from Vitest

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#1709]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Reproduction repository

—

### Reproduction steps

Start up a new Epic Stack app, add a new test, run Vitest.

### Current behavior

```sh
NetworkError: TypeError [ERR_INVALID_PROTOCOL]: Protocol "node:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:405:5)
    at new ClientRequest (node:_http_client:188:11)
    at request (node:http:100:10)
    at Request._performRequest (/epic-stack/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:106:28)
    at new Request (/epic-stack/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:27:10)
    at Object.createClient (/epic-stack/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:364:29)
    at XMLHttpRequestImpl.send (/epic-stack/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:643:31)
    at XMLHttpRequest.send (/epic-stack/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:323:34)
    at Socket.<anonymous> (/epic-stack/node_modules/jsdom/lib/jsdom/living/xhr/xhr-sync-worker.js:48:9)
    at Socket.emit (node:events:526:35)
 ❯ new NodeError node:internal/errors:405:5
 ❯ new ClientRequest node:_http_client:188:11
 ❯ request node:http:100:10
 ❯ Request._performRequest node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:106:28
 ❯ new Request node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:27:10
 ❯ Object.createClient node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:364:29
 ❯ XMLHttpRequestImpl.send node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:643:31
 ❯ XMLHttpRequest.send node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:323:34
 ❯ Socket.<anonymous> node_modules/jsdom/lib/jsdom/living/xhr/xhr-sync-worker.js:48:9
 ❯ Socket.emit node:events:526:35
```

### Expected behavior

File URLs are ignored by MSW. Alternatively, file URLs are supported since you can mock their buffer response and thus mock the file request, which is handy.

**Comment by silverwind** [comment]
Set your vitest `environment` to `node` if you are using node-specific APIs. There is `jsdom` in the stack trace and browser environments do not support `node:` protocol.

**Comment by kettanaito** [comment]
Thanks for the input, @silverwind. That sounds like something that should be configured in the userland though, does it not? MSW in itself doesn't control which testing environment you choose to run it.

**Comment by kettanaito** [comment]
I've just tried created a new Epic Stack app and adding a new test. That caused no errors. 

More to that, you can create `node:` URLs in Node.js v18+ now, it won't throw:

```js
new URL('node:foo')
```

I consider this issue non-reproducible. If you still encounter this, please open a new issue _and include a reproduction repository_. Thanks.
