### ISSUE TITLE
Can't install 1.2.4 version as it has pnpm specified to veriosn 7

### ISSUE THREAD

**Issue by n0r8** [kettanaito/msw#1712]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

16.16.0

### Reproduction repository

https://github.com/mswjs/msw/commit/c0cec117975e9f71c5d70bcdfbaaafd46ad81277

### Reproduction steps

use pnpm 8+
try to install package

### Current behavior

This error happened while installing a direct dependency of bla

Your pnpm version is incompatible with "msw/1.2.4".

Expected version: ~7.12
Got: 8.3.0

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

### Expected behavior

Should be possible to install the package.

**Comment by kettanaito** [comment]
Hu, @n0r8. Thanks for reporting this. 

This issue is caused by #1676, which was meant for contributors but leaks to consumers also. It shouldn't be this way and we should fix it.

**Comment by kettanaito** [comment]
## Released: v1.2.5 🎉

This has been released in v1.2.5!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v1.2.5)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/1.2.5)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
