### ISSUE TITLE
Typescript v5.2.2 has been released and is incompatible with msw latest version

### ISSUE THREAD

**Issue by ribeaud** [kettanaito/msw#1717]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Hi. Because of following restriction:
```json
...
    "typescript": "^5.0.2",
    "url-loader": "^4.1.1",
    "webpack": "^5.68.0",
    "webpack-dev-server": "^3.11.2",
    "webpack-http-server": "^0.5.0"
  },
  "peerDependencies": {
    "typescript": ">= 4.4.x <= 5.1.x"
  },
...
```
latest versions of both libraries: typescript and msw bite each other.

**Comment by satanshiro** [comment]
open pr is here: https://github.com/mswjs/msw/pull/1711

**Comment by kettanaito** [comment]
Thanks for reporting this, @satanshiro. I will close this because it's not an issue. We aren't promising TypeScript 5.2 support officially. The pull request is open to add that support and we will release it as soon as it's done.
