### ISSUE TITLE
Support Bun runtime

### ISSUE THREAD

**Issue by OleksandrKucherenko** [kettanaito/msw#1718]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.15.0

### Reproduction repository

https://github.com/OleksandrKucherenko/chatgpt-translate-md/pull/8

### Reproduction steps

- Take the branch - from PR https://github.com/OleksandrKucherenko/chatgpt-translate-md/pull/8
- Install BUN `curl -fsSL https://bun.sh/install | bash` (details: https://bun.sh/)
- Run `bun install`
- Run `bun test`

Refs:
- Can be related to incomplete implementation of the TEST API in BUN: https://github.com/oven-sh/bun/issues/1825 

Notes:
For switching between TS-NODE JEST and BUN you will need to changes lines:
<img width="815" alt="image" src="https://github.com/mswjs/msw/assets/6419758/9242fa0e-b390-41c9-9240-e2b2bddb20d5">

this is YARN 3.xx monorepo with multiple packages, that I try to make compatible with BUN 0.8.1

### Current behaviour

BUN produce this error

```
clis/gpt/src/gpt.test.ts:
879 |     if (this.aborted)
880 |       return;
881 |     this[kAbortController].abort();
882 |   }
883 | 
884 |   constructor(input, options, cb) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at ClientRequest (node:http:884:26)
      at new NodeClientRequest (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js:104:20)
      at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/http.request.js:37:15
      at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:284:8
      at new RedirectableRequest (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:66:2)
      at request (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:523:13)
      at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/axios/lib/adapters/http.js:438:10
      at dispatchHttpRequest (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/axios/lib/adapters/http.js:149:54)
      at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/axios/lib/adapters/http.js:143:4
      at new Promise (:1:20)
```

<img width="1377" alt="image" src="https://github.com/mswjs/msw/assets/6419758/daac8204-ff70-4696-a7ac-1ce0487333ee">

### Expected behavior

YARN+TS-NONE - produce this error

```
 FAIL  clis/gpt/src/gpt.test.ts
  ● gpt › should raise custom error on API error 429

    ⛔ API error.

      117 |   // raise errors on non-2xx responses or empty content
      118 |   if (!(response.status >= 200 && response.status < 300))
    > 119 |     throw new Error(Errors.ApiError, { cause: createAxiosError(response) })
          |           ^
      120 |   if (content === ``) throw new Error(Errors.EmptyContent)
      121 |
      122 |   return content

      at askGPT (clis/gpt/src/gpt.ts:119:11)
      at Object.<anonymous> (clis/gpt/src/gpt.test.ts:66:20)

    Cause:
    AxiosError: Request failed with status code 429

      3 | /** stolen from: axios/lib/core/settle.js:17:12 */
      4 | export const createAxiosError = (response: AxiosResponse): AxiosError =>
    > 5 |   new AxiosError(
        |   ^
      6 |     `Request failed with status code ${response.status}`,
      7 |     [AxiosError.ERR_BAD_REQUEST, AxiosError.ERR_BAD_RESPONSE][Math.floor(response.status / 100) - 4],
      8 |     response.config,

      at createAxiosError (clis/gpt/src/createAxiosError.ts:5:3)
      at askGPT (clis/gpt/src/gpt.ts:119:63)
      at Object.<anonymous> (clis/gpt/src/gpt.test.ts:66:20)
```

<img width="847" alt="image" src="https://github.com/mswjs/msw/assets/6419758/539b634b-a6bb-4c94-ac97-eac55e4bf9fd">

**Comment by kettanaito** [comment]
I'm closing this because MSW functions without issues in Node.js. If there are any issues in Bun, those are likely Bun issues with Node.js compatibility. I highly recommend you file those in Bun's repo to make the team aware. If you find something MSW-specific, feel free to update this thread.

**Comment by Valdermeyder** [comment]
Regarding your response above. It can be hard to draw a line between who should support what. Bun is not 100% compatible with NodeJs and maybe it shouldn't be. In both cases it would be great to have `msw` works in `bun`

Anyway, just wanted to share with you another error.
I'm trying to use Bun just as a testing runtime and the issue I spotted today is `msw` is failing on
```
458 |     const { status, statusText, headers, body } = mockedResponse;
459 |     this.response.statusCode = status;
          ^
TypeError: Attempted to assign to read only property.
      at respondWith (/Users/volodymyrhuzar/Sources/Twill/twill-email-templates/node_modules/@mswjs/interceptors/lib/node/chunk-YXLNUCS2.mjs:459:5)
      at /Users/volodymyrhuzar/Sources/Twill/twill-email-templates/node_modules/@mswjs/interceptors/lib/node/chunk-YXLNUCS2.mjs:342:9
```
bun - 1.0.26
"msw": "2.2.0"
Let me know if you are interested in more details

**Comment by kettanaito** [comment]
@VinceMalone, I can say with rather solid confidence that MSW will not ship anything specific to Bun. If you want to use MSW in Bun, you have to ensure Bun provides sufficient compatibility with Node.js (the `http` module and the global Fetch API, mainly). 

Regarding the error, looks like a bug in Bun. The [`IncomingMessage.statusCode`](https://nodejs.org/api/http.html#messagestatuscode) is not a readonly property. It's being assigned in the Interceptors library correctly.
