### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to get ServiceWorkerRegistration objects: The document is in an invalid state

### ISSUE THREAD

**Issue by acheong08** [kettanaito/msw#1724]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.17.1

### Reproduction repository

https://github.com/acheong08/rev-obsidian-sync-plugin/tree/testing

### Reproduction steps

Install the plugin into the obsidian electron app

### Current behavior

Fails at `return await this.startHandler(this.context.startOptions, options);`
```
Uncaught (in promise) DOMException: Failed to get ServiceWorkerRegistration objects: The document is in an invalid state
```

### Expected behavior

```
this.worker.start();
``` just loads a service worker

**Comment by kettanaito** [comment]
Hi, @marcosvega91. Thanks for reporting this. 

The error is thrown by Chromium, seems to be originating from here:

https://chromium.googlesource.com/chromium/src/+/2077dd71402ec96711c63d49566a16cbe34698e2/third_party/blink/renderer/modules/service_worker/service_worker_container.cc#430

This is not an MSW issue but this may be a behavior we need to account for. Depends on what is happening with the page and whether it makes sense to handle this on the library's side. Note that even if we account for this, **it will not fix the issue**. The issue originates in the browser, which means you are doing something unexpected that Chromium cannot register the worker correctly. 

From your code, I can spot a mistake straight away right here:

https://github.com/acheong08/rev-obsidian-sync-plugin/blob/f0160b5207472a959dfd6727823d352792fd7448/main.ts#L45

Please await the `worker.start()` Promise. 

I'm afraid I don't have the capacity to look into this issue right now so I highly recommend you scout the Internet. This is a general browser issue and I've found a few mentions of it just by googling:

- https://github.com/microsoft/vscode/issues/125993
- https://stackoverflow.com/questions/63037342/what-does-the-error-failed-to-register-a-serviceworker-the-document-is-in-an-i

**Comment by kettanaito** [comment]
I will close this because this isn't an issue with MSW directly. It's either related to the browser, or to how you start the worker in your Electron app. I wish I could provide more insight but I don't have time to look into this right now. You can look around, others have likely encountered this issue when working with Service Workers in Electron.
