### ISSUE TITLE
Handlers returning 3xx statuses fail in Safari

### ISSUE THREAD

**Issue by treuherz** [kettanaito/msw#1738]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Safari

### Reproduction repository

github.com/treuherz/msw-repro

### Reproduction steps

1. `pnpm run dev`
2. Open the dev-server link (normally http://localhost:5174/) in Safari 16.6 
3. Click the button, which fires a fetch to an MSW handler which returns a 303

### Current behavior

The fetch throws a "Load Failed" error. There's an unhelpful error message in the console.

### Expected behavior

The redirect is followed by Fetch successfully. This works in Firefox and Chrome.

**Comment by kettanaito** [comment]
Hi, @treuherz. Thanks for raising this. 

From the looks of it, this is a Safari-specific behavior, perhaps even a bug in there. MSW code doesn't change between browsers, but the way each browser implements Service Workers is up to them. Sadly, I don't see what we can change in this situation. 

MSW is a development tool. If you encounter an issue that's specific to a certain browser, switch to a different browser for the time being. It's the same as different developer tools capabilities across browsers: Chrome has a much better Service Worker debugging tools than Safari; Firefox is incredible in debugging overflow elements on the page; etc.
