### ISSUE TITLE
Next.js 13 No SSR Support.

### ISSUE THREAD

**Issue by Yefee8** [kettanaito/msw#1743]
### Prerequisites

- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue
- [x] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

privaterepo

### Reproduction steps

yarn test

### Current behavior

In Next.js 13, We can't load mocks in SSR. 
There's just one way to load mocks but that's just for CSR.

example:

```
"use client"

import { useState } from 'react';

export default function ChildrenFunction({ children }: any) {

    const [isLoaded, setIsLoaded] = useState(false);

    import('../../mocks').then(({ setupMocks }) => {
        setupMocks().then(() => {
            setIsLoaded(true)
        })
    });

    return (
        <main>
            {
                isLoaded ? children : <></>
            }
        </main>
    )
}
```
(I'm using this component in layout.tsx)

### Expected behavior

Loading Mocks In SSR with Next.js 13.

**Comment by kettanaito** [comment]
Hi, @Yefee8. Thanks for raising this. We don't currently have support for Next 13, and you should follow the progress on that support in #1644. Until it lands, we cannot accept issues around it.
