### ISSUE TITLE
Documentation Improvement suggestion

### ISSUE THREAD

**Issue by Lauro235** [kettanaito/msw#1748]
## User concern

I'm making an app with Vite and TypeScript. I'm looking through the documentation and everything is nice and easy, but then we get to the instructions regarding setting up according to the development flag.

Frustratingly the syntax used is require syntax. Now I'm no JS guru and I'm sure there are good reasons for this, but please could you consider offering the import syntax alternative at this juncture.

## My possible solution

This was what I did to get the MSW working. I've not tested it extensively and I don't know the service well enough to know what it is when the service is working or broken, but opening dev tools I can see the start message '[MSW] Mocking enabled'.

```tsx
  import('./mocks/browser.ts')
  .then(module => {
    module.worker.start();
    return () => {
      module.worker.stop();
    }
  })
  .catch(err => console.log(err)
  );
}
```

I'd be grateful for an update here.

Thanks.

**Comment by kettanaito** [comment]
Hi, @Lauro235. Thanks for suggesting this! I know the frustration with require/import and the difference in both syntax and behavior (this was crucial for tree shaking of MSW during production builds). 

The new version of the docs will feature the usage of `import` in the examples.
