### ISSUE TITLE
Browser reload bug

### ISSUE THREAD

**Issue by Lauro235** [kettanaito/msw#1753]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/Lauro235-dev-environments/possible-msw-bug

### Reproduction steps

1. Clone the repo.
2. Install the dependencies
3. Run the app

### Current behavior

When you load up the console in the dev tools you see the error. `Uncaught (in promise) SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON`.
If you now go to src/App.tsx, make a change and save, you can go back to the console in the browser and find that the promise has been parsed successfully.
However if you try to reload the window, you get the original error.

### Expected behavior

When I load, reload or save the file in which the request is made, I should get the a JSON response.

I've tried so many permutations of the fetch request. I'm not sure I've got any more async syntax left... Just in case it matters, I am using ES6 so import in the browser file in Main.tsx.

Thanks for your time and contribution.

**Comment by ruipserra** [comment]
Hey @Lauro235, it looks like the request is being sent before the `msw` mocks have been set up. That's why the first request fails and subsequent requests succeed.

Here's a commit that fixes your issue: https://github.com/ruipserra/possible-msw-bug-with-fix/commit/8628c5fe99d9bd71bfcb18062ee7f652f761e104. You can clone [my fork of your repro](https://github.com/ruipserra/possible-msw-bug-with-fix) and run it, you won't see any errors.

**Comment by kettanaito** [comment]
Thank you for providing a suggestion for this, @ruipserra! You are absolutely correct.

It's recommended to defer your application rendering before MSW is enabled to prevent situations like this. More on that in the [Browser integration](https://mswjs.io/docs/integrations/browser#conditionally-enable-mocking) in the docs.
