### ISSUE TITLE
msw has empty request headers in Node v18.18.2

### ISSUE THREAD

**Issue by wrporter** [kettanaito/msw#1772]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.18.2

### Reproduction repository

https://github.com/mswjs/msw

### Reproduction steps

This is easily reproducible on Node v18.18.2 (not a problem on 18.18.1, potentially due to the undici update in 18.18.2). 

```javascript
import { setupServer } from 'msw/node';
import { rest } from 'msw';

const baseUrl = 'http://localhost';
const server = setupServer(
    rest.all(baseUrl, (req, res, ctx) => res(ctx.status(200), ctx.json(req.headers.raw()))),
);

async function main() {
    server.listen();

    const request = new Request(baseUrl);
    request.headers.set('x-header-id', 'sample-header');
    const response = await fetch(request);

    console.log(await response.json());

    server.resetHandlers();
    server.close();
}

main();
```

### Current behavior

On Node 18.18.2, the above code always returns empty headers regardless of the headers that are set and outputs the following to the console.

```
{}
```

### Expected behavior

On Node 18.18.1, the above code works as expected and outputs the following to the console.

```
{ 'x-header-id': 'sample-header' }
```

**Comment by kettanaito** [comment]
Hi, @wrporter. Thanks for reporting this. 

MSW 1.x does not support Node.js 18. Please upgrade to `msw@next` which has such support. Follow this discussion to upgrade #1464. Thanks.
