### ISSUE TITLE
Please make 1.x documentation available

### ISSUE THREAD

**Issue by dmitryplatonov** [kettanaito/msw#1788]
Looks like with the release of v2.0.0 old (v1.x) documentation is no longer available. Given breaking changes in v2, it would be great if old documentation could be accessed somehow as most projects still use 1.x.

**Comment by kettanaito** [comment]
Hi, @dmitryplatonov. Thanks for proposing this.

You can access the V1 website and docs at https://v1.mswjs.io. It showcases the latest active deployments (dating 06.2023, to my best knowledge).
