### ISSUE TITLE
Please link v1.mswjs.io/docs from mswjs.io/docs

### ISSUE THREAD

**Issue by dmitryplatonov** [kettanaito/msw#1789]
It would be great if https://mswjs.io/docs can link to https://v1.mswjs.io/docs in some visible place - it's common practice when introducing major version change.
Otherwise it's hard to discover - both for search engines and humans.

Edit: the same goes for link from v1 to current docs.

**Comment by kettanaito** [comment]
Thanks for proposing this. The root [Documentation page](https://mswjs.io/docs/) now has a banner at the top that:

- Emphasizes you're viewing V2 docs;
- Adds a link to the V1 docs.

**Comment by gtjamesa** [comment]
Can you add it to all pages? I hadn't realised v2 had been released; I went to https://mswjs.io/ and pressed "Get Started" to install into a new project and was very confused for a minute because the docs didn't look how they did a week ago when I installed.

**Comment by kettanaito** [comment]
@gtjamesa, pull requests are welcome :)

**Comment by gtjamesa** [comment]
@kettanaito https://github.com/mswjs/mswjs.io/pull/277
