### ISSUE TITLE
Nuxt Build Error: No known conditions for "./node" specifier in "msw" package

### ISSUE THREAD

**Issue by snowdream** [kettanaito/msw#1800]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182224/job/18108684061

### Reproduction steps

pnpm generate

### Current behavior

build error：

```
Run pnpm build && pnpm generate

> vue-nuxt-element-template@0.1.0 build /home/runner/work/vue-nuxt-element-template/vue-nuxt-element-template
> MODE=prod nuxi build

[log] Nuxt 3.8.0 with Nitro 2.[7](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182224/job/18108684061#step:11:8).0
[warn] [@nuxtjs/i1[8](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182224/job/18108684061#step:11:9)n] JS / TS extension format is an experimental feature
[info] Building client...
[info] vite v4.5.0 building for production...
[info] transforming...
[info] ✓ 108 modules transformed.
[info] ✓ built in 3.33s
Error:  [commonjs--resolver] No known conditions for "./node" specifier in "msw" package
Error:  Nuxt Build Error: No known conditions for "./node" specifier in "msw" package
  at e (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.6[9](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182224/job/18108684061#step:11:10).5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:21445:25)
  at n (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:21445:646)
  at o (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:21445:[12](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182224/job/18108684061#step:11:13)97)
  at resolveExportsOrImports (node_modules/.pnpm/vite@4.5.0_@types+node@[18](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182224/job/18108684061#step:11:19).18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28746:20)
  at resolveDeepImport (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28765:31)
  at tryNodeResolve (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
  at Object.resolveId (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
  at node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

### Expected behavior

No error when building

**Comment by kettanaito** [comment]
@snowdream, I trust you've figured it out, given the CI is green now? Can you please share how you fixed it?

**Comment by snowdream** [comment]
@kettanaito 

https://github.com/snowdreamtech/vue-nuxt-element-template/issues/2

https://github.com/snowdreamtech/vue-nuxt-element-template/tree/main/plugins

i use msw in nuxt 3 project.

when mode is client
```
import { setupWorker } from 'msw/browser'
import path from 'path-browserify'
import { handlers } from './handlers'

export const worker = setupWorker(...handlers)

export function mockBrowser (config:any) {
  worker.start({
    serviceWorker: {
      url: path.resolve(config.baseURL, 'mockServiceWorker.js')
    },
    onUnhandledRequest: 'bypass'
  })
}
```
when mode is server 
```
import { setupServer } from 'msw/node'
import { handlers } from './handlers'

export const server = setupServer(...handlers)

export function mockServer (config?: any) {
  server.listen({
    onUnhandledRequest: 'bypass'
  })

  // server.events.on('request:start', ({ request }) => {
  //   console.log('MSW intercepted:', request.method, request.url)
  // })
}
```

That‘s it.

**Comment by kettanaito** [comment]
Hi, @snowdream. 

I've tried building your app and it built without issues:

```
> MODE=prod nuxi build

Nuxt 3.8.0 with Nitro 2.7.2                                                                          10:53:04 AM
ℹ Building client...                                                                                10:53:07 AM
ℹ vite v4.5.0 building for production...                                                            10:53:07 AM
ℹ ✓ 2003 modules transformed.  

...

ℹ ✓ built in 15.97s                                                                                 10:53:23 AM
✔ Client built in 15979ms                                                                           10:53:23 AM
ℹ Building server..

ℹ ✓ built in 14ms                                                                                   10:53:23 AM
✔ Server built in 26ms                                                                              10:53:23 AM
✔ Generated public .output/public                                                             nitro 10:53:23 AM
ℹ Building Nitro Server (preset: node-server)                                                 nitro 10:53:23 AM
✔ Nitro server built                                                                          nitro 10:53:27 AM
Σ Total size: 2.13 MB (502 kB gzip)
```

My environment:

- Node: 18.14.2
- pnpm: 7.12

I also have a few questions to your setup, based on the CI job you shared:

1. You can clearly see the job start with `[info] Building client...` but you get an error that `msw/node` is not resolved. I suspect that error is correct. There must be no imports to `msw/node` while building the client. If Nuxt fails to resolve it, Nuxt is simply telling you that you have a Node import in a browser-targeted bundle. 
2. Why is anything MSW-related even present in the _production_ build? This also strongly suggests that you don't enable MSW _conditionally_, which is the way you should be using API mocking. 

Please look into those questions and let me know if they help you resolve the issue.

**Comment by stichingsd-vitrion** [comment]
> @kettanaito
> 
> [snowdreamtech/vue-nuxt-element-template#2](https://github.com/snowdreamtech/vue-nuxt-element-template/issues/2)
> 
> https://github.com/snowdreamtech/vue-nuxt-element-template/tree/main/plugins
> 
> i use msw in nuxt 3 project.
> 
> when mode is client
> 
> ```
> import { setupWorker } from 'msw/browser'
> import path from 'path-browserify'
> import { handlers } from './handlers'
> 
> export const worker = setupWorker(...handlers)
> 
> export function mockBrowser (config:any) {
>   worker.start({
>     serviceWorker: {
>       url: path.resolve(config.baseURL, 'mockServiceWorker.js')
>     },
>     onUnhandledRequest: 'bypass'
>   })
> }
> ```
> 
> when mode is server
> 
> ```
> import { setupServer } from 'msw/node'
> import { handlers } from './handlers'
> 
> export const server = setupServer(...handlers)
> 
> export function mockServer (config?: any) {
>   server.listen({
>     onUnhandledRequest: 'bypass'
>   })
> 
>   // server.events.on('request:start', ({ request }) => {
>   //   console.log('MSW intercepted:', request.method, request.url)
>   // })
> }
> ```
> 
> That‘s it.

Hi men! We have this as well but when using for example useFetch, the first server side request is not captured, if you use refresh it works.

```js
function testFetchToGetPosts() {
  fetch('https://jsonplaceholder.typicode.com/posts')
    .then((response) => response.json())
    .then((json) => console.log(json))
}
function testFetchWithNuxtToGetPosts() {
  $fetch('https://jsonplaceholder.typicode.com/posts', {
    server: true,
    client: false,
  }).then((json) => console.log(json))
}
const { data: posts, refresh } = await useFetch(
  'https://jsonplaceholder.typicode.com/posts',
  {
    client: true,
  },
)
</script>

<template>
  <div>
    <p>{{ $t('welcome') }}</p>
    <Button label="testFetchToGetPosts" @click="testFetchToGetPosts" />
    <Button
      label="testFetchWithNuxtToGetPdosts"
      @click="testFetchWithNuxtToGetPosts"
    />
    <Button label="refresh" @click="refresh" />
    <nav>

```
    
mock.client.ts
 ```js
    export default defineNuxtPlugin(async () => {
  const config = useRuntimeConfig()
  if (config.public.mock === 'msw') {
    const { mockBrowser } = await import('../mocks/browser')
    await mockBrowser()
  }
})
```

mock.server.ts
```js
export default defineNuxtPlugin(async () => {
  const config = useRuntimeConfig()

  if (config.public.mock === 'msw') {
    const { mockServer } = await import('../mocks/server')
    mockServer()
  }
})
```

This works in client side but server side no success ( and i mean the prefetch no api.ts calls)

**Comment by danlourenco** [comment]
I think this might be relevant: https://github.com/unjs/ofetch/issues/295

**Comment by DanielAraldi** [comment]
Hello, I'm having this error too, but in my React app, I added a [new comment](https://github.com/mswjs/msw/issues/1657#issuecomment-1949109807) this is another issue, can anybody help me?
