### ISSUE TITLE
Create React App / Jest: Axios requests aren’t intercepted by MSW

### ISSUE THREAD

**Issue by joel-daros** [kettanaito/msw#1803]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v18.17.1

### Reproduction repository

https://github.com/joel-daros/msw2-text-encoder-issue/tree/main

### Reproduction steps

I created a simple repository with an example, testing `DogService.ts`:

```ts
import axios from "axios";

const axiosInstance = axios.create();

type DogFacts = {
  facts: string[];
};

export const getDogFacts = async (): Promise<string[]> => {
  const response = await axiosInstance.get<DogFacts>(
    "https://dogapi.dog/api/facts"
  );
  return response.data.facts;
};
```

The test:

```ts
import { setupServer } from "msw/node";
import { HttpResponse, http } from "msw";
import { getDogFacts } from "./DogService";

const server = setupServer();

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

server.events.on("request:start", ({ request }) => {
  console.log("MSW intercepted:", request.method, request.url);
});

it("returns the dog facts", async () => {
  server.use(
    http.get("/api/facts", () => {
      console.log("getDogFacts was intercepted by MSW");
      return HttpResponse.json(["fact1", "fact2"], { status: 200 });
    })
  );
  const result = await getDogFacts();
  expect(result).toStrictEqual(["fact1", "fact2"]);
});
```

But it looks like the MSW never intercepted the request, the test fails with the error:

```sh
 FAIL  src/DogService.test.ts
  ✕ returns the dog facts (33 ms)

  ● returns the dog facts

    AxiosError: Network Error

      at XMLHttpRequest.invoke (node_modules/axios/lib/adapters/xhr.js:163:14)
      at XMLHttpRequest.call (node_modules/@mswjs/interceptors/lib/node/chunk-JCWVLTP7.js:337:20)
      at Proxy.call (node_modules/@mswjs/interceptors/lib/node/chunk-JCWVLTP7.js:176:29)
      at XMLHttpRequestController.trigger (node_modules/@mswjs/interceptors/lib/node/chunk-JCWVLTP7.js:579:16)
      at XMLHttpRequestController.errorWith (node_modules/@mswjs/interceptors/lib/node/chunk-JCWVLTP7.js:547:10)
      at XMLHttpRequestController.xhrRequestController.onRequest (node_modules/@mswjs/interceptors/lib/node/chunk-JCWVLTP7.js:696:32)
```

### Current behavior

Test is failing

### Expected behavior

MSW intercept the request correctly returning the mocked response and test pass.

**Comment by niksimFS24** [comment]
Having the same problem... None of the `axios` calls are being intercepted with 2.0 version 🤷

**Comment by akanoce** [comment]
Same, but only mocks defined during `setupServer` are working.
Every other mock defined using `use` inside the tests is not.
I can clearly see new mocks being added to the handlers via `server.listHandlers()` but the network calls are not intercepted.
The server instance where i'm running use is the same i used to setup the server.

**Comment by niksimFS24** [comment]
@akanoce For me those in `setupServer` do not work either even though logging `server` instance shows all handlers registered in it. 🤔

**Comment by rostgoat** [comment]
same here.. after migrating to 2.0.0, axios is not intercepted. using `setupServer` in jest tests on a React NX monorepo

**Comment by ddolcimascolo** [comment]
I was going to start migrating my apps to v2, then I found this :(

@kettanaito Can you confirm this is an issue with v2? To be honest I doubt basic request interception don't work, but with CRA you never know...

**Comment by kivvvvv** [comment]
I'm experiencing almost the same problem, but I always got "Network Error" on any axios call on Jest.

Though, the same call, same URL, same MSW handlers, work properly on the service worker that is setup with `setupWorker()`.

**Comment by virendave96** [comment]
I'm facing the same.

**Comment by sauldeleon** [comment]
Having the same issue in a Nextjs app within an NX monorepo

Verified that `server.listHandlers()` contains my desired handler to be tested, but NetworkError appears instantly

![image](https://github.com/mswjs/msw/assets/2400723/42209999-cdda-419b-ad2c-d17e13e52afd)

**Comment by sauldeleon** [comment]
done a bit of debugging and... to throw more light into this, despite I dont know if it will help or not.

My config is as follows:
- I have the polyfills added to jest setup.
- Im using node > 18
- I have the `customExportConditions: ['']` property set

I have set a breakpoint in the file `node_modules/msw/lib/node/index.js`, line 81, and other in the catch block

![image](https://github.com/mswjs/msw/assets/2400723/00bb11d0-8219-4919-8b5d-500113e22ffc)

Basically, when launching the tests, I get the following:

![image](https://github.com/mswjs/msw/assets/2400723/69930223-6db4-48c5-bf2a-36c8f2d41117)

```
The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
```

But I have absolutelly no idea why this happens...

After this, the network error happens.

So, I have modified the code as follows:

```ts

        try {
          (0, import_node_events.setMaxListeners)(
            Math.max(import_node_events.defaultMaxListeners, this.currentHandlers.length),
            request.signal
          );
        } catch (error) {
          if (!(isNodeException(error) && error.code === "ERR_INVALID_ARG_TYPE")) {
            console.log(error.toString());
          }
        }
        
```

And the tests works. But Im pretty sure this is there for a good reason, and Im breaking something else...

Edit: Possibly related with https://github.com/mswjs/msw/issues/1785

**Comment by mattcosta7** [comment]
I believe this test was supposed to be validating a fix for this issue.

https://github.com/mswjs/msw/blob/88c45ea5295fa7a47a943311dff65c99ebb3111e/test/node/regressions/many-request-handlers-jsdom.test.ts#L1-L10

@sauldeleon if you have a scenario ready, I 'd be curious what `error` and `error.code` are in your case since it seems this check may need to be extended to account for other cases

https://github.com/mswjs/msw/blob/88c45ea5295fa7a47a943311dff65c99ebb3111e/src/node/utils/isNodeException.ts#L9

it wouldn't surprise me if `error` is not actually `instanceof Error` and maybe we're "good enough" to just check `error.code && error.code === 'ERR_INVALID_ARG_TYPE'`

if you modify that catch block check as such does it intercept properly?

```ts
- if (!(isNodeException(error) && error.code === "ERR_INVALID_ARG_TYPE")) {
+ // not sure if we need all of this to make typescript happy but being explicit
+ if (!(error && typeof error === 'object' && 'code' in error && error.code === "ERR_INVALID_ARG_TYPE")) {
    throw error
}
```

**Comment by Ladrillo** [comment]
I think I am having the same issue where Axios requests don't seem to be intercepted. Reproduction repository [HERE](https://github.com/Ladrillo/axios-problem-msw2).

**Comment by OlgaYasn** [comment]
I have the same issue  of "code: 'ERR_INVALID_ARG_TYPE'" but I am not using axios in my project, just fetch.

**Comment by mattcosta7** [comment]
https://github.com/mswjs/msw/pull/1813

I think this patch may fix the issue - but don't have the time at the moment to validate it

**Comment by Ladrillo** [comment]
@mattcosta7 The patch does fix the Axios issue in my repro [repo](https://github.com/Ladrillo/axios-problem-msw2)! 🥳

It also fixes [THIS](https://github.com/mswjs/msw/issues/1785) other issue. (The "eventTargets" argument etc error.)

Thank you!

**Comment by sauldeleon** [comment]
sorry @mattcosta7 for checking it late. Let me give it a try and I will edit this message. Thanks!

`error`

```
code: 'ERR_INVALID_ARG_TYPE'
message: 'The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal'
stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal\n    at new NodeError (node:internal/errors:405:5)\n    at EventEmitter.setMaxListeners (node:events:330:17)\n    at SetupServerApi.<anonymous> (/Users/sauldeleon/Projects/bonhams/nx/node_modules/msw/lib/node/index.js:83:50)\n    at Generator.next (<anonymous>)\n    at /Users/sauldeleon/Projects/bonhams/nx/node_modules/msw/lib/node/index.js:36:61\n    a…Format (/Users/sauldeleon/Projects/bonhams/nx/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at async jestAdapter (/Users/sauldeleon/Projects/bonhams/nx/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at async runTestInternal (/Users/sauldeleon/Projects/bonhams/nx/node_modules/jest-runner/build/runTest.js:367:16)\n    at async runTest (/Users/sauldeleon/Projects/bonhams/nx/node_modules/jest-runner/build/runTest.js:444:34)'
Symbol(kIsNodeError): true
toString: ƒ value() {\n          return `${this.name} [${key}]: ${this.message}`;\n        }
[[Prototype]]: Error
```

can confirm as well as @Ladrillo that that line fixes the issue

**Comment by kettanaito** [comment]
## Released: v2.0.2 🎉

This has been released in v2.0.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.0.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.0.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by niksimFS24** [comment]
Still getting `Network error` even with `2.0.2` version. Anyone else?

**Comment by weyert** [comment]
@niksimFS24 I would suggest to make repro so someone can debug it

**Comment by sauldeleon** [comment]
Removed node_modules, clean install of msw 2.0.2 and in my scenario I got the error removed. So can confirm in my scenario axios is working again. Thanks everybody!

**Comment by marciolima-pray** [comment]
Guys, I'm facing the same issue even after removing `node_modules` and installing `msw@^2.0.2`.

My environment:
```
Node: v18.15.0
System: MacBook M1
```

Dependencies:
```
"@testing-library/jest-dom": "^6.1.4",
"@testing-library/react": "^14.0.0",
"jest": "^29.7.0",
"msw": "^2.0.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
```

Here's a portion of my test related to the msw setup:

```js
import { HttpResponse, http } from 'msw';
import { setupServer } from 'msw/node';
import '@testing-library/jest-dom';

const endpoint = (uri) => new URL(uri, 'https://api.example.com').toString();

const handlers = [
  http.get(endpoint('/posts'), () => {
    return HttpResponse.json([
      { title: 'Post 1' },
    ]);
  }),
];

const server = setupServer(...handlers);

server.events.on('request:start', ({ request }) => {
  console.log('MSW intercepted:', request.method, request.url); // <-- this line never runs
});

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

describe('Posts Component', () => {
  it('displays posts', async () => {
    render(<Posts />, { wrapper: MockProviders });

    const post = await screen.findByText('Post 1');

    expect(post).toBeInTheDocument();
  });
});

// `MockProviders` creates the `QueryClientProvider` with the config of `retry: false`.
```

This is a simplified version of the Posts component:

```jsx

const api = axios.create({
  baseURL: 'https://api.example.com',
});

export default function Posts() {

  async function fetchPosts() {
     const response = await api.get('/posts');

     return response.data;
  }

  const { data } = useQuery({
    queryKey: ['posts'],
    queryFn: () => fetchPosts(),
  });
  
  return (
     <ul>
        {data.map((post) => (
          <li key={post.id}>{post.title}</li>
        ))}
     </ul>
  )
}
```

Because of this issue I had to switch to another API mocking solution in the meantime and it's working with pretty much the same setup. However, I would like to use `msw` instead and will surely move to it once this issue gets fixed.

**Comment by weyert** [comment]
@marciolima-praycom can you make a repro that shows this problem to ease the reproducing of your issue? That would speed things up

**Comment by marciolima-pray** [comment]
> @marciolima-praycom can you make a repro that shows this problem to ease the reproducing of your issue? That would speed things up

@weyert When I created a separate project to reproduce the issue, it actually seemed to partially work. By partially I mean that I can see the request being intercepted by `msw` but it doesn't return the mocked JSON response body. My actual environment uses yarn workspaces. There I don't even see the request being intercepted at all, as I mentioned above. Not sure if it could be related to the monorepo setup.

Anyways, I created this small project to reproduce the issue where the intercepted request seems to return an empty string instead of the mocked JSON object.

> https://github.com/marcioferlan/msw-axios-issue

Please let me know if you have any questions.

**Comment by weyert** [comment]
thanks, will have a look over the weekend. Got to do a work release on Friday afternoon :D

**Comment by OleksandrKucherenko** [comment]
```
"TypeError: Cannot read properties of null (reading 'setMaxListeners')
    at EventEmitter.setMaxListeners (node:events:312:34)
    at SetupServerApi.<anonymous> (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/msw/lib/node/index.js:83:50)
    at Generator.next (<anonymous>)
    at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/msw/lib/node/index.js:36:61
    at new Promise (<anonymous>)
    at __async (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/msw/lib/node/index.js:20:10)
    at _Emitter.<anonymous> (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/msw/lib/node/index.js:80:44)
    at emitAsync (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/node/chunk-5PTPJLB7.js:50:20)
    at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/node/chunk-YVNH3GJ5.js:290:40
    at until (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@open-draft/until/src/until.ts:23:24)
    at _NodeClientRequest.end (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/node/chunk-YVNH3GJ5.js:284:18)
    at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:134:22
    at _NodeClientRequest.write (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/node/chunk-YVNH3GJ5.js:253:35)
    at RedirectableRequest.Object.<anonymous>.RedirectableRequest.write (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:103:26)
    at RedirectableRequest.Object.<anonymous>.RedirectableRequest.end (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:132:10)
    at dispatchHttpRequest (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/adapters/http.js:401:11)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/dist/common.js:149:22
    at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/dist/api.js:1740:133
    at askGPT (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/clis/gpt/src/gpt.ts:103:20)
```

I see this stack trace with the msw 2.0.3

**Comment by mattcosta7** [comment]
> ```
> "TypeError: Cannot read properties of null (reading 'setMaxListeners')
>     at EventEmitter.setMaxListeners (node:events:312:34)
>     at SetupServerApi.<anonymous> (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/msw/lib/node/index.js:83:50)
>     at Generator.next (<anonymous>)
>     at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/msw/lib/node/index.js:36:61
>     at new Promise (<anonymous>)
>     at __async (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/msw/lib/node/index.js:20:10)
>     at _Emitter.<anonymous> (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/msw/lib/node/index.js:80:44)
>     at emitAsync (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/node/chunk-5PTPJLB7.js:50:20)
>     at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/node/chunk-YVNH3GJ5.js:290:40
>     at until (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@open-draft/until/src/until.ts:23:24)
>     at _NodeClientRequest.end (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/node/chunk-YVNH3GJ5.js:284:18)
>     at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:134:22
>     at _NodeClientRequest.write (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/@mswjs/interceptors/lib/node/chunk-YVNH3GJ5.js:253:35)
>     at RedirectableRequest.Object.<anonymous>.RedirectableRequest.write (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:103:26)
>     at RedirectableRequest.Object.<anonymous>.RedirectableRequest.end (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/follow-redirects/index.js:132:10)
>     at dispatchHttpRequest (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/adapters/http.js:401:11)
>     at new Promise (<anonymous>)
>     at httpAdapter (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/adapters/http.js:48:10)
>     at dispatchRequest (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
>     at Axios.request (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
>     at Function.wrap [as request] (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
>     at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/dist/common.js:149:22
>     at /Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/node_modules/openai/dist/api.js:1740:133
>     at askGPT (/Users/o.kucherenko2/workspace/gitlabs/gpt.md.translate/clis/gpt/src/gpt.ts:103:20)
> ```
> 
> I see this stack trace with the msw 2.0.3
> 

Can you share more about your test setup here?

This error says EventEmitter.setMaxListeners is not defined and I'm unfamiliar with a supported environment where that should be true - and want to understand a bit better

**Comment by marciolima-pray** [comment]
> > @marciolima-praycom can you make a repro that shows this problem to ease the reproducing of your issue? That would speed things up
> 
> @weyert When I created a separate project to reproduce the issue, it actually seemed to partially work. By partially I mean that I can see the request being intercepted by `msw` but it doesn't return the mocked JSON response body. My actual environment uses yarn workspaces. There I don't even see the request being intercepted at all, as I mentioned above. Not sure if it could be related to the monorepo setup.
> 
> Anyways, I created this small project to reproduce the issue where the intercepted request seems to return an empty string instead of the mocked JSON object.
> 
> > https://github.com/marcioferlan/msw-axios-issue
> 
> Please let me know if you have any questions.

@mattcosta7 I shared a demo project where the issue can be reproduced. You can see my test setup on it. But I'm basically using `react-scripts` to run the tests with the following script:

`"react-scripts test --watchAll --transformIgnorePatterns \"node_modules/(?!@bundled-es-modules)/\""`

And in `src/setupTests.js` I have the folowing code:

```js
import '@testing-library/jest-dom';
import 'whatwg-fetch';

import { TextEncoder, TextDecoder } from 'util';

global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
```

Other than that, I don't have any other specific configuration related to the tests.

**Comment by OleksandrKucherenko** [comment]
> Can you share more about your test setup here?

MacOS, Intel, node 16, node 18, yarn 3.5, monorepo - https://github.com/OleksandrKucherenko/chatgpt-translate-md

p.s. after several "full cleanups" tests start working as expected, the root cause was the test files in packages `dist` folder that jest tries to execute (packages/*/*.test.ts --> packages/dist/*.test.js).

**Comment by mattcosta7** [comment]
> > > [@marciolima-praycom](https://github.com/marciolima-praycom) can you make a repro that shows this problem to ease the reproducing of your issue? That would speed things up
> > 
> > 
> > [@weyert](https://github.com/weyert) When I created a separate project to reproduce the issue, it actually seemed to partially work. By partially I mean that I can see the request being intercepted by `msw` but it doesn't return the mocked JSON response body. My actual environment uses yarn workspaces. There I don't even see the request being intercepted at all, as I mentioned above. Not sure if it could be related to the monorepo setup.
> > Anyways, I created this small project to reproduce the issue where the intercepted request seems to return an empty string instead of the mocked JSON object.
> > > https://github.com/marcioferlan/msw-axios-issue
> > 
> > 
> > Please let me know if you have any questions.
> 
> [@mattcosta7](https://github.com/mattcosta7) I shared a demo project where the issue can be reproduced. You can see my test setup on it. But I'm basically using `react-scripts` to run the tests with the following script:
> 
> `"react-scripts test --watchAll --transformIgnorePatterns \"node_modules/(?!@bundled-es-modules)/\""`
> 
> And in `src/setupTests.js` I have the folowing code:
> 
> import '@testing-library/jest-dom';
> import 'whatwg-fetch';
> 
> import { TextEncoder, TextDecoder } from 'util';
> 
> global.TextEncoder = TextEncoder;
> global.TextDecoder = TextDecoder;
> Other than that, I don't have any other specific configuration related to the tests.

I'm not aware of any way to override the files that need to be overriden with create-react-app because `setupTests` is going to run after environment and not before it is setup (in jest this is `setupFilesAfterEvironment` and not `setupFiles`.

You might be able to customize your jest config if you use `jest` directly and not through `react-scripts` but will also need to copy some config to make that work?
