### ISSUE TITLE
Add option to reduce warnings for un-intercepted requests

### ISSUE THREAD

**Issue by mkarajohn** [kettanaito/msw#1811]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Right now MSW warns about every single request that goes through and does not have a corresponding mock handler. This ends up "polluting" the Warnings section of the console, making it difficult to notice other kinds of warnings.

There should be an option the user can pass to `setupWorker` in order to silence these kind of warnings.

I can make a PR for this if it's accepted as an issue and a solution strategy is proposed

**Comment by kettanaito** [comment]
Hi, @mkarajohn. Thanks for raising this. 

You can use the `onUnhandledRequest` option of the `worker.start()` / `server.listen()` to control which requests produce the unhandled request warning. Here's an example:

```js
worker.start({
  onUnhandledRequest(request, print) {
    // Only print the unhandled request warning if the
    // intercepter request's URL contains the string "foo".
    if (request.url.includes('foo')) {
      return print.warning()
    }

    // Otherwise, do nothing. 
  } 
})
```

> Learn more about the [`onUnhandledRequest` option](https://mswjs.io/docs/api/setup-worker/start#onunhandledrequest). It behaves identically for `worker`/`server`. 

You can also use the same option to control whether you want a warning, an error, or disable the unhandled request notifications altogether.

**Comment by mkarajohn** [comment]
Oh, man, feeling so stupid now; I was so close to this when I looked up the docs, yet I missed it :sweat_smile: The lesson is to not open issues on 4am :D
Cheers man
