### ISSUE TITLE
Axios FormData upload broken in v2

### ISSUE THREAD

**Issue by pschyma** [kettanaito/msw#1835]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v18.18.2

### Reproduction repository

https://github.com/pschyma/msw-examples/tree/axios-formdata-reproducer

### Reproduction steps

```
cd examples/with-vitest
npm install
npm test
```

### Current behavior

I'm not sure where the issue is, but as msw v2 triggered this issue for me, I'll start here.

After updating to msw 2 `FormData` upload via Axios stops working due to missing `boundary` in `Content-Type` header.

Headers observed when posting data with fetch:
```
{
  'content-type' => {
    name: 'content-type',
    value: 'multipart/form-data; boundary=----formdata-undici-088515513855'
  }
}
```
Headers observed when posting data with Axios:
```
{
  'content-type' => {
    name: 'content-type',
    value: 'multipart/form-data'
  }
}
```

### Expected behavior

Axios requests behave like when msw < 2 is used and provide the `boundary` in headers.

In previous msw version, I used `parse-multipart-data` to extract the `boundary` from request headers and for parsing the text content of that request.

**Comment by bignamehere** [comment]
I believe there is a CVE based on why you are no longer seeing this data:  https://github.com/axios/axios/issues/6006

axios 1.5.0 was the last working version with msw, and the axios 1.5.1 update breaks our Testing.

**Comment by kettanaito** [comment]
Hi, @pschyma. Thanks for reporting this. 

I looked at your reproduction example and it looks okay. More to that, if it works with `fetch` and breaks with Axios, then I assume this is an Axios' issue. 

MSW does not control/polyfill/affect/modify the `FormData` behavior. It's implemented by `undici` in Node.js and you can see that the same Undici (global `fetch`) appends the `boundary` to the `Content-Type` header correctly. 

Our [integration test for `FormData`](https://github.com/mswjs/msw/blob/461a1885280451ec0837fdce897f49521b8ff260/test/node/rest-api/request/body/body-form-data.node.test.ts#L26-L28) is passing so it's unlikely there's an issue with MSW. 

I recommend you create an issue in the Axios repo and share the team's response with us here so others can learn from it too. Thanks.

**Comment by pschyma** [comment]
Hi, thanks for the quick reaction.

> I recommend you create an issue in the Axios repo and share the team's response with us here so others can learn from it too. Thanks.

Done. The Axios team adapted their code, so everything should be working again when the change gets released.

**Comment by kettanaito** [comment]
Incredible collaboration! Thank you, @pschyma!
