### ISSUE TITLE
React Native: "Unable to resolve module http"

### ISSUE THREAD

**Issue by jeltehomminga** [kettanaito/msw#1841]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.9.0

### Reproduction repository

https://github.com/jeltehomminga/ReactNativeMsw2

### Reproduction steps

First of all thanks for the amazing library. Great work! B esides using msw for our web apps we have been also using it for react native which has really been helpfull, especially in situation when acceptance was down.

Unfortunately since ugrade to v2 mocking is not wokring anymore for React Native. I can see that the docs have been changed. In the faq section it is not mentioned anymore to import setupServer from 'msw/native' , so I guess should use 'msw/node' instead?

I tried both, but unfortunately no luck

In example repo I use 'msw/node'  which I guess is what the docs suggest

reproduce:

`npm i`

`npx react-native run-ios `

output:

> error: Error: Unable to resolve module http from /Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/@mswjs/interceptors/lib/node/chunk-YVNH3GJ5.js: http could not be found within the project or in these directories:
  node_modules
  12 |
  13 | // src/interceptors/ClientRequest/index.ts
> 14 | var _http = require('http'); var _http2 = _interopRequireDefault(_http);
     |                                                                   ^
  15 | var _https = require('https'); var _https2 = _interopRequireDefault(_https);
  16 |
  17 | // src/interceptors/ClientRequest/NodeClientRequest.ts
    at ModuleResolver.resolveDependency (/Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (/Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._addDependency (/Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 3)
    at async Graph._processModule (/Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/Users/jeltehomminga/coding/ReactNativeMsw2/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 13)

I guess the issue is with 

> http could not be found within the project or in these directories:
> node_modules

also looked if I could find something for http polyfill, but no luck. The new version looks good to me, so I hope it's possible to also use it for React Native like in v1

### Current behavior

cli error:

> http could not be found within the project or in these directories:
> node_modules

![CleanShot 2023-11-08 at 11 29 33@2x](https://github.com/mswjs/msw/assets/35220102/dcd0d5f3-6414-4447-a07e-7a3b56aa17bd)

### Expected behavior

no errors, result of mock on the screen

**Comment by kettanaito** [comment]
Thanks for reporting this, @jeltehomminga. May be a build config issue. Afaik, `http` doesn't exist in React Native, and MSW has been using `XMLHttpRequest` as the primary interception mechanism. What I'd do to check:

- Look at `tsup.config.ts` and see if Node.js standard modules are properly excluded;
- Examine the MSW build at `/lib/native` to see if it requires/imports `http` by mistake;
- Check the entrypoint at `src/native/index.ts` and its interceptor to make sure it only uses `XMLHttpRequestInterceptor` from the `@mswjs/interceptors` package.

**Comment by mattcosta7** [comment]
> In example repo I use 'msw/node' which I guess is what the docs suggest

I think you should be using `msw/native` - which I believe may fail currently related to: https://github.com/mswjs/msw/issues/1847

**Comment by mattcosta7** [comment]
here:  

https://github.com/jeltehomminga/ReactNativeMsw2/blob/26f26ee03283c016d08527bc74a4e9dcc94f96fa/msw/server.ts#L1-L5


Should probably be 

```diff
- import {setupServer} from 'msw/node';
+ import {setupServer} from 'msw/native';
import {handlers} from './handlers';

// Setup requests interception using the given handlers.
export const server = setupServer(...handlers);

```

**Comment by jeltehomminga** [comment]
> Thanks for reporting this, @jeltehomminga. May be a build config issue. Afaik, `http` doesn't exist in React Native, and MSW has been using `XMLHttpRequest` as the primary interception mechanism. What I'd do to check:
> 
> * Look at `tsup.config.ts` and see if Node.js standard modules are properly excluded;
> * Examine the MSW build at `/lib/native` to see if it requires/imports `http` by mistake;
> * Check the entrypoint at `src/native/index.ts` and its interceptor to make sure it only uses `XMLHttpRequestInterceptor` from the `@mswjs/interceptors` package.

I have used the default starter from the https://reactnative.dev/ , unfortunately cannot find a tsup.config.ts file in the project at all. 

Could it be the issue is related to the fact that in the new version we have to import http to do http.get for the handlers, while before it was rest.get ?

if we now have to use http for the handlers, but it doesn't exist in React Native could that then be the problem. Was the new version intended to work on React Native. If so is there maybe an example available that works with RN?

**Comment by jeltehomminga** [comment]
> > In example repo I use 'msw/node' which I guess is what the docs suggest
> 
> I think you should be using `msw/native` - which I believe may fail currently related to: #1847

yes tried that first, but then saw the docs have changed and it doesn't mention using 'msw/native' anymore

when I do try with msw/native I get a different error message. Something like that property location cannot be found

**Comment by kettanaito** [comment]
Thanks for pointing that out, @mattcosta7!

@jeltehomminga, I've added the [React Native integration](https://mswjs.io/docs/integrations/react-native) page to the docs. It's likely incomplete but together we can make it perfect. Please follow it and report any missing pieces. 

I also recommend you open a new issue for the `location cannot be found` error you are experiencing. Thanks.

**Comment by kettanaito** [comment]
@jeltehomminga, I've found an already reported issue for `location cannot be found` here https://github.com/mswjs/msw/issues/1777. I've opened a fix and will release new MSW that fixes this today.

**Comment by mattcosta7** [comment]
@jeltehomminga 

> if we now have to use http for the handlers, but it doesn't exist in React Native could that then be the problem. Was the new version intended to work on React Native. If so is there maybe an example available that works with RN?

This is different sets of `http`

`import {http} from "msw"` is the method to mock requests over the network

`import http from 'node:http'` is the error you saw with http not defined, which is node's http communication module.


the msw http is defined and doesn't rely on anything signfiicant, since it is mostly designed to create object 'handlers' to match and handle requests. 


I got your tests running locally this morning. Using msw 2.0.3, as your reproduction does. 

After modifying your tests to use `msw/native` instead of `msw/node` I received a few errors from `undici` because you're defining fetch with relative urls instead of absolute ones.

Relative urls don't make sense in react-native, because the app doesn't run on a url (afaik)

https://github.com/jeltehomminga/ReactNativeMsw2/blob/26f26ee03283c016d08527bc74a4e9dcc94f96fa/App.tsx#L69

```diff
-      const response = await fetch('/user');
+      const response = await fetch('https://example.com/user');
```


https://github.com/jeltehomminga/ReactNativeMsw2/blob/26f26ee03283c016d08527bc74a4e9dcc94f96fa/msw/handlers.ts#L7

```diff
- http.get('/user', () => {
+ http.get('https://example.com/user', () => {
```

It's likely the case you'd want to put some other full urls here, but these are just samples to get the tests completing
