### ISSUE TITLE
Tests not terminating after execution with msw when using FormData and Blob

### ISSUE THREAD

**Issue by tokuhirom** [kettanaito/msw#1843]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

21.1.0

### Reproduction repository

https://github.com/tokuhirom/msw-formdata-issue

### Reproduction steps

npm test

### Current behavior

I'm encountering an issue where the process does not terminate after running tests with `msw` when using `FormData` and `Blob`. Removing the line where the `Blob` is appended to the `FormData` allows the tests to terminate as expected.

Below is a simplified test case to illustrate the issue:

```
~/work/msw-formdata-issue/ npm test

> msw-formdata-issue@1.0.0 test
> mocha



  test
{}
    ✔ test


  1 passing (22ms)
```

When the above code is executed, the process does not terminate after running the test. However, if the line with `formData.append(...)` is commented out, the process terminates correctly. It seems that the use of FormData in combination with Blob in msw setup is causing some resources to not be released properly.

### Expected behavior

exit the process after running all tests.

**Comment by tokuhirom** [comment]
When I comment out `formData.append("file", new Blob(["testdata"], { type: "text/plain" }));`, the process exits after run.

**Comment by kettanaito** [comment]
Hi, @tokuhirom. Thanks for reporting this! 

The issue seems to be related to `FormData` and its `append` method (edit: any method that results in a non-empty post data). MSW doesn't control/polyfill that in any way. I suggest you raise this in [Undici](https://github.com/nodejs/undici), which is the fetch implementation in Node.js. They may have a bug there. Thanks.

**Comment by himself65** [comment]
I'm seeing this error again without formdata
