### ISSUE TITLE
MSW 'delay' never completes when using Cypress to mock timers (cy.clock)

### ISSUE THREAD

**Issue by rstoneIDBS** [kettanaito/msw#1848]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/rstoneIDBS/cypress-msw-delay-issue

### Reproduction steps

See readme in the attached repo.

Essentially if you include an `await delay()` call in a handler and you have a Cypress test that makes use of `cy.clock()` to mock timers, then the `await delay()`` call never resolves and the response is not returned.

### Current behavior

`await delay()` never returns if `cy.clock()` is used in a Cypress test that makes a call to an endpoint including the `await delay()`

### Expected behavior

Prior to 2.0.x this functionality worked, so it would be nice if it worked again. 

Looking at the new 'delay.ts' code in MSW shows it makes use of setTimeout, so I'm guessing it is affected by the Cypress mocking. The old code (1.3.2) appears to use a different mechanism to inject the delay into the response.

New code: https://github.com/mswjs/msw/blob/15e3006cdbcf1d23312252960ee2920d2011d1bb/src/core/delay.ts#L69

Old code: https://github.com/mswjs/msw/blob/2f7215294cac98149757f57118c7492d31a2a8e0/src/context/delay.ts#L69

**Comment by kettanaito** [comment]
Hey, @rstoneIDBS. Thanks for reporting this. 

> Prior to 2.0.x this functionality worked, so it would be nice if it worked again.

This is only partially true. What I'm afraid is happening here is Cypress mocking too many things in `cy.clock`, which prevents proper request/response reading. At least, that was a common issue in Node.js with `jest.useFakeTimers`. This needs investigation.  

> The old code (1.3.2) appears to use a different mechanism to inject the delay into the response.

This is incorrect. The `res.delay` is just an abstraction that still used `setTimeout` using the `res.delay` value as the timeout duration. The implementation is the same here. What changed is that MSW 2.0 relies more on standards, and that breaks some things in third-party packages (surprisingly).

**Comment by kettanaito** [comment]
If anyone wants to help here, the first step would be to look at the implementation for `cy.clock()` and see what exactly it's doing. Share it here to progress this discussion.

**Comment by rstoneIDBS** [comment]
Looks like Cypress use sinonjs fakeTimers:
https://github.com/cypress-io/cypress/blob/a23dba19af00516e0ef69fb61d17ec6c4b6b595a/packages/driver/src/cypress/clock.ts#L2

which appear to mock out everything:
https://github.com/sinonjs/sinon/blob/adcf936de0e946e2b72a513436c0469319f3da79/lib/sinon/util/fake-timers.js#L80

**Comment by kettanaito** [comment]
@rstoneIDBS, I believe that's partially the answer: since `cy.clock()` stops any `setTimeout`, which is how `delay()` is implemented, you have to progress the clock to make the `delay()` call in your request handler resolve.

Try adding `cy.tick(...)` after [this line](https://github.com/rstoneIDBS/cypress-msw-delay-issue/blob/main/src/App.cy.jsx#L10) in your Cypress test. Does that work?

**Comment by kettanaito** [comment]
I can confirm that progressing the timer via `cy.tick()` works, making both tests pass. Here's how the test with `delay()` should look like:

```diff
it('requests data (delay)', () => {
  cy.clock()
  cy.mount(<App />)
  cy.tick(11000)
  cy.get('#with-delay').click()
+ cy.tick(1000)
  cy.get('#data').contains('["Tom","Jerry","Spike"]')
})
```

This isn't an issue with MSW, it's an incomplete intention. You mock the timers via `cy.clock()` but also use `delay()` from MSW, which implies that you want a _timeout_ to occur when handling the request. You must call `cy.tick()` to progress the stubbed timers and make `delay()` Promise resolve that way.

**Comment by rasto68** [comment]
Ah sorry, my repro was incomplete. Our actual tests include multiple calls to cy.tick so I'm not sure why they fail. Will have a look when I'm back in work. It might be because we have multiple rest/graphql calls being made by each test, each one is being handled by MSW handlers and all of them include 'delay' calls. One option would be to remove these 'delay' calls as we only really need them when running the app in "local dev" mode and not when running cypress component tests.

I wonder if it might be worth mentioning something in your "delay" documentation about this to warn about interactions with fake timers?

**Comment by kettanaito** [comment]
> I wonder if it might be worth mentioning something in your "delay" documentation about this to warn about interactions with fake timers?

I don't think this is necessary. It's implied when you use fake timers that you become in charge of them (that's the whole purpose). Let's see if others experience a similar issue, perhaps then we will find a proper phrasing to prevent confusion.
