### ISSUE TITLE
Sending corrupted Blob breaks requests

### ISSUE THREAD

**Issue by flosincapite** [kettanaito/msw#1859]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.9.0

### Reproduction repository

https://github.com/flosincapite/msw-node-bug

### Reproduction steps

```
git clone https://github.com/flosincapite/msw-node-bug
cd msw-node-bug
npm install
npm test
```

### Current behavior

In these tests, I attempt to send arbitrary binary blobs in a request body.

I POST that request.

In a test, I set up an msw server and try to assert that the blob sent in the request is the one received by the server.

In most cases (I've put one working example in `good_blob.txt`), this works fine.

However, if the blob contains certain control characters (as seen in `bad_blob.txt`), the data gets corrupted.

### Expected behavior

I would expect the request body not to be corrupted. I've tested this exact payload (`bad_blob.txt`) against Express and Flask servers, and the data is not corrupted.

**Comment by kettanaito** [comment]
Hi, @flosincapite. Thanks for reporting this. 

I added your use cases as integration tests to MSW in https://github.com/mswjs/msw/pull/1861 and both good and bad blobs are passing without issues. 

I've noticed you are using an old version of MSW in your repo (in fact, an _extremely_ [old version](https://github.com/flosincapite/msw-node-bug/blob/7109113c22f6474184219eaa74c01e93bcc103bb/package.json#L12)). I highly recommend you upgrade to `msw@latest` (see the [Announcement post](https://mswjs.io/blog/introducing-msw-2.0)). It relies on the global Fetch API that implements Blobs, among other things, correctly. Once you upgrade, your issue will be fixed.

**Comment by flosincapite** [comment]
Ah! Okay, apologies, I hadn't realized I wasn't on the latest version.
Thanks!

**Comment by kettanaito** [comment]
## Released: v2.0.7 🎉

This has been released in v2.0.7!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.0.7)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.0.7)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by kettanaito** [comment]
@flosincapite, no worries! Let me know how it goes once you update.

**Comment by flosincapite** [comment]
Alright! I have updated and things are working smoothly. Thank you, and apologies for the noise!

**Comment by kettanaito** [comment]
@flosincapite, happy to hear all's fine now! 🚀
