### ISSUE TITLE
`A jest worker process (pid=135769) was terminated by another process: signal=SIGSEGV, exitCode=null.`

### ISSUE THREAD

**Issue by hugotiburtino** [kettanaito/msw#1873]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v18.16.0

### Reproduction repository

https://github.com/serlo/api.serlo.org/pull/1126

### Reproduction steps

1. `git clone https://github.com/serlo/api.serlo.org.git`
2. `cd api.serlo.org`
3. `git checkout dependabot/npm_and_yarn/msw-2.0.8`
4. `yarn`
5. `yarn test`

### Current behavior

```
FAIL  __tests__/schema/notification.ts
  ● Test suite failed to run

    A jest worker process (pid=135769) was terminated by another process: signal=SIGSEGV, exitCode=null. Operating system logs may contain more information on why this occurred.

      at ChildProcessWorker._onExit (node_modules/jest/node_modules/jest-worker/build/workers/ChildProcessWorker.js:370:23)
```
As you can see in https://github.com/serlo/api.serlo.org/pull/1126 in msw version 2.0.6 it worked fine, so something was added in version 2.0.7 or 2.0.8 that broke it.

### Expected behavior

Tests run

**Comment by kettanaito** [comment]
Thanks for reporting this. Looks like a direct duplicate of #1868.
