### ISSUE TITLE
Bump "typescript": ">= 4.7.x <= 5.2.x" to "typescript": ">= 4.7.x <= 5.3.x"

### ISSUE THREAD

**Issue by AdrienFromToulouse** [kettanaito/msw#1875]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Following recent typescript upgrade would be nice to upgrade the peer dep requirement so that build do not break.

**Comment by epreston** [comment]
Maybe swapping it to `^4.7.x || ^5.2.x` is closer to what you want ?

```
  "peerDependencies": {
    "typescript": "^4.7.x || ^5.2.x"
  },
```

Constraint will be satisfied by versions matching: `>=4.7.0 <5.0.0-0 || >=5.2.0 <6.0.0-0.`

This is not the shortest way to write this constraint but I feel it is the clearest.  
It meets these goals.
- Version 4 typescript should be modern.
- Version 5 typescript should be modern.

Confirmed with: https://jubianchi.github.io/semver-check/#/^4.7.x%20||%20^5.2.x/6.0

**Comment by JANA-itsaishvili** [comment]
can we get this on 1.3.2 as well, please

**Comment by mattcosta7** [comment]
> Maybe swapping it to `^4.7.x || ^5.2.x` is closer to what you want ?
> 
> ```
>   "peerDependencies": {
>     "typescript": "^4.7.x || ^5.2.x"
>   },
> ```
> 
> Constraint will be satisfied by versions matching: `>=4.7.0 <5.0.0-0 || >=5.2.0 <6.0.0-0.`
> 
> This is not the shortest way to write this constraint but I feel it is the clearest. It meets these goals.
> 
> * Version 4 typescript should be modern.
> * Version 5 typescript should be modern.
> 
> Confirmed with: [https://jubianchi.github.io/semver-check/#/^4.7.x%20||%20^5.2.x/6.0](https://jubianchi.github.io/semver-check/#/%5E4.7.x%20%7C%7C%20%5E5.2.x/6.0)

This will not be what we want. 

Typescript follows their own version scheme.

x.x.fix

where x.x increment as if they were a single number, and the `fix` is a stepped release that happens rarely (and they traditionally skipped 0 and 1 starting at 2).

so current typescript, `5.3.2` is really `53, stable release, first version`

the only peer dep that would make sense if we don't enforce a specific version would be

`>= version`

**Comment by epreston** [comment]
I see.  In that case, as you suggested, I would like to see a minimum peerDep that is expected or has been tested against.
- If I use a greater version, it's on me.
- Avoid not being able to use latest TS and latest MSW without tool warnings
- Make sure this is not a chore for maintainers

**Comment by ghost** [comment]
Hi! I had hope to see this fixed when seing a new msw minor release (2.0.10). Unfortunately the issue was not adressed.
I there any chance to see a fix defining minimum peerDep but no max as previously suggested?

**Comment by kimwes** [comment]
It's also a possibility to force a dependency to use a specific version https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides like:
```
{ 
  "devDependencies": {
    "msw": "^2.0.0",
    "typescript": "^5.3.3"    
  },
  "overrides": {
    "msw": {
      "typescript": "$typescript"
    }
  }
}
```

**Comment by waiyan13** [comment]
Any update on this issue?

**Comment by kettanaito** [comment]
## Released: v2.0.12 🎉

This has been released in v2.0.12!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.0.12)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.0.12)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by dannyBies** [comment]
Hi @kettanaito thanks for the release!
Would it be possible to release a new 1.x.x version with this PR included? I'm using this on a React-Native project but am unable to upgrade to 2.x.x.

**Comment by kettanaito** [comment]
@dannyBies, pull requests are welcome! 🚀 I don't have the capacity to backport changes to v1 but I have nothing against scoped changes like this one. You can count on my timely review and publishing of it.

**Comment by HassanNaqvi7** [comment]
@kettanaito How can I create a PR for the backport? There seems to be no branch to target to patch the 1.3.2 version

**Comment by kettanaito** [comment]
@HassanNaqvi7, you can checkout the v1.3.2 [tag](https://github.com/mswjs/msw/tree/v1.3.2) and branch from it. On that feature branch, make the changes and ping me to review them. Once they are reviewed, I can make a backport release to v1.

**Comment by SerkanSipahi** [comment]
@kettanaito please review https://github.com/mswjs/msw/pull/2029 support 5.3.x for msw 1.3.x in order to make a backport release.
