### ISSUE TITLE
Jest support through custom environments

### ISSUE THREAD

**Issue by wkeese** [kettanaito/msw#1878]
I see you documented using Jest in https://mswjs.io/docs/faq#requestresponsetextencoder-is-not-defined-jest, and also in https://github.com/mswjs/examples/tree/main/examples/with-jest.

I just wanted to suggest a different way that doesn't require a polyfill or installing undici:

1. npm install `jest-environment-jsdom` and/or `jest-environment-node`.

2. Create a custom Jest environment defining the missing symbols.  For JSDOM I created a file named `jest-environment-jsdom-with-globals.mjs`:

```js
import { TestEnvironment } from "jest-environment-jsdom";

export default class CustomEnvironment extends TestEnvironment {
  async setup() {
    await super.setup();

    // Add globals that are on real browsers and Node 18+, but aren't in Jest's builtin environments.
    this.global.Blob = globalThis.Blob;
    this.global.fetch = globalThis.fetch;
    this.global.File = globalThis.File;
    this.global.FormData = globalThis.FormData;
    this.global.Headers = globalThis.Headers;
    this.global.Request = globalThis.Request;
    this.global.Response = globalThis.Response;
    this.global.TextEncoder = globalThis.TextEncoder;
    this.global.TextDecoder = globalThis.TextDecoder;
  }
}
```

3. Reference it from your jest.config.mjs file:

```js
testEnvironment: "./jest-environment-jsdom-with-globals.mjs"
```

**Comment by kettanaito** [comment]
Hey, @wkeese. Thanks for this suggestion!

You can certainly use a custom Jest environment to work around Jest stripping you off of the Node.js globals. What I want to achieve with the migration guide/docs is an example of minimal entry. This way, anybody can solve the issue without having to know what a custom environment is and how to create one. 

I have nothing against the approach you propose and overall leave it to the developer's best knowledge to resolve this. At this point, it's a Jest thing, not an MSW thing. No change is needed on our end here.

**Comment by bhavyasaggi** [comment]
Jest is being a dumpster fire right now. This solves a lot of problems!!

**Comment by wkeese** [comment]
Thanks, I also think it's the optimal (i.e. easiest to implement / minimal entry / least lines of code) solution as you don't need to pull in Undici, polyfills, etc.
