### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by petera2c** [kettanaito/msw#1899]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.10.0

### Reproduction repository

https://github.com/petera2c/msw-bug-example

### Reproduction steps

yarn test

### Current behavior

the graphql intercept returns an empty body causing the rawRequest from graphql-request to throw an error in the json.parse() response

### Expected behavior

The msw intercepted graphql should respond with this data
```
data: {
        pets: [
          { id: 1, name: "Tom" },
          { id: 2, name: "Jerry" },
          { id: 3, name: "Spike" },
        ],
      },
```

**Comment by mattcosta7** [comment]
closing this one because it's an issue with create react app setup for jest, which mirrors other similar issues like https://github.com/mswjs/msw/issues/1803

**Comment by mattcosta7** [comment]
https://github.com/petera2c/msw-bug-example/pull/1/files

test go green when jest is properly configured according to the migration guide: https://mswjs.io/docs/faq/#requestresponsetextencoder-is-not-defined-jest
