### ISSUE TITLE
MSW does not intercept requests abstracted in functions within the context api

### ISSUE THREAD

**Issue by devguilhermecosta** [kettanaito/msw#1902]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v21.2.0

### Reproduction repository

https://github.com/devguilhermecosta/msw-issue.git

### Reproduction steps

npm i
npm run test:watch

In the console, below 'listening...', all MSW interceptions will be displayed...none

### Current behavior

I have an AuthContext that implements a login function, making a request to the API to obtain a token.
My login form calls the **handleLogin** function in **onSubmit** event.
MSW is unable to intercept the request in this way.

### Expected behavior

The MSW should intercept the request for the given url.

**Comment by mattcosta7** [comment]
@devguilhermecosta 

I'm unable to run any tests in your reproduction. it seems to not be building at all, so I can't help understand what's happening under the hood.

My initial thoughts are that the versions of globals in jsdom and in jest-setup are incorrect. 

I would ensure that you're following the set of globals here: https://mswjs.io/docs/faq/#requestresponsetextencoder-is-not-defined-jest

```ts
import {TestEnvironment } from 'jest-environment-jsdom';

const Environment = TestEnvironment;

export default class CustomTestEnvironment extends Environment {
  async setup() {
    await super.setup();

// pseudo mostly copy/pasted from the docs above, this may need to be handled slightly differently to fit your project properly

const { TextDecoder, TextEncoder } = require('node:util')
 
Object.defineProperties(this.global, {
  TextDecoder: { value: TextDecoder },
  TextEncoder: { value: TextEncoder },
})
 
const { Blob, File } = require('node:buffer')
const { fetch, Headers, FormData, Request, Response } = require('undici')
 
Object.defineProperties(this.global, {
  fetch: { value: fetch, writable: true },
  Blob: { value: Blob },
  File: { value: File },
  Headers: { value: Headers },
  FormData: { value: FormData },
  Request: { value: Request },
  Response: { value: Response },
})
  }
}
```

but this is a pure guess because I can't run the tests at all, since your demo fails to build

**Comment by devguilhermecosta** [comment]
Right matt, my jest environment was having difficulty parsing css files.
I made a commit changing the test environment to Vitest. I just did a basic configuration to demonstrate the error test.

**Comment by mattcosta7** [comment]
@devguilhermecosta does your code work in a browser?  I don't think it does.

The error you have is in the way you're parsing form data.   If it does work in a browser, then something is likely up with jsdom's form implementation, but either way unrelated to interception

```ts
function handleLogin( .....) {
+  const formData = new FormData(event.currentTarget);

   const response = await axios.post(url, {
-    username: event.currentTarget.username.value,
+    username: formData.get("username"),
-    password: event.currentTarget.password.value,
+    password: formData.get("password"),
    });
}
```

your `handleLogin` is throwing, so your `axios.post` was never being made. 

This doesn't have anything to do with `msw`. But if your request never gets made, there's nothing to intercept :-D

**Comment by mattcosta7** [comment]
FWIW - it does look like an implementation issue in `jsdom` - https://github.com/jsdom/jsdom/issues/1570

so it seems like there's no support there, which is why your code fails

**Comment by devguilhermecosta** [comment]
hey matt, what did you do here? hahah
Yes with formData it worked. I never thought about this, because when calling axios.post directly in **handleSubmit**, even using useState, it works.

With the solution below, MSW was able to intercept as well.

Anyway, thank you very much...you da man hehe.


```
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  async function handleSubmit(e: FormEvent<HTMLFormElement>): Promise<void> {
    e.preventDefault();
  
    if (!validateFields()) return;
    
    setLoading(true);

    await axios.post('http://127.0.0.1:8000/api/token/', {
      username: username,
      password: password,
    })
    .then(response => {
      userAuthentication(response.data);
      navigate('/admin/dashboard', { replace: true });
      setLoading(true);
    })
    .catch(() => {
      setLoading(false);
      setUsernameError('Usuário ou senha inválidos');
    })
  }
```

**Comment by mattcosta7** [comment]
> hey matt, what did you do here? hahah Yes with formData it worked. I never thought about this, because when calling axios.post directly in **handleSubmit**, even using useState, it works.
> 
> With the solution below, MSW was able to intercept as well.
> 
> Anyway, thank you very much...you da man hehe.
> 
> ```
>   const [username, setUsername] = useState('');
>   const [password, setPassword] = useState('');
> 
>   async function handleSubmit(e: FormEvent<HTMLFormElement>): Promise<void> {
>     e.preventDefault();
>   
>     if (!validateFields()) return;
>     
>     setLoading(true);
> 
>     await axios.post('http://127.0.0.1:8000/api/token/', {
>       username: username,
>       password: password,
>     })
>     .then(response => {
>       userAuthentication(response.data);
>       navigate('/admin/dashboard', { replace: true });
>       setLoading(true);
>     })
>     .catch(() => {
>       setLoading(false);
>       setUsernameError('Usuário ou senha inválidos');
>     })
>   }
> ```

Yep, that works as well, because you're passing state directly to the request

the only reason your code wasn't working was because JSDOM hasn't implement `form[name]` apis, so `event.currentTarget.username.value` and `event.currentTarget.password.value` were both throwing errors.

Those errors aren't being handled anywhere, so they were getting swallowed entirely.  Because that element access was throwing, your request was never made!  No request made, no request to intercept!
