### ISSUE TITLE
Empty File in FormData

### ISSUE THREAD

**Issue by harriganjames** [kettanaito/msw#1913]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

18.18.0

### Reproduction repository

https://github.com/harriganjames/vitest-react

### Reproduction steps

npm test

### Current behavior

When receiving a Blob via FormData, the size of the Blob is always zero

### Expected behavior

The size of the Blob being sent should match the size received in MSW

**Comment by kettanaito** [comment]
Hi, @harriganjames. Thanks for reporting this. 

I've added an integration test for this behavior and it's passing (see #1995). 

I've checked your reproduction repository and confirm that the test is failing there. After looking into it more, it seems to be a problem with JSDOM. If you use Node.js environment, the file's size will be correct. JSDOM is notoriously known for disrespecting your test environment and relying on polyfills for things that no longer need to be polyfilled. I suspect `FormData` and `Blob` are just a couple of those things. JSDOM breaks their behavior for your test. 

## Solution

I suggest raising this in the JSDOM repo on GitHub, it's a bug. Chances are, it's already reported.

**Comment by kettanaito** [comment]
## Released: v2.1.5 🎉

This has been released in v2.1.5!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.1.5)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.1.5)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by harriganjames** [comment]
@kettanaito - thanks for looking into this. The jsdom issue requirements ask for a minimal code snippet without any dependencies which demonstrates the problem. Do you know which jsdom feature is being used here, or are you able to point me in the right direction?

**Comment by kettanaito** [comment]
@harriganjames, first, check the existing issues. I suspect someone has stumbled upon this. 

> The jsdom issue requirements ask for a minimal code snippet without any dependencies which demonstrates the problem.

This itself may be the reason why jsdom is so broken. Within its locked-in environment of polyfills anything may happen. There's no truth in that. 

Prepare a proper reproduction scenario that uses `FormData` from `undici` (this is Node's global implementation of `FormData`) and `File`. See it fail in isolation (no MSW is needed here for it to fail), then report it to them.
