### ISSUE TITLE
Use of AbortSignal causes "Cannot construct a Request with a Request object that has already been used." error

### ISSUE THREAD

**Issue by ezzatron** [kettanaito/msw#1924]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v21.4.0

### Reproduction repository

https://github.com/ezzatron/msw-abort-signal-repro

### Reproduction steps

1. `npm ci`
2. `npm test`

### Current behavior

Instead of producing an abort error, the repro code produces the following error, despite only a single request ever being made:

> Cannot construct a Request with a Request object that has already been used.

See example output: https://github.com/ezzatron/msw-abort-signal-repro/actions/runs/7177213214/job/19543363576#step:5:25

### Expected behavior

The reproduction code should produce an abort error consistent with use of an `AbortSignal`.

**Comment by liorpevzner** [comment]
You are using the controller.abort() before the fetch, the controller is already used, you can't reuse it after its been aborted.
You need to switch the order, remove the await on the fetch request and put the controller.abort() right after the fetch, it should be caught in the .catch(error).

**Comment by ezzatron** [comment]
> You are using the controller.abort() before the fetch, the controller is already used, you can't reuse it after its been aborted.

I appreciate the reply, but I don't agree. An `AbortSignal` is **not** guaranteed to be aborted only _after_ it is used in a fetch call, and the abort signal is not always created by the same code that uses it. It should not be causing MSW to change behaviour here.

As an example, `fetch` handles this just fine: https://codepen.io/ezzatron/pen/xxBEevM?editors=0010

To clarify, MSW should still be throwing an exception in this case. But it should be an abort error, not a generic error.

**Comment by master1lan** [comment]
so,any iead to resolve this problem?

**Comment by aaditmshah-commversion** [comment]
I'm facing this issue too. Would love to see the needle move on fixing this.

**Comment by kettanaito** [comment]
Hi, @ezzatron. I've just tried the reproduction repo and the test there is passing:

```
 RUN  v1.0.4 /Users/kettanaito/Documents/web/contrib/msw-1924

 ✓ repro.test.js (1)
   ✓ should support AbortSignal
```

I believe this has been fixed somewhere during the improvements to how we handle `AbortController`.
