### ISSUE TITLE
Interception is no longer working since v2.0.6

### ISSUE THREAD

**Issue by ribeaud** [kettanaito/msw#1930]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.10.0

### Reproduction repository

https://gitlab.com/biomedit/portal/-/tree/main/frontend

### Reproduction steps

1. Checkout above repository and go to pointed directory
2. In `package.json`, change **msw** to  _v2.0.11_, run `npm i`
3. Execute test `PgpKeyInfoManage.test.tsx`: `npm test -- src/components/admin/PgpKeyInfoManage.test.tsx`

### Current behavior

The test is failing since _v2.0.6_. For some reason I do not understand yet, the interception is no longer working. We are using a mix of **msw**, **OpenAPI Generator**, **jest** and **react**.

I went through the release notes and I have no clue which change could be responsible for this behavior.

### Expected behavior

In a perfect world, the defined interception works and my test is green, as it used to be.

**Comment by kettanaito** [comment]
Hi, @ribeaud. Thanks for reporting this.

I see nothing in 2.0.6 - 2.0.11 releases that could have caused this. From the brief look at the repo, your setup seems to be okay. 

I recommend following the [Debugging runbook](https://mswjs.io/docs/runbook#debugging-runbook) to see if you can uncover any issues. Please do so and let me know what each step yields. Thanks.

**Comment by ribeaud** [comment]
Hi @kettanaito. Thanks for the pointer. I will follow the steps and let you know.

**Comment by ribeaud** [comment]
Hi @kettanaito. Thank you so much. This was, indeed, very useful.

I've found out the problem. Our generated API have a `fetch` [invocation](https://gitlab.com/biomedit/portal/-/blob/main/frontend/src/api/generated/runtime.ts#L206) which looks as following:
```ts
response = await (this.configuration.fetchApi || fetch)(fetchParams.url, fetchParams.init);
```
If I remove the last part `fetchParams.init`: `response = await fetch(fetchParams.url);` (knowing that `this.configuration.fetchApi` is _undefined_ in our case), then the call is intercepted by **msw** and the test becomes green.

To me it looks like **msw** gets stricter after _2.0.6_. Could you confirm?

Is that something I have to solve on my side? Or do you think this could trigger a change in **msw** library?

**Comment by kettanaito** [comment]
@ribeaud, I don't believe MSW has any changes affecting this. Do you observe any request difference when passing `undefined` as `init` to the fetch call vs not doing so? Is the request the same? 

I suspect that may affect how `fetch()` works, producing a different, non-matching request.

**Comment by ribeaud** [comment]
@kettanaito, Mmmmh... This is really weird. Changing the dependency to _2.0.6_, `npm i`, running the test, everything OK. Back to _2.0.11_, `npm i`, running the test, red. AFAIK, `fetch` does not change between the two procedures, or how? Does *msw* draw different sets of dependencies between the two versions, which could explain this behaviour on my end?

Now trying your suggestion with `undefined` _init_...

**Comment by ribeaud** [comment]
Setting _init_ to `undefined` works with both _2.0.6_ and _2.0.11_.

**Comment by ribeaud** [comment]
I just saw something interesting: after `npm i` with _2.0.11_, `"node-fetch": "^2.6.7"` disappears from **package-json.lock** and `@mswjs/interceptors` requires _^0.25.13_ (instead of _^0.25.11_) for **node_modules/msw**.

**Comment by ribeaud** [comment]
If I force my **openapi** code to use `node-fetch`, then I am back to normal (by default it is using [typescript-fetch](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md)). I now have a solution but I am not really sure what to do... What would you suggest to me?

**Comment by jd-carroll** [comment]
It is probably not an issue with `msw`. Speaking from my own cold bitter experience **do everything you possibly can to avoid multiple fetch implementations**. If you are using `msw` then you want to be using the native fetch from node.

Things I would do:
1) Move to nodejs v20.x
2) Remove any fetch pollyfill (e.g. `node-fetch` & `typescript-fetch`)

Obviously this may not be possible in your environment, but would strongly push for that.

**Comment by kettanaito** [comment]
Just gave this a try using `msw@2.1.4`:

```sh
> jest src/components/admin/PgpKeyInfoManage.test.tsx

 PASS  src/components/admin/PgpKeyInfoManage.test.tsx (5.767 s)
  PgpKeyInfoManage
    ✓ Should only show edit button for keys with allowedPgpKeyInfoStatusEnumSubset (217 ms)
```

The reproduction scenario is passing. I conclude this issue resolved. 

If you encounter any other problems, feel free to comment below. Thanks.
