### ISSUE TITLE
MSW node does not intercept if I set 'X-Request-Id' 

### ISSUE THREAD

**Issue by cythrawll** [kettanaito/msw#1935]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v18.16.1

### Reproduction repository

https://codesandbox.io/p/devbox/eager-kapitsa-s4cnj7

### Reproduction steps

1. create any handler.
2. create a call that should hit the handler.
3. see that it gets intercepted correctly.
4. Add 'X-Request-Id' header to call with any content.
5. See the call doesn't get intercepted.

### Current behavior

Calls with `X-Request-Id` header do not get intercepted. This worked in msw 1.x.

https://github.com/mswjs/interceptors/blob/122a6533ce57d551dc3b59b3bb43a39026989b70/src/interceptors/ClientRequest/NodeClientRequest.ts#L193

### Expected behavior

Calls with `X-Request-Id` should be intercepted. 

We use that header to pass the request id from the browser request back to the backend for logging purposes. So we would like to intercept those requests.  This header is a commonly used header for logging purposes.

**Comment by kkhanhluu** [comment]
Hi @cythrawll do you still encounter this issue?

**Comment by cythrawll** [comment]
@kkhanhluu I've had to roll back my 2.0 migration because of this bug. I've not heard any movement on this issue so I assume it's still an issue? Considering it took some effort in migration and our mocks have moved so much since then, I cannot test this issue at this time unless I see movement on the issue. It looks like the code still has the same header check. Is there a concern it might have been fixed?

**Comment by kettanaito** [comment]
Thanks for reporting this, @cythrawll. 

The `X-Request-Id` header is used internally by Interceptors to dedupe nested interceptors, such as XHR implemented via `http` in JSDOM (XMLHttpRequestInterceptor -> ClientRequestInterceptor). 

This is not a good solution. I've opened a task to replace it (https://github.com/mswjs/interceptors/issues/378). `AsyncLocalStorage` is a great way to mitigate this for a particular XHR -> ClientRequest scenario.

**Comment by kettanaito** [comment]
I've merged a workaround that would prevent Interceptors from meddling with the user-defined `X-Request-Id` header (https://github.com/mswjs/interceptors/pull/529). Will propagate to MSW soon.

**Comment by kettanaito** [comment]
Opened a fix for this in https://github.com/mswjs/msw/pull/2110.

**Comment by kettanaito** [comment]
## Released: v2.2.12 🎉

This has been released in v2.2.12!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.12)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.12)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
