### ISSUE TITLE
When angular lazily loads components, msw will report a warning about intercepting requests in the browser console.

### ISSUE THREAD

**Issue by huajian123** [kettanaito/msw#1936]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/huajian123/ceshimock

### Reproduction steps

If you load angular components through lazy loading, or obtain antdesign styles or static resources, a warning will appear. Here is a link to github reproduction.
https://github.com/huajian123/ceshimock2
https://github.com/huajian123/ceshimock

<img width="926" alt="image" src="https://github.com/mswjs/msw/assets/31737260/51b719e1-204f-44ab-9029-9ee5129025b0">
<img width="875" alt="image" src="https://github.com/mswjs/msw/assets/31737260/c20e5e4d-2b5d-47cb-8f19-358df86cf61d">

### Current behavior

show
devUtils.mjs:8 [MSW] Warning: intercepted a request without a matching request handler:

  • GET /chunk-6NOFO3UG.js

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks

### Expected behavior

no warning

**Comment by mattcosta7** [comment]
This is correct behavior. We don't have information about what requests you want to intercept, and the service worker gets _all requests_. 

You can make an explicit handler for js css or other assets and pass those requests directly through

```ts
http.get('*.js', () => passthrough())
```

there's not much we can do for _specific_ cases as msw is a general purpose tool.  The solution is to configure it for your usecase!
