### ISSUE TITLE
MSW intercepts sometimes do not set response data depending on json file

### ISSUE THREAD

**Issue by thewillmoss** [kettanaito/msw#1938]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [x] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/thewillmoss/mswjs

### Reproduction steps

1. git clone https://github.com/thewillmoss/mswjs.git
2. npm install
3. npm start
4. open network tab
5. might need to refresh to view calls to '/data1' and /data2' 

### Current behavior

Currently the network call to /data1 does not return a json response, while the call to /data2 does return a json response. The only difference is the number of fields in the json file passed to HttpResponse.json()

### Expected behavior

A call to /data1 should return the specified json instead of sending back no data in the response.

**Comment by AinaM** [comment]
Could it be because the Service Worker registration is not ready yet when the calls are done?

The documentation [Browser integration](https://mswjs.io/docs/integrations/browser) mentions 
> Because registering the Service Worker is an asynchronous operation, it’s a good idea to defer the rendering of your application until the registration Promise resolves.
> [see code example on documentation]
> Make sure to await the worker.start() Promise! Service Worker registration is asynchronous and **failing to await it may result in a race condition between the worker registration and the initial requests your application makes**.

When checking the code, you would need to wait for `worker.start()` to be done before rendering your app

**Comment by thewillmoss** [comment]
@AinaM You were right, I added the code in the article you linked and it worked.
