### ISSUE TITLE
Handlers for OPTIONS / HEAD Calls are not working

### ISSUE THREAD

**Issue by janwidmer** [kettanaito/msw#1951]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/janwidmer/spartacus-test-2211.23.0
Please let me know, when trying to reproduce, as the Reproduction Repository needs an npmrc file.

### Reproduction steps

1. Checkout Repo
2. Make sure, you run node version 20.11.1
3. Run `npm i`
4. Run `npm run start`
5. Open Browser URL `http://localhost:4200/electronics-spa/de/USD/login`
6. Click on the register button
7. Register new user (values do not matter)
8. Submit Registration
9. Login with the created user
10. Notice the 401 Errors for the calls to the url `
https://spartacus-demo.eastus.cloudapp.azure.com:8443/occ/v2/electronics-spa/users/anonymous/consenttemplates?lang=de&curr=USD` (Request Type HEAD)

### Current behavior

The Request seems to go to the actual URL `https://spartacus-demo.eastus.cloudapp.azure.com:8443` and returns with a 401 error, because on that system, the user is not logged in. 

### Expected behavior

The request is handled by msw, as I have added the handlers (According to the docs: https://mswjs.io/docs/api/http/#httphead):
<img width="519" alt="image" src="https://github.com/mswjs/msw/assets/3381820/e97defd6-7f49-4fe2-b777-41c8be0d17a5">

<img width="696" alt="image" src="https://github.com/mswjs/msw/assets/3381820/28ced9bd-6d6a-4a3e-8811-8b21c30c811c">

<img width="699" alt="image" src="https://github.com/mswjs/msw/assets/3381820/2b3cc0e7-d45a-4831-8d8a-74f6773e60dd">

And the handlers are corretly there (Printout from `worker.listHandlers()` to the browser console:
<img width="812" alt="image" src="https://github.com/mswjs/msw/assets/3381820/2826fbe8-1d01-4b43-9130-a0ab31c7d3b3">

If the request would be correctly handeled by MSW, you would see a console log `head call for anonymous consent templates`

**Comment by janwidmer** [comment]
Bug is not an msw bug.

**Comment by janwidmer** [comment]
I am again having this problem and it actually DOES seem to be a problem with MSW, also with the latest version of MSW

**Comment by kettanaito** [comment]
Hi, @janwidmer. Can you please follow the [Debugging runbook](https://mswjs.io/docs/runbook) and share the results?

That runbook will help you discover a potential root cause for this issue. 

At the first glance, this doesn't seem like an MSW issue to me. This is likely caused by your request client not performing those `OPTIONS` or `HEAD` requests, to begin with (again, the runbook will help you see that). 

Since you are using extra setup on top of MSW (https://valantic.gitbook.io/spartacus-mock), make sure that setup has no issues that may be causing this.
