### ISSUE TITLE
Package ./node is not exported from package Users/User/Application/node_modules/msw

### ISSUE THREAD

**Issue by Boughris-Abdelmalek** [kettanaito/msw#1965]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v21.5.0

### Reproduction repository

examples/with-jest

### Reproduction steps

Yarn start

### Current behavior

Package ./node is not exported from package Users/User/Application/node_modules/msw

### Expected behavior

start server

**Comment by kettanaito** [comment]
Hi, @Boughris-Abdelmalek. Thanks for reporting this. I will take a look at what's going on and let you know.

**Comment by kettanaito** [comment]
## Running `with-jest` example with Yarn

```sh
with-jest % yarn test
yarn run v1.22.19
warning package.json: No license field
$ jest
 PASS  ./example.test.ts
 PASS  ./example-jsdom.test.ts

Test Suites: 2 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        0.937 s
Ran all test suites.
✨  Done in 3.01s.
```

There are no issues running the latest `with-jest` example using Yarn. 

**Please make sure you follow the [example](https://github.com/mswjs/examples/tree/main/examples/with-jest)**. You have to configure additional things to make Jest run modern JavaScript.

**Comment by Boughris-Abdelmalek** [comment]
> Hi, @Boughris-Abdelmalek. Thanks for reporting this. I will take a look at what's going on and let you know.

Just for more context, I having issues when running `yarn start` && `yarn build`, the tests works fine.

My setup uses: 
`
msw: 2.0.14
jest: 29.7.0
react-scripts: 5.0.1
yarn: 4.0.2
node: (I tried different versions from 18 >)
`

If you need more informations please let me know :)

I followed the documentation about the setup, I would love to give you more informations about the repo I am using but as it is a private one from my company it's unfortunately not possible, thank you for your understanding.

**Comment by kettanaito** [comment]
@Boughris-Abdelmalek, I'm not sure I follow. The Jest example doesn't have the `start` and `build` scripts, those must be yours. Do you want to submit a reproduction repository for me to look at? The one you mentioned in the OP works fine. 

I understand you cannot share your company's project. I encourage you to extract the setup into a standalone repo and submit that. Omit any sensitive data. Yes, it will take time. The upside here is that you are highly likely to discover the root cause of the issue and fix it yourself while extracting it to a standalone repo.

**Comment by Boughris-Abdelmalek** [comment]
I will try to reproduce the setup and link the repo when it's ready, thank you !

**Comment by Boughris-Abdelmalek** [comment]
Hello @kettanaito , so here is the repo with the exact error reproduced, I hope this will be helpful !

https://boughris-abdelmalek@github.com/Boughris-Abdelmalek/msw-1965-bug

Thank you in advance for your time :)

**Comment by Boughris-Abdelmalek** [comment]
> Hello @kettanaito , so here is the repo with the exact error reproduced, I hope this will be helpful !
> 
> https://boughris-abdelmalek@github.com/Boughris-Abdelmalek/msw-1965-bug
> 
> Thank you in advance for your time :)

I think I found the issue, I have a pathResolve function in `<rootDir>/src/utils` that basically checks if the app is running on browser or node, and It seems like it's what was causing the issue.

The import somehow was conflicting and declaring the function on top of the handlers resolves it.

I don't know if it's supposed to behave like this or it was my mistake but I hope that this can be helpful !
