### ISSUE TITLE
TypeScript error using `passthrough()` in GraphQL mock

### ISSUE THREAD

**Issue by callummr** [kettanaito/msw#1977]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.5.1

### Reproduction repository

https://codesandbox.io/p/sandbox/msw-gql-passthrough-typeerror-jz9s6m?file=%2Fsrc%2Fmsw.ts

### Reproduction steps

Open `msw.ts`. Observe TS errors.

### Current behavior

TypeScript error when trying to `return passthrough()` in a GraphQL handler.

```ts
const operationHandler = graphql.operation(() => {
  return passthrough();
});
```

```
Argument of type '() => Response' is not assignable to parameter of type 'ResponseResolver<GraphQLResolverExtras<GraphQLVariables>, null, GraphQLResponseBody<Record<string, any>>>'.
  Type 'Response' is not assignable to type 'AsyncResponseResolverReturnType<GraphQLResponseBody<Record<string, any>>>'.
    Property '[bodyType]' is missing in type 'Response' but required in type 'StrictResponse<GraphQLResponseBody<Record<string, any>>>'.typescript(2345)
```

Can be worked around by casting the passthrough type:
```ts
const graphqlPassthrough = passthrough as () => ReturnType<
  typeof HttpResponse.json<{ data: any }>
>;

const operationHandler = graphql.operation(() => {
  return graphqlPassthrough();
});
```

### Expected behavior

`passthrough()` can be returned in `graphql` mocks, as it can in `http` mocks.

**Comment by kettanaito** [comment]
## Released: v2.1.6 🎉

This has been released in v2.1.6!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.1.6)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.1.6)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
