### ISSUE TITLE
2.1.0 breaks browser usage

### ISSUE THREAD

**Issue by thepassle** [kettanaito/msw#1981]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/thepassle/msw-bug

### Reproduction steps

`npm i && npm test`

### Current behavior

When using `msw@2.0.14` it works:

<img width="651" alt="image" src="https://github.com/mswjs/msw/assets/17054057/39fea0f4-b433-4da0-b563-3fca85d4323b">

When using `msw@2.1.0` it breaks:
<img width="859" alt="image" src="https://github.com/mswjs/msw/assets/17054057/f552a5d2-d8a1-4b70-8c2f-beeb2b5873e4">

I havent been able to debug (but I was able to pin it down to version `2.1.0` as the breaking version), and im unlikely to have time to dive into this for the next couple of days or so, but I figured i'd report it so maybe somebody else can pick it up

### Expected behavior

It works :)

**Comment by peschee** [comment]
I‘m running into the same issue.

**Comment by kettanaito** [comment]
Hi, @thepassle. Thanks for reporting this. 

Where is the `Not Found` response coming from? Is it from the `@web/mocks/plugins.js` package? Something along the line attempts to read it as JSON, resulting in a parsing error. If we figure out what and why, we solve the bug.

**Comment by thepassle** [comment]
The `@web/mocks/plugins.js` module is just a dev server plugin that resolves the service worker file, it ignores any other requests.

The only place where we touch the request is in the source code, in the test's `Response.json`: https://github.com/thepassle/msw-bug/blob/main/test.js#L6

And in the "polyfill" (which would go unused in this case, because Chrome, on which I tested this, `Response.json` is supported): https://github.com/modernweb-dev/web/blob/master/packages/mocks/polyfills.js#L3

Otherwise, we don't do anything special, we just pass request handlers to MSW pretty much 1-on-1: https://github.com/modernweb-dev/web/blob/master/packages/mocks/registerMockRoutes.js#L40

If you want I can try to make an even more minimal reproduction tomorrow without using the `@web/mocks` package, but just MSW directly.

**Comment by kettanaito** [comment]
🤔 Then where is "Not Found" response coming from? Hm. I will take a look once I have a minute. See if you don't beat me to it. 

Can it be that you are requesting a page route and it returns a `text/html` body with `Not Found` string in it? Like hitting a 404 route that your web runner handles with a placeholder page.

**Comment by thepassle** [comment]
I was able to reproduce like this as well, cutting out `@web/mocks` out completely: 

<img width="1287" alt="image" src="https://github.com/mswjs/msw/assets/17054057/4f24427a-da5d-4bcb-838c-184ae772cc22">

**Comment by thepassle** [comment]
Ive updated the reproduction repo with my latest changes: https://github.com/thepassle/msw-bug

**Comment by thepassle** [comment]
Changed the name title to `browser usage` rather than `@web/test-runner`, WTR is not the problem. I've tested with several browser tools (Vite, @web/dev-server) that `msw@^2.1.0` does not work in the browser correctly anymore.

Repro:
```html
<html>
  <body>
    <script type="module">
      import { http } from 'msw';
      import { setupWorker } from 'msw/browser';

      const worker = setupWorker();
      worker
        .start({
          serviceWorker: {
            url: './mockServiceWorker.js',
          },
        });
      worker.use(http.get('/api/foo', () => Response.json({ foo: 'foo' })));

      const response = await fetch('/api/foo').then(r => r.json());
      if(response.foo !== 'foo') {
        throw new Error('response.foo !== "foo"');
      }  
    </script>
  </body>
</html>
```

**Comment by kettanaito** [comment]
I've added a regression test for this scenario in https://github.com/mswjs/msw/pull/1994 and it passes without issues using our browser integration testing setup. I suspect the issue is in the tooling used to run MSW. 

Next, I will look into the reported project itself. 

> I wish it was a bit easier to put such examples into tests but right now we always require an entrypoint in `loadExample`. I recall I was experimenting with arbitrary HTML as reproduction examples but, apparently, that never got merged.

**Comment by kettanaito** [comment]
@thepassle, the root cause seems to be not awaiting `worker.start()`. Remember, it's an asynchronous action that you _must_ await before your app/tests are running. 

If I add a simple `await` statement right here, your reproduction repository passes:
https://github.com/thepassle/msw-bug/blob/8bbec16ddcd0bca4166a2407b0838a9429fb870f/test.js#L5

```sh
Finished running tests in 1.1s, all tests passed! 🎉
```

In our examples (browser tests) we don't await `worker.start()` for two reasons:

1. Our compiler doesn't like root-level async/await.
2. Not all tests should await it. The await mechanism is built-in into `loadExample` and you can even opt-out of it via `skipActivation: boolean`.

**Comment by thepassle** [comment]
Okay, looks like this change indeed was the breaking change here: https://github.com/mswjs/msw/pull/1964/files

It's not entirely clear to me why this was removed in a minor version, when this is definitely a breaking change, and why the deprecation warning was only added after the behavior was removed?

**Comment by kettanaito** [comment]
I write about this not being a breaking change in here: https://github.com/mswjs/msw/pull/1964#issuecomment-1890922798

If a library ships a bug and people rely on that bug, it doesn't make it a part of the library's promise. I find semver to be solely related to promises a particular API makes. 

The promise has always been this: await `worker.start()`. It was in the old docs, and it's now in the new docs. Us catering to incorrect usage led to the release of `waitUntilReady`, which is a hack that introduced a huge amount of runtime issues (it never cleaned up after itself!). You mustn't be using it. Instead, await promises.

**Comment by thepassle** [comment]
FYI it was in fact a breaking change, and did break for us at work. Whether it was hacky or not, it was for sure a behavior of the library

> It was in the old docs

It definitely wasnt in the old docs either btw: 

<img width="807" alt="image" src="https://github.com/mswjs/msw/assets/17054057/a6b489d9-c974-45c2-a3df-7fb4e3ea75df">

**Comment by kettanaito** [comment]
I was referring to [this page](https://v1.mswjs.io/docs/getting-started/integrate/browser#start-worker). But you're right, we didn't recommend deferring the app, only linked to it if you have race conditions. Glad we are doing a better job with the new docs. 

"The library worked that way" isn't an argument here, to be honest. When you call a function that returns a Promise, and rely on some third-party to await that promise for you, you aren't writing proper JavaScript. Once again, I acknowledge `waitUntilReady` was a hack. I wish we taught people to defer the app rendering as the default. But it's quite unreasonable to state that this is a breaking change:

```diff
-worker.start()
+await worker.start()
someDependentCode()
```

Asking you to properly await promises is a good thing. It's a thing you should do. And in that context, what has been before was a bug, and what is now is how it was always meant to be.

**Comment by thepassle** [comment]
> Asking you to properly await promises is a good thing. It's a thing you should do. 

I agree, I'm just letting you know that release `2.1.0` resulted in an expected behavior of the library breaking in our projects at work, fyi. Hopefully in the future we can be a bit more careful about deprecations/removals of behavior

**Comment by kettanaito** [comment]
Thanks for letting me know. I've also heard about other apps breaking. Luckily, the fix is simple. And the gain is huge, albeit you probably won't see it. The things `waitUntilReady` did to your client-side JavaScript were unacceptable. Trust me, you are happy it's gone. 

> Hopefully in the future we can be a bit more careful about deprecations/removals of behavior

Noted and agreed.
