### ISSUE TITLE
Drop `headers-polyfill`

### ISSUE THREAD

**Issue by thepassle** [kettanaito/msw#1985]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I noticed MSW uses `headers-polyfill`, presumably this is a remnant of before node 18. It's also used in the browser module graph, where ideally we wouldnt use a polyfill for this at all.

We should see if we can remove the dependency

<img width="515" alt="Screenshot 2024-01-21 at 10 15 06" src="https://github.com/mswjs/msw/assets/17054057/d9b0d908-5bb5-445c-97c8-3788ae19b1e2">

**Comment by kettanaito** [comment]
Hi, @thepassle. We use `headers-polyfill` not to actually polyfill headers but to transform headers:

https://github.com/mswjs/msw/blob/2c095f4bee0e1ae6933123482e45212a9ad22f02/src/core/utils/internal/parseMultipartData.ts#L18

What we can improve here is bundle `headers-polyfill` better so it has individual functions in the build, which will make MSW import just that single `stringToHeaders` function it needs, and not the entire library. 

The package also has no effect on runtime, which makes it, as you've rightfully pointed out, a ponyfill. We aren't replacing the global `Headers`.

**Comment by thepassle** [comment]
Looks like `headers-polyfill` is actually a ponyfill, so it doesnt pollute browser globals, which is good. We also only seem to use it for the `stringToHeaders` function, so that should be fine. Closing

**Comment by kettanaito** [comment]
The package is rather small so we wouldn't get much fain from restructuring its exports. If anybody wants to tackle this, it's a nice exercise in package bundling so go ahead! 

- https://github.com/mswjs/headers-polyfill
