### ISSUE TITLE
Consider bundling browser entrypoints

### ISSUE THREAD

**Issue by thepassle** [kettanaito/msw#1986]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Currently the build leaves bare module specifiers of dependencies in-tact, for nodejs projects this is a common thing to do, but in the browser this leads to large request waterfalls, slowing local development and unit tests down significantly. It would be good to consider bundling the browser entrypoint so that we can reap the benefits of treeshaking and dead code elimination

**Comment by kettanaito** [comment]
Our browser build config does set `bundle: true`:

https://github.com/mswjs/msw/blob/42f147367709d85c09ec44eb300848d0bbbf1b6d/tsup.config.ts#L61

I wonder, what can be wrong here?

**Comment by thepassle** [comment]
<img width="931" alt="image" src="https://github.com/mswjs/msw/assets/17054057/abd5142f-d0da-4d3e-9924-23e0ae411d8b">

**Comment by kettanaito** [comment]
I see. We can read the package.json and provide those two dependencies to tsup.config.ts. Should be an easy fix?

**Comment by thepassle** [comment]
Looks like we have to provide them to `noExternal`: https://paka.dev/npm/tsup@8.0.1/api#module-index-export-Options:~:text=matching%20given%20patterns-,noExternal,-%3F%3A%20(

**Comment by kettanaito** [comment]
@thepassle, would you have a minute to give this a try? No worries if not, we can add this in the next release.

**Comment by thepassle** [comment]
https://github.com/mswjs/msw/pull/1988

**Comment by kettanaito** [comment]
Closed by #1988. Thank you, @thepassle 👏
