### ISSUE TITLE
Request in worker.events.on('response:mocked', {request} is always null

### ISSUE THREAD

**Issue by canrozanes** [kettanaito/msw#2014]
### Discussed in https://github.com/mswjs/msw/discussions/1991

Just converting it to an issue so that it can be tracked. 

<div type='discussions-op-text'>

<sup>Originally posted by **canrozanes** January 22, 2024</sup>
Hi, 

I was following the docs on [life-cycle events](https://mswjs.io/docs/api/life-cycle-events/) and I was trying to assert on a response after making an API call.

I have the following piece of code that saves all the requests so that I can assert on the responses later.

```
// QUnit  setup
hooks.beforeEach(async function (this: TestContextWithMsw) {
    this.worker = setupWorker(...handlers);
    this.worker.events.on('response:mocked', ({ request, requestId, response }) => {
      this.handledRequests.push({ request, requestId, response });
    });
});
```

I can clearly see that MSW sends a response in the browser network tab but when I add a debugger inside the 'response:mocked' callback, I see that all the request are null. 

![Screenshot 2024-01-22 at 10 39 35 AM](https://github.com/mswjs/msw/assets/37912128/0fe4ceba-aedb-4a47-a3b3-581b414e1e4c)

What could I be missing?</div>

**Comment by kettanaito** [comment]
Hi, @canrozanes. I've already tackled this issue in #1992. Please update MSW to get the fix:

```sh
npm i msw@latest
```

Released in v2.1.5 ([Release notes](https://github.com/mswjs/msw/releases/tag/v2.1.5)). Thanks.

**Comment by canrozanes** [comment]
Hey @kettanaito sorry for the duplicate. Thanks for the fix. 

Also, is there a reason url is not properly populated in the response object?

**Comment by kettanaito** [comment]
@canrozanes, do you mean the `response` instance you get from the life-cycle event listener doesn't have the correct `response.url` set?

**Comment by canrozanes** [comment]
@kettanaito yes exactly! `response.url` is `''`

**Comment by kettanaito** [comment]
Got it! Tracking in https://github.com/mswjs/msw/issues/2030, fixing in https://github.com/mswjs/msw/pull/2031. Thanks!
