### ISSUE TITLE
 TextEncoder is not defined

### ISSUE THREAD

**Issue by dev-faisaal** [kettanaito/msw#2015]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.10.0

### Reproduction repository

https://github.com/dev-faisaal/apitesting.git

### Reproduction steps

..

### Current behavior

I will encountered this issue

FAIL  src/users/users.test.jsx
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

    > 1 | import { setupServer } from 'msw/node'
        | ^
      2 | import { handlers } from './handlers'
      3 |
      4 | export const server = setupServer(...handlers)

      at Object.<anonymous> (node_modules/@mswjs/interceptors/src/utils/bufferUtils.ts:1:17)
      at Object.<anonymous> (node_modules/@mswjs/interceptors/lib/node/index.js:7:24)
      at Object.<anonymous> (node_modules/msw/src/node/SetupServerApi.ts:6:8)

### Expected behavior

it shoud not give that error

**Comment by kettanaito** [comment]
Hi, @dev-faisaal. Thanks for reporting this.

It looks like you are using the latest MSW with Jest (via Create React App). To correctly set up Jest to be able to run modern JavaScript code, you should follow [these instructions](https://mswjs.io/docs/migrations/1.x-to-2.x#requestresponsetextencoder-is-not-defined-jest) in the docs. 

Note that Create React App abstracts the Jest setup from you so you cannot apply those instructions in your current repository. You have a choice to either eject and follow MSW docs, or migrate away from CRA (it's not recommended for use to anyone).

**Comment by dev-faisaal** [comment]
I use this and I got error in this variable globalThis
the error is " 'globalThis' is not defined."
If you have any sample code for this would you please share me its repository link

I have updated the code in the repository
https://github.com/dev-faisaal/apitesting.git

const { TextDecoder, TextEncoder } = require('node:util')
 
Object.defineProperties(globalThis, {
  TextDecoder: { value: TextDecoder },
  TextEncoder: { value: TextEncoder },
})
