### ISSUE TITLE
Use "assertType" from Vitest for type testing

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#2019]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

## What

There's a more reliable way to write type testing that we have right now. Turns out, Vitest comes with first-class support for type testing. I suggest we migrate to the setup they recommend, utilizing utility types like `assertType` and `expectTypeOf`.

## Why

- We can assert on the actual types instead of relying on inference. 
- We will be able to assert on the actual expected errors instead of using `@ts-expect-error`.

## Materials

- https://vitest.dev/guide/testing-types.html#testing-types

**Comment by KaiSpencer** [comment]
Hey @kettanaito,
Would you be open to a contribution on this? 

I would be happy to pick it up, looks like a great starter into the msw repo.

**Comment by kettanaito** [comment]
@KaiSpencer, I would be thankful! You can find our existing type tests in `test/typings`, and you can run them with `pnpm test:ts`. Look around the setup, see how we run type tests on different versions of TypeScript—it can be quite interesting to dive into. 

Once you are confident, open a pull request. I will be glad to help you with the review. Thank you!

**Comment by kettanaito** [comment]
## Released: v2.2.10 🎉

This has been released in v2.2.10!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.10)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.10)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
