### ISSUE TITLE
difficuly using axios patch or post call with payload using mock service worker 2.0.11

### ISSUE THREAD

**Issue by ashwary23** [kettanaito/msw#2024]
### Scope

Improves an existing behavior

### Compatibility

- [X] This is a breaking change

### Feature description

patch call:
import axios from "axios";
const axiosInstance = axios.create();
`export function unlinkRecord(contractId: string, contractIdToUnlink: string, body: { code: string; value: string }) {
  return axiosInstance.patch(
    `patchendpoint`,
    body
  );
}`
handler:
`http.patch("patchendpoint", async () => {
console.log("cursor is not reaching here")
      return new Response(JSON.stringify(""), {
        headers: {
          "Content-Type": "application/json",
        },
      });
    }),`

using msw 2.0.11, the patch call with payload is not reaching to handler patch call
its works if we dont pass any payload or data

please fix this issue or give some solution for patch with payload (same issue with post with payload and delete with payload as well)

**Comment by kettanaito** [comment]
@ashwary23, thanks for reporting this. It looks like the issue you're experiencing is on the older version of MSW (the latest at the moment is 2.1.7). Please update MSW and see if it's not fixed already.

If you still encounter this problem after updating, provide a reproduction repository where the bug can be reproduced. You can use our existing [Examples](https://github.com/mswjs/examples) for a quick start with the reproduction repo. Thanks.

**Comment by ashwary23** [comment]
@kettanaito, I have updated it to 2.1.7 as well but still the same, and the example link does not contain any axios post/patch call with body/payload in it so the issue still exists.

for example I have this **axios** call:

`export function unlinkRecord(contractId: string, contractIdToUnlink: string, body: { code: string; value: string }) {
  return axiosInstance.patch(
    `https://agreements.dev.maersk-digital.net/contract-management/v1/contracts/${contractId}/unlink/${contractIdToUnlink}`,
    body
  );
}`
here you see we have **body** as well passed in the patch call

and the **handler** which I need to trigger is:

`http.patch("https://agreements.dev.maersk-digital.net/contract-management/v1/contracts/:contractId/unlink/:contractIdToUnlink", async ({ request }) => {
      return new Response(JSON.stringify(contract), {
        headers: {
          "Content-Type": "application/json",
        },
      });
    }),`

so the issue is the patch call with payload is not reaching to handler patch call
