### ISSUE TITLE
difficulty using axios patch or post call with payload using mock service worker

### ISSUE THREAD

**Issue by ashwary23** [kettanaito/msw#2027]
### Scope

Improves an existing behavior

### Compatibility

- [X] This is a breaking change

### Feature description

@kettanaito, I have msw as 2.1.7, the patch call with payload is not reaching to handler patch call
its works if we dont pass any payload or data

for example I have this axios call:

```
export function unlinkRecord(contractId: string, contractIdToUnlink: string, body: { code: string; value: string }) { return axiosInstance.patch( [https://agreements.dev.maersk-digital.net/contract-management/v1/contracts/${contractId}/unlink/${contractIdToUnlink}`](https://agreements.dev.maersk-digital.net/contract-management/v1/contracts/$%7BcontractId%7D/unlink/$%7BcontractIdToUnlink%7D%60),
body
);
}
```
here you see we have body as well passed in the patch call

and the handler which I need to trigger is:

`http.patch("https://agreements.dev.maersk-digital.net/contract-management/v1/contracts/:contractId/unlink/:contractIdToUnlink", async ({ request }) => { return new Response(JSON.stringify(contract), { headers: { "Content-Type": "application/json", }, }); }),`

so the issue is the patch call with payload is not reaching to handler patch call

**Comment by theishinz-maersk** [comment]
I'm a colleague of @ashwary23 .

Our issue is related to:

https://github.com/mswjs/msw/issues/1931
https://github.com/mswjs/msw/discussions/1915

I'm not into all the details. But had installed polyfills as described in the migration guide: 

https://mswjs.io/docs/migrations/1.x-to-2.x/#requestresponsetextencoder-is-not-defined-jest

But MSW still failed to deal with requests with bodies.


Downgrading 'undici' to 5.0.0 however finally solved it for me: https://github.com/mswjs/msw/discussions/1915

I'm not an expert on the nodejs and Jest layer, so I can't say who is to blame here.
But Jest is such a popular framework, that I do think it would be nice if MSW could make some kind of official support of it - even if it is them to blame.

**Comment by kettanaito** [comment]
I write in detail about this issue, why it happens, and how to fix it here: https://github.com/mswjs/msw/issues/1916#issuecomment-1908544946. This isn't an MSW issue and we cannot address it. You can raise a bug with Jest to stop polyfilling Node.js globals.
