### ISSUE TITLE
"response.url" is empty in "response:*" life-cycle events in the browser

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#2030]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/mswjs/msw/issues/2014#issuecomment-1935108305

### Reproduction steps

```js
worker.events.on('response:mocked', ({ response }) => {
  console.log(response.url)
})
```

### Current behavior

`response.url` is empty (`''`)

### Expected behavior

`response.url` must equal to the resolved response URL.

**Comment by kettanaito** [comment]
## Released: v2.2.0 🎉

This has been released in v2.2.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by radiantone** [comment]
Maybe this problem is related, but msw won't initialize
![image](https://github.com/mswjs/msw/assets/25509097/bbe37c78-2748-4170-a480-2547377cc159)

**Comment by radiantone** [comment]
``` if (!response.url) {
      Object.defineProperty(response, 'url', {
        value: request.url,
        enumerable: true,
        writable: false,
      })
    }```
 request is always null

**Comment by opatril** [comment]
@radiantone Im having same issue, its opened here https://github.com/mswjs/msw/issues/2053
