### ISSUE TITLE
JSON response with special chars truncated since 2.2.0

### ISSUE THREAD

**Issue by LeBenLeBen** [kettanaito/msw#2045]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.9.0

### Reproduction repository

https://github.com/LeBenLeBen/msw-truncated

### Reproduction steps

Clone the reproduction repo, then:
1. `npm install`
2. `npm start`
3. Visit http://localhost:7051/user

### Current behavior

The JSON response is truncated a few characters before the end and cannot be parsed by the browser. It’s caused by the special char `é` in the response. The problem does not occur before MSW 2.2.0, so I’m guessing it’s a regression caused by #1658 

### Expected behavior

The JSON response should be complete.

**Comment by ZeroCho** [comment]
I left a comment in #1658 but as this is the same problem with mine, I'll copy it here.

> I have an issue with `2.2.0+` version of MSW, when I put CJK(Chinese, Japanese, Korean character) in MSW response.
> Until `msw@2.1.0`, it was fine. I checked out what was changed in 2.2.0, and I found this commit could be the problem.
> 
> For example, the length of string '조현영'  (which is Korean) is 9 bytes in network, whereas 'abc' is 3 bytes. But both are 3 lengths in JavaScript. I think current implementation which calculate length by just `string`.length can be problem.
> I think using `new TextEncoder().encode(str).length` would be better to calculate `Content-Length`. Thank you
> 

<img width="358" alt="image" src="https://github.com/mswjs/msw/assets/10962668/e572955f-9eb6-4f18-840b-8730e87d89f5">

**Comment by kettanaito** [comment]
## Root cause

Right now, we are relying on the string length to determine the value of the automatic `Content-Length` response header. 

Instead, we should convert the string to buffer and measure its byte length. There are a couple of ways to do that:

1. `new TextEncoder().encode(text).byteLength`
2. `new Blob([text]).size`

Pull requests are welcome! I'd start with a failing test for special characters right here:

https://github.com/mswjs/msw/blob/23fc36432a3140043211d142f6dbd63b36efb3e2/src/core/HttpResponse.test.ts#L16

**Comment by kettanaito** [comment]
## Released: v2.2.2 🎉

This has been released in v2.2.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
