### ISSUE TITLE
Mocked stream response with multiple enqueues hangs process

### ISSUE THREAD

**Issue by aduth** [kettanaito/msw#2051]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.11.1

### Reproduction repository

https://github.com/aduth/msw-repro

### Reproduction steps

1. Run `npm install`
2. Run `node index.js`

### Current behavior

Output logs "text helloworld" and the process hangs indefinitely.

### Expected behavior

Output logs "text helloworld" and the process ends cleanly.

**Comment by aduth** [comment]
With the reproduction example, I'm largely copying directly from the documented example: https://mswjs.io/docs/recipes/streaming

Strangely, calling `enqueue` once seems to work fine.

Using [`why-is-node-running`](https://www.npmjs.com/package/why-is-node-running), there's a few pointers referencing the [clone happening in the fetch interceptor](https://github.com/mswjs/interceptors/blob/bddf2a1e865fba8525cf8dcfc94ec48f9e120d3d/src/interceptors/fetch/index.ts#L144-L147).

**Comment by kettanaito** [comment]
Hi, @aduth. Thanks for reporting this! 

Interesting. Your use case looks almost identical to this test we have passing:

https://github.com/mswjs/msw/blob/313691b8ca93a7c82294cd5ef1744c1c5da8641a/test/node/rest-api/response/body-stream.node.test.ts#L23-L50

Does anything different catch your eye between these two? We should certainly support pushing as many chunks as you need.

**Comment by kettanaito** [comment]
Can you try this on the latest minor version of Node.js v18? 

I could reproduce your issue on v18.14.2 but the issue is gone on v18.19.0. Node.js can have issues too! In fact, there have been a few in the past that broke `FormData`. Changing the Node.js version makes your reproduction repository pass (the process exists properly).

**Comment by aduth** [comment]
I just re-tested on latest versions of Node.js 18 and 20 (18.19.1 and 20.11.1) and unfortunately still seems to hang in both versions.

Regarding your comment on the similarities, yes, I tried code adapted both from documentation and from those exact tests to try to use in my project, which is why I was surprised when I found it wasn't working.

**Comment by kettanaito** [comment]
@aduth, quite strange. Your repo passes for me on v18.19. 

This is very unlikely an issue with MSW. I encourage you to look at Node.js/Unidici issues, especially related to request body cloning. For example, I've reported one today to Node.js (https://github.com/nodejs/node/issues/52167), which is actually an active issue in Undici (https://github.com/nodejs/undici/issues/2413).

**Comment by aduth** [comment]
That makes sense. If I find time, I'll try testing on another device to see if it's specific to my machine. In the meantime, fair to assume it's something outside MSW.
