### ISSUE TITLE
Wrong url for mockServiceWorker.js when base config set in Vite 5.x config

### ISSUE THREAD

**Issue by othierry-asi** [kettanaito/msw#2055]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.), Firefox, Safari

### Reproduction repository

https://github.com/chawax/msw2-vite5-base-issue

### Reproduction steps

- Install the projet with "npm install"
- Start the project with "npm dev"
- Open `http://localhost:5173/my-app/`

### Current behavior

The application does not start correctly because MSW can't start.

There is this message in Chrome console
```
Uncaught (in promise) TypeError: Failed to update a ServiceWorker for scope ('http://localhost:5173/') with script ('http://localhost:5173/mockServiceWorker.js'): A bad HTTP response code (404) was received when fetching the script.
````

It can't find `http://localhost:5173/mockServiceWorker.js`. Actually it should load `http://localhost:5173/my-app/mockServiceWorker.js` because `my-app` is set as base for the application in `vite-config.ts` file.

### Expected behavior

It should use `base` config if it exists to build `mockServiceWorker.js` url.

If you downgrade to Vite 4 it work.

**Comment by Fallsleep** [comment]
it's vite 5 features: [Align dev and preview HTML serving behaviour](https://vitejs.dev/guide/migration.html#align-dev-and-preview-html-serving-behaviour)
in msw, you can follow [Using custom "homepage" property](https://mswjs.io/docs/recipes/using-custom-homepage), in my project, I do not set `homepage` in `package.json`, only set `serviceWorker.url` when start worker:
```typescript
import packageJson from '../package.json'
 
if (process.env.NODE_ENV === 'development') {
  const { worker } = await import('./mocks/browser')
 
  await worker.start({
    serviceWorker: {
      // Provide a custom worker script URL, taking
      // the "homepage" into account.
      url: `${packageJson.homepage}/mockServiceWorker.js`,
    },
  })
}
```

**Comment by othierry-asi** [comment]
Thanks, it helped me a lot. I could make it work using `import.meta.env.BASE_URL` to set service worker url

```js
  if (import.meta.env.DEV) {
    const { worker } = await import("./mocks/browser");
    await worker.start({
      serviceWorker: {
        url: `${import.meta.env.BASE_URL}/mockServiceWorker.js`,
      },
    });
  }
```
