### ISSUE TITLE
Add delay before each request

### ISSUE THREAD

**Issue by primeapple** [kettanaito/msw#2056]
### Scope

Adds a new behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

I want to have what was described here https://github.com/mswjs/msw/issues/260 , but isn't usable anymore since V2.

Basically add a `delay()` before each request. What would the suggested approach to this be?

I tried using the lifecycle methods but had no success.

**Comment by ZeroCho** [comment]
https://mswjs.io/docs/api/delay
Have you tried this one?

**Comment by primeapple** [comment]
Sure, but it requires me to manually set a delay for each handler, which is not what I want. I want a delay before EVERY request.

**Comment by mattcosta7** [comment]
You can do something like a higher-order resolver similar to these:

https://mswjs.io/docs/recipes/higher-order-resolver. It still requires manually wrapping each handler's resolver with that per handled request, but provides a good mechanism for handling those
