### ISSUE TITLE
Infering the `boundary` callback arguments

### ISSUE THREAD

**Issue by Tenga** [kettanaito/msw#2069]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Currently, when using the MSW boundaries, the callback provided to the boundary has no inferred types. 

This is a slight issue when using boundaries and concurrency, as when using concurrency in Vitest, [in certain cases you are required to use the local `expect` from the `context` instead of the imported `expect`](https://vitest.dev/guide/features#running-tests-concurrently).

<img width="423" alt="Screenshot 2024-03-06 at 14 11 18" src="https://github.com/mswjs/msw/assets/419948/f6bf558b-48ad-4482-8a36-5b6d67421ea6">

So I went digging a bit as to what the root cause of this is, and eventually I ran into [this issue on the TypeScript repository](https://github.com/microsoft/TypeScript/issues/50719). I believe this issue also describes the basic interaction between Vitest's `test` typings and MSW `boundary` typings.

I applied Daniel's suggested alternative to `boundary` locally

```diff
declare class SetupServerApi extends SetupServerCommonApi implements SetupServer {
    constructor(handlers: Array<RequestHandler>);
-   boundary<Fn extends (...args: Array<any>) => unknown>(callback: Fn): (...args: Parameters<Fn>) => ReturnType<Fn>;
+   boundary<Fn>(callback: Fn & Function): Fn & Function;
    close(): void;
}
```

and indeed the `boundary` callback's arguments became correctly inferred

<img width="657" alt="Screenshot 2024-03-06 at 14 12 26" src="https://github.com/mswjs/msw/assets/419948/bbf92c06-7017-4326-b540-b70c01ae77af">

and I could use the expect from the context with inferred types for it.

<img width="504" alt="Screenshot 2024-03-06 at 14 29 01" src="https://github.com/mswjs/msw/assets/419948/b94f623b-f849-40a6-8c78-be176229615e">

I'm unsure if this change would bring something undesireable or if there's something I missed. Correct me if I'm wrong, but I believe that the proposed change's outcome is an improvement as what the current types are trying to do anyway.

**Comment by kettanaito** [comment]
Hi, @Tenga. Thanks for letting me know!

I'd love to use this suggestion but it doesn't seem to work in the `boundary` implementation:

<img width="1050" alt="Screenshot 2024-03-18 at 18 35 36" src="https://github.com/mswjs/msw/assets/14984911/87989ee5-278a-4bbc-97df-ef8d5b552c7f">

`T & Function` is not guaranteed to be a function. I can use some help with this. @andarist, if you have a moment, do you see something wrong with what I'm doing? The behavior is reproducible in https://github.com/mswjs/msw/pull/2100, `pnpm build`. Thank you.

**Comment by kettanaito** [comment]
## Released: v2.2.9 🎉

This has been released in v2.2.9!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.9)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.9)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by Tenga** [comment]
Thanks for looking into this, both of you!

I just got around to updating MSW to `2.2.12`. Unfortunately the changes had no effect on this issue on my end.

<img width="1065" alt="Screenshot 2024-03-27 at 17 11 32" src="https://github.com/mswjs/msw/assets/419948/3ae62081-3224-4d43-a876-bae66a3f1852">

Parameters are still `any` unless manually provided to `boundary`. 

I'm on ~~`typescript@3.4.3`~~`typescript@5.4.3`. Are there any `tsconfig` settings needed to make this be correctly infered? 

If not, can we reopen this or is the only other resolution to wait for the `typescript` to fix the issue linked in the first post?

**Comment by kettanaito** [comment]
@Tenga, are you certain you aren't using TS **4**.3? MSW doesn't support any TypeScript versions older than 4.7.

**Comment by Tenga** [comment]
> @Tenga, are you certain you aren't using TS **4**.3? MSW doesn't support any TypeScript versions older than 4.7.

@kettanaito Sorry, yeah I mistyped that somehow. [The project (and VS Code) is using `typescript@5.4.3`](https://github.com/digime/digime-sdk-nodejs/blob/v-next/package.json#L53).

**Comment by Andarist** [comment]
could you share a repro case of the problem with the current version of MSW?

**Comment by Tenga** [comment]
@Andarist I've made a quick minimal repro repo that can be found [here](https://github.com/Tenga/msw-boundary-infer-repro). 

Below is what I get in the `sample.test.ts` in the project.

<img width="1097" alt="Screenshot 2024-03-27 at 19 08 13" src="https://github.com/mswjs/msw/assets/419948/662b6951-37d4-40e3-a70a-8f9ce4be42bc">


The project and branch I've originally encountered this is [here](https://github.com/digime/digime-sdk-nodejs/tree/v-next). Pardon the wild mess the branch is in, in case you decide to go looking. 😁

**Comment by kettanaito** [comment]
@Tenga, in the code snippet above, I'm pretty sure `expect` is any because the entire argument is cast to any:

```diff
-({ expect }: any)
+({ expect })
```

Is there any difference if you omit any explicit types?

**Comment by Andarist** [comment]
That doesn't look like an explicit type annotation but rather like an inlay hint

**Comment by Tenga** [comment]
Yup, @Andarist is correct, there is no explicit typing in the screenshot. Bright gray text is the VS Code inlay hints that I've enabled to show the inferred types clearly everywhere.

The source from the screenshot is identical to the code in the repro case I've provided in my previous post.

https://github.com/Tenga/msw-boundary-infer-repro/blob/main/sample.test.ts#L6
