### ISSUE TITLE
Set-Cookie responses containing commas are not handled correctly

### ISSUE THREAD

**Issue by ushiboy** [kettanaito/msw#2074]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/ushiboy/msw-example

### Reproduction steps

1. `git clone https://github.com/ushiboy/msw-example`
2. `cd msw-example`
3. `npm install`
4. `npm start`
5. Open http://localhost:3000
6. Open DevTools and check the Cookies in the Applications tab.

### Current behavior

The value of the cookie will be as follows.
- Unnamed cookie with missing date value.
- The value of `a` is `1`.
- The value of `b` is `no`.

![image](https://github.com/mswjs/msw/assets/1749203/abb6f165-b695-41aa-90dc-488df9db55d8)

### Expected behavior

Expect the cookie value to be as follows.
- The value of `a` is `1,2,3`.
- The value of `b` is `no`. `Expires` must be valid.

**Comment by kettanaito** [comment]
## Released: v2.2.4 🎉

This has been released in v2.2.4!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.4)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.4)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
