### ISSUE TITLE
Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by kmiwa-clari** [kettanaito/msw#2083]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

N/A

### Reproduction steps

msw version: 2.2.1

For some reason, the `request` object [here](https://github.com/mswjs/msw/blob/main/src/browser/setupWorker/start/createResponseListener.ts#L21) is occasionally undefined. When it is, [this line ](https://github.com/mswjs/msw/blob/main/src/browser/setupWorker/start/createResponseListener.ts#L58) throws

```
Cannot read properties of undefined (reading 'url')
```

Seem to be introduced during https://github.com/mswjs/msw/commit/0e9d65ffbfb1f83a47c7dc2fcb2c885cbbf5d2ac

I don't know if this is intentional or not, or what the fix is, just reporting this runtime error.  Thanks for all you do!

### Current behavior

Throws

```
Cannot read properties of undefined (reading 'url')
```

### Expected behavior

Does not throw this error

**Comment by benjaminpearson** [comment]
I've been experiencing this as well for a couple of weeks on a project, came here to see if anyone else had opened a bug. It looks like its also been raised here https://github.com/mswjs/msw/issues/2053 and the last comment there is that its being looked into and downgrading to 2.1.4 in the meantime is one workaround (in case that helps).

**Comment by kmiwa-clari** [comment]
Yup that's what I ended up doing although I think 2.1.7 should work as it's just before the 2.2.0 release which added this runtime error.

**Comment by kettanaito** [comment]
Opened a fix in https://github.com/mswjs/msw/pull/2094.

**Comment by kettanaito** [comment]
Also marking this as a duplicate of https://github.com/mswjs/msw/issues/2053.

**Comment by kettanaito** [comment]
## Released: v2.2.6 🎉

This has been released in v2.2.6!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.6)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.6)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by ghost** [comment]
This is still happening in `2.3.1`.

**Comment by SwarupaWare26** [comment]
This is still happening in 2.3.4

**Comment by PedroBarbosaSw** [comment]
This is still happening in `v2.4.0`.

**Comment by parksu0219** [comment]
This is still happening in `v2.4.9`

**Comment by ghost** [comment]
Can we reopen this issue?

**Comment by diego-aquino** [comment]
@mbwestphal, I believe the open issue https://github.com/mswjs/msw/issues/2146 is about the same problem.
