### ISSUE TITLE
drop CommonJS support

### ISSUE THREAD

**Issue by Hajime-san** [kettanaito/msw#2097]
### Scope

Adds a new behavior

### Compatibility

- [X] This is a breaking change

### Feature description

The context is as follows.

https://github.com/nodejs/node/pull/51977

I think that when this changing to be stable and back port to stable node...
- CJS users can `require` ESM library whether it's not contain top level await
- library authors need only publishing ESM

**Comment by ljharb** [comment]
It isn’t even landed yet, so this is very premature for anyone. When it’s landed, and the experimental status and flag is removed, and it’s available in every supported node that way, *then* packages may begin to safely drop CJS support in a semver-major. We’re talking 3-5 years minimum.

**Comment by kettanaito** [comment]
We will drop CommonJS eventually but I agree with @ljharb here. That kind of change will take time to even be considered. Until then, this is closed.
