### ISSUE TITLE
"Cannot read properties of undefined (reading 'get')" when using generators/async generators as resolvers

### ISSUE THREAD

**Issue by juliusmarminge** [kettanaito/msw#2109]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.11

### Reproduction repository

https://github.com/juliusmarminge/msw-async-generator

### Reproduction steps

`bun i && bun run test`

### Current behavior

![CleanShot 2024-03-25 at 13 01 38@2x](https://github.com/mswjs/msw/assets/51714798/ff8cb79c-37f7-4a5b-8a5a-03531594b707)

### Expected behavior

According to the docs here: https://mswjs.io/docs/recipes/polling async generator should be supported

**Comment by juliusmarminge** [comment]
Note that there are 2 issues here:

1. async generators are not allowed on the type level
2. the test fails in runtime

**Comment by kettanaito** [comment]
Hi, @juliusmarminge. Thanks for reporting this! 

I looked into it and indeed uncovered two issues in MSW that caused this. Addressed both in https://github.com/mswjs/msw/pull/2108. Also added missing integration tests for these cases.

**Comment by kettanaito** [comment]
## Released: v2.3.3 🎉

This has been released in v2.3.3!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.3.3)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.3.3)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
