### ISSUE TITLE
`TypeError: crypto.randomUUID is not a function` with msw 2.2.12

### ISSUE THREAD

**Issue by maxime-bc** [kettanaito/msw#2111]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.), Firefox, Safari

### Reproduction repository

https://github.com/maxime-bc/test-msw

### Reproduction steps

`npm install && npx vite --host 0.0.0.0`

Then, try to access the website using both local and network addresses. In the tab accessed by the network address, the error will appear in the console.

Then, downgrade `msw` to 2.2.11 and start the dev server again:
`npm install msw@2.2.11 && npx vite --host 0.0.0.0`

Again, access the website using both local and network addresses. This time the error will not appear.

### Current behavior

Hello,

I'm encountering the following behavior: when accessing a website via its local address,  `msw` works. But when using a network address, the following error is raised in the browser console : `TypeError: crypto.randomUUID is not a function`. 

As far as I understand, this is the intended behavior as `crypto.randomUUID` is only available in secure contexts, such as localhost.

What I found strange is that prior updating to `msw` 2.2.12, I was on version 2.1.4 and I never had any issues with `crypto.randomUUID`, which was introduced in 2.0.0. 

I tried version 2.2.11 and had no issues, the error is not raised at all so it seems to be a problem with version 2.2.12 ?

### Expected behavior

This error should not be raised ?

**Comment by kettanaito** [comment]
Hi, @maxime-bc. Thanks for reporting this!

Looks like an oversight on my part. We cannot rely on `crypto` because it's unavailable in some contexts. TIL. I think this is a good indication we need to migrate to a different ID algorithm.

**Comment by kettanaito** [comment]
Opened the fix in the underlying Interceptors package: https://github.com/mswjs/interceptors/pull/536. Will update the dependency in MSW once it's released.

**Comment by kettanaito** [comment]
## Released: v2.2.13 🎉

This has been released in v2.2.13!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.13)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.13)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
