### ISSUE TITLE
When running Cypress tests in Electron, MSW activation occurs after test completion, causing tests to fail

### ISSUE THREAD

**Issue by jolientb** [kettanaito/msw#2114]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Reproduction repository

https://github.com/jolientb/msw-cypress.git

### Reproduction steps

- Run: npx cypress open
- Choose E2E testing
- Choose the Electron browser
- Click on: Start e2e Testing in Electron
- Click on: spec.cy.ts

### Current behavior

**Cypress test fails in Electron browser**
When you run the cypress e2e test in the Electron browser for the first time the test fails, because msw is only enabled after the test has finished. When running the test again in the same session, msw is enabled on time and the test does succeed.

![msw-cypress](https://github.com/mswjs/msw/assets/165278135/df8a652a-c0e1-41d7-a926-b8cdb4f9036f)

Ps. When running the test in the chrome browser or in Electron 118 (headless) msw is enabled on time, and the test succeeds. And I tried adding an await before worker.start(), but this doesn't solve the problem.

### Expected behavior

**Electron browser: MSW should be enabled before test is completed**
When you run the cypress e2e test in the Electron browser for the first time, msw should be enabled before the test finishes and the test should succeed (just like in the Chrome browser).

**Comment by kettanaito** [comment]
Hi, @jolientb. 

Your [MSW setup](https://github.com/jolientb/msw-cypress/blob/dcd3f02e795f80d8fa73fc45b604b402c6e266f8/src/main.ts#L9) seems good to me. The root cause of your issue is that Cypress doesn't seem to wait for your application to render. You may want to explicitly instruct Cypress to wait until a certain HTML element is visible on the page before running the test suite. 

This is not an MSW issue.
