### ISSUE TITLE
disable prettier as well 

### ISSUE THREAD

**Issue by scr2em** [kettanaito/msw#2120]
### Scope

Improves an existing behavior, I can add it to .prettierignore but I was wondering maybe we can add it in the file itself like the rest

### Compatibility

- [ ] This is a breaking change

### Feature description

my prettier keeps running on the msw file. is it possible to add disable prettier comment as well ? 
```
/* eslint-disable */
/* tslint:disable */

/**
 * Mock Service Worker (2.1.0).
 * @see https://github.com/mswjs/msw
 * - Please do NOT modify this file.
 * - Please do NOT serve this file on production.
 */
 ```

**Comment by kettanaito** [comment]
Hi, @scr2em. 

Configure your Prettier to ignore files in `public`. You should do that even if you aren't using MSW. 

```
// .prettierignore
/public/mockServiceWorker

// Or, even:
/public
```
