### ISSUE TITLE
Missing `await` in the getting started example section for fetch call

### ISSUE THREAD

**Issue by johnsonsamuel** [kettanaito/msw#2142]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.12.0

### Reproduction repository

https://github.com/mswjs/msw/issues

### Reproduction steps

```
// src/index.js
import { server } from './mocks/node'
 
server.listen()
 
// This is a simple Node.js application that
// does a network request and prints the response.
async function app() {
  const response = fetch('https://example.com/user')
  const user = await response.json()
  console.log(user)
}
 
app()

```

### Current behavior

Missing `await` in the getting started example section for fetch call, so response.json fails.

### Expected behavior

Adding `await` to `fetch` call solves the problem.

**Comment by kettanaito** [comment]
Hi, @johnsonsamuel. Can you please point me to the page where you are seeing this?

Neither GitHub README nor our Getting Started guide in the docs have this problem.

**Comment by johnsonsamuel** [comment]
https://mswjs.io/docs/getting-started 

<img width="1039" alt="Screenshot 2024-05-08 at 11 37 43 AM" src="https://github.com/mswjs/msw/assets/4627394/6a5093e1-e021-440b-8f72-9cde24fc228a">

@kettanaito

**Comment by kettanaito** [comment]
@johnsonsamuel, got it! Pushed a fix in https://github.com/mswjs/mswjs.io/pull/395. Thank you for letting me know.

**Comment by johnsonsamuel** [comment]
@kettanaito happy to help 🙏🏽.
