### ISSUE TITLE
Issue when no response.url and request is undefined

### ISSUE THREAD

**Issue by averageokguy** [kettanaito/msw#2164]
https://github.com/mswjs/msw/blob/d97a528914df6a656dfe7b1f63985c85845df533/src/browser/setupWorker/start/createResponseListener.ts#L58

as stated in the title, i'm running into an issue where we're entering this if block because `!response.url === true`. however, request is undefined. this results in error cascading back up the chain. i'm not fully aware of the entire repo architecture at the moment, so i can't raise PR. should this be surrounded with try/catch? check in if condition that `request !== undefined`? use nullish coalescing operator `request?.url ?? ""`? 

thanks in advance!

**Comment by kettanaito** [comment]
I know this came first, but I will close it in favor of #2193.
