### ISSUE TITLE
intercepted request won't abort on node 20 w/ msw@1.3.3

### ISSUE THREAD

**Issue by gerbyzation** [kettanaito/msw#2184]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.6.1

### Reproduction repository

https://github.com/gerbyzation/msw-node20-undici-fetch-abort-repro

### Reproduction steps

Setup:
```
git clone https://github.com/gerbyzation/msw-node20-undici-fetch-abort-repro
cd msw-node20-undici-fetch-abort-repro
pnpm i
```

To demonstrate the abort doesn't work with an MSW handler, but does work without run the two scripts below:
```
node not-working-abort.mjs
node working-abort.mjs
```

### Current behavior

Request completes without throwing an abort error

### Expected behavior

`fetch` should throw an abort error

**Comment by kettanaito** [comment]
I'm sure this is fixed in v2. I have no plans to backport it to v1. Please upgrade to v2 to get this fix. Thanks.
