### ISSUE TITLE
v1: Add generic type to MockedRequest.passthrough()

### ISSUE THREAD

**Issue by sbaechler** [kettanaito/msw#2195]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

This is a quick feature request for v1. 

Currently, `MockedRequest.passthrough()` has the following signature:

    passthrough(): MockedResponse<null>;

This causes type issues when a handler should return a different type.

If the function was generic, we could add the expected return type.

    passthrough<T = null>(): MockedResponse<T>;

**Comment by kettanaito** [comment]
Hi, @sbaechler. Thanks for reporting this. 

I think it's a good idea to backport it to v1. Would you be interested in opening a pull request and seeing this change through? 

1. Fork the repo.
2. Branch from https://github.com/mswjs/msw/tree/backport/v1.
3. Implement the changes.
4. Open a PR to `backport/v1`. I will help with the code reviews and getting the change published. 

I'm afraid I don't have the resources to support v1. It's readonly at this point. You are highly encouraged to update to v2, which brings a ton of improvements.

**Comment by sbaechler** [comment]
I created a merge request. We do plan on update eventually. We tried for a few hours but got nowhere so we had to put the task back into the backlog.

**Comment by kettanaito** [comment]
## Released: v1.3.4 🎉

This has been released in v1.3.4!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v1.3.4)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/1.3.4)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
