### ISSUE TITLE
"Light Mode" in documentation

### ISSUE THREAD

**Issue by ravshansbox** [kettanaito/msw#2201]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Add "Light Mode" to the documentation page

**Comment by kettanaito** [comment]
Hi, @ravshansbox. Thanks for raising this. The effort behind the light mode is tracked here https://github.com/mswjs/mswjs.io/pull/357. It will likely need a huge update after I merge the new site structure.
