### ISSUE TITLE
Document various URL patterns (colon, asterisk etc.)

### ISSUE THREAD

**Issue by silvenon** [kettanaito/msw#2203]
In #2202 it took me a while to figure out how to use MSW with SuperTest. It's making requests to random ports, which MSW is reporting as warnings/errors because they hadn't been intercepted. The goal is to tell MSW to ignore them, because those are requests to our own app.

It's clear that MSW has a parameter component of the URL preceded by the colon, but it seems to also supports an asterisk as a catch-all, which is what I was looking for in this case. However, I seem to have unfortunately combined both of them by preceding the asterisk with the colon and achieved a result that I didn't understand 😬 

Luckily, after removing the colon everything worked as expected. I believe URL patterns should be documented in a way that makes it clear to people how to deal with situations like SuperTest.

Btw, did I stumble upon a bug? I guess URL matching can't really recognize ports vs. params when the URL is not finished.

**Comment by kettanaito** [comment]
Hi, @silvenon. Thanks for raising this!

I believe we do mention the documentation for it. MSW uses a package called [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp), which has become the standard for path matching in JavaScript (used in Express, lies in the foundation of the upcoming `URLPattern` standard API). 

![Screenshot 2024-07-09 at 16 35 33](https://github.com/mswjs/msw/assets/14984911/812b0432-87c6-492b-b339-ced4644a1ca2)

Please read that package's README to learn about the supported special tokens when defining paths. Thanks!

**Comment by kettanaito** [comment]
> Btw, did I stumble upon a bug? I guess URL matching can't really recognize ports vs. params when the URL is not finished.

This does sound like a bug though. Can you please open a new issue for this?

**Comment by silvenon** [comment]
Ah, indeed, there it is, I missed it! 🙂 

I raised the wildcard bug separately in #2204 if anyone wants to follow.
