### ISSUE TITLE
Console log left over 

### ISSUE THREAD

**Issue by Lalem001** [kettanaito/msw#2216]
Any reason console.log was left on the following line?

https://github.com/mswjs/msw/blame/b5960cd/src/core/utils/cookieStore.ts#L194

**Comment by kettanaito** [comment]
Oops! Shouldn't be there. Would you like to help me patch that, @Lalem001?

**Comment by Lalem001** [comment]
@kettanaito Sure, what should I name the branch? Not familiar with your conventions (other than conventional commits)

**Comment by Lalem001** [comment]
I figure out a name

**Comment by kettanaito** [comment]
## Released: v2.3.4 🎉

This has been released in v2.3.4!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.3.4)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.3.4)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
