### ISSUE TITLE
Is it good practice to reference a video tutorial that is behind a pay wall?

### ISSUE THREAD

**Issue by andersoyvind** [kettanaito/msw#2237]
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Make an introductory training video on msw yourself, or make it so that the egghead series linked to in the Introduction section is free of charge. Alternatively make it explicitly clear, that the course is behind a subscription. Or remove the reference, so that new users are not fooled, and will continue reading instead.

**Comment by kettanaito** [comment]
Hi 👋 

You can find free introductory videos on [MSW's YouTube channel](https://www.youtube.com/@ApiMocking). The README also clearly mentions [Documentation](https://mswjs.io/docs) numerous times, which contains everything the Egghead course contains, and much more. And it's free!

The Egghead link is not going anywhere. I've spent years building MSW. I am still building MSW, despite so many companies using it and not giving back. You can support the project by watching the paid courses I do on it. And yes, that is more than a good practice.
