### ISSUE TITLE
XHR Upload events are not being triggered

### ISSUE THREAD

**Issue by gmarcos87** [kettanaito/msw#2263]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Reproduction repository

https://github.com/mswjs/msw/pull/2262

### Reproduction steps

1. Create a XHR request
2. Add event listeners to the upload object https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload
3. Upload a blob using the XHR request

### Current behavior

The upload events are not triggered at any time. This makes it impossible to test any functionality that depends on those events, such as upload progress.

### Expected behavior

Events should be triggered as they normally happen in the browser.

**Comment by AmrElabbasy** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by DavidSousaZ** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by kettanaito** [comment]
Should be fixed by https://github.com/mswjs/msw/releases/tag/v2.4.4. XHR now correctly triggers upload events in Node.js (and browser-like). In the browser, that should've been working before as was.
