### ISSUE TITLE
Module not found: Error: Can't resolve 'graphql'

### ISSUE THREAD

**Issue by kguptaping** [kettanaito/msw#2264]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/kguptaping/msw-issue

### Reproduction steps

`cd <folder>`
`yarn`
`npx msw init public --save`
`yarn start`

### Current behavior

Error: 
`ERROR in ./node_modules/msw/lib/core/utils/internal/parseGraphQLRequest.mjs 17:12-29
Module not found: Error: Can't resolve 'graphql' in '/Users/<user>/codebase/node_modules/msw/lib/core/utils/internal'
` 

### Expected behavior

Should not show any issue.

**Comment by kettanaito** [comment]
## Released: v2.4.3 🎉

This has been released in v2.4.3!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.4.3)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.4.3)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
