### ISSUE TITLE
Node.js (Undici) fetch doesn't follow redirects when mocked with MSW

### ISSUE THREAD

**Issue by islazh** [kettanaito/msw#2266]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

22.8.0

### Reproduction repository

https://github.com/islazh/msw-redirection-bug-repro

### Reproduction steps

# Steps to reproduce

- run `nvm use`
- run `corepack enable`
- run `pnpm install`
- run `pnpm test`

### Current behavior

The requests do not automatically "follow" the redirect and a 302 is returned in the response with Location header. The test fails as a result.

### Expected behavior

The requests should "follow" the redirect and progress to /redirected. The response status should be 200 with whatever HTML is returned.

**Comment by kettanaito** [comment]
Hi, @islazh. Thanks for reporting this.

Could you please check how is your issue different from #2177? I know you are not using Axios, but I suspect the root cause for this behavior is the same. Thanks.

**Comment by kettanaito** [comment]
Closed in favor of https://github.com/mswjs/interceptors/issues/626. Please follow the updates there.
