### ISSUE TITLE
Mocked response cookie persists after sending `max-age=0`

### ISSUE THREAD

**Issue by TinsFox** [kettanaito/msw#2272]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/TinsFox/mws-example

### Reproduction steps

1. pnpm install
2. pnpm dev
3. open chrome devtools
4. Click `Get User` button and observe the console output
5. Click `Login` button and observe the cookie in devtool
6.  Click `Get User` button and observe the console output, you can find cookie in output
7. Click `Logout` button
8. Click the `Get User` button and observe the console output. You will find that the cookie is still not empty, but the cookie set when logging in before.

### Current behavior

Whether I clear the cookies through the API or manually clear the cookies, when I clear the cookies and then request the API, I can still get the old cookies.

### Expected behavior

After I clear the cookie, the cookie obtained by requesting the API should be empty instead of the previously set one.

**Comment by TinsFox** [comment]
After a few hours of troubleshooting, I got some useful information. Everything works fine in v2.2.2, but I'm using v2.4.4.

I found that MSW_COOKIE_STORE in localStorage will be read and written in v2.4.4, but v2.2.2 will not.

**Comment by kettanaito** [comment]
@TinsFox, thanks for reporting this!

Your observation is correct. We've moved away from a custom cookie store to using `CookieJar` (see https://github.com/mswjs/msw/pull/2206). 

At first glance, looks like the `CookieJar` isn't reacting to you sending a `max-age=0` response. This is likely an issue on our end. 

When MSW received that `max-age=0` response, here's what it does. First, it propagates it to `document.cookie`:

https://github.com/mswjs/msw/blob/1263c0f03f2ea9b20b0bee80adaa261f0e0ed67c/src/core/utils/HttpResponse/decorators.ts#L67-L72

When the next request happens, here's where it decides which cookies will be exposed to that request:

https://github.com/mswjs/msw/blob/1263c0f03f2ea9b20b0bee80adaa261f0e0ed67c/src/core/utils/request/getRequestCookies.ts#L67-L71

There are multiple cookie groups:

- Cookies present in `document.cookie` and matching the request's `credentials` property;
- Cookies present in the request's `cookie` header;
- Cookies present in the cookie store matching this request URL.

**Comment by kettanaito** [comment]
I've added a failing test in https://github.com/mswjs/msw/pull/2275, which confirms that we've got a bug.

**Comment by kettanaito** [comment]
I can confirm that the incorrectly present cookie comes from the cookie store:

<img width="875" alt="Screenshot 2024-09-10 at 16 52 37" src="https://github.com/user-attachments/assets/186e99c6-fe9c-4b6a-8c46-792303baf184">

> `document.cookie` is also `''` empty as expected.

If I take a look at the store, I can see _two_ entries for the same `mockedCookie` after receiving the mocked response with `max-age=0`:

<img width="711" alt="Screenshot 2024-09-10 at 16 54 04" src="https://github.com/user-attachments/assets/bfcf1b51-3b68-4cbd-8b03-bdc08dcb52f7">

However, after the final `GET` request, the cookie store is (correctly) empty. Maybe that suggests that we aren't removing the `max-age=0` cookies at the right time (e.g. removing them on getting the values instead of receiving the value in the store).

**Comment by kettanaito** [comment]
Pushed a fix in 517c8f265dee1e7e37c20d9966a58c8b2a5a1ddc.

**Comment by kettanaito** [comment]
## Released: v2.4.5 🎉

This has been released in v2.4.5!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.4.5)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.4.5)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by TinsFox** [comment]
@kettanaito Thanks!

But it doesn’t seem to be completely repaired.

I forgot to add a scenario where I would manually clear cookies from devtool.

I have upgraded my reproduction repository to 2.4.5. Please check again if there is any problem during this operation. Thank you very much!

Here is my operation video
https://share.cleanshot.com/qr2d8X4l
