### ISSUE TITLE
TypeError: Cannot redefine property: Request at Function.defineProperty (<anonymous>)

### ISSUE THREAD

**Issue by AdrienFromToulouse** [kettanaito/msw#2286]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20

### Reproduction repository

https://donthavearepotoshare.com

### Reproduction steps

Hi, since `2.4.4` there was this issue https://github.com/mswjs/msw/issues/2276 unfortunately the `2.4.7` version has still some issues it seems. With the error `TypeError: Cannot redefine property: Request at Function.defineProperty (<anonymous>)`
I think linked to: https://github.com/mswjs/msw/pull/2283

Cheers,

### Current behavior

TypeError: Cannot redefine property: Request at Function.defineProperty (<anonymous>)

### Expected behavior

No error.

**Comment by kettanaito** [comment]
Hi, @AdrienFromToulouse. Thanks for reporting this. Sadly, I cannot look into issues without a reproduction repo. Whomever encountering this also are highly encouraged to provide one. Thank you for understanding.

**Comment by rafaelji** [comment]
I'm facing the same problem! Couldn't find a solution 😞

**Comment by jcrang** [comment]
For us this was an issue with the recommended Jest polyfills.

We've resolved this by changing the recommended Jest polyfills to make `Request` and `Reponse` configurable.

PR for the docs change https://github.com/mswjs/mswjs.io/pull/416

**Comment by AdrienFromToulouse** [comment]
> For us this was an issue with the recommended Jest polyfills.
> 
> We've resolved this by changing the recommended Jest polyfills to make `Request` and `Reponse` configurable.
> 
> PR for the docs change [mswjs/mswjs.io#416](https://github.com/mswjs/mswjs.io/pull/416)

Many thanks for pointing that out @jcrang works like a charm now 🙏
