### ISSUE TITLE
Memory Leak while running e2e test.

### ISSUE THREAD

**Issue by aq1018** [kettanaito/msw#2289]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v22.8.0

### Reproduction repository

https://github.com/think-life/msw-memory-leak

## Positive Test

1. clone the [reproduction repository](https://github.com/think-life/msw-memory-leak)
2. run `npm install`
3. run `node --expose-gc --no-compilation-cache ./node_modules/.bin/jest --silent  --runInBand --detectOpenHandles --logHeapUsage`

You will see something like:

```
 PASS  test/e2e/i.spec.ts (201 MB heap size)
 PASS  test/e2e/a.spec.ts (214 MB heap size)
 PASS  test/e2e/h.spec.ts (224 MB heap size)
 PASS  test/e2e/d.spec.ts (233 MB heap size)
 PASS  test/e2e/k.spec.ts (243 MB heap size)
 PASS  test/e2e/f.spec.ts (253 MB heap size)
 PASS  test/e2e/l.spec.ts (262 MB heap size)
 PASS  test/e2e/c.spec.ts (272 MB heap size)
 PASS  test/e2e/j.spec.ts (282 MB heap size)
 PASS  test/e2e/e.spec.ts (291 MB heap size)
 PASS  test/e2e/b.spec.ts (301 MB heap size)
 PASS  test/e2e/g.spec.ts (310 MB heap size)
```

Notice the heap size keeps increasing.

Note, I added `global.gc()` in `afterAll` so that GC is run at the end of each test suite.

## Negative Test

1. Edit the `package.json` file, and change the `msw` version number to `2.4.3`.
2. Run `npm install`
3. Run `node --expose-gc --no-compilation-cache ./node_modules/.bin/jest --silent  --runInBand --detectOpenHandles --logHeapUsage`

You will see something like this:

```
 PASS  test/e2e/i.spec.ts (205 MB heap size)
 PASS  test/e2e/h.spec.ts (218 MB heap size)
 PASS  test/e2e/d.spec.ts (218 MB heap size)
 PASS  test/e2e/f.spec.ts (218 MB heap size)
 PASS  test/e2e/k.spec.ts (219 MB heap size)
 PASS  test/e2e/j.spec.ts (219 MB heap size)
 PASS  test/e2e/e.spec.ts (219 MB heap size)
 PASS  test/e2e/l.spec.ts (219 MB heap size)
 PASS  test/e2e/c.spec.ts (220 MB heap size)
 PASS  test/e2e/a.spec.ts (220 MB heap size)
 PASS  test/e2e/g.spec.ts (220 MB heap size)
 PASS  test/e2e/b.spec.ts (220 MB heap size)
```

Although it is still increasing in size, the magnitude is much smaller.

### Current behavior

Memory usage keep increasing. It seems the interaction between `@msw/interceptors`, `supertest`, and `nestjs` server is causing memory not being GC'ed properly.

### Expected behavior

Memory usage should be relatively stable.

**Comment by kettanaito** [comment]
Hi, @aq1018. Thanks for reporting this!

Can you please try this in Vite? We are not addressing Jest-related issues (see [this](https://github.com/mswjs/msw/blob/5342c19ee53f517b39128de30c5e24230d1c122f/decisions/jest-support.md)). Until we can confirm this is happening in modern test runners, I will close the issue.

**Comment by aq1018** [comment]
Hi @kettanaito,

I create [a new branch](https://github.com/think-life/msw-memory-leak/tree/vitest) on my test repo to use `vitest`, and it does not leak memory.

I'm sold on `vitest`.
