### ISSUE TITLE
XMLHttpRequest FormData / File upload never resolves

### ISSUE THREAD

**Issue by ondrejsevcik** [kettanaito/msw#2326]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.14.0

### Reproduction repository

https://github.com/ondrejsevcik/msw-xhr-upload-issues

### Reproduction steps

The reproduction repository contains two tests. One is firing an XHR request, and the other one is firing an XHR request with a FormData body.

If you use v2.4.3, the tests will pass. When using version 2.4.4+ it fails.

1. npm install
2. npm run test

### Current behavior

The XHR request with FormData never resolves. This has worked fine previously, but since [version 2.4.4](https://github.com/mswjs/msw/releases/tag/v2.4.4), it does not work anymore.

### Expected behavior

It is possible to upload file / FormData with msw using XMLHttpRequest.

**Comment by kibertoad** [comment]
@kettanaito Most likely related to this change: `Adopts a new, Socket-based request interception algorithm.`

**Comment by roastnewt** [comment]
I am encountering the same issue

**Comment by LarsJK** [comment]
I am also encountering this, but only on linux. On my Mac it works fine. What OS are you using?

**Comment by roastnewt** [comment]
Windows. And also in our Ubuntu build/test pipeline

**Comment by RabbitShare** [comment]
Same issue on Mac and Debian. Node v22.11.0

**Comment by RabbitShare** [comment]
Also example from documentation not working https://mswjs.io/docs/recipes/file-uploads/

**Comment by veekeys** [comment]
Getting same only on Linux (windows and mac work fine).
Has there been any work started on this?

**Comment by sayedMurtadha** [comment]
I had a similar issue and it worked only on Node V18. I tried with V20, V21, and V22, all of them failed the tests.

**Comment by kettanaito** [comment]
@ondrejsevcik, the reproduction repository has its tests successfully passing without any changes:

```sh
> msw-xhr-upload-issues@1.0.0 test
> vitest run


 RUN  v2.1.3 /Users/kettanaito/Projects/contrib/msw-2326

 ✓ src/upload-issues.test.tsx (2)
   ✓ upload-issues (2)
     ✓ handles JSON POST request
     ✓ handles POST file upload

 Test Files  1 passed (1)
      Tests  2 passed (2)
   Start at  15:43:23
   Duration  725ms (transform 37ms, setup 0ms, collect 56ms, tests 52ms, environment 285ms, prepare 81ms)
```

I can confirm the upload request triggers the request handler and gets handled as described in it. Works on both Node.js v18 and v20. 

@RabbitShare, submit a reproduction repo to prove it's not working. We have an extensive test suite for XMLHttpRequest, and all the tests are passing. 

What often helps is:

1. Make sure you are on the latest Node.js. There's been a number of issues related to `FormData` over the years, and you only get the fixes to those if you update your version of Node.js, so please do so.
2. Make sure you are on the latest `msw`.
3. Don't use JSDOM. If you must, use HappyDOM instead.

**Comment by kibertoad** [comment]
@kettanaito What OS are you using? I think it was already mentioned that it works fine on Mac OS.

I can confirm the original repro from the repo failing on Windows without any changes:

![image](https://github.com/user-attachments/assets/94a017b8-d3f2-447d-8d4b-8e2057b10484)

**Comment by kettanaito** [comment]
MSW ships no platform-specific code so this doesn't look like our issue to address. I suggest debugging it, looking at JSDOM and Node.js as the first potentially problematic layers.

**Comment by kibertoad** [comment]
@kettanaito Why would it regress on specific versions of msw then?

**Comment by LarsJK** [comment]
It looks like it is only an issue with msw + jsdom on linux.

I added a test that uses a node webservere and only the ones using msw fail.

No tests fail if I use happydom.

https://github.com/LarsJK/msw-xhr-upload-issues/actions/runs/12083712508/job/33697417110

**Comment by LarsJK** [comment]
More info:

It looks like jsdom doesnt include an empty json object in the request

**jsdom + msw**
```
------formdata-undici-072483690769
Content-Disposition: form-data; name="file"; filename="test.json"
Content-Type: application/json


------formdata-undici-072483690769--
```

**jsdom + node**
```
----------------------------767463351636047866406519
Content-Disposition: form-data; name="file"; filename="test.json"
Content-Type: application/json

{}
----------------------------767463351636047866406519--

```

**happy-dom + msw**
```
------HappyDOMFormDataBoundary0.edtoy14x6yp
Content-Disposition: form-data; name="file"; filename="test.json"
Content-Type: application/json

{}

```

**happy-dom + node**
```
------HappyDOMFormDataBoundary0.7aso9fkxkgh
Content-Disposition: form-data; name="file"; filename="test.json"
Content-Type: application/json

{}

```

So that probably means its a jsdom issue?

If this is the issue it is probably related to jsdom/jsdom#3800

**Comment by kettanaito** [comment]
There's is an issue reported to Interceptors that may be causing this: https://github.com/mswjs/interceptors/issues/684. Follow the PR for that issue, try it out, and let me know if it fixes the problem. Thanks.

**Comment by kettanaito** [comment]
@LarsJK, not sure. I generally don't look into issues related to JSDOM, so I recommend you try to reproduce this in Vitest+HappyDOM instead. If it's broken there, it's more likely to be an MSW issue. 

@kibertoad, a good point. See the issue reference above.

**Comment by sayedMurtadha** [comment]
Replacing JSDOM with HappyDOM resolved the issue for me on node versions newer than v18. At first, I tried the interceptors update without switching to HappyDOM to confirm, but that did not resolve the issue.
