### ISSUE TITLE
TS1005: ',' expected.

### ISSUE THREAD

**Issue by GonEbal** [kettanaito/msw#2358]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/mswjs/examples

### Reproduction steps

I followed these steps to set up msw in storybook: https://storybook.js.org/docs/writing-stories/mocking-data-and-modules/mocking-network-requests

### Current behavior

Getting `TS1005: ',' expected.` errors.

**Versions:**
_Global:_
`npm: 8.19.2`
`node: 18.12.0`
_Repo:_
`"typescript": "4.4.4"`
`"msw": "2.6.4"`
`"msw-storybook-addon": "2.0.4"`

<img width="1114" alt="Screenshot 2024-11-14 at 12 19 19 PM" src="https://github.com/user-attachments/assets/109bdea7-3825-467d-9f7e-aa8184fac0c6">

### Expected behavior

`TS1005: ',' expected.` errors should not be present

**Comment by kettanaito** [comment]
Hi, @GonEbal. Thanks for reporting this. 

MSW requires TypeScript 4.8 and higher, you seem to be using TS 4.4, which has reached end-of-life. Please upgrade the TypeScript version and have the issue solved.

**Comment by GonEbal** [comment]
Thanks! That resolves the issue! Also needed to update `ts-loader` to work with 4.8 TypeScript version

**Comment by kettanaito** [comment]
@GonEbal, great job! Glad that helped.
