### ISSUE TITLE
Callback not being executed in server.boundary with jest and react testing library

### ISSUE THREAD

**Issue by kmmccafferty96** [kettanaito/msw#2366]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.12.1

### Reproduction repository

https://github.com/kmmccafferty96/msw-server-boundary-issue-reproduction

### Reproduction steps

1. Run `npm install`
2. Run `npm test`

Note that both tests pass even though the second should not. Also to note, the first writes to the console but the second does not.

### Current behavior

When using jest with react-testing-library, the callback supplied to `server.boundary()` is seemingly not executed and tests pass no matter what.

### Expected behavior

The callback should be executed and tests should be ran properly.

**Comment by kettanaito** [comment]
Hi, @kmmccafferty96. Thanks for sharing this.

It appears you aren't using `server.boundary()` correctly:

https://github.com/kmmccafferty96/msw-server-boundary-issue-reproduction/blob/f702a6ed51c4956e3c64225b62da0bf1e74c4c85/src/MyComponent.test.jsx#L33-L34

This block should look like this:

```ts
it('renders data fetched on load with server boundary', server.boundary(async () => {
```

Once you rewrite it this way, the test will run correctly. 

`server.boundary()` _returns a function_. Right now, it returns a function and you never run it.

**Comment by kmmccafferty96** [comment]
Ah, I misread the docs. Makes sense. Thank you @kettanaito!
