### ISSUE TITLE
Failed to write to a request stream: stream does not exist with `dd-trace`

### ISSUE THREAD

**Issue by marouanekadiri** [kettanaito/msw#2373]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.18.0

### Reproduction repository

N/A

### Reproduction steps

```
const { setupServer } = require('msw/node');
const tracer = require('dd-trace');

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

const main = async () => {
    const handlers = []
    const server = setupServer(...handlers);
    
    server.listen({
        onUnhandledRequest: 'bypass'
    });

    tracer.init({
        logInjection: true,
        runtimeMetrics: true
    })

    await sleep(50000)

}

main();
```

Just by running this simple node script I managed to reproduce it.
I'm using msw@2.6.6

### Current behavior

It is currently failing with `Invariant Violation: Failed to write to a request stream: stream does not exist` when dd-trace tries to call `GET http://127.0.0.1:8126/dogstatsd/v2/proxy`.

### Expected behavior

It shouldn't fail and it should `passthrough` properly.

**Comment by letehaha** [comment]
I have a similar issue 👍

**Comment by kettanaito** [comment]
Hi, @marouanekadiri. Thanks for reporting this, but I cannot look into the issue unless you post a minimal reproduction repository. Please do so, and let's look at what's going on here. Thanks.
