### ISSUE TITLE
vuedevtools style exception when used with msw v2.6.4+

### ISSUE THREAD

**Issue by jerrywu001** [kettanaito/msw#2374]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

.

### Reproduction steps

[vuedevtools-msw2.6.4.zip](https://github.com/user-attachments/files/17953406/vuedevtools-msw2.6.4.zip)

from this version msw@2.6.4, [commit](https://github.com/mswjs/msw/commit/2fa98c327acc51189f87789d9155c4ec57be2299)

1. download the `vuedevtools-msw2.6.4.zip`
2. `pnpm i`
3. `npm run dev`

**Follow the steps below to reproduce the problem**

![image](https://github.com/user-attachments/assets/a29c984f-98c3-4e84-ae9c-25fce9abd0b6)

**like this**

![image](https://github.com/user-attachments/assets/62dc30b7-ee5d-440c-b97b-d272439b6f8d)

**then click the "vue logo"**

**got it**

![image](https://github.com/user-attachments/assets/4164c2ba-b4df-43ef-bbd7-2fd07665909e)

### Current behavior

[vuedevtools-msw2.6.4.zip](https://github.com/user-attachments/files/17953406/vuedevtools-msw2.6.4.zip)

from this version msw@2.6.4, [commit](https://github.com/mswjs/msw/commit/2fa98c327acc51189f87789d9155c4ec57be2299)

1. download the `vuedevtools-msw2.6.4.zip`
2. `pnpm i`
3. `npm run dev`

**Follow the steps below to reproduce the problem**

![image](https://github.com/user-attachments/assets/a29c984f-98c3-4e84-ae9c-25fce9abd0b6)

**like this**

![image](https://github.com/user-attachments/assets/62dc30b7-ee5d-440c-b97b-d272439b6f8d)

**then click the "vue logo"**

**got it**

![image](https://github.com/user-attachments/assets/4164c2ba-b4df-43ef-bbd7-2fd07665909e)

### Expected behavior

[vuedevtools-msw2.6.4.zip](https://github.com/user-attachments/files/17953406/vuedevtools-msw2.6.4.zip)

from this version msw@2.6.4, [commit](https://github.com/mswjs/msw/commit/2fa98c327acc51189f87789d9155c4ec57be2299)

1. download the `vuedevtools-msw2.6.4.zip`
2. `pnpm i`
3. `npm run dev`

**Follow the steps below to reproduce the problem**

![image](https://github.com/user-attachments/assets/a29c984f-98c3-4e84-ae9c-25fce9abd0b6)

**like this**

![image](https://github.com/user-attachments/assets/62dc30b7-ee5d-440c-b97b-d272439b6f8d)

**then click the "vue logo"**

**got it**

![image](https://github.com/user-attachments/assets/4164c2ba-b4df-43ef-bbd7-2fd07665909e)

**Comment by kettanaito** [comment]
Hi, @jerrywu001. Could you please double-check the current/expected behaviors descriptions of this issue? They seem to contain the instructions again instead of describing what's supposed to happen. I don't understand the issue based on the screenshots alone. Please provide more context, then I can look into it. Thanks.
