### ISSUE TITLE
argument name is invalid

### ISSUE THREAD

**Issue by coderlzw-cn** [kettanaito/msw#2378]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

none

### Reproduction steps

Isn’t it possible to configure the proxy mode of nginx? The project uses http
<img width="1320" alt="image" src="https://github.com/user-attachments/assets/8fc94289-f17b-473e-aef5-ed47cdf297b5">

<img width="1519" alt="image" src="https://github.com/user-attachments/assets/576be7df-095a-4ce6-b55b-90d2201b9f0b">
<img width="793" alt="image" src="https://github.com/user-attachments/assets/29067d9f-8d2a-4a69-89a6-be46741a3420">

### Current behavior

<img width="1519" alt="image" src="https://github.com/user-attachments/assets/576be7df-095a-4ce6-b55b-90d2201b9f0b">

### Expected behavior

What should I do to allow the mock to access it normally?

**Comment by kettanaito** [comment]
Hi, @coderlzw-cn. As the error suggests, some of the request cookies you have contain invalid data. I suspect it may be a name or a value forbidden by the spec.

Please submit a minimal reproduction repo so I could help you.

**Comment by ahmedrowaihi** [comment]
it's caused due to an invalid cookie name, 
the [@bundled-es-modules/cookie](https://github.com/mswjs/msw/blob/de3bedf8fd9376920add73ef823827dce3593ac9/src/core/utils/request/getRequestCookies.ts#L1C26-L1C53) is using  [cookie](https://github.com/jshttp/cookie/blob/master/src/index.ts)

so just open you localhost in the browser and clear all localhost cookies.

**Comment by ahmedrowaihi** [comment]
whatever your browser is, you can clear cookies in Inspect -> Application -> cookie 

note: be sure you are on localhost or whatever hostname your msw is served from

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/d2f22b83-f2be-4909-bf60-c010bc290888">
