### ISSUE TITLE
msw breaks styling

### ISSUE THREAD

**Issue by massimopalmieri** [kettanaito/msw#2380]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Reproduction repository

https://github.com/massimopalmieri/msw-style

### Reproduction steps

```
npm install
npm run dev
```
- open http://localhost:5173
- notice the black background and white text
- make any change to app/routes/_index/route.tsx and save

### Current behavior

after a hmr update, the page doesn't have any styling

### Expected behavior

the page should keep the styling

Note: 
This bug cannot be reproduced in msw v1

**Comment by kettanaito** [comment]
Hi, @massimopalmieri. Thanks for reporting this. 

MSW should be affecting your styles. I've encountered a similar issue in Remix, and what helped was switching how I include my styles in the app. Here's what you can do.

## 1. Upgrade Remix

Make sure you are on the latest version of Remix and all its dependencies before continuing. 

## 2. Import styles directly

Right now, you include them as a URL string (`?url`) in [here](https://github.com/massimopalmieri/msw-style/blob/779263fec51e941ef93f64f7c5a819f84fddfe14/app/root.tsx#L2). Try changing that to an import, which will parse the styles and include them in the app:

```diff
-import stylesheet from "./app.css?url";
+import "./app.css";
import { ReactNode } from "react";
import { Route } from "./+types/root";

export const links: Route.LinksFunction = () => [
-  { rel: "stylesheet", href: stylesheet },
];
```

Once you tried these steps, let me know. If it doesn't help, I will take a look at what else you can do.

**Comment by massimopalmieri** [comment]
Hi @kettanaito. Thanks for your help. 

I upgraded to v2.6.7 and the issue is gone. If it occurs again, I’ll be sure to let you know.
