### ISSUE TITLE
Using Typescript lib es2024 and arrayBuffer, types are hard to use

### ISSUE THREAD

**Issue by danilofuchs** [kettanaito/msw#2388]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v22.12.0

### Reproduction repository

https://github.com/danilofuchs/examples/blob/main/index.ts

### Reproduction steps

- Set lib to `es2024` or `esnext` to use features such as `Object.groupBy`
- Read a file using `readFile` or create a mocked buffer using `Buffer.from("fake-file")`
- Try to pass this to `HttpResponse.arrayBuffer`

### Current behavior

Typescript does not allow, but msw accepts it in runtime:

![image](https://github.com/user-attachments/assets/902fcf3f-67e7-47ad-8f27-012eb77e575b)

### Expected behavior

Previous lib versions works as expected

This is due to the introduction of `SharedArrayBuffer` in lib es2024

Using the output of readFileSync is documented as supported by msw:
![image](https://github.com/user-attachments/assets/5d7c89c5-73e1-4a1d-b86f-734bbb146606)

**Comment by kettanaito** [comment]
## Released: v2.6.9 🎉

This has been released in v2.6.9!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.6.9)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.6.9)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by danilofuchs** [comment]
@kettanaito I think my fix was not effective, we will have to reopen this and think of a different strategy:

![image](https://github.com/user-attachments/assets/89e450e9-5022-45ea-88dc-7e6beb9b7991)

lib es2024 added these required properties to `ArrayBuffer` that are not present in Node.js `Buffer`:

![image](https://github.com/user-attachments/assets/da12c7e7-bbd2-418f-9897-b022dcc4c653)

I understand `msw` core should not know about `Node.js` buffers and should understand Web Standards only (ArrayBuffer, SharedArrayBuffer), so it may be necessary to implement some sort of `ArrayBufferLike` interface that also allows Buffer to function

**Comment by danilofuchs** [comment]
Using `ArrayBufferView` as the parameter type (present in lib `dom`, same interface allowed in `BodyInit`) solves the issue for Buffers, but does not allow a SharedArrayBuffer:

![image](https://github.com/user-attachments/assets/769f7914-f5d1-418a-9e7c-b961ac09a684)

**Comment by kettanaito** [comment]
@danilofuchs, we need to also consider if that's a bug someplace else, we likely shouldn't be accommodating it in MSW, to begin with. Type casting would be a more preferable approach before the bug is fixed.

From my experience, `Buffer.from()` never produces `ArrayBuffer`.

**Comment by l-astro** [comment]
Is it possible to re-open this issue please? Casting buffer as ArrayBufferView doesn't seem to help here.
