### ISSUE TITLE
`graphql.operation` cannot intercept the unnamed graphql

### ISSUE THREAD

**Issue by andykao1213** [kettanaito/msw#918]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.35.0   |
| browser | Chrome  v93.0.4577.82   |
| OS      |   MacOS v11.5.2   |

## Request handlers

```js
import { setupWorker, rest } from 'msw'

const worker = setupWorker(
  graphql.operation((res, req, ctx) => {
    // ...
  })
)

worker.start()
```

## Actual request

```js
import { request, gql } from "graphql-request";

const query = gql`
  {
    hero {
      name
      friends {
        name
      }
    }
  }
`;

request("/", query)
```

## Current behavior

The handler didn't work, and there is a warning in the console:
```
[MSW] Failed to intercept a GraphQL request at "POST /": unnamed GraphQL operations are not supported.

Consider naming this operation or using "graphql.operation" request handler to intercept GraphQL requests regardless of their operation name/type. Read more: https://mswjs.io/docs/api/graphql/operation    
```
Note that using `rest.post` is workable:
```js
rest.post(/\//, (res, req, ctx) => {
   // ...
})
```

## Expected behavior

The handlers should works.

## Screenshots

Here is a reproducible [codesandbox](https://codesandbox.io/s/runtime-leftpad-okgvp?file=/src/App.js).

Finally, thanks for the fantastic library 🙌.  MSW helps my daily work a lot! Please let me know if there is anything I can help with this issue.

**Comment by kettanaito** [comment]
Hey, @andykao1213. Thank you for reporting this!

We are aware of this issue and collaborating with @neilime who has already implemented a fix! Please await the next release.

**Comment by andykao1213** [comment]
@kettanaito Thanks for the fast reply. Looking forward to the next release!

**Comment by anentropic** [comment]
I am getting this error too
```
   [MSW] Failed to intercept a GraphQL request at "POST <my gql endpoint>": anonymous GraphQL operations are not supported.

    Consider naming this operation or using "graphql.operation" request handler to intercept GraphQL requests regardless of their operation name/type. Read more: https://mswjs.io/docs/api/graphql/operation
```

But I don't understand what the problem is and the docs linked in the error don't explain it

**Comment by kettanaito** [comment]
Hey, @anentropic. 

The error message implies you're not using `graphql.operation` to intercept a request. Can you share a reproduction repository when this issue happens for you? 

It looks like you're using `graphql.query`/`graphql.mutation` with an anonymous operation. That is, in fact, not supported. 

Also, make sure you're using the latest `msw` package so you have the fix for this.

**Comment by anentropic** [comment]
thanks... the part that was confusing me is, as far as I can tell, the mutation was not anonymous

I was tired and frustrated yesterday and couldn't see any way to debug what was wrong - msw didn't give enough info about the requests it was complaining about (like e.g. the request body), and VS Code debugger didn't seem to want to step into the handler function

I gave up today and just mocked the graphql-request client directly

anyway, I apologise for the low quality drive-by comment, my best wishes

**Comment by R4YM3** [comment]
For others who find this, i had this issue aswell.
It did a mutation like this:

```
updateSomething(input: $input){
  foo
  bar
}
```

but it should have been:
```
mutation UpdateSomething($input: UpdateSomethingInput){
  updateSomething(input: $input){
    foo
    bar
  }
}
```

Regards
