### ISSUE TITLE
`server.events` is undefined in msw/node (so life-cycle events are inaccessible)

### ISSUE THREAD

**Issue by buob** [kettanaito/msw#924]
## Describe the bug

I'm trying to follow the example for [Asserting request payload](https://mswjs.io/docs/extensions/life-cycle-events#asserting-request-payload), but I'm getting an error saying server.events is undefined:

```js
TypeError: Cannot read property 'on' of undefined

       6 |   let requestId = ""
       7 |   return new Promise((resolve, reject) => {
    >  8 |     server.events.on("request:start", req => {
```

console.logging the server after setup:

```js
    {
      server: {
        listen: [Function: listen],
        use: [Function: use],
        restoreHandlers: [Function: restoreHandlers],
        resetHandlers: [Function: resetHandlers],
        close: [Function: close]
      }
    }
```

## Environment

- `msw: 0.20.5`
- `nodejs: 14.17.0`
- `npm: 6.14.13`

I removed extra sections that seemed unapplicable, but can add more details. Thank you very much!

**Comment by kettanaito** [comment]
Hey. Please use the latest version of MSW, which is 0.35.0 right now. Run npm install msw@latest.
