### ISSUE TITLE
Usage of different word than "master" in src/mockServiceWorker.js

### ISSUE THREAD

**Issue by wwahammy** [kettanaito/msw#953]
First off, I absolutely love msw so far. It's such an elegant solution to so many related problems across all kinds of testing.

One change I'm hoping that the community would consider is removing the word "master" from the msw. A lot of people feel really uncomfortable with usage of the word master in code and many Black developers find it quite offputting. While I would encourage any project community to consider removing the word "master", msw is in bit of a unique situation: the code in `src/mockServiceWorker.js` is included in the repo of any project using msw. For projects who want to be especially inclusive, using msw means [including a term](https://github.com/mswjs/msw/blob/55eb6544ea901b32b78f240e278a3b9122cd9d56/src/mockServiceWorker.js#L90) they're trying to remove from their code base.

Looking at the code, I don't believe that the `resolveMasterClient` function is considered part of the external API of msw. Additionally, it only seems to be [used once](https://github.com/mswjs/msw/blob/55eb6544ea901b32b78f240e278a3b9122cd9d56/src/mockServiceWorker.js#L112), in the `handleRequest` function. So I don't believe a change would cause any technical problems to users. Would the terms "canonical" or "primary" be equivalent for this use-case? If the msw team is agreeable, I am happy to make a (very small) PR with the change.

Thanks for your consideration and for the amazing work you've done with msw; it's truly an amazing tool!

**Comment by kettanaito** [comment]
Hey, @wwahammy. Thank you for your kind words!

We work hard on making MSW a great developer experience, and we cannot achieve that without feedback from our community. Inclusion and diversity are the essential qualities of an open-minded world, which we entirely support.

I think in the context of this function we wish to look up the initial client that registered the worker, so adopting function names like `findMainClient` or `findInitialClient` would complement the intention rather well. Feel free to open a pull request with the change, I'd be happy to help you with the code review!

**Comment by msutkowski** [comment]
> Hey, @wwahammy. Thank you for your kind words!
> 
> We work hard on making MSW a great developer experience, and we cannot achieve that without feedback from our community. Inclusion and diversity are the essential qualities of an open-minded world, which we entirely support.
> 
> I think in the context of this function we wish to look up the initial client that registered the worker, so adopting function names like `findMainClient` or `findInitialClient` would complement the intention rather well. Feel free to open a pull request with the change, I'd be happy to help you with the code review!

@kettanaito While we're at it, should we tackle renaming the primary branches from `master` -> `main` as well? It'd take a little bit of time, but we can probably just get this in across all msw-related repos. I can also do a pass on the copy in all of the other repos as well and issue PRs where appropriate.

The thing to consider on our end is that we might have to reconnect any github apps like codesandbox ci _(shouldn't be an issue)_ that track specific branches. I can research this beforehand though :tada:

**Comment by wwahammy** [comment]
@kettanaito thanks for your commitment to inclusion! The linked PR has a changed the references from 'master' client to 'main' client. Thanks once again for the great work you've done msw.

@msutkowski I would also support the rename from master to main but I chose not to address that in my original issue because I wasn't sure how my original concern would be received :smile:

**Comment by cliffordfajardo** [comment]
Thank you for the commit @wwahammy!
Adding a data point:
- A few tools at large companies (LinkedIn etc) now have code scanners that run during pull requests look for non-inclusive keywords. If there is a non-inclisive keyword we either have to fix it or add a eslint-like code comment above it explaining the context of the word.
