### ISSUE TITLE
POST request being fired, but GET method got intercepted

### ISSUE THREAD

**Issue by tiffanyhuang517** [kettanaito/msw#956]
I'm using React + [ReuxToolkit](https://redux-toolkit.js.org/rtk-query/overview) to fire a POST request, 

```
//API slice
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

import { RootState } from 'src/redux/store/ReduxStore';
import { valveAPIEndPoint } from 'src/utils/clientHelper';

export interface ChangeRecommendation {
  valveChangeRecommendations: string;
  valveID: string;
}
export const implementValvePath = '/valve-implementation';

export const valveAPI = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: valveAPIEndPoint,
    prepareHeaders: (headers, { getState }) => {
      const token = 'token placeholder'; 
      token && headers.set('authorization', `Bearer ${token}`);
      return headers;
    },
  }),
  endpoints: builder => ({
    submitChangeRequest: builder.mutation({
      query: (changeRequest: ChangeRecommendation) => ({
        body: changeRequest,
        method: 'POST',
        url: implementValvePath,
      }),
    }),
  }),
  reducerPath: 'valveAPI',
  tagTypes: ['ChangeRecommendations'],
});

export const { useSubmitChangeRequestMutation } = valveAPI;

```
without msw I can see a POST methot being fired,
<img width="709" alt="Screen Shot 2021-10-29 at 10 54 50 AM" src="https://user-images.githubusercontent.com/38504519/139465848-1f770676-738f-420b-8981-9acbc4bd8f63.png">
<img width="676" alt="Screen Shot 2021-10-29 at 10 54 17 AM" src="https://user-images.githubusercontent.com/38504519/139465979-c8f5e2fc-beb7-4aa6-bd52-b4341a55b2e5.png">

However, after starting a msw worker, MSW is only intercepting a GET request from this path, not POST
<img width="749" alt="Screen Shot 2021-10-29 at 10 58 19 AM" src="https://user-images.githubusercontent.com/38504519/139466407-2abb6977-550a-4272-ab7d-f3583a7d6929.png">

This is how I set up msw handler:
```
export const handlers = [
  rest.post('https://example/valve-implementation', (req, res, ctx) => {
    {
return res(
          ctx.json(getSuccessImplementationObj(valveID)),
          ctx.delay(300),
          ctx.status(200),
        );
}
}),
];
```
After I change `rest.post` to `rest.get` , msw mocks response as expected. 
Is this a bug?

Thanks for helping !!

 
---------------------------------------------------------------
using "msw": "^0.35.0"

**Comment by msutkowski** [comment]
Nice choice in tools! We use MSW extensively for the RTK Query tests and all examples if you need further references. 

You'll want to double check your handler and make sure the url matches exactly what you're expecting. You'd typically want to construct the url the same way that you do in your fetchBaseQuery - but I can't tell if that's the case here as you use http://example/

**Comment by tiffanyhuang517** [comment]
ya thanks for checking. yes the URL are the same, I just replaced variable names with "http://example/" for the purpose of this post.

**Comment by tiffanyhuang517** [comment]
> Nice choice in tools! We use MSW extensively for the RTK Query tests and all examples if you need further references.
> 
> You'll want to double check your handler and make sure the url matches exactly what you're expecting. You'd typically want to construct the url the same way that you do in your fetchBaseQuery - but I can't tell if that's the case here as you use http://example/

would love to see some examples for MSW + RTK Query! would you please link it? thank you!

**Comment by kettanaito** [comment]
Hey, @tiffanyhuang517. 

The warning you see warns you about a request that is _not_ mocked. The warning confirms your expected behavior: the POST request is indeed not intercepted: "captured a request **without** a corresponding request handler".

You should see a `[MSW] 00:00:00 GET https://your.endpoint 200 OK` (or similar) log message when your handled request is fired.

**Comment by tiffanyhuang517** [comment]
> Hey, @tiffanyhuang517.
> 
> The warning you see warns you about a request that is _not_ mocked. The warning confirms your expected behavior: the POST request is indeed not intercepted: "captured a request **without** a corresponding request handler".
> 
> You should see a `[MSW] 00:00:00 GET https://your.endpoint 200 OK` (or similar) log message when your handled request is fired.

Thanks @kettanaito  

I don't understand, what I fired is a 'POST' reuest, not a 'GET' request, why would MSW detect a GET request for the target path when I trigger a 'POST' request? 

I expect to mock `rest.post` in steand of mocking `rest.get`  when a POST method is being triggered from RTK Query.

**Comment by kettanaito** [comment]
Your code did fire a GET request along the way. MSW captures _all_ requests, regardless if you intend to mock them or not, and then looks up if you've defined any handlers for each of them. If not, it'll print the warning like above, by default. 

If you're absolutely sure there are no GET requests issues by you or any abstraction on top of requests, please submit a reproduction repository for us to look into that.
