### ISSUE TITLE
Can't access cross-origin cookies in Node.js with "include" credentials

### ISSUE THREAD

**Issue by ghost** [kettanaito/msw#967]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.35.0  |
| node | 16.9.1  |
| OS   | Ubuntu 21.04 |

I've created a [reproduction repo](https://github.com/aryzing/repro-msw-weird) where you can easily reproduce this issue.

## Current behavior

In Jest, cross origin cookies are being stripped from requests when msw is running, even if the requests are to a different domain from what msw is configured to listen to (eg, msw set up to intercept reqs on localhost:4444 and express is running in localhost:5555, requests to the express server will not have any cookies).

## Expected behavior

Cookies should be present.

**Comment by kettanaito** [comment]
Hey, @edu-bound. Thanks for letting us know. 

That sounds like an issue. If I'm not mistaken, using `includes` as `credentials` must include all the cookies with the request. At least, that's the intention.

Here are some relevant discussions:

- https://github.com/mswjs/msw/issues/189
- https://github.com/mswjs/interceptors/issues/18

I'll look into this right now, as things might've changed since the last time we discussed this.

**Comment by kettanaito** [comment]
[My comment here](https://github.com/mswjs/msw/issues/189#issuecomment-637342780) explains why this is not working. There's no way for MSW to know what "credentials" were used in Node.js when constructing an isomorphic request object. The "credentials" option is relevant only to the request client (i.e. `fetch`) and is handled there. When it actually performs a request, the request itself also doesn't know anything about the cookies. That's handled on the request client's side. 

We can only introduce a partial solution here, which would work only if `fetch` is polyfilled via `XMLHttpRequest` is Node.js (which, again, depends on the polyfill you're using). `XMLHttpRequest` has the `withCredentials` internal flag. It won't comply with _three_ possible "credentials" options ("omit", "include", "same-origin"), but we can coerce the boolean value of `withCredentials` into:

- `true`, treat at `include`;
- `false`, treat at `omit`.

**Comment by ghost** [comment]
Appreciate the update and you looking into this again 🙏. Will close for now as there's no immediate obvious fix.

**Comment by kettanaito** [comment]
@edu-bound, actually, I've opened a pull request to `@mswjs/interceptors` that will fix this (https://github.com/mswjs/interceptors/pull/170). It has all the limitations described in the linked issue. I've tested that this change makes your test behave the same with and without MSW enabled.
