### ISSUE TITLE
onUnhandledRequest event handler doesn't work (even after a restart)

### ISSUE THREAD

**Issue by guyflax1234** [kettanaito/msw#970]
## Describe the bug
I work with CRA + msw.js and my worker is outputting a lot of warnings of unhandled requests.
Naturally, It makes looking at the devtools a nightmare to look at..

## Environment

- `msw: 0.35.0`
- `pnpm: 6.19.1`

Browser Version: 95.0.4638.69 (Official Build) (64-bit)

## To Reproduce
Just register a worker with default CRA and you will get similar warnings of 
missing handlers for logo.png, manifest.json etc..

**this is my browser.ts file:** 
```js
import { setupWorker } from "msw";
import { handlers } from "./handlers";

export const worker = setupWorker(...handlers);

worker.start({
  onUnhandledRequest: ({ method, url }) => {
    if (!url.pathname.startsWith("/api")) {
      // do nothing..
    }
  },
});

// OR
worker.start({
  onUnhandledRequest: "bypass"
});
```

## Expected behavior
I expect onUnhandledRequest to disable the default warnings that comes with msw
(prefixed: [MSW] Warning: yada yada ...) and show nothing instead.

 

## Screenshots
![Screenshot from 2021-11-06 14-54-56](https://user-images.githubusercontent.com/45357746/140610361-65fa21e0-c344-4f7b-b15c-b034361db3b7.png)

**Comment by kettanaito** [comment]
Hey, @guyflax1234. 

Could you please share a reproduction repository? I can't replicate this issue on a fresh CRA+MSW setup using this:

```js
// src/mocks.js
import { setupWorker } from 'msw'

export const worker = setupWorker()
```

```js
// src/index.js
import { worker } from './mocks'
worker.start({
  onUnhandledRequest: 'bypass',
})
```

No warnings are printed into the console:

<img width="787" alt="Screen Shot 2021-11-06 at 16 15 11" src="https://user-images.githubusercontent.com/14984911/140614607-8ae43812-9250-485d-814b-a81534114e76.png">

**Comment by guyflax1234** [comment]
Sure, 
https://github.com/tobiasbueschel/msw-example-react-hackernews
- pnpm install && pnpm start
And that's what I get:
![Screenshot from 2021-11-06 18-10-28](https://user-images.githubusercontent.com/45357746/140616230-4a9763ad-9051-4870-90e3-86ccb4da44ab.png)

**Comment by kettanaito** [comment]
@guyflax1234, thank you for sharing!

Could you please provide `onUnhandledRequest: 'bypass'` option when you call `worker.start()` here?

https://github.com/tobiasbueschel/msw-example-react-hackernews/blob/43ce1ee881ac26efbd09d75d12d73c1f7756fe8b/src/index.js#L17

**Comment by guyflax1234** [comment]
Ok, there is no bug at all.
I had two versions of the worker.start()
The version that I looked at was not called.
I solved it while trying to reproduce it so you helped me anyway!

sorry for wasting your time :)

**Comment by kettanaito** [comment]
No worries. I'm glad you've resolved it!
