### ISSUE TITLE
Compilation error when running `tsc` after installation

### ISSUE THREAD

**Issue by rvenugopal** [kettanaito/msw#975]
## Environment

- `msw: 0.35.0`
- `nodejs: 12.2.1`
- `npm: 0.0.0`
- `tsc: 3.9.7`

> Please also provide your browser version.
NA.  This is on Node.

## To Reproduce
1. Install msw 
2. Run `tsc -p .`
3. See error below
```
node_modules/msw/lib/types/context/set.d.ts:7:71 - error TS1110: Type expected.

7 export declare type ForbiddenHeaderError<HeaderName extends string> = `SafeResponseHeader: the '${HeaderName}' header cannot be set on the response. Please use the 'ctx.cookie()' function instead.`;
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[1:21:56 PM] Found 1 error. Watching for file changes.

```

My tsconfig looks like the following

```
{
  "compilerOptions": {
    "module": "commonjs",
    "strict": true,
    "target": "ES6",
    "noEmit": false,
    "incremental": true,
    "inlineSourceMap": true,
    "removeComments": true,
    "outDir": "dist",
    "lib": ["es6", "es2016.array.include", "es2017.object"],
    "alwaysStrict": true,
    "traceResolution": false,
    "baseUrl": "./",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "strictPropertyInitialization": false
  },
  "include": [
    "app.ts",
    "config",
    "migration",
    "src",
    "test"
  ]  
}

```

## Expected behavior
Compilation succeeds

**Comment by kettanaito** [comment]
Hey, @rvenugopal.

TypeScript 3.9 is not supported by the MSW ecosystem. Please use the newer version of TypeScript (the latest is 4.4, the minimum required should be 4.2).

**Comment by rvenugopal** [comment]
Is this information about minimum typescript version documented?  Thanks @kettanaito

**Comment by willbuckingham** [comment]
Yup, just ran into this one myself, thank fully found this, I think ideally this would have a peer dependency for typescript if that is the case.

**Comment by kettanaito** [comment]
@rvenugopal, I'm afraid not. We need to find an efficient way to store the minimal required TypeScript version. Something like `engines.typescript` would be ideal in your package.json. Such things are troublesome to document, as this is a technical detail that may shift periodically. Documentation is at risk of getting out-of-date on this, creating even more confusion. 

> think ideally this would have a peer dependency for typescript if that is the case.

That's a sound idea but we don't wish to enforce TypeScript to those who decide not to use it. MSW is perfectly functional in plain JavaScript.

**Comment by kettanaito** [comment]
My bad, read it as "dev dependency". @willbuckingham, yes, using `peerDependencies` is a great idea. Would you be interested in opening a pull request with that fix?
