### ISSUE TITLE
Decode path components in "req.params"

### ISSUE THREAD

**Issue by VanTanev** [kettanaito/msw#976]
**Is your feature request related to a problem? Please describe.**
Given the following definition:
```ts
rest.get('/check-url/:url', (req, res, ctx)=> {
  return res(ctx.json({ url: req.prams.url }))
})
```

We get the following behavior:
```ts
GET /check-url/http%3A%2F%2Fexample.com

{
  "url": "http%3A%2F%2Fexample.com"
}
```

This is undesirable.

**Describe the solution you'd like**

```ts
GET /check-url/http%3A%2F%2Fexample.com

{
  "url": "http://example.com"
}
```

**Fix**
This can be accomplished by editing this line of code:

https://github.com/mswjs/msw/blob/fe6751f76108047fb27b16a875497693da1eb66d/src/utils/matching/matchRequestUrl.ts#L45

Instead:
```ts
const result = match(cleanPath, { decode: decodeURIComponent })(cleanUrl)
```

**Additional context**

To my knowledge, all major backend frameworks perform decode.

**Comment by kettanaito** [comment]
Hey, @VanTanev. Thank you for suggesting this!

Could you double-check if you're using the latest version of `msw`? We've recently migrated to use `path-to-regexp` library (powers path matching in Express), which should perform path parameters decoding by default. Perhaps we have it misconfigured in our usage (the `decode` option suggested by you)?

May I ask you to add a failing integration test for this? Ideally, for both Node.js and browser interception.

**Comment by VanTanev** [comment]
@kettanaito Can you please point me to the proper place to add the tests?

**Comment by kettanaito** [comment]
Sure. I'd add those 2 tests in [here](https://github.com/mswjs/msw/tree/fe6751f76108047fb27b16a875497693da1eb66d/test/rest-api/request/matching) (`test/rest-api/request/matching`):

- `path-params-decoding.test.ts`
- `path-params-decoding.node.test.ts`

Take a look at [in-browser](https://github.com/mswjs/msw/blob/fe6751f76108047fb27b16a875497693da1eb66d/test/rest-api/request/matching/method.test.ts#L25-L36) and [Node.js](https://github.com/mswjs/msw/blob/fe6751f76108047fb27b16a875497693da1eb66d/test/msw-api/setup-server/scenarios/relative-url.test.ts#L1-L3) integration tests for inspiration. Let me know if you have any questions.
