### ISSUE TITLE
Wrapping handlers in jest.fn doesn't work when done up front

### ISSUE THREAD

**Issue by cuongluu8** [kettanaito/msw#983]
## Describe the bug
So far I defined a bunch of handlers very similar to your example https://github.com/mswjs/examples/tree/master/examples/graphql-react-apollo/src.

In some unit tests, I create an inline server handler where I wrap the handler in a `jest.fn` to assert the handler was called.  I thought, why not wrap all handlers in `jest.fn` by default to make it all consistent.
However, it doesn't seem to call the server handler when you wrap it in a `jest.fn` up front.

## Environment

- `msw: 0.35.0`
- `nodejs: 14.16.0`
- `npm: 6.14.11`

## To Reproduce
server-handlers.js
```
export const mockHandler = jest.fn((req, res, ctx) => {
  return res(ctx.data({}));
});

export const handlers = [
  graphql.mutation("CreateUser", mockHandler),
];
```

server.js
```
import { setupServer } from "msw/node";

import { handlers } from "./server-handlers";

const server = setupServer(...handlers);

export { server };
```

## Expected behavior
test.js
```
test("it should create a user", async () => {
  await renderAndCreateUser();

  expect(mockHandler).toHaveBeenCalled();
});
```
This should pass, but the mockHandler is never called and I get a warn
`[MSW] Expected a mocking resolver function to return a mocked response Object, but got: undefined. Original response is going to be used instead.`

However, this does work
test.js

```
test("it should create a user", async () => {
  const handler = jest.fn((req, res, ctx) => {
     return res(ctx.data({}));
  });
   
   server.use(graphql.mutation("CreateUser", handler));

  await renderAndCreateUser();

  expect(handler).toHaveBeenCalled();
});
```

**Comment by kettanaito** [comment]
Hey, @cuongluu8. 

Could you please verify that you're indeed returning the mocked response from the `jest.fn` function? Your examples above look correct. There should be no difference at which point you wrap the handler in `jest.fn`. The warning you see from MSW means that the handler does get called, but it returns no mocked response. Here's an example of such _invalid_ handler:

```js
const handle = jest.fn((req, res, ctx) => {
    // Note: forgotten "return" statement.
  res(ctx.json({ a: 1 }))
})
```

If you confirm that you return the mocked response but still experience this issue, please create a small reproduction repository for us to look at. Thanks.

**Comment by cuongluu8** [comment]
Hi @kettanaito 

Here's a repo to reproduce the issue https://github.com/cuongluu8/msw-test/

**Comment by kettanaito** [comment]
Hey, @cuongluu8. Thank you for preparing the repository! It helped me figure out what's the culprit.

## Solution

Do not use `resetMocks: true` option in your `jest.config.js`. 

When the [resetMocks] option is used, you're resetting the _implementation_ of all `jest.fn()` before each test. This means that your `jest.fn()` calls no longer do what the passed implementation function does. You can verify it with any function:

```js
const example = jest.fn(() => 2)

// This assertion will fail because "resetMocks" will force "example"
// to lose its implementation (() => 2), returning undefined. 
expect(example()).toEqual(2)
```

- See https://github.com/facebook/jest/issues/9131#issuecomment-668790615

Consider a different way to reset your mock functions (I believe the thread I linked above suggests the alternatives).
