### ISSUE TITLE
Support GraphQL v16

### ISSUE THREAD

**Issue by alexandernanberg** [kettanaito/msw#995]
**Is your feature request related to a problem? Please describe.**

GraphQL v16 has been released, it would be great if `msw` supported it

**Describe the solution you'd like**

Update `msw` to support the latest GraphQL version

**Describe alternatives you've considered**
N/A

**Additional context**

https://github.com/graphql/graphql-js/releases/tag/v16.0.0

**Comment by kettanaito** [comment]
Hey, @alexandernanberg. Thank you for raising this suggestion.

We should definitely support GraphQL 16 and will put it on our roadmap. Judged by the changelog, there aren't any breaking changes that'd imply API change on the MSW's side. It should be a matter of bumping the `graphql` dependency in our package.json:

https://github.com/mswjs/msw/blob/128086b7ca0cf15df77b386b1d2f925e58e2c2f0/package.json#L76

I suggest the following update strategy:

1. Update to the latest `15.x` version and release it in a minor version bump.
2. Update to `16.x` and release it in another minor version bump.

There are currently quite a few features and bug fixes in progress, so we may not be as swift regarding this update.

**Comment by alexandernanberg** [comment]
Thought at first that it didn't work at all with v16, but it was just me who forgot to update the internal use of `graphql` execute. So not an urgent issue but would be nice to avoid having 2 versions of graphql in `node_modules`
