### ISSUE TITLE
Error: Can't resolve 'stream/web' when using webpack 5

### ISSUE THREAD

**Issue by forbid403** [kettanaito/msw#998]
## Describe the bug
```
Module not found: Error: Can't resolve 'stream/web' in '/node_modules/fetch-blob'
```
This error occurs when building react app, same errors occur with `util`,`http`,`https`,`stream`,`crypto`,`zlib`.
MSW works well despite error occurs, but the terminal and webpack-dev-server complains about it.

I think this issue occurs with webpack5 issue. ref: 
https://webpack.js.org/configuration/resolve/#resolvefallback
```json
"stream": false,
"util": false,
"http": false,
"crypto": false,
"https": false,
"zlib": false
```
I solved this issue by adding above code in package.json: resolve.fallback,
but I propose because I think msw have to handle this issue internally.

## Environment
- `webpack 5.53.0`
- `webpack-cli 4.8.0`
- `webpack-dev-server 4.2.1`
- `msw: 0.35.0`
- `nodejs: 14.17.0`
- `npm: 6.14.13`

> Please also provide your browser version.
Chrome 95.0.4638.69

## To Reproduce
1. run msw with webpack5

## Expected behavior
- App should run without error.

## Screenshots
![image](https://user-images.githubusercontent.com/41617388/143034422-2410fcde-0415-468e-b699-832765243a1e.png)

**Comment by kettanaito** [comment]
Hey, @forbid403. Thank you for reporting this.

May I kindly ask you to prepare a reproduction repository where I can look into this issue? That'd save me time trying to match your setup and would help me help you faster. Thanks.

**Comment by forbid403** [comment]
@kettanaito Hello, I find out why this issue happens.
Its because of my `package.json` file.
```
optionalDependencies: {
  node-fetch: ^3.0.0
}
```
I have node-fetch over v.3.0.0 in my optional dependency list.
MSW works well when i downgrade this to ^2.6.0

Sorry for bothering you.
Thanks

**Comment by kettanaito** [comment]
No worries. I'm glad you've figured it out! 🎉

**Comment by sniffer72** [comment]
I am running into this issue as well and I have tried some of other pkg solution without luck.


1. npx create-expo-app coreApp --template tabs@50
2. Install firebase resources
% npm install firebase @react-native-firebase/app @react-native-firebase/auth
3. I am able to login to my mobile app with this tutorial on IOS but when I try using expo web I get that error below.
https://github.com/Cebraiil/firebase_auth_tutorial/blob/master/App.js

Metro error: Unable to resolve module stream/web from /Users/justin/coreApp/node_modules/undici/lib/core/util.js: stream/web could not be found within the project or in these directories:
  node_modules
  369 | function ReadableStreamFrom (iterable) {
  370 |   if (!ReadableStream) {
> 371 |     ReadableStream = require('stream/web').ReadableStream
      |                               ^
  372 |   }
  373 |
  374 |   if (ReadableStream.from) {

I have tried to install the stream npm package and that didn't solve it either.

## Environement ##
% npm -v
10.4.0

% node -v
v18.19.0


## package.json = does not work ##
{
  "name": "coreapp",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-native-firebase/app": "^18.9.0",
    "@react-native-firebase/auth": "^18.9.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~50.0.7",
    "expo-font": "~11.10.3",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.7",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.3",
    "expo-web-browser": "~12.8.2",
    "firebase": "^10.8.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.4",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "jest": "^29.2.1",
    "jest-expo": "~50.0.2",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },
  "pkg": {
		"patches": {
			"./node_modules/undici/lib/fetch/body.js": ["require('stream/web')", "require('stream').web"],
			"./node_modules/undici/lib/core/util.js": ["require('stream/web')", "require('stream').web"],
			"./node_modules/undici/lib/fetch/request.js": ["require('stream/web')", "require('stream').web"],
			"./node_modules/undici/lib/fetch/index.js": ["require('stream/web')", "require('stream').web"]
		}
	},
  "private": true
}

**Comment by alphax00** [comment]
same!

**Comment by alphax00** [comment]
> I am running into this issue as well and I have tried some of other pkg solution without luck.
> 
> 1. npx create-expo-app coreApp --template tabs@50
> 2. Install firebase resources
>    % npm install firebase @react-native-firebase/app @react-native-firebase/auth
> 3. I am able to login to my mobile app with this tutorial on IOS but when I try using expo web I get that error below.
>    https://github.com/Cebraiil/firebase_auth_tutorial/blob/master/App.js
> 
> Metro error: Unable to resolve module stream/web from /Users/justin/coreApp/node_modules/undici/lib/core/util.js: stream/web could not be found within the project or in these directories: node_modules 369 | function ReadableStreamFrom (iterable) { 370 | if (!ReadableStream) {
> 
> > 371 |     ReadableStream = require('stream/web').ReadableStream
> > |                               ^
> > 372 |   }
> > 373 |
> > 374 |   if (ReadableStream.from) {
> 
> I have tried to install the stream npm package and that didn't solve it either.
> 
> ## Environement
> % npm -v 10.4.0
> 
> % node -v v18.19.0
> 
> ## package.json = does not work
> { "name": "coreapp", "main": "expo-router/entry", "version": "1.0.0", "scripts": { "start": "expo start", "android": "expo start --android", "ios": "expo start --ios", "web": "expo start --web", "test": "jest --watchAll" }, "jest": { "preset": "jest-expo" }, "dependencies": { "@expo/vector-icons": "^14.0.0", "@react-native-firebase/app": "^18.9.0", "@react-native-firebase/auth": "^18.9.0", "@react-navigation/native": "^6.0.2", "expo": "~50.0.7", "expo-font": "~11.10.3", "expo-linking": "~6.2.2", "expo-router": "~3.4.7", "expo-splash-screen": "~0.26.4", "expo-status-bar": "~1.11.1", "expo-system-ui": "~2.9.3", "expo-web-browser": "~12.8.2", "firebase": "^10.8.0", "react": "18.2.0", "react-dom": "18.2.0", "react-native": "0.73.4", "react-native-safe-area-context": "4.8.2", "react-native-screens": "~3.29.0", "react-native-web": "~0.19.6" }, "devDependencies": { "@babel/core": "^7.20.0", "@types/react": "~18.2.45", "jest": "^29.2.1", "jest-expo": "~50.0.2", "react-test-renderer": "18.2.0", "typescript": "^5.1.3" }, "pkg": { "patches": { "./node_modules/undici/lib/fetch/body.js": ["require('stream/web')", "require('stream').web"], "./node_modules/undici/lib/core/util.js": ["require('stream/web')", "require('stream').web"], "./node_modules/undici/lib/fetch/request.js": ["require('stream/web')", "require('stream').web"], "./node_modules/undici/lib/fetch/index.js": ["require('stream/web')", "require('stream').web"] } }, "private": true }

I have same issue too for:
import { getStorage, ref, uploadBytes, getDownloadURL } from "firebase/storage";
did you figure out yet??
